### ISSUE TITLE
Node 6+ conversion of anonymous objects

### ISSUE THREAD

**Issue by snypelife** [facebook/immutable-js#1001]
Searched around, and didn't find very much online. I found these, but nothing related to Immutable.
- https://github.com/brianc/node-postgres/issues/1062
- http://stackoverflow.com/questions/37997665/node-js-6-and-anonymous-objects
### What happened

I attempted to use the `fromJS` method to deeply convert a javascript object into an Immutable object. When the object contains a value that is labeled as "anonymous", the `fromJS` seems to skip trying to convert the value.
### How to reproduce

``` js
const obj = {
  child1: anonymous {
    id: '59869fcb-57af-437b-b5ad-a6bfcdec2f0f',
    createdAt: '2016-10-24T01:14:19.777Z' 
  },
  child2: []
}

const newObj = Immutable.fromJS(obj)

// result
console.dir(newObj.get('child1', { depth: null, colors: true })

 anonymous {
    id: '59869fcb-57af-437b-b5ad-a6bfcdec2f0f',
    createdAt: '2016-10-24T01:14:19.777Z' 
  }

console.dir(newObj.get('child2', { depth: null, colors: true })
List {
  size: 0,
  _origin: 0,
  _capacity: 0,
  _level: 5,
  _root: undefined,
  _tail: undefined,
  __ownerID: undefined,
  __hash: undefined,
  __altered: false }
```

As an interim solution, I serialize+deserialize the object with `stringify` and `parse` before passing it to the fromJS function. Obviously this solution blows,

**Comment by leebyron** [comment]
Any Object that has a prototype Immutable.js assumes isn't a candidate for conversion to Map/List. If you want to explicitly convert them, you can wrap them in the type you want:

```js
const obj = fromJS({
  child1: Map(yourCustomClassInstance),
  child2: []
})
