### ISSUE TITLE
Iterator missing in type definitions 

### ISSUE THREAD

**Issue by linusnorton** [facebook/immutable-js#1003]
### What happened

Unable to use a Map in a for..of loop in TypeScript because the iterator is not defined in the definition file.
### How to reproduce

``` ts
import {Map} from "immutable";

const m = Map({ a: 1 });

for (const [key, value] of m) {
    console.log(key, value);
}
```

Error

```
TSError: ⨯ Unable to compile TypeScript
src/test.ts (6,28): Type must have a '[Symbol.iterator]()' method that returns an iterator. (2488)
```

**Comment by linusnorton** [comment]
It's possible https://github.com/facebook/immutable-js/pull/942 would fix the issue but that PR has been unmerged for 3 months.

**Comment by WhyEvenTry** [comment]
https://www.reddit.com/r/javascript/comments/5abgex/whats_going_on_with_immutablejs/

**Comment by linusnorton** [comment]
Yeah, that was me actually - I've asked on twitter as well as I thought this was a very popular library but it seems to have died off.

**Comment by nicholasgonzalezsc** [comment]
+1 Can we get this fix in

**Comment by leebyron** [comment]
Merged, will be in the next release
