### ISSUE TITLE
Mori's zipmap - is there an equivalent?

### ISSUE THREAD

**Issue by NeverwinterMoon** [facebook/immutable-js#1004]
I have a general question and I did look around a bit before asking.

I really love Mori's zipmap operator (it allows to create a map from two arrays). I wasn't able to find a way to do exactly the same in one operation with Immutable.js. Is there anything similar? Is there a plan to add it? And I do know how to achieve the similar result using more than one step, but I love the verbocity of aforementioned zipmap.

**Comment by leebyron** [comment]
Yes, checkout `zip` http://facebook.github.io/immutable-js/docs/#/List/zip

**Comment by NeverwinterMoon** [comment]
@leebyron How is this the same? ImmutableJS' `List#zip` provides a list of lists: 
```
var keys = ["foo", "bar", "baz"]
var vals = [1, 2, 3]
List(keys).zip(List(vals)).toJS() // => [ ["foo", 1], ["bar, 2], ["baz", 3] ]
```

`mori#zipmap`, on the other hand, provides an object/map:
```
var keys = ["foo", "bar", "baz"]
var vals = [1, 2, 3]
mori.toJs(mori.zipmap(keys, vals)) // => {"foo": 1, "bar": 2, "baz": 3}
```

https://jsfiddle.net/NeverwinterMoon/hbnzb2qq/

zipmap is very convenient for some cases in our code, but zip requires additional manipulations.

**Comment by leebyron** [comment]
Right to get a hashmap output, just wrap with Map:

Map(keys.zip(vals))
