### ISSUE TITLE
Open up immutable.js to more contributors

### ISSUE THREAD

**Issue by linusnorton** [facebook/immutable-js#1005]
I would like to suggest that this project is opened up to more contributors from the community.

The project has only ever really been developed by @leebyron but unfortunately he appears rather busy at the moment and unable to move the project forward. 

While the library may be considered feature complete there are a number of issues that have built up and been ignored. Many contain PRs that have also been ignored. 

I feel the project would be able to continue in a more healthy manner if it didn't depend on so heavily on a single person or organisation.

I understand this is a Facebook project but it has become quite a large project, important for many people. There are 15,556 stars at the time of writing.

**Comment by leebyron** [comment]
I'd love to do this - I think tactically there are a few things we need to do to enable this.

First is to nominate some volunteers - anyone who has a good understanding of the library and it's mission and wants to contribute to maintenance. I'm open to suggestions.

Second is to bias towards creating an ecosystem around immutable-js. I know there are a lot of requested features, and I think the best case scenario is that we encourage a small-library ecosystem around a set of shared patterns and interfaces. That enables a marketplace of ideas and removes myself, Facebook, or any other maintainers from the path of innovation.

**Comment by linusnorton** [comment]
Thanks for considering this request. I'll do everything I can to help the process. As the person that created this issue I feel obliged to put myself forward but I hope more qualified contributors come forward.

Could you clarify your idea of the ecosystem? Are you proposing something like extensions to keep the core small and focused? It sounds like a good idea to me. I think this is a very feature stable library and the core of it should stay that way. 

Deciding the governance model will be important. Assuming people do step forward we'll need some agreement on how decisions are made so that it doesn't all fall on your shoulders, but also doesn't go away from your original vision entirely.

**Comment by leebyron** [comment]
Hey @linusnorton - sorry for not following up on this discussion sooner.

> Could you clarify your idea of the ecosystem?

Ideally installing immutable.js gives you a small set of core functionality, and you can use other npm modules for additional behavior - that way we can allow for anyone to release ideas that work well with immutable.js. I think it would be a failure if the only way new ideas and features can be introduced is if they have to all be added to this library in particular.

> Are you proposing something like extensions to keep the core small and focused? It sounds like a good idea to me. I think this is a very feature stable library and the core of it should stay that way.

Yes, 100% agreed. In my mind, the answer to most feature requests should not be to evaluate the feature itself but instead evaluate if there is a missing extension point that's in line with the libraries intended use.

> Deciding the governance model will be important. Assuming people do step forward we'll need some agreement on how decisions are made so that it doesn't all fall on your shoulders, but also doesn't go away from your original vision entirely.

I agree this is important, but also something I'm a bit stumped on accomplishing. I'm open to ideas but right now my thought is to introduce more co-workers who are using Immutable.js at Facebook to help maintain, and then slowly adding trusted contributors from the community at large if necessary.

Overall though, this library intentionally moves slowly and there aren't many decisions to make. The goal is to bias heavily towards stability - so doc clarity, bug fixes, and perf improvements are valuable, but altering the feature set is less valuable. I think this approach shouldn't require a huge amount of effort in governance.

**Comment by linusnorton** [comment]
There hasn't been a large number of people stepping forward as potential collaborators so I think the best thing is to convince some colleagues of yours, as you suggest.

I think the most immediate thing is just getting people to help with the large number of open issues and PRs and then we can see how it evolves from there.

**Comment by leebyron** [comment]
Totally agree. In fact you should see some folks helping drive down the issues. The gracious @lacker is already making a dent!

**Comment by leebyron** [comment]
In the spirit of that, I'm going to close this issue as well. 

I'll try to get a reviewathon scheduled sometime soon to help press down the outstanding PRs. We'll go from there

**Comment by lacker** [comment]
This reviewathon could really use some Typescript & Flow expertise - my first learning after going through a chunk of pull request and issues is what a large % of the issues are actually just updates to the type definitions.

**Comment by skeet70** [comment]
Should this be reopened? Were any trusted folks ever added to the list of people that can merge PRs/do releases? Is there a good set of guidelines for how we can help with issues/PRs and lessen the load on you as you're busy with other FBOSS projects @leebyron? I ask because these months long periods of people contributing PRs (mostly bugfixes, stability, type improvements) that stagnate probably aren't going to get better without changing anything.

**Comment by rgbkrk** [comment]
I am more than happy to make my core responsibility as a maintainer be for the flow definitions.

Eventually this project will just have to start enabling people, many of us work on other large open source projects and are used to doing issue triage.
