### ISSUE TITLE
shallowEqual should return true for two identical immutable-objects

### ISSUE THREAD

**Issue by macrozone** [facebook/immutable-js#1006]
Maybe i am standing totally on the hose, but...

I would expect that shallowEqual from fbjs (https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/shallowEqual.js)
would return true for two equal immutable objects, but it does not.

Recompose (https://github.com/acdlite/recompose) provides a "pure"-hoc that uses shallowEqual, but i was suprised that my component rerendered, despite the fact that i used an Immutable.Map.

Is this the expected behaviour? Do I am missing something important here?

**Comment by akindr** [comment]
+1, I'm running into the same issue when using `Immutable.Map` as a prop for a `PureComponent`.

**Comment by leebyron** [comment]
`shallowEqual` relies on `===` for each value in `props` to determine equality. Two value-equal immutable collections are not necessarily `===` for the same reason two arrays with the same items won't be `===`.

However Immutable collections typically attempt to return themselves whenever an operation results in a no-op, that means that `===` can often be used alongside Immutable collections, but if you're constructing two collections independently and comparing them with `===` will always yield `false`.
