### ISSUE TITLE
Cannot set on an immutable record.

### ISSUE THREAD

**Issue by petarslavnic** [facebook/immutable-js#1007]
Throws error: Cannot set on an immutable record.
```js
var MyRecord = Immutable.Record({ size: 0 });
var inst = new MyRecord({ size: 1024 });
```

**Comment by AugustinLF** [comment]
`size` is not a field you can set on a Record.

**Comment by petarslavnic** [comment]
I will forget about `Immutable.Record` for now.

**Comment by mschipperheyn** [comment]
@petarslavnic you shouldn't. It's awesome. Just don't set 'size'

**Comment by dhenson02** [comment]
Definitely should have googled this hours ago.  Can't believe this was it the whole time.
