### ISSUE TITLE
Sort()ing by numerical proprerty and index confusion

### ISSUE THREAD

**Issue by vivasonico** [facebook/immutable-js#1009]
Hi there,

I have encoutered what seems to be a bug in the sort() method for Lists. I have the following reducer in which listelements is a n immutable List. It handles a list of items from a restaurant and each category of dishes (pizzas, salads, drinks...) has a tipoOrden proprerty that I use to sort them (starting from 1). In this case, pizzas have tipoOrden: 2 and drinks tipoOrden: 6. 

When I have more than 7 items in the List, if I add a pizza it appears after the drinks. I have managed to solve this issue by changing the tipoOrden proprerty to a string (pizzas  have now tipoOrden:'2')

I guess that there might me some problem with sort()ing by a numerical proprerty and the item index.

```
    case ishopActions.ADD_TO_CART:
      return state.set('listelements', state.listelements.push(payload.element).sort(
        (a,b) => a.tipoOrden >b.tipoOrden
      ));
```

**Comment by leebyron** [comment]
Sorry I can't reproduce your issue without runnable code and expected/actual results.

Remember that sort functions return numbers not booleans:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
