### ISSUE TITLE
[Documentation] - List.get() docs seems counter to functionality

### ISSUE THREAD

**Issue by thomb** [facebook/immutable-js#1011]
From https://facebook.github.io/immutable-js/docs/#/List/get
```
Returns the value associated with the provided key, or notSetValue if the Iterable does not contain this key.
```

Yet, 
```
        const testing = Immutable.List([1, 2, 3, 100]);
        console.log(testing.get(-1)); // Outputs 100
```

I know this is correct behaviour based on #116 but these docs seem to read as though `-1` should return a `notSetValue`. 

Other documentation - such as for `set`, `delete` and `update` - makes this behaviour clearer.

**Comment by leebyron** [comment]
Yeah we don't really advertise this much, and I'm not sure negative indices will stick around for future major versions since it breaks with native indexed collections and can be buggy along with indexOf so I'm not keen on starting to encourage usage now.
