### ISSUE TITLE
Is ImmutableJS inactive / dead?

### ISSUE THREAD

**Issue by davidwparker** [facebook/immutable-js#1012]
It seems that this repo has quite a few issues, a ton of PRs, and no one official from Facebook working on it.

Is this the case? 

Thanks, (and hopefully) keep up the good work!

**Comment by leebyron** [comment]
Not dead! Immutable.js is still used heavily both within Facebook and in the broader dev community. However right now maintenance has slowed. I've been working on some strategies to get more attention to continued maintenance but the focus needs to be on refinements and bug fixes - most issues ask questions and PRs attempt to add new features which deserve their own libraries.

I'll hopefully have more to update soon.

**Comment by davidwparker** [comment]
Thanks for the response @leebyron!

**Comment by viebel** [comment]
@leebyron  Is Immutable.js still a live project in November 2020?
