### ISSUE TITLE
Convert a List of Immutable back to javascript objects with toJS() 

### ISSUE THREAD

**Issue by lexon0011** [facebook/immutable-js#1013]
I use the toJS() method to convert immutables back to raw JavaScript objects. For this I write the following sample code:

```
interface IImmutable1 {
    id: string;
    immutableList: Immutable.List<Immutable2>;
}

export class Immutable1 {
   private immutableRecord1 = Immutable.Record(<IImmutable1>{
       id: <string>null,
       immutableList: <Immutable.List<Immutable2>>null,
   });

   public getAsJavascriptObject(): IProductionRequestModelUpdate {
        return this._record.toJS();
    }
}
```

I use the immutable in the following way:
```
var immutableInstance = new Immutable1();
var rawObject = immutableInstance.getAsJavascriptObject();
```

The `toJS()` method converts the `Immutable.List<Immutable2>` to a simple array, **BUT** it does not convert the Immutable2 to a raw javascript object. So I will get an error, if I write the following instruction:

```
rawObject.immutableList[0].someProperty = "hello";   
// error, because rawObject.immutableList[0] is an Immutable and not a raw javascript object
```

What is the correct way to convert an immutable object which include a List of Immutables to an raw javascript object?

Thanks!!

**Comment by mx781** [comment]
Can anyone confirm if this is a bug or expected behavior? Documentation suggests that toJS does deep conversion:

> All immutable Iterables can be converted to plain JavaScript Arrays and Objects shallowly with toArray() and toObject() or deeply with toJS().

**Comment by leebyron** [comment]
`toJS` will convert deeply - you can check out some examples in the `__tests__` directory for illustration. Note that `immutableList[0]` indexing does not work with Immutable collections. You must use `.get()` and `.set()` instead.

Also, `toJS` converts as deeply as it can before encountering something it does not know how to convert. For example your code is using JS classes which are not immutable collections. My guess is that upon encountering an instance of `Immutable2` which is a general JS class and not an Immutable collection, `toJS` believes that it has converted as far as it can
