### ISSUE TITLE
OrderedMap flow type inheritance problem

### ISSUE THREAD

**Issue by rt2zz** [facebook/immutable-js#1015]
### What happened
OrderedMap inherits its type from Map, which means the return value of all OrderedMap methods are of type Map.

One solution is to not inherit OrderedMap from Map and instead redefine all methods. I am hoping there is a more elegant solution using a `this` type, although a cursory attempt failed because this cannot be parameterized.

### How to reproduce
```js
[1, 2, 3]
  .reduce((acc: OrderedMap<number, number>, num: number) => {
    return acc.set(num, num)
  }, OrderedMap())
```
flow error:
```
Error:
  186:   }, OrderedMap())
            ^^^^^^^^^^^^ Map. This type is incompatible with
  184:   .reduce((acc: OrderedMap<number, number>, num: number) => {
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ OrderedMap
```

**Comment by wokalski** [comment]
I *think* it's impossible to express with `flow` now. I added an [issue](https://github.com/facebook/flow/issues/2959).

**Comment by howardjing** [comment]
I ran into the same issue with `OrderedMap` / `OrderedSet` / `toOrderedMap` / `toOrderedSet`. The easiest thing I can think of to fix this is to copy paste the typings of `Map` and `Set`, and adjust return values appropriately. Will have a PR up shortly.
