### ISSUE TITLE
Trying to create a field called 'size' on a Record causes an incomprehensible run-time error

### ISSUE THREAD

**Issue by mnpenner** [facebook/immutable-js#1016]
### What happened

I tried defining a new Record class:

```js
const FileRecord = Immutable.Record({
    name: '',
    size: 0,
    progress: 0,
}, 'FileRecord');
```

Which runs fine.

And then tried creating a new instance:

```js
let fr = new FileRecord();
```

But this results in this error:

> Cannot set on an immutable record.

It took me a long time to figure out that "size" is special property and you're not allowed to use this in your Record.

### How to reproduce

Example is above. Quite easy to reproduce.

I think a descriptive error should be thrown when you try to create a Record Class with that property rather than when you try to use it. Maybe something like,

> Cannot set the 'size' property on Record; it is reserved for the number of properties.

**Comment by nathraQ** [comment]
I put it here, as it's probably the last in a long list of similar issues.
As `size`and other keys are reserved, why can't they be Symbols to make size as a property available again?

**Comment by philpl** [comment]
I don't think they should be symbols. `size` is used through out every Immutable data structure.

However, there should be a runtime check - at least in development - that outputs an error when a key `size` is being specified.
