### ISSUE TITLE
Weird behaviour in prototype extension of Record

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/immutable-js#1019]
Can someone explain this difference to me?

Defined this

		const JobCandidate = new Record({
			pk : null,
			user : null,
			offer : null,
			status : jobCandidateStatus.UNKNOWN,
			title : null,
			introduction : null,
			cv : null,
			dteCreate : null,
			dteUpdate : null,
		});

		JobCandidate.prototype.equals = function(that){
		  console.log('equals', this, that); //this is defined
			return !( (!this && !that) || (!this && that) || (this && !that) ) && this.pk === that.pk;
		};

		JobCandidate.prototype.hashCode = function(){
			return hash_int32array([this.pk]);
		};

Undefined this

		const JobCandidate = new Record({
			pk : null,
			user : null,
			offer : null,
			status : jobCandidateStatus.UNKNOWN,
			title : null,
			introduction : null,
			cv : null,
			dteCreate : null,
			dteUpdate : null,
		});

		JobCandidate.prototype.equals = (that) => {
		  console.log('equals', this, that);//this is always undefined
			return !( (!this && !that) || (!this && that) || (this && !that) ) && this.pk === that.pk;
		};

		JobCandidate.prototype.hashCode = () => {
			return hash_int32array([this.pk]);
		};

**Comment by leebyron** [comment]
Arrow functions do not capture `this`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
