### ISSUE TITLE
List.findIndex -1 not compatible with List.get

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/immutable-js#1020]
`List.findIndex` returns `-1` if the item can't be found. If you then provide this index to `List.get`, it will return the last item! I would expect `undefined`.

**Comment by wokalski** [comment]
I think it's a feature. 
`List.findIndex` works like indexOf in `Array`
Using negative indices for getting values has been implemented in #116.

You should probably check if `findIndex` returns a negative value before passing it to `List.get`

**Comment by OliverJAsh** [comment]
I expected parity with `[1,2,3][-1] => undefined`

**Comment by wokalski** [comment]
It's understandable since docs don't mention it.

**Comment by lacker** [comment]
It would be great to get a pull request improving the docs to mention this! For this particular bug report though I think we should close as "working as intended". Thanks for bringing this up!
