### ISSUE TITLE
not deeply frozen, is this secure?

### ISSUE THREAD

**Issue by msteckyefantis** [facebook/immutable-js#1025]
[my npm module](https://github.com/msteckyefantis/is-deep-frozen) that does deep unfrozenness tests found some results that you may or may not find interesting or relevant.

the following code:
```.js
const Immutable = require( 'immutable' );

const isDeepFrozen = require( 'is-deep-frozen' );

const map1 = Immutable.Map({a:1, b:2, c:3});

console.log( isDeepFrozen( map1 ).error );
```
will log:
```
{ NotDeeplyFrozenError: property: inputValue, value: {
    "a": 1,
    "b": 2,
    "c": 3
}
property: inputValue[ "_root" ], value: {
    "ownerID": {},
    "entries": [
        [
            "a",
            1
        ],
        [
            "b",
            2
        ],
        [
            "c",
            3
        ]
    ]
}
property: inputValue[ "_root" ][ "ownerID" ], value: {}
property: inputValue[ "_root" ][ "entries" ], value: [
    [
        "a",
        1
    ],
    [
        "b",
        2
    ],
    [
        "c",
        3
    ]
]
property: inputValue[ "_root" ][ "entries" ][ "0" ], value: [
    "a",
    1
]
property: inputValue[ "_root" ][ "entries" ][ "1" ], value: [
    "b",
    2
]
property: inputValue[ "_root" ][ "entries" ][ "2" ], value: [
    "c",
    3
]

    at isDeepFrozen (/Users/ ...
```

Essentially it says that a bunch of objects in your immutable map are not frozen (i.e. they are mutable).
```.js
// ... continued from code snippit above

map1[ "_root" ][ "entries" ][ "1" ][ 1 ] = {

    xxx: 69
};

console.log( map1.get( 'b' ) ); // logs { xxx: 69 }
```

Just wanted to run this by you facebook people on case this is a potential issue or whatever.

**Comment by dannytatom** [comment]
Gf

**Comment by calvinmetcalf** [comment]
Out of curiosity, have you done any research on the performance penalty that freezing causeses?  I mean in theory it could even be a speed up but my gut guess is that it's not free currently.

**Comment by msteckyefantis** [comment]
I don't think there is any performance benefits:

[http://stackoverflow.com/questions/8435080/any-performance-benefit-to-locking-down-javascript-objects](http://stackoverflow.com/questions/8435080/any-performance-benefit-to-locking-down-javascript-objects)

This is more about making your objects/functions immutable in a javascript way:

[https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)

"In essence the object is made effectively immutable."

**Comment by msteckyefantis** [comment]
Never mind, I didn't see it before, but when I searched again, I've seen that this topic has already been discussed a few fews back:

[174](https://github.com/facebook/immutable-js/issues/174)
