### ISSUE TITLE
Create Map from Object which has length Property

### ISSUE THREAD

**Issue by jaganathanb** [facebook/immutable-js#1026]
There is a [question](https://stackoverflow.com/questions/41222781/custom-fromjs-immutablejs-issue/41241727#41241727) in SO which talks about custom `fromJS`

`fromJS` is taken from the [Immutable docs page](https://github.com/facebook/immutable-js/wiki/Converting-from-JS-objects)

```
function fromJS(js) {
    return typeof js !== 'object' || js === null ? js :
        Array.isArray(js) ? 
            Immutable.Seq(js).map(fromJS).toOrderedSet() :
            Immutable.Seq(js).map(fromJS).toMap();
}

var output = fromJS({
    measurements: {
        length: 5,
        weight: 30
    }
}).toJS();
```
The above code outputs,

```
//output
[object Object] {
  measurements: [object Object] {
    0: undefined,
    1: undefined,
    2: undefined,
    3: undefined,
    4: undefined
  }
}
```

But it has to be printed as below.

```
[object Object] {
  measurements: [object Object] {
    length: 5,
    weight: 30
  }
}
```

What is wrong with the above custom `fromJS` function.

JSBin is [here](http://jsbin.com/zawixoj/edit?js,console)

**Note:** If we change the property `length` to `mLength`, it works as expected.

**Comment by philpl** [comment]
@jaganathanb The problem seems to be here: https://github.com/facebook/immutable-js/blob/master/src/Seq.js#L359

`Seq` is creating an `ArraySeq` if the object passed has a property `length` that is a number, which seems to be bollocks. I'm not sure why it isn't using `Array.isArray`.

You could just write a version that doesn't use `Seq` for plain objects:

```js
function fromJS(x) {
  if (Array.isArray(x)) {
    return new List(x).map(fromJS)
  } else if (typeof x === 'object') {
    return Object.keys(x).reduce((acc, key) => (
      acc.set(key, fromJS(x[key]))
    ), new Map().asMutable())
  }

  return x
}
```

This is of course not optimal, but it should work.

**Comment by ShirtlessKirk** [comment]
@philpl "I'm not sure why it isn't using `Array.isArray`

Because things like `NodeList`s and `arguments` aren't arrays, but are array-like. The problem here is that if there is a `length` property, to truly check if it is array-like the key of `length - 1` should be defined on the object:

```
var o = {
  '4': undefined, // array 'index' property, set to undefined to muck with simple checks like a[a.length-1] !== undefined
  length: 5,
  width: 30
}; // o.hasOwnProperty(o.length - 1) === true, so object is truly array-like
```

**Comment by philpl** [comment]
@ShirtlessKirk True! I didn't think of those. In that case, I'll open a PR for the extra check.

**Comment by leebyron** [comment]
In the meantime, `Seq.Keyed()` will not expect array-likes.
