### ISSUE TITLE
Iterable.reduce takes null as firstReduction if explicitly given.

### ISSUE THREAD

**Issue by lukasbuenger** [facebook/immutable-js#1028]
### What happened

I wrote a super simple higher order function for `List.reduce` in order for reduce to be composable in a Ramda context:

```js
const reduce = reducer => initialReduction => list => list.reduce(reducer, initialReduction); 
```

With this style, if I wanted to concat a list of strings, according to the docs I'd simply have to explicitly give the `null` as `firstReduction`:
```js
const concatToString = reduce((acc, val) => acc.concat(val))(null);
```
From the [docs](https://facebook.github.io/immutable-js/docs/#/List/reduce):
> If `initialReduction` is not provided, ***or is null***, the first item in the Iterable will be used.

Turns out, that `null` (or `undefined` for what it's worth) is still passed as `initialReduction` which leads to unwanted behavior or even to errors. 

### Cause of error

https://github.com/facebook/immutable-js/blob/master/src/IterableImpl.js#L206

The check on L206 only takes the number of passed arguments into account, otherwise blindly assigns `reduction = firstReduction` (L209). 

### Possible solutions

a. Fix the docs
b. Fix the check
###### Premise
```js
const reduce = reducer => initialReduction => list => list.reduce(reducer, initialReduction); 
const addValues = reduce((a, b) => a + b)(null);
const concatValues = reduce((a, b) => a.concat(b))(null);

const listOfNumbers = Immutable.List.of(1, 2, 3)
const listOfStrings = Immutable.List.of('Hunter', 'S.', 'Thompson');
const listOfLists = Immutable.List.of(
  Immutable.List.of(1, 2),
  Immutable.List.of(3, 4),
  Immutable.List.of(5, 6)
);
```

###### Cases
```js
// Expected 6
// This works as expected as the numeric value of `null` is 0.
addValues(listOfNumbers);
// 6
```

```js
// Expected 'HunterS.Thompon' 
addValues(listOfStrings);
// 'nullHunterS.Thompon'
```

```js
// Expected 'HunterS.Thompon' 
concatValues(listOfStrings);
// Uncaught TypeError: Cannot read property 'concat' of null
```

```js
// Expected [1, 2, 3, 4, 5, 6] 
concatValues(listOfLists).toJS();
// Uncaught TypeError: Cannot read property 'concat' of null
```

**Comment by leebyron** [comment]
Thanks for the report. The docs are out of date with the implementation which was updated to match the behavior of [Array#reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)
