### ISSUE TITLE
confused use the get() method passing the key of string/number

### ISSUE THREAD

**Issue by pannz** [facebook/immutable-js#1030]
[same question in stackoverflow](http://stackoverflow.com/questions/41299497/immutable-js-confused-when-use-get-method)

I'm using the immutable.js and redux in project, and I found an quite strange issue.

here is the code used in selector:
```
{
  dealDetail   : dealDetails.get(id.toString()).toJS(),
  dealTrackLog : dealTrackLogs.get(id).toJS()
}
```
First, the id is Number, in detail, I must pass string of id, and in trackLogs, on the contrary, it must be Number, otherwise will cause error, "cannot read property toJS() of undefined"

and I think the problem maybe in reducer, here is the code:

```
// dealDetailReducer
// const initialStateOfDealDetail = fromJS({})
let details = {}
action.data.details.map((detail) => {
  details[detail.id] = detail
})
return state.merge(fromJS(details))

 ...

// dealTrackLogsReducer
// initialStateOfDealTrackLogs = fromJS({})
if (state.get(action.data.id)) {
  // has id in state, update
  return state.withMutations(s =>
    s.update(
      action.data.id, 
      trackLog => trackLog.merge(fromJS(action.data.trackLogs))
     ) 
   )
}
// no id in state, just set, id : data 
return state.set(action.data.id, fromJS(action.data)
```

so, I'm hard to understand why and when to pass a Number/String ?

**Comment by philpl** [comment]
@pannz Are you aware that `details[detail.id]` converts the id to a string? In JS objects only take strings as keys.

Also, why are you creating a temporary `details` object at all? You could do:

```js
// dealDetailReducer
let res = state.asMutable()
action.data.details.forEach((detail) => {
  res = res.set(detail.id, detail)
})
return res.asImmutable()
```

Another thing, don't use `.map` for side effects. ;)

**Comment by leebyron** [comment]
Thanks for answering @philpl. The key detail here is that javascript object keys are always strings, even if the characters in the strings look like numbers, and a numeric key and a string key that has the same numeric characters as the number aren't the same.
