### ISSUE TITLE
import type immutable can not get any autocomplete tip

### ISSUE THREAD

**Issue by hufeng** [facebook/immutable-js#1031]
```js
//@flow
import type {Map} from 'immutable'

function test(state: Map<string, number>) {
    state. // can not get any tip
}

//@flow
import {Map} from 'immutable'

function test(state: Map<string, number>) {
  state. // yes, autocomplete tip
}

```

![image](https://cloud.githubusercontent.com/assets/533008/21467805/cef4acd0-ca34-11e6-8529-7acd614a9f7f.png)

![image](https://cloud.githubusercontent.com/assets/533008/21467808/de5c5ab0-ca34-11e6-8781-a0468a38dfd0.png)

```sh
# flow version
Flow, a static type checker for JavaScript, version 0.37.4
```

package.json
```javascript
{
  "name": "hello",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "immutable": "^3.8.1"
  }
}
```

.flowconfig
```ini
[ignore]

[include]

[libs]

[options]

```

**Comment by wokalski** [comment]
Map is not a type. It's a class as you can see [here](https://github.com/facebook/immutable-js/blob/master/type-definitions/immutable.js.flow#L489). For more info about `import type...` see [here](https://flowtype.org/blog/2015/02/18/Import-Types.html).
