### ISSUE TITLE
Record.map() mutates itself and return undefined

### ISSUE THREAD

**Issue by stepennwolf** [facebook/immutable-js#1033]
I use Immutable.Record for building the state of my app. So, in one of my transformations I used `recordInstance.map()` call and faced with unexpected behavior: it returns undefined, though mapped immutable object has been expected. Plus, it mutates itself after each `.map()` call.

I described that issue in the simple example below:
```javascript
const {Record} = require('immutable');

const Circle = Record({ x: 20, y: 30, r: 50 });
const circleRec  = new Circle;

console.log( circleRec.map((item) => item * 2) ); // OUTPUT: undefined
console.log( circleRec ); // OUTPUT: Record { x: 40, y: 60, r: 100 }
```

Although, with `Immutable.Map` it works fine:
```javascript
const {Map} = require('immutable');

const circleMap = Map({ x: 20, y: 30, r: 50 });

console.log( circleMap.map( (item) => item * 2).toJS() ); // OUTPUT: { x: 40, y: 60, r: 100 }
console.log( circleMap.toJS() ); // OUTPUT: { x: 20, y: 30, r: 50 }

```

I also added [Live demo on jsbin](http://jsbin.com/tahiqiseja/edit?js,console).

As I investigated, the issue is appear [there](https://github.com/facebook/immutable-js/blob/master/src/Operations.js#L802) (execution of `iter.constructor(seq)`: with `Map` it's ok, but with `Record` it returns nothing).  The call stack is next: `reify() -> mapFactory() -> map()`.

In my project I use `3.8.1`. Also tested on `3.0.0`, `3.7.6`. 
As platform used `Google Chrome  55.0.2883.95` and `node 7.0.0`.

**Comment by leebyron** [comment]
Unfortunately this is a consequence of the current implementation of `Record`. Using the collections higher-order API on them can lead to unexpected results.

Fixing this requires some rather dramatic changes to the implementation of `Record` and will require a major version bump of the library, so unfortunately for now there isn't much that can be done.
