### ISSUE TITLE
Please publish new version since typings are wrong on npm but right on source code

### ISSUE THREAD

**Issue by RafaelSalguero** [facebook/immutable-js#1034]
### What happened
Wrong type definitions on `Iterable.Map`, the mapper function have an undefined value which mess with typescript `strictNullChecks`, the source code is already fixed, it seems that the package was not published yet.

This is the code on `dist/immutable.d.ts` at line `1964` version `3.8.1`
```
    map<M>(
      mapper: (value?: V, key?: K, iter?: /*this*/Iterable<K, V>) => M,
      context?: any
    ): /*this*/Iterable<K, M>;
```

### How to reproduce

- Install the package with `npm i -S immutable`
- Check the file `node_modules/immutable/dist/immutable.d.ts` at line `1964` 

It looks like the source is already fixed at [line 2155](https://github.com/facebook/immutable-js/blob/master/dist/immutable.d.ts#L2155) the only thing missing is the version increment and package publication

**Comment by leebyron** [comment]
Coming very soon!

**Comment by bleshik** [comment]
Looks like not that soon :\
