### ISSUE TITLE
Provide an es import compatible build

### ISSUE THREAD

**Issue by ianks** [facebook/immutable-js#1044]
Looking at my build, currently Immutable takes up `139.14 KB`. I only use a few things from Immutable, so it would be nice to only pay for what I use.

# Proposed solution

Provide an `es6` build which compiles everything down except for modules, much like `react-router`, `reselect`, `redux`, etc. This way, the user can rely on their module bundler to perform tree shaking to only include what is neccesary.

Would this be possible to implement?

**Comment by simonkberg** [comment]
Worth noting is that Immutable greatly benefits from gzipping, so the actual size comes down to 15.21 kb (with level 9 compression). 
That said I definitely think it would make sense to provide a build preserving ES modules for tree-shaking purposes (and/or the top-level API as individual CJS modules we could import selectively).

**Comment by leebyron** [comment]
Yeah this would be great to have, but it's not easy to implement incrementally - some breaking changes would be necessary.

Specifically right now all types have a `toList()` and `toMap()` etc methods which convert between various collection types. That ties all of the library together and tree shaking typically isn't smart enough to trim prototype methods as well. A breaking major version change would be necessary to remove these methods to enable tree shaking.

However I don't actually think you would shave much from the ~15kb build already. That's roughly split into thirds: Map, List, and everything else.

**Comment by leebyron** [comment]
Merging into #317

**Comment by moravcik** [comment]
I have just one note regarding `toList()` and `toMap()` methods on all types. 

Maybe RxJS operators are similar case: `import 'rxjs/add/operator/switchMap'` adds `switchMap` operator to `Observable` interface in ES import/export friendly way.
