### ISSUE TITLE
takeLast creates new object even when it's a no-op

### ISSUE THREAD

**Issue by MichaelBlume** [facebook/immutable-js#1046]
### What happened

When acting on a List of <=n elements, takeLast(n) creates a new List. This can, e.g., lead to unnecessary React rendering. Be nice if it could just return this.

I realize takeLast needs to operate on Iterables, so counting may not always be cheap, but at least when applied to a List it seems like this path could be optimized.

### How to reproduce

foo = List([1, 2, 3])
bar = foo.takeLast(1000)
foo !== bar

**Comment by MichaelBlume** [comment]
Ah, using slice(-1000) solves the problem

**Comment by leebyron** [comment]
Thanks for the report! Same issue with `skipLast(0)`
