### ISSUE TITLE
Proposal for Flow Types: Change Variance of Collection Types to Covariant

### ISSUE THREAD

**Issue by DJCordhose** [facebook/immutable-js#1052]
I just noticed that the variance for collection types like List seem to be invariant in the flow declaration file:

https://github.com/facebook/immutable-js/blob/master/type-definitions/immutable.js.flow#L425

Since List is immutable what is the reason for not making it covariant?

That would mean instead of `class List<T>` why don't we have `class List<+T>`? 

This code illustrates this:

```javascript
let animals: List<Animal> = List.of();
let dogs: List<Dog> = List.of();

// why not allow this? 
animals = dogs;
```

I understand that there is a risk in doing the above for mutable data structures, but what is the problem here, as the data structure is immutable?

Have a look at this as a reference to variance in generics:
https://flowtype.org/docs/classes.html#polymorphism-and-type-parameter-variance

**Comment by leebyron** [comment]
No problem. It's just a new feature to flow and hasn't made it's way to immutable type definitions yet.

This would be a great task for anyone looking to contibute.

**Comment by DJCordhose** [comment]
Great, thanks a lot!
