### ISSUE TITLE
Feature request: Support for Maybe/Either monads

### ISSUE THREAD

**Issue by eirslett** [facebook/immutable-js#1060]
(Sorry if this has already been asked for, I searched through but couldn't find any other GitHub issues)

I assume people are already familiar with these constructs, from other languages like Haskell, Scala or Elm.
Should they be added to Immutable.js? I suppose it's mostly a political/philosophical/strategical question. I imagine the implementation itself should be viable.

There are loads of articles online, enumerating all the reasons why monads are the greatest thing since sliced bread, I'm sure people are familiar with these too. There are also arguments about how monads play better together with type systems - Immutable.js is working quite well together with Flow and TypeScript nowadays, which certainly helps a lot.

Immutable.js is one of the (if not the) most widely used libraries to solve the immutability problem in JavaScript; there is a whole ecosystem around it, tools like Redux DevTools understand it, and so on. One could always point to one of the millions of npm libraries that implement monad data structures, use that one instead. But one would lose out on the ecosystem part of it - one of the benefits with Immutable.js is that many tools understand it.

Here are some things one would gain:

Having a Redux state tree with Option/Maybe monads, so you don't get runtime exceptions like `Cannot read property 'foo' of null`.

The Redux Devtools would actually understand what Maybe/Either constructs are, so it could show them in the UI in a way that makes sense (remember issues [like these?](https://github.com/gaearon/redux-devtools/issues/51)).

Performance optimisations could be made, for example if you have a map of Option/Maybe's of strings; if you use whatever monad library is out there, you will not benefit from Immutable.js' optimized equality checking, which would slow down operations like diffing a Redux state tree.

One other nice thing; compile-to-JS languages that only deal with immutable types (I'm thinking of Elm in particular here) could be set up to use Immutable.js as their core library, which would make it much easier to interop with JavaScript. One could imagine an Elm application that is compiled into a Redux/Immutable.js/React application, for example.

**Comment by zalmoxisus** [comment]
> The Redux Devtools would actually understand what Maybe/Either constructs are, so it could show them in the UI in a way that makes sense (remember issues [like these?](https://github.com/gaearon/redux-devtools/issues/51)).

BTW, we managed to solve the UI representation, persisting and exporting for Redux DevTools extension, see [the release notes](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.12.1). However the suggestion I like the suggestion here.

**Comment by eirslett** [comment]
> BTW, we managed to solve the UI representation

That's my point - since Immutable.js is so widely used, Redux DevTools spent time building a good integration with it ;-) Supposedly the same would apply for prospective Immutable.js monads.

**Comment by leebyron** [comment]
My only concern is growing the scope of the library. Maybe types aren't really about immutable data. I would prefer there to be a really good stand-alone library that provided Maybe/Either, but if there is some interoperability concern that building into the library directly would solve, I'd love to hear it.

What sort of interoperability are you thinking about?

**Comment by leebyron** [comment]
I'm going to close this issue - I believe Maybe/Either/Option is a really cool construct, but I'd love to see such a thing take off as a general use library outside of this one first. Then if interoperability opportunities arise we can take those on in more detail.
