### ISSUE TITLE
Immutable.hash() is not a function

### ISSUE THREAD

**Issue by janusch** [facebook/immutable-js#1072]
### What happened

Would like to use `Immutable.hash()` to generate react keys is that a valid use case?
I found that `hashCode()` can be used instead on immutablejs data types, which might be just as good. Just wondering why the function is documented if it is not meant to be public, or why it isn't public?

### How to reproduce
```
import Immutable, { hash } from 'immutable';

Immutable.hash({1:1})
```
Thank you, and keep up the great work!

**Comment by leebyron** [comment]
Sorry about this. The documentation site is produced from master branch, and this change happened very recently and has not yet been released on npm. After the next release this function will be available

**Comment by janusch** [comment]
Thank you for the clarification, looking very much forward to the next release!

**Comment by dimitarg** [comment]
Is there a dev version / release candidate with which one can test this out? I tried switching to 4.0.0-rc.2 but I got too many typechecker errors and backed out.
Is 4.0 the next release planned? Or is there a 3.x-rc that could be used?
Thanks for your awesome work!
