### ISSUE TITLE
Is there any way I can convert an entire immutable tree into a string / binary form?

### ISSUE THREAD

**Issue by adamtal3** [facebook/immutable-js#1084]
The key is to be able to save an immutable tree to a database while benefiting from the node sharing.

I have a big undo array, most of the items share almost everything. In the browser's memory it takes a small amount of memory - I want to get a string/binary form of that tree so it's size will be as close as possible to the size it takes in the browser.

Could this be possible in any way?

Thanks for this great project!

**Comment by leebyron** [comment]
Unfortunately there's nothing like that today - but you could certainly try to build it!

When doing something like that along with Immutable.js, you would need to reach into the implementation details of the data structures to have access to node sharing.

If you want to get a string representation of the  *whole* collection, you can just use `JSON.stringify()` to get a JSON representation
