### ISSUE TITLE
Poor memory performance with lots of small maps

### ISSUE THREAD

**Issue by blablabla42** [facebook/immutable-js#1103]
### What happened

Creating a list of lot's of small maps has significant overhead contrasted to native types. For significantly small maps (< 5 key/value pairs) the overhead can be as much as 10x native types.

### How to reproduce

[Codepen with a generation script](http://codepen.io/anon/pen/wJogjg?editors=0010). Tweaking `i` changes number of items in a list, tweaking `j` changes number of elements in a map.

For `i = 4000` and `j = 4` Chrome's heap snapshot shows a 10x difference in memory usage.

![image](https://cloud.githubusercontent.com/assets/22395836/23671505/8319cdd4-0339-11e7-9954-dc544f3ed8bf.png)

### Use case

I'm using maps to represent sparse arrays of tabular data, instead of the more conventional list of lists. Apologies in advance if there's a better fitting data structure that I should be using.

**Comment by leebyron** [comment]
Can you share what version of the library you're using and also if this memory performance hit is still visible when using the latest build in the master branch?

**Comment by blablabla42** [comment]
Woops! Didn't make that clear, the codepen is referencing [3.8.1](https://cdnjs.cloudflare.com/ajax/libs/immutable/3.8.1/immutable.js) - will try to repro in master.

**Comment by leebyron** [comment]
I just swapped out the js version for the master build: https://rawgit.com/facebook/immutable-js/master/dist/immutable.min.js and see this:

<img width="692" alt="screenshot 2017-03-07 12 16 37" src="https://cloud.githubusercontent.com/assets/50130/23676029/21a3412e-0330-11e7-9bdb-90f09caf3f63.png">

That looks like the immutable copy is about 38% larger, certainly better than 10x :)

**Comment by leebyron** [comment]
Closing this issue just for queue management, but feel free to reopen if there's more to discuss or more discovered
