### ISSUE TITLE
Question about Lazy Sequences

### ISSUE THREAD

**Issue by eggsby** [facebook/immutable-js#112]
I'm confused about the best way to use Lazy Seqs in this library.

Is a user of this library meant to be able to construct them? For example, is it possible to make a lazy sequence of random strings?

Is there documentation or code examples somewhere of how it could be done?

The stuff in Sequence.js is pretty dense and I'm not sure where to get started, though it looks like Range.js and others just extend IndexedSequence.

If this is the case are there particular core methods to implement?
Is it possible to have something like `Sequence.create({ /* methods */ })` in the vein of `Object.create`?

-- Thanks,
Thomas Omans

**Comment by leebyron** [comment]
Closing this - but note that in v3 (released late last year), Seq got it's own API directly.

```js
var lazySeqOfStrings = Seq(["a", "b", "c");
```

Then you can use the full collections API on these.
