### ISSUE TITLE
Fix Prettier spread values

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#1124]
It's pretty common for us to use the `arguments` object but leave a comment to explain what the arguments represent. Prettier screws those up.

Desired:

```js
static of (/*...values*/) {
```

Produced:

```js
static of /*...values*/() {
```

This was introduced to the codebase in #1123 and hopefully when fixed (https://github.com/prettier/prettier/issues/882 ?) will require a manual pass to cleanup.

**Comment by vjeux** [comment]
I'm glad I went through recent issues and saw a link to here. The comment in parenthesis is fixed in 0.21 (not remember when) but looks like class methods are still broken. I'll open an issue for this!

```js
function f(/* a */) {}
class X {
  f(/* a */) {}
}
```

outputs

```js
function f(/* a */) {}
class X {
  f /* a */() {}
}
```

**Comment by vjeux** [comment]
Once https://github.com/prettier/prettier/pull/957 lands, 

```js
static of /*...values*/() {
```

will be normalized to

```js
static of (/*...values*/) {
```

so you'll just have to run prettier again on your codebase and it'll fix it.

**Comment by leebyron** [comment]
Sweet!

**Comment by vjeux** [comment]
Can be closed now :)
