### ISSUE TITLE
Alias length of size in List

### ISSUE THREAD

**Issue by alanzanattadev** [facebook/immutable-js#1126]
Hi,

I wonder why List don't have an alias of size : length. Arrays in javascript require require us to use "length" and immutable uses "size", with an alias, code could be compatible. I assume there's a reason, but maybe it's possible ? Do you think it would be a good idea ?

Thank you :)

**Comment by leebyron** [comment]
Unfortunately there is a lot of code out there, including built into the JavaScript core and in browsers that assumes if value.length is a number that it's safe to use value[1] style indexing, which only works on Arrays and not custom data structures. 

If List were to expose a length property then a lot of existing code would break. Note that the native Map and Set collections also expose value.size for the same reasons
