### ISSUE TITLE
Map::toObject() does not throw for non-string keys

### ISSUE THREAD

**Issue by gkz** [facebook/immutable-js#1132]
The docs for Map::toObject() specify that:

"Throws if keys are not strings."

https://facebook.github.io/immutable-js/docs/#/Map/toObject

However, it does not throw for non-string keys:

```
const x = {};
const y = {};

const m = Map([[x, 11], [y, 22]]);

console.log(m.toObject());
//=> {"[object Object]":22}
```

Furthermore, it might not make sense to throw for all non-string keys - certainly keys with typeof "object" it is worth throwing, but for numbers, booleans, etc. which are consistently converted to strings, it would not make sense to throw.

**Comment by leebyron** [comment]
Ah yes thanks this documentation note is long overdue to be removed. 

There are actually plenty of object types that have toString() methods that make for reasonable strings as well, so I agree that it shouldn't throw.
