### ISSUE TITLE
Typesafe typescript support

### ISSUE THREAD

**Issue by goloveychuk** [facebook/immutable-js#1142]
Hey. So I experimented with immutable and typescript.
So I have an idea how to make nested type safe immutable structures. And make typesafe mutations on it.
This here are some scratches.
```ts
import {Record, Map } from 'immutable';

class Y{
    x: string
}
class X {
    x: number
    c: number
}
class B {
    n: number = 34
    x: X
    y: Y
    z = Map<string, number>() as any as MyMap<number>
}
class A {
    b = IRecord(B)
    c: number = 12
}
interface MyMap<V> {
    [key: string]: V;
}

type IWrapper<T> = T & Wrapper<T>;

type Wrapper<T> = {
    set<K extends keyof T>(k: K, v: T[K]) : IWrapper<T>
    setIn<K extends keyof T, K2 extends keyof T[K]>(k: K, k2: K2, v: T[K][K2]) : IWrapper<T>
    setIn<K extends keyof T, K2 extends keyof T[K], K3 extends keyof T[K][K2]>(k: K, k2: K2, k3: K3, v: T[K][K2][K3]): IWrapper<T>
    setIn<K extends keyof T, K2 extends keyof T[K], K3 extends keyof T[K][K2], K4 extends keyof T[K][K2][K3]>(k: K, k2: K2, k3: K3, k4: K4, v: T[K][K2][K3][K4]): IWrapper<T>
   // .......
}
function IRecord<T>(t: {new() : T}): IWrapper<T> {
    const a = new t();
    const R = Record(a);
    const c = new R(a)
    return c as any as IWrapper<T>
}

const c = IRecord(A);
let c2 = c.set('c', 212)
let c3 = c2.set('c', 21232)
let c4 = c3.setIn('b', 'n', 1)
let c5 = c3.setIn('b', 'z', 'key', 12)
console.log(c, c2, c3, c4, c5)
```
Looks like the only requirement to declaring structures - don't forget to declare default values.
Do you like an idea?
Could it be merged to original immutable library in future after finishing it?

**Comment by leebyron** [comment]
Definitely interesting - I like the idea of using predefined tuples for `setIn` type safety.

The master branch contains some pretty dramatic improvements to Record vs what's currently on npm (to be released very soon), so start from those if you're working on concrete improvements, otherwise please feel free to test and submit pull requests when you have this working!
