### ISSUE TITLE
Flow-friendly method for filtering nulls

### ISSUE THREAD

**Issue by omerzach** [facebook/immutable-js#1146]
It'd be great to have a method on `Collection`s that turns a `Collection<?T>` into a `Collection<T>` by filtering out `null` and `undefined` values.

You can trivially do this with `xs => xs.filter(x => !!x)` or something along those lines, but Flow isn't smart enough to infer the desired return type.

Currently we're doing this with a utility function, but it'd be nice to have it as a method so it can be called in a sequence of other chained methods.

**Comment by leebyron** [comment]
I'd love to support this in a general way, but as far as I know Flow and Typescript don't support lifting a predicate function onto a collection like this. As soon as they add support, then your function as written would pick up that knowledge.

Until then I recommend a type cast or utility function as you're using today.
