### ISSUE TITLE
Collection#flatten not working as expected

### ISSUE THREAD

**Issue by haocenxu** [facebook/immutable-js#1160]
### What happened

Calling `flatten()` on nested collection does not flatten the collection properly.

### How to reproduce
```
var immutable = require("immutable")
const list1 = immutable.List().push('a').push('b');
const list2 = immutable.List().push('c').push('d');
let map = immutable.Map();
map = map.setIn(['level1', 'level2branch1'], list1);
map = map.setIn(['level1', 'level2branch2'], list2);
console.dir(map.toJS());
console.dir(map.flatten(0).toJS());
```

Since each list contain 2 items, one would expect the flattened obj would contain 4 items.

What to expect:
```
Obj:
0: "a"
1: "b"
2: "c"
3: "d"
```

What actually happend:
```
Obj:
0: "c"
1: "d"
```

version: immutable@3.8.1

I assume this is because the key is not unique? But the `List` can always have duplicated keys during flattening, is there a way to avoid this?

**Comment by leebyron** [comment]
Thanks for the report. Does this only occur when used with the `uuid` library, or will this also work for a simpler test case?

**Comment by leebyron** [comment]
Also could you please let me know what version of the library you're using

**Comment by haocenxu** [comment]
@leebyron sorry about the confusion, I updated the issue with version info and without `uuid`

**Comment by haocenxu** [comment]
FYI, this example produce expected result:
```
var immutable = require("immutable")
const list1 = immutable.List().push('a').push('b');
const list2 = immutable.List().push('c').push('d');
let list = immutable.List();
list = list.push(list1).push(list2);
console.dir(list.toJS());
console.dir(list.flatten(0).toJS());
```

output:
```
Array:
0: "a"
1: "b"
2: "c"
3: "d"
```
