### ISSUE TITLE
isImmutable is not a function

### ISSUE THREAD

**Issue by Bamieh** [facebook/immutable-js#1165]
### What happened

when calling `isImmutable(/* any value, ex: Immutable.Map()*/)` I get the following error:

```
Uncaught TypeError: isImmutable is not a function
```
### How to reproduce

The issue is reproducible even on the doc's console, or in Node, using the doc's syntax.

```javascript
import Immutable, {isImmutable} from 'immutable';
//or
const { isImmutable, Map, List, Stack } = require('immutable');

isImmutable([]);
 // or
Immutable.isImmutable(Immutable.Map())
```

What i noticed is that its not in the required Immutable object in the first place.
docs link:  https://facebook.github.io/immutable-js/docs/#/isImmutable

**Comment by snnsnn** [comment]
Yes, isImmutable function is not exposed. 

`const { isImmutable, Map, List, Stack } = require('immutable');
console.log(isImmutable); //undefined`

**Comment by leebyron** [comment]
What version of immutable are you using? The docs have been updated for the 4.0RC

**Comment by snnsnn** [comment]
4.0.0-rc.2

**Comment by leebyron** [comment]
Merging into #1167

**Comment by rossPatton** [comment]
So if we're on 3.8.1 what is the suggested method for checking if an object is Immutable?

I'm running into this problem at the moment

**Comment by Bamieh** [comment]
@rossPatton i looked it up from my old code, i used to use this method:
```javascript
Immutable.Iterable.isIterable(MY_ENTITY)
```

Since all immutables inherit from the `Iterable` class, checking isIterable on any object returns true if its immutable, false if its not.

**Comment by hickeroar** [comment]
Thanks for the suggestion. The docs really confused me on this topic. I didn't realize the docs were for 4.0, even though that's not complete yet.

**Comment by hanxu317317** [comment]
why not update npm's package to lasted version ????

**Comment by ElGoorf** [comment]
@Bamieh thanks for your solution, except it still returns true if I use, for your example `MY_ENTITY.asMutable()`, not sure what to do about that.

**Comment by Bamieh** [comment]
@ElGoorf can you show some code, i cannot really understand your case. `asMutable` is a method on immutableJS objects, so having this function implicitly indicates that you are using an immutableJS entity. additionally, calling `asMutable` on an immutable object returns an immutable object, with the only difference that it keeps assigning to itself rather than to a new object.

> Another way to avoid creation of intermediate Immutable maps is to create a mutable copy of this collection

**Comment by ElGoorf** [comment]
This is for unit testing and trying to track down bugs in code, and want to catch any functions which are returning Maps which have had `asMutable()` called on them, but not `asImmutable()`

**Comment by turnerhayes** [comment]
This is really confusing; as far as I can tell, nowhere on the docs site does it say they are for the RC version, so when I tried using `isIndexed` with `v3.8.1`, it failed. Can the docs site be updated to say what version they are for (or better yet, have a "available as of version X" annotation on the individual parts of the API that are different)?

In the meantime, I'm using `foo instanceof Collection.Indexed` for now; not sure if that's reliable or not.

**Comment by iamsolankiamit** [comment]
One way to find if the object is immutable of not is to check for `toJS` function on it.
```javascript
const jsObject = {};
console.log(!!jsObject.toJS) // false

const immutableObject = fromJS({});
console.log(!!immutableObject.toJS) // true
```

**Comment by turnerhayes** [comment]
That's not a great way; it gives false positives if the object happens to have a function called `toJS` but is not an immutable. It also doesn't distinguish between a `Collection.Indexed` and other types of Immutable collection, as `isIndexed()` does.
