### ISSUE TITLE
create functionality for structure with mix of lists and maps. 

### ISSUE THREAD

**Issue by sagswe** [facebook/immutable-js#1166]
let obj = fromJS({a:{}})

I need to create a structure like the following
{ "a": Map { "b": List [ Map { "c": "k" } ] } } in plain obj {'a':{'b':[{'c':'k'}]}}
I am trying to use setIn method on the immutable object

obj.setIn(['a','b',0,'c'],'k')
But its creating object like { 'a': Map { 'b': Map { 0: Map { 'c': 'k' } } } }"

how can u tell setIn method to see the numeric  value in keypath as List , not Map

If the obj = fromJS({'a':{'b':[{'c':'d'}]}}), the setIn method is working good for my case. 

codepen : https://codepen.io/sagswe/pen/vxJZmJ?editors=1112

**Comment by dispix** [comment]
I am also looking for a simple way to do that. It's pretty common in a complex structure to be in that situation where you need to set a value deeply nested in both objects and array. I don't know what's the best practice at the moment for that.

**Comment by leebyron** [comment]
`setIn()` will create Maps if you use a key path that is deeper than what currently exists.

If you'd like to create a List instead, you should first use `setIn()` or `updateIn()` with a shorter path to create the List, then follow up to create the Map.

```js
obj.updateIn(['a','b'], v => v || List()).setIn(['a','b',0,'c'], 'k')
```
