### ISSUE TITLE
undefined functions: isImmutable, isCollection, isKeyed, isIndexed, isAssociative, isOrdered, isValueObject

### ISSUE THREAD

**Issue by snnsnn** [facebook/immutable-js#1167]
### What happened

Hi @leebyron , It seems so bizzare but all **is** fuctions are undefined.

I checked isImmutable, isCollection, isKeyed, isIndexed, isAssociative, isOrdered and isValueObject, they are all undefined.

I used node v7.5.0. Updated to latest version but still got error.

There is another issue opened (#1165) but reports only isImmutable undefined. Sorry for the direct mention but because of the severity of the situation, I thought It would be better this way.

Regards

**Comment by leebyron** [comment]
What version of immutable.js?

**Comment by snnsnn** [comment]
4.0.0-rc.2

**Comment by leebyron** [comment]
Could you show me what code you're writing to get this issue? I can't reproduce. What I'm running:

```
mkdir test-project
cd test-project
npm init -y
npm install -SE immutable@rc
node
> isImmutable = require('immutable').isImmutable // namespace export
[Function: isImmutable]
> isImmutable = require('immutable').default.isImmutable // default export
[Function: isImmutable]
```

**Comment by leebyron** [comment]
Note that exporting these functions from the top level is new as of v4.0, so they'll only exist in the RC. Perhaps double check which version you're using?

**Comment by snnsnn** [comment]
Sorry, I didn't use **rc** flag. It was not mentioned in docs on website.

I am really sorry, in a rush I mixed up version numbers. My installed version was ^3.8.1 but mistakenly reported 4.0.0-rc.2.

Please can you update documentation about **rc** flag so you don't have to deal with similar problems.

Thank you for your time and effort.
