### ISSUE TITLE
Unclear how to accept Record types

### ISSUE THREAD

**Issue by jkk** [facebook/immutable-js#1172]
It's unclear how to annotate Record instances with Flow types:

```js
// @flow
import {Record} from 'immutable';

const TestRec = Record({a: 0, b: 0});

// Flow gives an error for the `rec` argument's type:
//
//   RecordClass
//   Ineligible value used in/as type annotation (did you forget 'typeof'?)
//   TestRec
//
// Is there a type that can be used here? `typeof TestRec`
// does not work, nor do any other variations I've tried.
function handleRec(rec: TestRec) {
  console.log(rec.a);
}

const myRec = TestRec();
handleRec(myRec);
```

If it's possible, examples in the docs would be great. Or, if it's not possible, documentation about the limitations of Records + Flow types would also be great. Happy to help write docs if I can figure out what's going on.

**Comment by leebyron** [comment]
The same issue affects TypeScript. I'm not sure how to improve this but would love some help.

**Comment by EChikunov** [comment]
@jkk 
In case of TypeScript I'm using it like this:

```js
import * as Imm from "immutable";
interface ITestRec {
    field1: number;
    field2: string;
}

const TestRec = Imm.Record<ITestRec>({field1: 0, field2: "default text"});

function someMethod(rec: Imm.Record.Instance<ITestRec>) {
    console.log(rec.field1);
}
```

@leebyron 
Offtop: v4 is a lot better in terms of typescript integration. Thank you guys, it removed a lot of frustration, nice job!

**Comment by jkk** [comment]
@EChikunov Unfortunately the equivalent in Flow doesn't seem to work.

I've tried a million variations, and also tried revising `immutable.js.flow`, but my static-typing skills are not strong enough.

**Comment by thessem** [comment]
I'd absolutely love an example of how to do what @EChikunov did in flow

**Comment by johnfn** [comment]
Hey guys,

I was able to get Records to work with TypeScript with no additional interface types.

Here's the implementation: https://gist.github.com/johnfn/12defda0d0548a4b165201f77618f36c (It's quite long because I copied a lot from other immutable.js definitions. If anyone knows how to clean it up, please feel free to do so.)

Here's a typical use case:

```
const record = MakeRecord({
    a: 1,
    b: foo,
});

console.log(record.a); //.a autocompletes, as does all methods on the Record class.
```

One really cool thing about this implementation is that you can even have functions with a `this` parameter that refers to the current object. Dunno if you'll want this, but it was super useful for me. You just need to use an anonymous class. Example:

```
const fancyRecord = MakeRecord{new class {
    a = 1;
    get getterForA() { return this.a; }
});

console.log(fancyRecord.getterForA);
```

Hopefully these definitions are as useful for you as they are for me!

**Comment by Daniel15** [comment]
This is what we do in my team at Facebook, although it's super hacky:
```js
class MyRecord extends Immutable.Record({
  foo: '',
  bar: 0,
}) {
  foo: string;
  bar: number;
}
```

What works:
 - Flow recognises `MyRecord` as a type
 - Flow knows that `.foo` returns a string and `.bar` returns a number

What doesn't work:
 - Pretty much everything else 😛 . `set`, `setIn` and friends are still untyped.

**Comment by gajus** [comment]
How are people using Immutable with Flow without this?

I am probably missing something. But without Record type I am only able to use higher level collections such (as `List`) and the "record" type itself remains mutable. Is that right?

**Comment by basherr** [comment]
@Daniel15 Angular Cli doesn't seem to compile this stuff I already have...! Is there any work around other then this..
```
import { List, Record } from 'immutable';
class MyRecord extends  Record({
  foo: '',
  bar: 0,
}) {
  foo: string;
  bar: number;
}
ERROR in Error encountered resolving symbol values statically. Symbol reference expected (position 17:31 in the original .
ts file), resolving symbol Customer in C:/xampp/htdocs/angular/src/app/customer/customer.ts
```

**Comment by LaurensRietveld** [comment]
@EChikunov Your example doesnt work for me (TS 2.3.1, Immutable rc2). I get a `Property field1 does not exist on type Instance<ITestRec>`. Only way I could get this to work was make a union type with ITestRec:

```
import * as Imm from "immutable";
interface ITestRec {
    field1: number;
    field2: string;
}

const TestRec = Imm.Record<ITestRec>({field1: 0, field2: "default text"});

function someMethod(rec: Imm.Record.Instance<ITestRec> & ITestRec) {
    console.log(rec.field1);
}

```

**Comment by LaurensRietveld** [comment]
For a more generic typescript solution I updated the record instance definition as such: https://github.com/facebook/immutable-js/compare/master...OpenTriply:recordTypes?expand=1

I'm not confident enough that all corner-cases are covered (although it works fine for me), so I haven't submitted it as PR.

**Comment by acusti** [comment]
@gajus I believe the 90% use case for immutable with flow is heavy use of `Map` and `List` collection types, which are all entirely immutable, as long as you instantiate them properly at every level of your data structure or generate them with `fromJS`. The types then look like:

```js
type Bar = List<Map<string, string>>;
type Foo = Map<string, number | string | Bar>;
const foo: Foo = Map({
  id: 42,
  qux: 'quux',
  bar: List([
    Map({ baz: 'baz' }),
  ]),
});
```

and every datum is 100% immutable. Is that what your question was referring to?

**Comment by gajus** [comment]
> I believe the 90% use case for immutable with flow is heavy use of Map and List

No, the question was how you'd describe Records and make them work with Flow.

If your code is 90% Map/ List then one of us doing something very wrong/ different, because pretty much everything relies on Records in my code base. Sure, Records are contained in Map/ List, etc. But if Records are not typed-checked, then it makes Immutable useless with types.

As I've mentioned in another comment, I've opted to completely drop Immutable from our workflow. Instead, I am enforcing covariance and `$ReadOnlyArray` with Flow. This is no where near as elegant as using Immutable, but until Record issue is solved, I put more importance on types than immutability.

**Comment by jkk** [comment]
Chiming in to say that my experience matches @gajus. It sucks to have to choose between Flow and Immutable, but I made the same choice as him, and it's definitely cumbersome. Flow + Immutable Records would be a holy-grail combo. Hoping someone is able to figure this out (I wish it could be me, but I don't have the skills or time).

**Comment by leebyron** [comment]
Closing this since this is dramatically better in the latest RCs.

You can now type inputs that expect Records using `RecordOf<T>`:

For your original example:

```js
type TestRecValues = {a: number, b: number}
const TestRec = Record({a: 0, b: 0});

function handleRec(rec: RecordOf<TestRecValues>) {
  console.log(rec.a);
}

const myRec = TestRec();
handleRec(myRec);
```

**Comment by jkk** [comment]
Yesssss!!! 🎉 Can't wait to give this a go!

**Comment by jonathanmarvens** [comment]
@leebyron My apologies if this information already exists elsewhere: When can we expect the __Immutable.js__ __v4__ release? I currently use __Immutable.js__ (__v3.8.2__) with __TypeScript__ and untyped records really suck 😕 …
