### ISSUE TITLE
Immutable.hash and arrays

### ISSUE THREAD

**Issue by myitcv** [facebook/immutable-js#1178]
Following on from #1176, specifically the second bullet point in [my comment](https://github.com/facebook/immutable-js/issues/1176#issuecomment-287000974)

Consider:

```typescript
import * as Immutable from "immutable";

let x = [1,2];

let a = Immutable.hash(x);
let b = Immutable.hash(x);

let c = Immutable.hash([1,2]);
let d = Immutable.hash([1,2]);
```

Now `a === b` holds, but `c === d` does not. 

If this is the intended semantics that's absolutely fine but can I request a couple of things:

* we update the docs to be clear on the behaviour of `Immutable.hash` on collection types (maps, arrays)
* we expose `Immutable.hashMerge` (or similar) which allows the caller to achieve the effect of `c === d` by iterating a collection type themselves

**Comment by myitcv** [comment]
@leebyron any thoughts here?

**Comment by leebyron** [comment]
Sorry for letting this issue sit.

This is definitely the intended semantics. Plain objects and arrays are mutative and use reference equality and their generated hash codes reflect that. Each instance will have a unique hash.

I just added a commit which updates the documentation for hash() to include this
