### ISSUE TITLE
Seq sort evaluated immediately.  Is this Intended behavior?

### ISSUE THREAD

**Issue by cmschuetz** [facebook/immutable-js#1181]
### What happened

Calling sort on a Seq evaluated the Seq immediately even though I expect it to not evaluate until the Seq is actually used.

### How to reproduce

When I run:

```
Seq([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).filter(x => {
  console.log('filtering');
  return x >= 5;
});
```

I see no output, which is expected behavior.  However, when I append a `.sort()` after the filter call:

```
Seq([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).filter(x => {
  console.log('filtering');
  return x >= 5;
}).sort();
```

 I receive the following output:

```
filtering
filtering
filtering
filtering
filtering
filtering
filtering
filtering
filtering
filtering
```

Is this intended behavior?  If so, do you have any suggestions for combining sort functions with lazy evaluation?

**Comment by zhaozy93** [comment]
Seq is lazy.
therefore the first scrip does not perform any work, because the resulting Seq is never used.
however in the second script, the first resulting Seq(filter method) will be uesd in sort method, so you will see filtering string was printed ten times.

**Comment by leebyron** [comment]
`sort()` is always an eager operation (much like `groupBy()`) - I've added this to the documentation
