### ISSUE TITLE
Add support for `for..of` in TypeScript.

### ISSUE THREAD

**Issue by MicahZoltu** [facebook/immutable-js#1183]
Based on some older issues, it appears that all collections here are Iterable.  However, it seems that they don't provide the necessary `Symbol.iterator` to make them work inside a TypeScript `for..of` loop.

Example:
```typescript
const myList = List<MyClass>();
for (const item of myList) {
	// item here is a `MyClass`
}
```

I don't understand the issue well enough, but it sounds like maybe adding support for this creates ES5 compatibility issues?  If so, can those issues be documented here so future readers searching the issue history can understand why this isn't supported?

If this is just an oversight, then consider this a feature request and entry-level documentation on requirements can be found here: https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html

**Comment by begincalendar** [comment]
This looks like it might be a non-trivial job.

It seems as if certain "lib.es6.d.ts" definitions have been duplicated into the type definition file for this project/package, which is my guess as to why this issue has arisen.

E.g. There is a definition for an `Iterator` interface, but it doesn't mirror the "lib.es6.d.ts" definition (e.g. it's missing the `Symbol.Iterator` property, which would be necessary for this particular issue).

I'm not familiar with the code, but would it not be wise to remove all the duplicate definitions and just rely on the ones from "lib.es6.d.ts"?

**Comment by begincalendar** [comment]
It seems as if this issue will be resolved when v4 is released.

v4 is currently in release candidate stage, but the type definitions are still buggy.

**Comment by leebyron** [comment]
Just FYI - support for iterators and for-of loops have been in the v4 builds for a while. A breaking change in v4 was requiring Typescript v2 which added this support.
