### ISSUE TITLE
Record#deleteIn is not implemented

### ISSUE THREAD

**Issue by cormacrelf** [facebook/immutable-js#1184]
In the new Record implementation, `Record#deleteIn` (and `#removeIn`) appears in the typescript definitions and logically should exist (since `updateIn` is implemented already), but in actual use it's `undefined`.

Presumably this is a one-liner to assign from `MapPrototype` in `Record.js`, since it already has updateIn and MapPrototype's version just uses this. I'd do it myself, but I haven't looked at the internals long enough to be sure. Is there a test for this functionality?

**Comment by philipp-spiess** [comment]
I already prepared a PR (#1179) to fix just that. :)
