### ISSUE TITLE
immutable.js.flow - map not found in Seq

### ISSUE THREAD

**Issue by dimitarg** [facebook/immutable-js#1187]
```map``` is not defined for Seq and this fails to typecheck:

```js
//@flow
declare var test: any
declare var expect: any
import {Seq} from "immutable"
test("hmmm", () => {


    const xs : Seq<number, string> = Seq.of("a", "b", "c")

  // this does not typecheck, map not found in Seq
    const ys :  Seq<number, string> = xs.map(x => x + x)

  // map is in fact in seq, the following assertion passes
    expect(ys.toJS()).toEqual(["aa", "bb", "cc"])
})
```

My env is:

immutablejs: 3.8.1
flow-bin: 0.42.0
flow-typed: 2.0.0

I am sorry if this is a known issue. I looked at the currently open ones and there does not seem to be anything related, though.

**Comment by fikriauliya** [comment]
Encountered the same issue. Even in the latest Flow definition, `map` is not defined in `Seq` not its parent classes

**Comment by leebyron** [comment]
`Seq` is an abstract type - try `Seq.Indexed<string>` which does have this type.
