### ISSUE TITLE
Map::updateAll for updating multiple keys in a map

### ISSUE THREAD

**Issue by xixixao** [facebook/immutable-js#1192]
For great success of #825 can we also add `updateAll`? Anything stopping this?

```es6
const base = Immutable.Map({x: 1, y: 2, z: 3});
const shrinked = base.updateAll(['x', 'z'], x => x + 1); // => {x: 2, y: 2, z: 4}
```
cc @vinnymac

**Comment by leebyron** [comment]
We're trying to keep the API surface area from growing much more than it has, especially for less common methods which can be easily implemented by the user. In this case:

```js
function updateAll(base, keys, op) {
  return base.withMutations(b => {
    keys.forEach(key => {
      b.update(key, op);
    });
  });
}
```
