### ISSUE TITLE
Online documentation out of date with npm module

### ISSUE THREAD

**Issue by snowinferno** [facebook/immutable-js#1197]
It has been 11 months since the last npm publish according to [the npm registry page](https://www.npmjs.com/package/immutable).

The documentation page lists an `isImmutable` method for checking if an object is an Immutable object.
This method does not exist anywhere in the published npm module.

Is there a reason that the docs and released module are out of sync?
If this basic method is missing, what else is present in the documentation but absent from the published module?

**Comment by gbroques** [comment]
The `isImmutable()` method listed in the docs threw me off as well. Docs should be updated accordingly.

**Comment by psenger** [comment]
Can I suggest someone put the Build Version in the documentation. It would be helpful to have some idea what version the documentation is in reference to. Thank you for your hard work, this product is  exceptional.

**Comment by JFGHT** [comment]
This issue is quite annoying. I thought isImmutable was in `v.3.8.1` because docs do not specify which build is that included in.

**Comment by th3fallen** [comment]
+1 docs are incredibly confusing atm

**Comment by wmill** [comment]
+1 Build versions aren't absolutely needed, but the docs should be accurate for the latest release instead of partially updated for the release candidates.

**Comment by Zerim** [comment]
Great library (thank you), but also just killed quite a bit of time reaching the same conclusion.

**Comment by leebyron** [comment]
I've updated the website build script to include a version number and only build when we push a new version.

The website will always reflect the most recent version pushed, even if that is a release candidate.
