### ISSUE TITLE
Browser vs. Node difference with getIn()

### ISSUE THREAD

**Issue by erikras** [facebook/immutable-js#1201]
I had a bug in my code that my test suite could not detect because ImmutableJS (`v3.7.3`) is failing silently on Node, but throwing an exception in the browser.

### What happened

If I set up a `Map` with a plain JS structure inside of it, and mistakenly try to access properties of the inner plain JS object with `getIn()`, I get back `undefined` on Node (`v7.7.4`), and an error in the browser (Chrome `58.0.3029.41 beta (64-bit)`).

### How to reproduce

```js
// reproduce.js
function runTest(Immutable) {
  // construct map with plain JS structure inside:
  const map = new Immutable.Map().set('a', { b: [1, 2, 3] })
  console.info(map.toJS())
  const result = map.getIn(['a', 'b'])
  console.info(result)
}

runTest(require('immutable'))
```

If I run `node src/reproduce.js`, the output is:

```
{ a: { b: [ 1, 2, 3 ] } }
undefined
```

If I run the same code in the browser, I get:

![browser](https://cloud.githubusercontent.com/assets/4396759/24709543/81303b96-1a1a-11e7-913d-e8cbd049b788.jpg)

### Cause

The code for `getIn()` I see in my `node_modules/immutable/dist/immutable.js` is:

```js
getIn: function(searchKeyPath, notSetValue) {
  var nested = this;
  // Note: in an ES6 environment, we would prefer:
  // for (var key of searchKeyPath) {
  var iter = forceIterator(searchKeyPath);
  var step;
  while (!(step = iter.next()).done) {
    var key = step.value;
    nested = nested && nested.get ? nested.get(key, NOT_SET) : NOT_SET;
    if (nested === NOT_SET) {
      return notSetValue;
    }
  }
  return nested;
},
```
and the one in my webpack-generated bundle on the browser is:
```js
getIn: function getIn(searchKeyPath, notSetValue) {
  var nested = this;
  var keyPath = coerceKeyPath(searchKeyPath);
  var i = 0;
  while (i !== keyPath.length) {
    if (!nested || !nested.get) {
      throw new TypeError(
        'Invalid keyPath: Value at [' +
          keyPath.slice(0, i).map(quoteString) +
          '] does not have a .get() method: ' +
          nested
      );
    }
    nested = nested.get(keyPath[i++], NOT_SET);
    if (nested === NOT_SET) {
      return notSetValue;
    }
  }
  return nested;
},
```

### Conclusion

Obviously, this problem is due to a user of the library doing something dumb, but I think it really should fail the same way in Node. It's unclear to me why it would not.

**Comment by anilreddykatta** [comment]
@erikras I tested this with version 3.8.1, 3.7.1 it is behaving consistently. [jsfiddle](https://jsfiddle.net/anilreddykatta/essvbkvz/).. For your reference. 

Let me know if it helpse

**Comment by erikras** [comment]
This must be related to how my webpack is bundling my code for the browser, then. Strange...
