### ISSUE TITLE
v4.0.0-rc.2 Record.equals breaks when passed null or undefined

### ISSUE THREAD

**Issue by cmschuetz** [facebook/immutable-js#1202]
### What happened

When passing in `null` or `undefined` into a record instance's `.equals` method, I receive a `TypeError: Cannot read property '_keys' of null` exception instead of the expected `false`.

### How to reproduce

```
const ABRecord = Record({ a: 1, b: 2 });
const myRecord = new ABRecord();

console.log(myRecord.equals(null));
console.log(myRecord.equals(undefined));
console.log(myRecord.equals(0);
console.log(myRecord.equals('');
console.log(myRecord.equals(false);
```

Output

```
TypeError: Cannot read property '_keys' of null
TypeError: Cannot read property '_keys' of undefined
false
false
false
```

**Comment by anilreddykatta** [comment]
I would like to take up this issue. Adding a check for null or undefined in equals should fix this?
