### ISSUE TITLE
Broken Online Documentation

### ISSUE THREAD

**Issue by fikriauliya** [facebook/immutable-js#1205]
### What happened

http://facebook.github.io/immutable-js/docs/ 's links are all broken

### How to reproduce
1) Open http://facebook.github.io/immutable-js/docs/
2) Click any links on the right hand side. e.g. `Collection` links to http://facebook.github.io/Collection

**Comment by jameskraus** [comment]
Check it again: 
![image](https://cloud.githubusercontent.com/assets/415057/24878951/20940280-1e03-11e7-8c98-2567337e6a85.png)

**Comment by jayjaycross** [comment]
@fikriauliya could you potentially reopen this issue?  I'm experiencing the same problem but only over a slow connection.

### How to reproduce
1. Set your browser to throttle (in Chrome devtools under the network tab set throttle to 2G)
2. Open http://facebook.github.io/immutable-js/docs/
3. Click any links on the right hand side. e.g. OrderedSet links to http://facebook.github.io/OrderedSet

<img width="640" alt="screen shot 2017-06-14 at 11 45 33 am" src="https://user-images.githubusercontent.com/1153686/27141913-8041a67a-50f7-11e7-92a4-315a7dd24ab8.png">

**Comment by fikriauliya** [comment]
I see, it happens if `bundle.js` not yet loaded and one of the links are clicked.
However, I am pretty sure at the time it happened to me, my Internet connection was good. Perhaps something happened on server s.t. `bundle.js` was not returned to me.

Yes, as @jayjaycross mentioned, this problem may apparent on those having bad Internet connection (9-10 seconds to download `bundle.js`). Since the page is apparently server rendered, visitors may clicks any of the links (and encounter error) within those periods.

**Comment by MrOrz** [comment]
Currently the following docs is totally not accessible at all.

http://facebook.github.io/immutable-js/docs/#/List
http://facebook.github.io/immutable-js/docs/#/OrderedSet
http://facebook.github.io/immutable-js/docs/#/Stack

But other docs are OK (at least reloading browser with the URL works).

### Steps to reproduce
1. click any of the link above.

### Expected
Documentation of List / OrderedSet / Stack, respectively.

### Current
This page is shown instead: http://facebook.github.io/immutable-js/docs/#/

**Comment by leebyron** [comment]
Another example of breakage is if, in the side bar you click "Seq" then "Seq.Keyed", the sidebar no longer shows nested types
