### ISSUE TITLE
4.0.0-rc: Why change toJSON behavior?

### ISSUE THREAD

**Issue by namuol** [facebook/immutable-js#1206]
From the [4.0.0-rc-1 release notes](https://github.com/facebook/immutable-js/releases/tag/v4.0.0-rc.1):

> The `toJSON()` method is now a shallow conversion (previously it was an alias for `toJS()`, which remains a deep conversion).

To avoid any confusion when upgrading from 3 => 4, why not replace `toJSON()` with a more descriptive name such as `toShallowJS()`?

**Comment by anilreddykatta** [comment]
@namuol Valid point. But when you are using immutable in combination with any of the tools which requires `JSON` representation, like `redux-devtools` `toJSON` is called and corresponding `return` value is printed

**Comment by leebyron** [comment]
`toJSON()` is a method intended for and called by the built-in `JSON.stringify()` (https://www.ecma-international.org/ecma-262/8.0/index.html#sec-serializejsonproperty), so renaming it would cause `JSON.stringify()` to fail.

Originally it was added with an implementation identical to `toJS`, however that was a mistake, and caused very slow `JSON.stringify()` performance. This fixed that issue by changing the implementation of `toJSON()` however it does not change the existing behavior of `toJS()`

**Comment by ianstormtaylor** [comment]
@leebyron do you have any more information on why a deep `toJSON` results in slow `JSON.stringify` performance? I'm trying to debug something and think this might be an issue, but I want to double check my assumptions. Thank you!
