### ISSUE TITLE
Map includeAll (invert deleteAll)

### ISSUE THREAD

**Issue by wizzl35** [facebook/immutable-js#1207]
Forgive me if I am asking for something in the works (I did search).  There are times when I would like to get a new Map, but for it to only include entries with a set of keys that I pass back to it.  Something that is basically the same same as [lodash's pick function](https://lodash.com/docs/4.17.4#pick).

**Comment by anilreddykatta** [comment]
@wizzl35  I guess you are looking for this [https://github.com/facebook/immutable-js/wiki/Predicates](https://github.com/facebook/immutable-js/wiki/Predicates)

**Comment by wizzl35** [comment]
Yup, that would it.  I have come across that before I remember a while back.  Maybe this should go into the official docs on the site.
