### ISSUE TITLE
4.0.0-RC: about flowtypes

### ISSUE THREAD

**Issue by xareelee** [facebook/immutable-js#1209]
I'm using immutable.js `4.0.0-rc.2` with flowtype `0.40.0` (installed by `yarn`). I read the docs:

> Installing immutable via npm brings with it type definitions for Flow (v0.39.0 or higher) and TypeScript (v2.1.0 or higher), so you shouldn't need to do anything at all!

but my following code doesn't work with **flowtype**:

```js
const initialState = Immutable.fromJS({
  selected: 'US',
});

initialState.set('selected', 'UK');
```

```
$ flow

 10: initialState.set('selected', 'UK');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `set`. Method cannot be called on
 10: initialState.set('selected', 'UK');
     ^^^^^^^^^^^^ mixed
```

How should I add the type to `initialState`?

**Comment by anilreddykatta** [comment]
@xareelee As it is returning `mixed` type, we must check for the type of return value or add typeof
```
if (typeof initialState === 'object') { // not a very good solution but works
  initialState.set('selected', 'UK)
}
```

Better way would be to import types 
```
import type { Map } from 'immutable'
const initialState : Map = Immutable.fromJS({ selected: 'US' })
initialState.set('selected', 'UK')
```

Let me know if it helps

**Comment by xareelee** [comment]
@anilreddykatta thanks for your reply.

What if I have a specific structure of `state`:

```js
// exact type
type State = {|
  default?: string,
  selected: string,
  list?: Array<number>
|}

const state: State = {
  selected: 'yes'
}

// What is the type of immutableState?
const immutableState = Immutable.fromJS({
  selected: 'US'
})
```

What is the type of `immutableState`?

Is that possible to check whether the key is valid for the type when using `set` or `get`? For example:

```
immutableState.set('selected', 'UK') // Good

immutableState.set('selected', 101) // Error! The value type doesn't match the type `State`. It should be a string type.
immutableState.set('select', 'UK') // Error! The key `select` doesn't match the type `State`.
```

**Comment by anilreddykatta** [comment]
@xareelee You are talking about two different objects here. 
```
const state: State = { // Plain JS object with flow definition
  selected: 'yes'
}

const immutableState = Immutable.fromJS({ // This will be immutable Map
  selected: 'US'
})
```

But if I understand your question correct. Do you want to define specific structure for the immutable Map itself? Whenever you initialize `immutable Map, List, etc. ` you will get flow types defined for them. I don't think currently defining structure how immutable should handle types. 

In my opinion, it goes one-way library authors (in this case immutable) defines what are the expected input `types` and return `types` of any particular function. I don't currently see a way we can do this.

I would love to know if you find solution for this 😄

**Comment by xareelee** [comment]
@anilreddykatta Thank you for paying attention on this issue.

My goal is simple: I'm trying to use Redux with Immutable.js and Flowtypes in the best practice way.

I want to use Immutable objects for the state of Redux, and add the types to check the code when accessing the immutable objects.

```js
// Define the exact type for the state.
type State = {|
  default?: string,
  selected: string,
  list?: Array<number>
|}

// Q1: What is the type of immutableState?
const immutableState = Immutable.fromJS({
  selected: 'US'
})

// Q2: How to check the accessor keys and values with flowtypes
immutableState.set('selected', 'UK') // Good
immutableState.set('selected', 101) // Error! The value type doesn't match the type `State`. It should be a string type.
immutableState.set('select', 'UK') // Error! The key `select` doesn't match the type `State`.
```

I want to check the types when accessing immutable objects.

If it can't, I want to know how to leverage flowtypes with immutable objects.

**Comment by anilreddykatta** [comment]
@xareelee Sounds interesting! I will update you

**Comment by stunaz** [comment]
@xareelee I read a lot that you just can't using `Map`. You have to use `Record`. But I couldnt find any clear examples so far

**Comment by pbomb** [comment]
Even Immutable.Records are not able to be typed really well, it seems. I ended up creating the [flow-immutable-models](https://github.com/pbomb/flow-immutable-models/) library to try to get the best of immutable and typed data structures in our redux applications. So far, it's been a pretty good mix, although it definitely has its tradeoffs. @xareelee, if you're up for it, I'd love to get some more feedback on this approach and curious if it works well for your use case.

**Comment by xareelee** [comment]
@pbomb Actually, I'm going to give up using Immutable.js. Flowtype provides [covariant properties](https://flow.org/en/docs/frameworks/redux/#toc-typing-redux-state-immutability) for the immutable state, and I'd like to try it.

**Comment by gajus** [comment]
> @pbomb Actually, I'm going to give up using Immutable.js. Flowtype provides covariant properties for the immutable state, and I'd like to try it.

Same here. `$ReadOnlyArray<>`, covariant properties and [`deep-freeze`](https://www.npmjs.com/package/deep-freeze) does the job.

Shame that Immutable.js is not an option.

**Comment by acusti** [comment]
As of `4.0.0-rc.3`, the `RecordInstance` type is available and seems to resolve much of the Record type-checking pain of the past: https://github.com/facebook/immutable-js/pull/1276#issuecomment-320791436

**Comment by leebyron** [comment]
Record typing in the latest release is now dramatically better thanks to the new `RecordOf<T>` flow type.

(I'm also a fan of using covariant flow object types!)

`fromJS()` isn't well typeable, which is why it looks to you to cast to something more useful. I suggest using the `List()` and `Map()` constructors directly to get excellent flow types
