### ISSUE TITLE
Example doesn't work for Seq.update()

### ISSUE THREAD

**Issue by Altiano** [facebook/immutable-js#1210]
The example here : https://facebook.github.io/immutable-js/docs/#/Seq/update DOESN'T work.

<img width="373" alt="1" src="https://cloud.githubusercontent.com/assets/8316282/25034233/8e7029c0-2117-11e7-9a8c-14d1da90972f.png">

**Comment by leebyron** [comment]
Looks like runkit was embedding an older version of immutable - this API works in the 4.x builds
