### ISSUE TITLE
v4.0.0-rc2: Record: invalid Flow

### ISSUE THREAD

**Issue by oreqizer** [facebook/immutable-js#1211]
### What happened

Record classes are not correctly recognized as classes. `typeof`, extending and nominal typing doesn't work correctly and no constructor is found.

### How to reproduce

```js
/* @flow */
import { Record } from 'immutable';

const Class = Record({ a: 'asd', b: 123 });

const val = new Class();  // NOPE, no constructor found in RecordClass

class AnotherClass extends Class {
  // NOPE cannot extend
}
```

Fixed in https://github.com/facebook/immutable-js/pull/1193

**Comment by leebyron** [comment]
In general, using `new` is discouraged for records - those are factory functions. Merged that fix PR, but know that the flow types are less correct in that case
