### ISSUE TITLE
Online documentation doesn't work in console. 

### ISSUE THREAD

**Issue by lowe** [facebook/immutable-js#1212]
Related to issue #1197, documentation examples involving `is*()` functions do not work when tried out in the doc page console. 

Repro: 

1. browse to [docs](http://facebook.github.io/immutable-js/docs). 
2. open console. 
3. Try first line of first code example (under `fromJS` API doc):
```
> const { fromJS, isIndexed } = require('immutable')

> fromJS
function ...

> isIndexed
undefined 
``` 

Suggested fixes: 
* put 4.0.0-rc2 in the bundle, leave docs alone. 
* leave bundle alone, make docs consistent with 3.8.1

**Comment by leebyron** [comment]
Yeah this is super confusing, isn't it. I'll fix this
