### ISSUE TITLE
takeUntil/takeWhile inclusive

### ISSUE THREAD

**Issue by shiptoncraig** [facebook/immutable-js#1213]
I've been working with Lists for a good couple of weeks and keep finding myself looking for a takeUntil/takeWhile style function that includes the element that satisfies the predicate.

I can achieve it in other ways that are more verbose, e.g.:
- Reversing the list, applying skipUntil/skipWhile and reversing again.
- Finding the index of the element and using index-based functions to slice the list.

I wanted to know if this would be out-of-scope of this project, or if I've completely overlooked an operation that would do it.

**Comment by leebyron** [comment]
We're trying to keep the scope of operations from growing further, and I think this is probably an edge case.

I would recommend using `reduce()` to implement this efficiently, but the reversing trick sounds clever. As long as you use Seq before doing the reversal, it should have low overhead
