### ISSUE TITLE
Backporting Flow default export fix to v3.8.1

### ISSUE THREAD

**Issue by arjun-menon** [facebook/immutable-js#1214]
My company uses Immutable.js v3.8.1 in production. However, v3.8.1 has a flow-related bug (#854), that was fixed in v4.0.0 by #961. We recently started using Flow, and require this bug fix. Since we have a large number of active users, we are uncomfortable moving to the RC release of 4.0.0. Would it be possible to back-port this bug fix to 3.8.x?

**Comment by leebyron** [comment]
Unfortunately not, we're avoiding branched patch fixes when possible.

On v3.x builds you can circumvent this issue with:

```js
import * as Immutable from 'immutable';
```

**Comment by arjun-menon** [comment]
Alright. We ended up patching the Immutable.js Flow libdef file, and adding it as a custom libdef. But perhaps the approach you suggested might have been simpler/cleaner.
