### ISSUE TITLE
Record constructor argument type

### ISSUE THREAD

**Issue by a-x-** [facebook/immutable-js#1218]
Record constructor expects js plain object argument type only now.
But I expect argument of any Map-like Immutable types (Map, Record, OrderedMap, etc).

**Comment by a-x-** [comment]
my ugly code:
```js
    this.dicts = Record(DICTS.toJS())(Map(DICTS).map(dict => toOptions(dict)));
```

**Comment by a-x-** [comment]
And I expect Record has `.map` and another methods like this.

`record.map(v=>v)` returns `undefined` now.

**Comment by a-x-** [comment]
my Record#map implementation:
```es6
Record.prototype.map = function RecordMap(fn) {
  return Map(this).reduce((record, val, key) => record.set(key, fn(val, key)), this);
}
```

**Comment by leebyron** [comment]
Records are not collections, and don't have methods like `map` and `reduce` in the master builds (v4.x).

If you update to v4.x, you should find that Records can now be created from any collection, not just plain objects.
