### ISSUE TITLE
Range#map

### ISSUE THREAD

**Issue by a-x-** [facebook/immutable-js#1219]
I want to use `Range` like python's `range`:

`Range(0, 3).map(doSmthg)`

I have to write out `Range(0, 3).toList().map(..)` now.
Is that performant?

Do you think Range should have Seq interface methods?

**Comment by Daniel15** [comment]
`Range` does have a `map` method already - It returns `Seq.Indexed` which has all the Seq methods.

**Comment by a-x-** [comment]
ok, thank you
