### ISSUE TITLE
sortBy fails to sort arrays containing both numbers and strings

### ISSUE THREAD

**Issue by efonsell** [facebook/immutable-js#1221]
When array contains numbers and strings in mixed order the sorting does not work as I expect. Only subsequent numbers and subsequent strings are sorted:

```javascript
console.log(Immutable.fromJS([1, 0, 'foo', 'bar', 4, 2]).sortBy(i => i).toJS());
=> [0, 1, "bar", "foo", 2, 4]
```

I would expect the same result as in plain javascript:

```javascript
console.log([0, 1, "foo", "bar", 2, 4].sort());
=> [ 0, 1, 2, 4, "bar", "foo" ]
```

**Comment by leebyron** [comment]
Sorry for closing this issue, but I wasn't able to reproduce the problem.

If you could please submit a pull request with a failing test case, that would be helpful
