### ISSUE TITLE
v4.0.0-rc2 List.size: Invalid flowtype definition

### ISSUE THREAD

**Issue by EvHaus** [facebook/immutable-js#1225]
### What happened

The following code using `immutable@v4.0.0-rc2`:

```
import Immutable from 'immutable';
const stageCount = Immutable.List([]).size;
```

Returns the following Flowtype error:

```
2: 		const stageCount = Immutable.List([]).size;
     		                                      ^^^^ property `size`. Property not found in
2: 		const stageCount = Immutable.List([]).size;
     		                   ^^^^^^^^^^^^^^^^^^ List
```

This is unexpected since `Immutable.List` definitely has a `size` property defined.

### How to reproduce

Using `flow-bin@0.46.0` and `immutable@v4.0.0-rc2`:

**Comment by eirslett** [comment]
I encountered the same. I use a helper function that casts via `any`:

```javascript
function listSize<T: im.List<*>> (list): number {
  return (list: any).size;
}

const stageCount: number = listSize(List([]));
```

But that's just a temporary hack/workaround, we need this to work with immutable-js directly...

**Comment by XaxisJosh** [comment]
I'm having the same issue but on OrderedMap. Seems like size should be on Collection so it gets inherited by all the other collections?

**Comment by leebyron** [comment]
Thanks for the report. It's fixed in master, so you can use the latest build (https://github.com/facebook/immutable-js/tree/npm) if you like, but a new RC publishing the fix is coming very soon
