### ISSUE TITLE
Flow types - Indexable signature not found in List

### ISSUE THREAD

**Issue by smozely** [facebook/immutable-js#1227]
Hi there,

Just highlighting a case I've found with flow, that works, but flow complains about 

take this code ... 
```
    const [first, second] = Immutable.List.of('a', 'b');
    console.log(first); // Logs 'a'
    console.log(second); // Logs 'b'
```

Works as expected ... but flow will complain with "Indexable signature not found in List" 

Would be useful to have flow not complain, raising without a PR because I don't know enough about complex types in flow to implement a fix it quickly (hoping someone else does)

**Comment by leebyron** [comment]
I suggest opening this bug against the Flow project - unfortunately this is not solvable from this codebase
