### ISSUE TITLE
There are still several references to Iterable in the typescript definitions

### ISSUE THREAD

**Issue by jbrownson** [facebook/immutable-js#1231]
I first noticed this on a definition of `concat`:

```typescript
      /**
       * Returns a new Seq with other collections concatenated to this one.
       */
      concat<C>(...valuesOrCollections: Array<Iterable<C> | C>): Seq.Indexed<T | C>;
```

Seems like it should be

```typescript
      /**
       * Returns a new Seq with other collections concatenated to this one.
       */
      concat<C>(...valuesOrCollections: Array<Collection.Indexed<C> | C>): Seq.Indexed<T | C>;
```

I searched through the file and found a large number of other Iterables that I believe should be Collections now.

Or are these actually supposed to be Iterables?

**Comment by leebyron** [comment]
These are supposed to be `Iterable` - they refer to the ES iterable protocol: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols
