### ISSUE TITLE
Trap in forEach behavior

### ISSUE THREAD

**Issue by mburnell** [facebook/immutable-js#1234]
I'm aware this is documented behaviour, that there was probably a reason the call was designed this way, and that changing it probably constitutes an unpalatable breaking change, but...

It's really easy to accidentally stumble into the feature of "forEach" that ceases iteration if it encounters a false value. forEach accepts a function, and in ES6 and TS, it is customary to use lambdas / fat arrow functions instead of functions, and it is customary, when the lambda is a single line, to omit the curly braces. The primary use of forEach is mutation. Mutations are often achieved using assignments. Assignments return the value assigned. Hence, assigning a false value in a "naked" (un-curly-braced) lambda will terminate iteration.

Consider the following:

let y;

someOrderedSet.forEach(x => y = x);

someOrderedSet.forEach(x => { y = x; });

Many people would assume the two usages above are equivalent, but because of the "terminate on false" behaviour, they are not. Does the utility of the "terminate if false" behaviour outweigh the sharpness of this edge? Am I doing JavaScript wrong with all these lambdas without braces?

**Comment by leebyron** [comment]
I agree with you that diverging from `Array.forEach` behavior was probably more confusing than helpful, unfortunately many rely on this behavior now. I've added this condition to the documentation in hopes of guiding people from this, but this would be a difficult breaking change to make.
