### ISSUE TITLE
Data lost when zipping two arrays of not same length

### ISSUE THREAD

**Issue by vcarel** [facebook/immutable-js#1235]
I'm using the List.zip method to transform a list of items into a list of pairs:

    const Immutable = require('immutable')
    
    const hits = Immutable.fromJS([{ price: 1 }, { price: 2 }, { price: 3 }, { price: 4 }, { price: 5 }])
    
    const evens = hits.filter((value, index) => index % 2 === 0)
    const odds = hits.filter((value, index) => index % 2 === 1)
    const pairs = evens.zip(odds)
    
    console.log('evens', evens.toJS())
    console.log('odds', odds.toJS())
    console.log('pairs', pairs.toJS())

Which produces:

    evens [ { price: 1 }, { price: 3 }, { price: 5 } ]
    odds [ { price: 2 }, { price: 4 } ]
    pairs [ [ Map { "price": 1 }, Map { "price": 2 } ],   [ Map { "price": 3 }, Map { "price": 4 } ] ]

The last element has been lost, because the events list a longer than the odds one. I would expect to get instead something like:

    pairs [ [ Map { "price": 1 }, Map { "price": 2 } ],   [ Map { "price": 3 }, Map { "price": 4 } ] ,  [ Map { "price": 5 }, undefined ] ]

(see https://github.com/jashkenas/underscore/issues/1237)

**Comment by dimitarg** [comment]
Null and Undefined don't compose. If the .zip call is part of a larger map / flatMap / reduce / filter / etc pipeline, how should those operations behave in the presence of null and undefined?

**Comment by vcarel** [comment]
@dimitarg I don't get your point. Could you provide a use case ?

IMO, in a map / reduce / filter operation, you may handle null and undefined references in the callback.

**Comment by axelg12** [comment]
I'm experiencing the same thing. I was looking at the stackoverflow question listed below which suggests using interleave but the same problem exists there too that is if the two lists aren't of the same size.  But according to the top voted answer it seems like this use to work.

https://stackoverflow.com/questions/42832612/immutable-js-flat-zip-two-lists

So what I'm trying to do in essence: 
```
const a = List([1,2,3, 4]);
const b = List([a,b,c]);

const c = a.interleave(b) // Or zip
// Expected [1, a, 2, b, 3, c, 4] 
// Actual [1, a, 2, b, 3, c]
```

**Comment by leebyron** [comment]
This is intentional as `zip` creates a collection that is guaranteed to have an item from each collection. In the master builds, `zipAll` was added which zips for the longest
