### ISSUE TITLE
Immutable.Map Flowtype

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/immutable-js#1237]
Is there a way to type a Immutable.Map yet with the latest version of flow-type and is this on the roadmap?

If its possible, is there an example I can look at?

**Comment by athomann** [comment]
I think you can get the type by doing. 
`import type { Map } from 'immutable';`

**Comment by lifeiscontent** [comment]
@athomann do you know how to use that type then?

**Comment by athomann** [comment]
I think You can do something like `Map<string, string>`.  Related issue: https://stackoverflow.com/questions/37033339/how-to-describe-immutable-js-map-shape-with-flow

**Comment by leebyron** [comment]
Maps can be flow typed with `Map<KeyType, ValueType>`

Thanks for answering @athomann !
