### ISSUE TITLE
immutable 3.8.1: TypeScript definitions for Map.get and Map.update are wrong.

### ISSUE THREAD

**Issue by jsdw** [facebook/immutable-js#1238]
Hello there,

Thanks for the great library.

I have just started using immutablejs, and have noticed that the type of `Map.get` is

```
(key: board.Board, notSetValue?: IssuesByBoard | undefined): IssuesByBoard
```

But since get can fail to return output, this is a lie. I would tack an `| undefined` on the end.

The type of map.update is:

```
    update(updater: (value: Map<K, V>) => Map<K, V>): Map<K, V>;
    update(key: K, updater: (value: V) => V): Map<K, V>;
    update(key: K, notSetValue: V, updater: (value: V) => V): Map<K, V>;
```

But from my experimentation, the updater function can also receive `undefined` if the value you ask to update is not found and you don't provide a notSetValue (This would have caused issues as I was initially under the impression due to the types that update does nothing if the key isn't found).

**Comment by radix** [comment]
I can work on a PR for this if it's deemed by the Immutable developers that it would be accepted.

**Comment by radix** [comment]
Actually, it looks like someone has already fixed Map.get (or really, Iterable.get and Indexed.get) in master / the 4.0 release candidates! very happy to see that. It doesn't look like the `update` method has been fixed, though.

**Comment by leebyron** [comment]
Sorry, we're not going to do point releases to the v3.x builds, we're fixing these issues on v4.x
