### ISSUE TITLE
Attaching methods / a custom JS prototype to a Record type?

### ISSUE THREAD

**Issue by manuel** [facebook/immutable-js#124]
I'd like to use immutable-js records for all data types in my program.  One thing I'm missing is the ability to attach methods to records, so they can be used like JS objects of a custom type.

**Comment by dminkovsky** [comment]
@manuel How did you do this? By passing functions as values in the object passed to `Record()`? Thanks

**Comment by manuel** [comment]
Just setting them directly on the prototype of a newly created record IIRC.
