### ISSUE TITLE
Flow doesn't type check my Record properly

### ISSUE THREAD

**Issue by eirslett** [facebook/immutable-js#1240]
I've tried creating a new `Person` record, and added a couple of test cases for it that should fail the static type checking.

```javascript
// @flow
import { Record } from 'immutable';

type PersonFields = {
  name: string,
  age: number
};

// I also tried this, which didn't work; Use Class<PersonType> instead of Class<*>
// import type { RecordInstance } from 'immutable';
// type PersonType = RecordInstance<PersonFields> & PersonFields;

const Person: Class<*> = new Record(({
  name: '',
  age: 0
}: PersonFields));

const john = new Person({
  name: 'John',
  age: 'invalid' // should give a type error ('invalid' is not a number), but it doesn't
});

// Should give type error ('invalidProperty' cannot be set), but it doesn't
const updatedPerson = john.set('invalidProperty', 4);

// Should give type error ('invalid' doen't exist), but it doesn't
console.log(john.get('invalid'));
```

Is this a bug in the flow definitions for Immutable, or have I used the API wrong? Is there a good example somewhere of how to define a new `Record` with a corresponding flow type for it?

**UPDATE**
For the record, I was using immutable@4.0.0-rc.2 and flow 0.47.0.

I had this in my .flowconfig:

```
[libs]
node_modules/immutable/dist/immutable.js.flow
```

When I removed that line, suddenly it type checked as expected. So this might be a Flow configuration problem on my side. Are we supposed to never include flow typings from node_modules?

**Comment by eirslett** [comment]
This still fails though:

```javascript
const john = Person({
  name: 'John',
  age: 20
});

function increaseAge(person: Person): Person {
  return person.update('age', i => i + 1);
}

console.log(increaseAge(john));
/* FLOW ERROR:
function increaseAge(person: Person): Person {
                                  ^^^^^^ RecordClass. Ineligible value used in/as type annotation (did you forget 'typeof'?)
*/
```

**Comment by singhshashi** [comment]
```
const {Record} = require('immutable');

const PersonRecord = Record({
  name: undefined,
  age: undefined,
});

class Person extends PersonRecord {
  name: string;
  age: number;
  
  constructor(name: string, age: number){
    super({
     name: name,
     age: age
    });
  }
}

function increaseAge(person: Person) : Person {
   return person.update('age', i => i + 1);
}

const John = new Person('John', 20);
console.log(increaseAge(john));
```

**Comment by eirslett** [comment]
@kozlitinaelja I tried running your example (inserting `// @flow` before the first line), unfortunately it didn't type check:

```
js/person.js:9
  9: class Person extends PersonRecord {
                          ^^^^^^^^^^^^ function call. Expected polymorphic type instead of
  9: class Person extends PersonRecord {
                          ^^^^^^^^^^^^ RecordClass

```

**Comment by singhshashi** [comment]
Works for me. Could you share the complete code? 

https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1AbwEoCmqATgCYC+oAvKCYQI4CuAlvQBQDkLAtj01gCGAI2iFOASgDciFOmygACoRIZ0RUmRqgNscu1yJQoNIJ6EAXKCZoyhSCzSEyAGiOhBAc0vXb9x85uFNKyyNCCGBhKKmpooIQAHliEtlHKqurEelqGxqbmVtgkjp4yxl4+aEw8wiploO6omFgkTMhYeuz5PkUlLh7eVlU1KhK5xqAYTAAOKgbuE91DZoRuE+WDA4QLoMH1FIgHiJA27SzooI7I9BGEAILe7LMZaFbpsRKgbzEX43SEWCYJDiz1iADoZmRBMkuBVOP0WDQAHyXUAAalAAEYQkcmgoAFawAAWcVoTng0ReXAAUsS0PDQAAmAAMITxsDEYLgnnYVxuGHuj0JJIk0iAA

**Comment by eirslett** [comment]
Could it be that you're using immutable@3? I'm testing this with immutable@4.0.0-rc.2 and the flow types have been rewritten.

**Comment by singhshashi** [comment]
Possible. I tried with immutable@4.0.0-rc.2 but flow throws an error for the require statement. 

```
const {Record} = require('immutable');
                      ^^^^^^^^^^^^^^^^^^^^ immutable. Required module not found

```

Not sure why that is happening.

**Comment by leebyron** [comment]
Closing this issue since we now have `RecordOf<T>` and `RecordFactory<T>` flow types which makes typing Records much much better
