### ISSUE TITLE
Request: Overload for Map.get/Map.set that accepts keypath 

### ISSUE THREAD

**Issue by billfienberg** [facebook/immutable-js#1241]
I think it would be nice to be able to pass a keyPath to `.get`/`.set` when accessing nested data instead of having to use a completely different method (`.getIn`/`.setIn`). 

For example:
```
import { Map } from "immutable";
const data = {
  event: {
    address: {
      streetAddress: '...',
      city: '...',
      state: '...',
      postalCode: '...'
    }
  }
}
const structure = Map(data);

// Current
const postalCode = structure.getIn(['event', 'address', 'postalCode'])

// Preferred
const postalCode = structure.get(['event', 'address', 'postalCode'])
```

**Comment by cmmcleod** [comment]
This would break currently supported behavior of using Arrays as keys.

```
const myObj = {foo:1, bar: 2};
const anArray = ["myString", "Another string"];

const immutableMap = Immutable.Map()
  .set(anArray, 'I belong to the array')
  .set(myObj, 'I belong to the object');

console.log(immutableMap.get(anArray));
```

While this type of use is probably not commonplace, it would cause some very nasty bugs.

**Comment by billfienberg** [comment]
@cmmcleod you are absolutely correct. I didn't think about the use case of using arrays as keys. Closing this issue.
