### ISSUE TITLE
Docs site should reflect the latest stable release

### ISSUE THREAD

**Issue by erquhart** [facebook/immutable-js#1242]
### What happened

The docs show the `is` methods, but they're only available in the 4.x release candidate, and not in any stable release. If someone installs from npm as the docs instruct, these documented functions won't work.

**Comment by liubinyi** [comment]
@kozlitinaelja do you think it will be helpful to add build version to the header ?
and the version will link to the lastest stable release v3.8.1
https://github.com/facebook/immutable-js/releases
kinda like how react does it:
<img width="1196" alt="screen shot 2017-06-14 at 7 04 55 pm" src="https://user-images.githubusercontent.com/5498827/27162192-d372794a-5134-11e7-83c7-d225ca2e2039.png">

and for all the is methods we just add v4.x.x next to it and remove them later once version 4 is out and point the build version to the new version.

 this might also can address the issue #1197

please let me know what's your thoughts?( i can sent a pr if this solution works for you)

**Comment by erquhart** [comment]
It seems like the best route is to keep the release candidate off of master. Any thoughts from maintainers on this?

**Comment by leebyron** [comment]
I've added the version to the website - it also now only builds when a new version is pushed, not just when master is updated.

**Comment by dangerousdan** [comment]
@leebyron Can this be reopened?

The docs show the latest version (currently v4.0.0-rc9, which is a prerelease), and there is no obvious way to view the v3 docs.

**Comment by dangerousdan** [comment]
As @erquhart mentioned, it seems like this was caused by release candidates being merged into master.

Is it possible to allow users to select which docs version to use? Something similar to [how Laravel does it](https://laravel.com/docs/5.5)

**Comment by franklinyu** [comment]
Any news?
