### ISSUE TITLE
.map() and .concat() don't retain referential equality?

### ISSUE THREAD

**Issue by Daniel15** [facebook/immutable-js#1243]
### What happened

Consider this code:
```js
var first = Immutable.Set(['1', '2', '3'])
var second = first.add('1')
var third = first.withMutations(x => { x.add('1'); x.add('2'); })
var fourth = first.concat(['1'])
var fifth = first.map(x => x)
```

All of these variables will contain a set of `{'1', '2', '3'}`. Since they're all based off `first`, I'd expect them all to be referentially equal. However, this is not the  case!

```

> first === second
true
> first === third
true
> first === fourth
false
> first === fifth
false
```

What's particularly confusing about this is that `first.add('1')` does return the same instance, but `first.concat(['1'])` does not!

### How to reproduce
See code above

**Comment by Daniel15** [comment]
`filter` is another one I expected to retain the same collection:
```js
const numsOne = Immutable.Set([20, 30, 40, 50])
const numsTwo = numsOne.filter(x => x > 15)
numsOne === numsTwo // false
```

**Comment by xargi** [comment]
For map and filter it behaves as documented though. Concat does not explicitly state either way.
> [Note: map() always returns a new instance, even if it produced the same value at every step.](https://facebook.github.io/immutable-js/docs/#/Set/map)

**Comment by smallhadroncollider** [comment]
I found that if I used `reduce` (on `List` and `Map`) I could get the same behaviour as `map` while keeping referential equality. It's not perfect, but it had a significant performance increase on a Redux app I was working on (stopped a lot of unnecessary rerendering).

I hadn't spotted the note in the documentation. It would be great if `map` and `filter` could keep referential equality if there are no changes, but I imagine there's a good reason they don't.

**Comment by leebyron** [comment]
Unfortunately this is a challenging balance between performance and functionality.

There is no guarantee that if some operation would return a value-equal result, that it will also be referentially equal. The library tries to do that when it can be done performantly, since referential equality is used as a "memoization" optimization, however when it can't be done performantly it won't try.
