### ISSUE TITLE
takeLast(0) should return an empty collection

### ISSUE THREAD

**Issue by jmzhang** [facebook/immutable-js#1245]
Calling takeLast(0) on a collection should return an empty collection, rather than a full copy of the collection, as given in the implementation here [https://github.com/facebook/immutable-js/blob/master/src/CollectionImpl.js#L511](https://github.com/facebook/immutable-js/blob/master/src/CollectionImpl.js#L511)

**Comment by leebyron** [comment]
Good ol' `-0`. Thanks for the report!
