### ISSUE TITLE
[typescript] List.map and undefined

### ISSUE THREAD

**Issue by filipesabella** [facebook/immutable-js#1246]
### What happened

It's likely that I'm doing something wrong as this is a fundamental use case. Apologies in advance if that's the case. I did however go through the source code and couldn't find alternatives.

```
List([1, 2, 3]).map(e => e + 1);
```

Yields the following typescript compiler error:

```
[ts] Object is possibly 'undefined'.
(parameter) e: number | undefined
```

Which is expected given the method's definition:
```
/**
 * Returns a new Iterable of the same type with values passed through a
 * `mapper` function.
 *
 *     Seq({ a: 1, b: 2 }).map(x => 10 * x)
 *     // Seq { a: 10, b: 20 }
 *
 */
map<M>(
  mapper: (value?: V, key?: K, iter?: /*this*/Iterable<K, V>) => M,
  context?: any
): /*this*/Iterable<K, M>
```

As a side note the code in the doc string doesn't compile either.

Typescript: 2.3.2
Immutable: 3.8.1

**Comment by aleffert** [comment]
The same issue occurs in places like `filter`, `filterNot` and probably many others. The typings conflate the fact that it is optional for the function to have this argument with the argument passed to the function being optional. This is a pretty bad flaw in the typings IMO.

I suspect that the correct thing to do is offer multiple typings for each function (which typescript is designed to support). For example:

```
map<M>(
  mapper: (value: V) => M,
  context?: any
): /*this*/Iterable<K, M>;
map<M>(
  mapper: (value: V, key: K) => M,
  context?: any
): /*this*/Iterable<K, M>;
map<M>(
  mapper: (value: V, key: K,  iter: /*this*/Iterable<K, V>) => M,
  context: any,
): /*this*/Iterable<K, M>;
```

**Comment by aleffert** [comment]
In the meantime, you can add your own `.d.ts` file to your project containing those typings. For example:

```
import { Map, List, Iterable } from 'immutable';

declare module "immutable" {

    export interface List<T> {
        filter(
            predicate: (value: T) => boolean,
            context?: any
            ): /*this*/Iterable<number, T>;
        filterNot(
            predicate: (value: T) => boolean,
            context?: any
            ): /*this*/Iterable<number, T>;
    }

}
```

**Comment by aleffert** [comment]
@wtatum I suspect there won't be any movement here without a PR. If you did that, it would make me super happy. I think it would just add the multiple typings like I have above?

**Comment by wtatum** [comment]
@aleffert I think it should be even easier than that. The variance rules of functions as arguments are such that actual functions supplied don't need to accept all the parameters, as long as they produce the correct return type.

If we had this type definintion
```
map<M>(
  mapper: (value: V, key: K,  iter: /*this*/Iterable<K, V>) => M,
  context: any,
)
```

it's still valid to call it as List.of(1, 2, 3).map( (i) => i * 2) // List(2, 4, 6)
Marking the parameters as optional means they're optional for the caller to provide (the map function itself). They're always optional for the supplied function to accept.

Note the section "Callback Types > Optional Parameters in Callbacks" of this [dos and don'ts document](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html) from the TypeScript docs

> Don’t use optional parameters in callbacks unless you really mean it:
> 
> This has a very specific meaning: the done callback might be invoked with 1 argument or might be invoked with 2 arguments. The author probably intended to say that the callback might not care about the elapsedTime parameter, but there’s no need to make the parameter optional to accomplish this – it’s always legal to provide a callback that accepts fewer arguments.
> 
> Do write callback parameters as non-optional:

**Comment by aleffert** [comment]
Oh weird. I wouldn't have expected that/never read that part of the docs. For non-higher order functions, the rule per the docs is "In short, the number of arguments given to a function has to match the number of parameters the function expects". I guess it makes sense if you're adapting to JS land though

**Comment by wtatum** [comment]
In a "traditional" statically typed setting, the arity (and type) of methods is used to during dispatching, so that you can achieve things like method overloading. Since JavaScript doesn't identify functions by their arity, only by name or reference, you can pass functions that expect fewer than what are actually provided. The calling function (map in this case) will still provide the full argument list, and looking at the 'arguments' object at runtime will still show the whole argument list, but they aren't bound to anything.

I'll see about a PR later this week.

**Comment by leebyron** [comment]
Closing this since it's been fixed for a while - please use the 4.x builds which have dramatically better typescript and flow support.

**Comment by wtatum** [comment]
Apologies for not getting around to a PR, the last week was more hectic than expected. I hadn't been following the 4.0.0 RCs, but I'll check that out and see if it addresses the issue.

**Comment by jonfreedman** [comment]
Is there an ETA for 4.x exiting release candidate builds?  It's unfortunate that just installing gives you a 3.x build where this is broken.

**Comment by searene** [comment]
Just use `yarn add immutable@4.0.0-rc9`

**Comment by wtatum** [comment]
Obviously it's possible to just use the RC by pinning the version, but it's a little alarming that the project produced 9 RCs within a few months almost a year ago, but never got a general release. That corresponds exactly to a noticeable drop in the number of commits and contributors to the project. It leaves the distinct impression that nobody is working on or even thinking about the library. Not trying to sow FUD, but it's certainly a cause for concern to me.

If RC9 is stable enough to use, why not release a 4.0.0? If it is not then encouraging people to use it over 3.x doesn't make sense.

**Comment by Davidkle** [comment]
This is still a problem in 2020. When will there be a new release?
