### ISSUE TITLE
Defaulted `Record` instance reports `true` after instantiation

### ISSUE THREAD

**Issue by jaredru** [facebook/immutable-js#1247]
### What happened

Immediately after being constructed--without constructor values and without further changes--a Record instance returns `true` for `wasAltered()`.

### How to reproduce

**Version**: v4.0.0-rc.2

```js
const R = Record({ a: 1 });
const r = new R();

r.wasAltered(); // true
r.a;            // 1

r.clear().wasAltered(); // false
r.clear().a;            // 1
```

**Comment by mmoravec** [comment]
This is happening to me too! I couldn't believe it.

**Comment by leebyron** [comment]
Thanks for the report, I'll take a look
