### ISSUE TITLE
toImmutable alias for fromJS

### ISSUE THREAD

**Issue by giuseppeg** [facebook/immutable-js#1248]
N.B. this is a super nit / nice to have.

When using `fromJS` I always alias it to `toImmutable` because the former is not that descriptive. 
To be clear I understand the reason why it is called like that i.e. it is symmetrical to `toJS` (also `Immutable.fromJS` although most of the times I don't import the whole thing) yet I think it is worth asking if you'd be open to add the alias / accept a PR.

cheers

**Comment by pigulla** [comment]
Not sure why you would need this? `Immutable.fromJS()` is perfectly descriptive and you can always do:

```js
import { fromJS as toImmutable } from 'immutable';
// or
const { fromJS: toImmutable } = require('immutable');
```

**Comment by jackson-sandland** [comment]
@leebyron What are you thoughts on keeping data from Redux in React views as immutable objects. For example, you make a getRequest, and make the data immutable in the reducer, and then serve it to the view. What is the advantage of keeping the data immutable throughout, as opposed to converting it to a plain JS object using toJS() when it 'hits' the view. An engineering team I am a part of is curious about whether it makes sense to keep the data immutable at all times. Thanks in advance!

**Comment by giuseppeg** [comment]
Closing because it is not a big deal, I also realized that I can write a babel plugin.
