### ISSUE TITLE
Record.isRecord() errors

### ISSUE THREAD

**Issue by joshvito** [facebook/immutable-js#1250]
[I found a related closed issue, with no answer.](https://github.com/facebook/immutable-js/issues/775)

### What happened

I am trying to use `Record.isRecord(thing: any)` per the documentation for [Immutable.Record](https://facebook.github.io/immutable-js/docs/#/Record/isRecord)

### How to reproduce
It is easily reproduced. [Here](http://plnkr.co/edit/kTFqP0?p=preview) is a Plunk

Also, example code
```
const I = Immutable;
enum Types {
  CatA,
  CatB
}
let things = [
    {referenceId: 1,
      referenceType: 0,
      name: 'one',
      id: 11
    },
  ];

interface IItem {
  id: number;
  referenceId: number;
  name?: string;
  referenceType?: Types
}

const itemRecord = I.Record({
  id: 0,
  referenceId: 0,
  name: null,
  referenceType: Types.CatA
});

class Item extends itemRecord implements IItem {
  id: number;
  referenceId: number;
  name: string;
  referenceType: Types;
  
  constructor(config: IItem) {
    super(config);
  }
}

const record = new Item(things[0]);
console.log(record); // Item {_map: ct}
console.log(I.Record.isRecord(record)); // Uncaught TypeError: I.Record.isRecord is not a function
```

Is this just an omission from the type definition, or am I reading the documentation wrong?

**Comment by nihaux** [comment]
I found out that the doc is in advance vs the latest npm release.
isRecord function is not in the latests 3.8.1 version but is in [master](https://github.com/facebook/immutable-js/blob/78def5bc6c60c618a9f8523a17e7156f0c9ce8f1/src/Record.js#L170)
I upgraded in 4.0.0-rc2 (which has it) but I would not advise this as it seems unstable (it introduce some bugs in my app, so I had to downgrade).

**Comment by erquhart** [comment]
Same issue as #1242 - Immutable documentation is based off of the release candidate instead of the latest stable release.

**Comment by albertfdp** [comment]
Ah. I wish I had seen this before :/ I went crazy thinking I had a problem with my setup. Any chances the docs could be aligned with the latest release instead of master? Thanks!

**Comment by leebyron** [comment]
I'm going to add the latest version number to the docs, I think that will help resolve confusion on this front
