### ISSUE TITLE
No v4 RC with (already completed) TypeScript strictNullChecks fix

### ISSUE THREAD

**Issue by bhouser** [facebook/immutable-js#1253]
This issue was fixed:
https://github.com/facebook/immutable-js/issues/1158

But it didn't make it into the 4.0.0rc2 release.  It should allow the TypeScript types to build when using the `strictNullChecks` compiler flag.

Can we have another release candidate with this fix?

**Comment by leebyron** [comment]
Another release coming very soon! Sorry for the wait!
