### ISSUE TITLE
It does not work when creating Map from json

### ISSUE THREAD

**Issue by m0a** [facebook/immutable-js#1254]
i try in typescript

```
test('map test', () => {
  let m = Map<number, string>({
    0: 'test'
  });

  // expect(m.get('0')).toBe('test'); // it works
  expect(m.get(0)).toBe('test');
});
```

expect m.get argument is number. but dont't work

**Comment by zbrukas** [comment]
When doing the get, Immutable pairs keys and values and do a strict compare. Keys are treated as strings, so 
```js 
0 === "0"
``` 
will be false. Also, 
```js
get(0)
``` 
is "Get me index 0", not "Get me key 0".

**Comment by m0a** [comment]
thankyou for replay.
