### ISSUE TITLE
Plans for a proper v4.0.0?

### ISSUE THREAD

**Issue by SavePointSam** [facebook/immutable-js#1255]
The most recent release was v4.0.0-rc.2. This build is near 3 months old at this point. I don't see a lot of recent activity in the commit history for master either. I'm curious the state of this project and if there are any plans/roadmap for a full release.

**Comment by rsolomon** [comment]
![image](https://user-images.githubusercontent.com/448432/29297932-3617fa70-8119-11e7-9c8a-c6ab31553cf2.png)

**Comment by Armour** [comment]
I've been waiting for more than 3 months with my little ugly [patch](https://github.com/Armour/express-webpack-react-redux-typescript-boilerplate/blob/master/patch.sh) 😭

**Comment by SavePointSam** [comment]
Relevant comment [here](https://github.com/facebook/immutable-js/issues/1215#issuecomment-325027309). Closing this issue in favor of older, more active issue.
