### ISSUE TITLE
Methods like isIndexed isKeyed cannot found

### ISSUE THREAD

**Issue by powerformer** [facebook/immutable-js#1257]
![image](https://user-images.githubusercontent.com/26423749/27429059-77d3e52c-5776-11e7-9bd0-dccc23732e1b.png)
![image](https://user-images.githubusercontent.com/26423749/27429060-7b21dc98-5776-11e7-80da-c4e3bb65386b.png)

**Comment by erquhart** [comment]
Same issue as #1242 - Immutable documentation is based off of the release candidate instead of the latest stable release.

**Comment by leebyron** [comment]
These functions were added in the latest release, and aren't available in older releases

**Comment by richtera** [comment]
The old version has isKeyed as a static on Iterable. What's the standard way to write code that will work with 3.x and 4.x? Typescript seems to be complaining a bit.
