### ISSUE TITLE
Record.mapEntries returns undefined

### ISSUE THREAD

**Issue by wildeyes** [facebook/immutable-js#1260]
```
R = Immutable.Record({'foo': 'bar'})
r = new R({'foo': 'baz'})
r.mapEntries(() => [42, 42])
```

steps to reproduce:
1. open https://facebook.github.io/immutable-js/docs/#/
2. f12
3. paste and run code
4. cry.

**Comment by leebyron** [comment]
A Record is not a collection - where in v3 these functions have undefined behavior, they've been removed in v4.
