### ISSUE TITLE
Typings: reduce `Record.Instance<T> & Readonly<T>` boilerplate

### ISSUE THREAD

**Issue by Retsam** [facebook/immutable-js#1264]
The improved typescript typings in v4 are great, particularly for Records.  

However, one pain point I've found so far, is that because instances of a particular Record are typed as `Record.Instance<T> & Readonly<T>` it creates quite a bit of boilerplate for function signatures and interface definitions that take record instances.  

For example:

```
const Foo = Record<IFoo>(fooDefaults);

//IMO awkward amounts of boilerplate in this signature
const doSomethingWithFoo = (foo: Record.Instance<IFoo> & Readonly<IFoo>) => {};

//And in this interface definition
interface FooContainer {
    theFoo: Record.Instance<IFoo> & Readonly<IFoo>
}
```

As a workaround, I've started doing `type FooRecord = Record.Instance<IFoo> & Readonly<IFoo>`, and this seems to work, but it'd be nice if the type signature was a bit more friendly in the first place.  

Ideally it seems like `Record.Instance<T>` could just imply `Readonly<T>`, but even just adding a generic equivalent to my `FooRecord` type would be helpful.  (Though I'm a bit stumped on what that would be called, since `Instance` is already claimed)

Thanks for your work!

**Comment by dharries** [comment]
You could also have your own generic type: `type RecordInstance<T> = Record.Instance<T> & Readonly<T>`

But I think the best name for the type is `Foo`, defined something like this:

```
const Foo = Record<IFoo>(fooDefaults);
const fooInstance = new Foo(fooDefaults);
type Foo = typeof fooInstance;
```

The types would then behave the same way as instantiating a normal class in typescript.  I have no idea whether there's any black magic that could be added to the typings to create that type automatically.

**Comment by sccolbert** [comment]
I create a class which extends the record, then refer to that class as a type:

```typescript
class Foo extends Record<{
  thing1: number;
  thing2: number;
}>({
  thing1: 42,
  thing2: 24
}) { }
```

**Comment by leebyron** [comment]
The latest master build (install from https://github.com/facebook/immutable-js/tree/npm) now includes `RecordOf<T>` to make this easier! It will be included in the next release

**Comment by Methuselah96** [comment]
@leebyron The latest build includes `RecordOf<T>` for Flow, but how are you supposed to use Records (v4.0.0rc-9) with TypeScript, since `RecordOf<T>` isn't available in the TypeScript definitions?

**Comment by cormacrelf** [comment]
@Methuselah96 it's a one-liner you can use your own code.

```typescript
// RecordOf.ts
import { Record } from 'immutable';
export type RecordOf<T> = T & Record<T>;
```

**Comment by Methuselah96** [comment]
@cormacrelf This one-liner doesn't seem to be quite work because it doesn't insure that the properties read-only. I've resorted to @dharries's suggestion, but it seems cumbersome to have to create an instance of the record to get its type.

**Comment by dakom** [comment]
Assuming the one-liner is correct, should it not be added to the exported typescript definitions?

**Comment by caleb** [comment]
For typescript, this works for me:

```typescript
// RecordOf.ts
import { Record } from 'immutable';
export type RecordOf<T> = Readonly<T> & Record<T>;
```

`Readonly<T> & Record<T>` is the type returned from the `new` method in `Record.Factory`.
