### ISSUE TITLE
How would you transfer data of an immutable.js object between server and client?

### ISSUE THREAD

**Issue by michaellee8** [facebook/immutable-js#1277]
Background: I want to implement a react-redux app with immutable collection as store, but I am thinking of how to transfer the immutable data between server and client.

The only possible way to solve the problem is using `JSON.stringify(ImmutableObject.toJS())`, but `toJS()` is absolutely unusable and extremely slow. However I cannot simply do the trick by `JSON.stringify(ImmutableObject)` because that would 100% break the structure. Does anyone got a nice way to do that?

**Comment by ricokahler** [comment]
I've seen this: https://github.com/glenjamin/transit-immutable-js
but I have never used it

**Comment by michaellee8** [comment]
Seems useful, did anyone used it and can tell us its speed?
Are there any offical solution for this kind of data transfer?

**Comment by leebyron** [comment]
I recommend Transit JS

**Comment by tconroy** [comment]
how is `.toJS()` slow? How large is the immutable structure you're trying to convert?

In a project I am working on, we pretty much just convert to a JS object via `toJS()` and let our request library handle the serialization to JSON and have not encountered any performance issues, even with large payloads.
