### ISSUE TITLE
OrderedMap.skip(Infinity) returns the entire collection

### ISSUE THREAD

**Issue by meta-meta** [facebook/immutable-js#1287]
### What happened

I would expect `OrderedMap.skip(Infinity)` to return an empty OrderedMap. It returns the collection.
List works as expected.

### How to reproduce

```
new Immutable.OrderedMap([['a', 1]]).skip(Infinity).size
1
```

**Comment by leebyron** [comment]
This issue was fixed in a prior release, but just to confirm I added your reproduction case as a test!
