### ISSUE TITLE
Record.Instance link present in docs sidebar but section does not exist

### ISSUE THREAD

**Issue by kedromelon** [facebook/immutable-js#1288]
In the sidebar, `Record.Instance` is present, but the link (https://facebook.github.io/immutable-js/docs/#/Record.Instance) does not lead anywhere -- there is no `Record.Instance` section on the [`Record` page](https://facebook.github.io/immutable-js/docs/#/Record).

![image](https://user-images.githubusercontent.com/5393571/29190965-0725ad48-7dea-11e7-9b1a-134c3e617f3c.png)

**Comment by skeet70** [comment]
I think it's an exported type in the `.ts` file, which the docs are generated off of. It's just an instance of a `Record` with all the `Map` methods hanging off it.

**Comment by leebyron** [comment]
Looks like it got fixed!
