### ISSUE TITLE
Record#merge() converts argument to Immutable structure

### ISSUE THREAD

**Issue by elliotbonneville** [facebook/immutable-js#1293]
Calling `Record#merge()` will convert the argument passed in into an Immutable structure, yielding the same output as calling `fromJS()` with it. Since instantiating a `Record` directly does not do this, it seems to be a bug.

Example:

```
const State = Immutable.Record({ foo: 'bar', biz: 'baz' });
const deepObject = { qux: 'quux' };

const firstState = new State({ foo: deepObject });
const secondState = new State().merge({ foo: deepObject });

console.log(firstState.toString());
console.log(secondState.toString());
console.log(firstState.equals(secondState));
```

Output:

```
> "n { 'foo': [object Object], 'biz': 'baz' }"
> "n { 'foo': Map { 'qux': 'quux' }, 'biz': 'baz' }"
> false
```

Expected:

```
> "n { 'foo': [object Object], 'biz': 'baz' }"
> "n { 'foo': [object Object], 'biz': 'baz' }" 
> true
```

**Comment by leebyron** [comment]
Thanks for the report.

I'm not sure if this is a bug or just confusing behavior, either way it deserves a closer look

**Comment by punksta** [comment]
I have this issue with `"immutable": "^3.8.2",.`
```
new Map([[1, {foo: 'bar'}]]).merge(new Map([[2, {foo2: 'bar2'}]]))
```
`{foo:'bar'}`s objects become Map from Object

Solved by using to `concat`

**Comment by bateau** [comment]
In case anyone stumbles onto this, `set` also works.
