### ISSUE TITLE
Why is "value?" nullable in #map(), #filter() and etc

### ISSUE THREAD

**Issue by nwtgck** [facebook/immutable-js#1294]
My question is **why `value` in `mapper` or `predicate` is nullable type**.
In `immutable-nonambient.d.ts`, `map` and `filter` is defined bellow.

```ts
map<M>(
  mapper: (value?: V, key?: K, iter?: /*this*/Iterable<K, V>) => M,
  context?: any
): /*this*/Iterable<K, M>;
```

```ts
filter(
  predicate: (value?: V, key?: K, iter?: /*this*/Iterable<K, V>) => boolean,
  context?: any
): /*this*/Iterable<K, V>;
```

If `value` is like the following, could you tell me what is wrong.  

```ts
mapper: (value: V, key?: K, iter?: /*this*/Iterable<K, V>) => M
```

```ts
predicate: (value: V, key?: K, iter?: /*this*/Iterable<K, V>) => boolean
```

Combination of nullable types and `strictNullChecks` option of TypeScript is not so good.

**Comment by cyrilgandon** [comment]
Another example:

`const list = List([1, 2, 3]).map(n => **n** * 2);`

The typescript compiler returns `Object is possibly 'undefined`. Very annoying.

**Comment by cristicbz** [comment]
It seems like the types are just the wrong. TS is happy to coerce functions of fewer arguments to functions of multiple ones, so _none_ of the arguments should be `?`.

**Comment by cyrilgandon** [comment]
It has been fixed since forever by this commit:

https://github.com/facebook/immutable-js/commit/e7be08bcf353aa29fcf5400022973d6dcfaa1cc2

You just need to install the V4 RC to get the rights typings!

**Comment by nwtgck** [comment]
Thank you very much for the good news! Do you know how to npm-install RC version?
I tried to `npm install -D @types/immutable@4.0.0-rc.2` but it says "error notarget a package version that doesn't exist."

**Comment by cyrilgandon** [comment]
The typings are directly in the immutable npm package, not the @types ones.

`npm install -D immutable@4.0.0-rc.2`

**Comment by nwtgck** [comment]
Thank you very much! I can install RC2 and use non-nullable `List#map`! Thank you.
