### ISSUE TITLE
Is this project abandoned or is there a chance 4.0 will be released?

### ISSUE THREAD

**Issue by vaclavhofler** [facebook/immutable-js#1295]
I always thought this project will be active if it's under Facebook organisation, but it looks like nobody takes care of anything here. So @leebyron, can you please at least add a notice to the readme that this project it's no longer maintained? (I can create a PR for this but it won't probably be merged 😞). Otherwise, there is still a useless hope someone will do something like merging PRs.

**Comment by karland** [comment]
I could not agree more. It would be nice to have some clarity, if this project is not maintained ony longer or if it is looking for a new maintainer of if there are other plans. Especially, since there are a lot of references from React and Redux to immutable-js.

**Comment by thomhos** [comment]
discussion is also here; #1215

**Comment by YurySolovyov** [comment]
I'm not sure the project is abandoned, it is totally possible that it is just considered "Done". That might not be true, just a possible explanation6+

**Comment by thomhos** [comment]
I doubt it, considering v4 has some real improvements but aren't released yet.

**Comment by skeet70** [comment]
Feels abandoned. If it is then the community can come together behind a fork that's maintained, but we need clarification before doing that.

**Comment by ricokahler** [comment]
Maybe we can give them some incentive to work on this thing?? I'd gladly donate to help keep this project updated more often.

**Comment by acateland** [comment]
@leebyron hello bumbing on to this issue, do you intend to officially release the project to the community so it can be maintened ?
Should the community create an "official" fork to take care of this project ?

**Comment by cormacrelf** [comment]
Relevant comment from #1215: https://github.com/facebook/immutable-js/issues/1215#issuecomment-325027309

Plus Facebook has decided to MIT-license it. There's going to be at the very least a new commit on master for that.

**Comment by leebyron** [comment]
Still maintained! Sorry we're slow sometimes. I'm working on getting more help from other Facebook engineers for maintenance help.

Releasing 4.0 is close - I need to help update our internal repositories to support the latest version.

I'm working on an MIT license change as well
