### ISSUE TITLE
undefined is not a function(evaluating '_iterator[typeof Symbol === "function"?Symbol.iterator:"@@iterator"]()')

### ISSUE THREAD

**Issue by huangtubiao** [facebook/immutable-js#1305]
I used "for(let...of...){}" to  traverse a Map object at react-native，I got this error.
it's working perfectly for IOS and android debug mode,  but not working for android normal mode.

![image](https://user-images.githubusercontent.com/10185166/30315417-7fd0c60e-9769-11e7-8bc8-7a14236a895f.png)

**Comment by leebyron** [comment]
Unfortunately this bit of code you're running into is not part of Immutable.js, but is instead an issue with Babel transpilation.

Android's JS runtime defines `Symbol`, however does not define `Symbol.iterator` - updating to a later version of JSC or Babel will likely fix your issue.

**Comment by ayessymkanov** [comment]
@leebyron what is JSC?

**Comment by ayessymkanov** [comment]
@huangtubiao have you solved the issue?

**Comment by huangtubiao** [comment]
@ayessymkanov  https://github.com/facebook/react-native/issues/15902

**Comment by Runtime007** [comment]
`import 'core-js/es6/symbol';
import 'core-js/fn/symbol/iterator';`

it works for me.

**Comment by CodingJbz** [comment]
@Runtime007 thank you . it works for me . but why it works

**Comment by ericketts** [comment]
@CodingJbz do you have any links regarding the BackHandler bug? Is it introduced by including the core-js polyfills?

**Comment by rgoldiez** [comment]
@Runtime007 - your solution works, but why is it needed, and only on Android?

**Comment by ericketts** [comment]
@rgoldiez that polyfills Symbol and iterator stuff that's missing out of the box on android

**Comment by adirzoari** [comment]
@Runtime007  where to make these imports?
I have same issue.

**Comment by ericketts** [comment]
@adirzoari you can import them anywhere, so long as they get imported before whatever is causing an error for you -- a common pattern is to create a `polyfills.js` file and do the imports there, then import that `polyfills.js` file before any others (some people use `require` because the semantics are often easier to reason about)

**Comment by ericketts** [comment]
its wild to me that RN ships broken on android! perhaps a better choice, both in terms of thinking long term and about perf, is to upgrade the JSC that ships with Android RN so that the functionality you're presently polyfilling is implemented natively. 

I did this months ago and all it took was adding the JSC dep and then a pretty simple tweaking of the gradle scripts if memory serves.

**Comment by iamkaustubh1019** [comment]
I had the same issue while using firebase just add this to index.js
global.Symbol = require('core-js/es6/symbol');
require('core-js/fn/symbol/iterator');
require('core-js/fn/map');
require('core-js/fn/set');
require('core-js/fn/array/find');

**Comment by sunithakk** [comment]
> `import 'core-js/es6/symbol'; import 'core-js/fn/symbol/iterator';`
> 
> it works for me.

where i have import these two lines???????????????????????

**Comment by maasantos10** [comment]
Hi guys, I did exactly the following steps



1 - create a polyfills file code and I put in a file named polyfills.js, at the same level with index.js (entry point of my react-native project)

2-the code:

global.Symbol = require('core-js/es6/symbol');
require('core-js/fn/symbol/iterator');
require('core-js/fn/map');
require('core-js/fn/set');
require('core-js/fn/array/find');

3 - On the first line within index.js file, I inclue the following code: import './polyfills.js'

I was very very happy. I was one week trying to fix this problem.

Thank you....

**Comment by lalakiyaRahul** [comment]
> > `import 'core-js/es6/symbol'; import 'core-js/fn/symbol/iterator';`
> > it works for me.
> 
> where i have import these two lines???????????????????????

Yes...whare is import this.

**Comment by leebyron** [comment]
Please read above comments. You can install any module including core-js with npm.
