### ISSUE TITLE
Add a safe merge/mergeDeep to Records

### ISSUE THREAD

**Issue by idris** [facebook/immutable-js#1307]
### What happened
`Record.mergeDeep` throws an Error when trying to merge an object into a `Record` if the object has keys which are not present in the `Record`.

This behavior is expected, but it would be nice to have an option like `mergeSafe` which will omit extra keys rather than throwing an Error.

### How to reproduce
To see the error:
```js
var Rec = new Immutable.Record({ foo: 'bar', hello: 'world', some: null });
var myRec = new Rec();

// Throws an Error: Cannot set unknown key "missing" on myRec
myRec.mergeDeep({ missing: 'stuff' });
```

Proposed solution:
```js
var Rec = new Immutable.Record({ foo: 'bar', hello: 'world', some: null });
var myRec = new Rec();

var merged = myRec.mergeDeepSafe({ missing: 'stuff', some: 'thing' });
// No error was thrown.
// merged now contains: { foo: 'bar', hello: 'world', some: 'thing' }
```

**Comment by leebyron** [comment]
I believe this error was reduced to a warning in the latest RC

**Comment by leebyron** [comment]
Actually, the error throwing behavior was completely removed in v4 - so please try out the latest version
