### ISSUE TITLE
Relicensing with MIT license (patch release)

### ISSUE THREAD

**Issue by leipert** [facebook/immutable-js#1309]
Per this announcement [[1]](https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/) immutable.js will be re-licensed with the MIT license.

I just created the issue to track this.

\[1]: https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

**Comment by leebyron** [comment]
Thanks for creating the issue

**Comment by mistercrunch** [comment]
Assuming semantic versioning (and breaking changes in 4.x), can we also get a `3.8.2` release under MIT?

Very grateful for the move to MIT and the awesome work out of FB!

**Comment by leebyron** [comment]
Reopened to track doing that as well

**Comment by leebyron** [comment]
v3.8.2 with MIT license is now out!
