### ISSUE TITLE
hashCode broken in rc3

### ISSUE THREAD

**Issue by agaurav** [facebook/immutable-js#1326]
### What happened
It seems `rc3` hashCode is ignoring values of any field.

### How to reproduce

you can try the below to verify :

```
const im1 = Immutable.fromJS({
  "firstName": "John",
  "lastName": "Smith",
});

const im2 = Immutable.fromJS({
  "firstName": "Bron",
  "lastName": "Sith",
});

const im3 = Immutable.fromJS({
  "firstName": "Tron",
  "lastName": "Smit",
});

const im4 = Immutable.fromJS({
  "firstName": "Cron",
  "lastName": "Mith",
});

console.log(im1.hashCode(),im2.hashCode(),im3.hashCode(),im4.hashCode());

im1.hashCode() === im2.hashCode(); 
im1.hashCode() === im3.hashCode();
im1.hashCode() === im4.hashCode();
```

Don't know about the earlier version but it seemed to be working in `rc2`

**Comment by errendir** [comment]
Hey, it seems like I also just discovered that issue. Here is my PR that fixes it: https://github.com/facebook/immutable-js/pull/1325

**Comment by leebyron** [comment]
Thanks for the report! I've also added regression tests for this, crazy that there were not tests covering this case. I'll have rc 4 out very soon

**Comment by leebyron** [comment]
rc4 is now released with this critical fix!

**Comment by szagi3891** [comment]
@leebyron 
Why is there no flowtype in the project? Such errors are immediately captured by static analysis.
