### ISSUE TITLE
GitHub page has broken link to immutable.js

### ISSUE THREAD

**Issue by gustafc** [facebook/immutable-js#1329]
### What happened

When you open up the JS console in the [docs](https://facebook.github.io/immutable-js/docs/), you see `ReferenceError: Immutable is not defined`, like so:

<img width="600" alt="screen shot 2017-10-03 at 10 39 43" src="https://user-images.githubusercontent.com/3645254/31116662-43e159a0-a827-11e7-9e42-da661eb0f56b.png">

A layman's guess is it might be caused by https://github.com/facebook/immutable-js/commit/a229c4be96c7acfa61e50eb818cd721e6b1aa156

### How to reproduce

Open console on https://facebook.github.io/immutable-js/docs/
It tries including https://facebook.github.io/immutable-js/docs/immutable.js which 404's

**Comment by leebyron** [comment]
Thanks for the report
