### ISSUE TITLE
Any plans for MapOf<T> and MapFactory<T> flow types?

### ISSUE THREAD

**Issue by stepankuzmin** [facebook/immutable-js#1355]
Immutable `v4.0.0-rc.5` has introduced very useful flow types `RecordOf<T>` and `RecordFactory<T>`.

Is there any plans to implement similar flow types for `Map`? Something like `MapOf<T>` and `MapFactory<T>`?

**Comment by leebyron** [comment]
Unnecessary! You can just type maps as `Map<K, V>` as per usual

**Comment by stepankuzmin** [comment]
Thanks for reply! I just think of type where I can specify values types in key-value pairs (like in `Record`). It seems that it is not possible with `Map<K, V>` type, since I can't specify different value types.

**Comment by leebyron** [comment]
That's correct and intentional, `Map` is not a heterogeneous collection, it's designed to have one type of keys and one type of values. Records are a better use case for heterogeneous data
