### ISSUE TITLE
TypeScript types of Seq.Indexed<T>.reduce

### ISSUE THREAD

**Issue by Fahrradflucht** [facebook/immutable-js#1356]
### What happened
Given this TypeScript code
```TypeScript
interface Item {
     payload: {};
}

mylist.valueSeq().reduce((result: Item[], item) => {
    if (item && item.payload) {
      result.push(item.payload);
    }

    return result;
}, []);
```
the TypeScript compiler tells me that everything is fine because it assumes that the `item` passed into the reduce function is of type `Item`. But actually it isn't, it is `ArrayMapNode` which means it is of type `Indexed` and I can only access `payload` by calling `get('payload')` on it, which I can't because `get()` doesn't exist on `Item` for the TS compiler.

**Comment by leebyron** [comment]
Sorry, could you please include a test case that I can reproduce? I'm not sure what `mylist` is, and without that I'm unable to reproduce your issue.

Please feel free to re-open if you have more information.

If possible, please submit in the form of a PR with a new failing test case.
