### ISSUE TITLE
Record typedef for get doesn't include notSetValue

### ISSUE THREAD

**Issue by chrisnojima** [facebook/immutable-js#1359]
Hi,

Trying out 4.0 rc-7. Noticed the new Record types (awesome). But also noticed Record.get() doesn't type the notSetValue so flow complains if I do
```
r.get('myProp', 123)
```
even though it actually works

Thanks! (super excited for this release, keep up the good work)

**Comment by leebyron** [comment]
Thanks for the report!

This is partly intentional, since it's trying to emulate the behavior where flow checks to see if you're using a prop that wasn't defined (and all props defined for a record are "set"), though since the behavior still exists, I'll look for what the right fix is
