### ISSUE TITLE
PlainObjInput Flow Type Errors in v4.0.0-rc.4 or later.

### ISSUE THREAD

**Issue by devanecondition** [facebook/immutable-js#1360]
Versions v4.0.0-rc.4+ are causing new flow errors for me based around the `PlainObjInput` type.

### What happened

Using `flow-bin@v0.46.0`, upgrading to rc4 or higher is causing flow errors related to passing object literals to the Map object.

```
globalState: Map({
  loggedInUser: state.getIn(['globalState', 'loggedInUser']),
})
```

Produces errors:

```
static <K, V>(collection: Iterable<[K, V]>): Map<K, V>;
                                   ^^^^^^^^^^^^^^^^ property `@@iterator` of $Iterable. Property not found in. See: node_modules/immutable/dist/immutable.js.flow:788` `^ object literal
```

```
Error:
  789:   static <K, V>(obj?: PlainObjInput<K, V>): Map<K, V>;
                             ^^^^^^^^^^^^^^^^^^^ property `__proto__`. Property not found in. See: node_modules/immutable/dist/immutable.js.flow:789` `^ object literal
```

### How to reproduce

Using `flow-bin@v0.46.0` (or later) and `v4.0.0-rc.4` (or later), create a `Map` and pass it an object literal.

**Comment by leebyron** [comment]
Could you try updating your flow-bin to a later version? I think adding `__proto__` both fixed v55 and required v54

**Comment by devanecondition** [comment]
Thanks @leebyron - looks like that did it.

**Comment by jkomyno** [comment]
I'm having the same issue with `flow-bin@0.55.0 `and `immutable@4.0.0-rc.7`

**Comment by leebyron** [comment]
@jkomyno - please open a new issue with additional details. We've been running tests with that version and haven't seen the issue before, so there may be something different happening for you
