### ISSUE TITLE
getIn behavior changed in v4.0.0-rc.7? null items will spawn a warning and future error?

### ISSUE THREAD

**Issue by chrisnojima** [facebook/immutable-js#1372]
Hi,

I'm attempting to upgrade to 4.0.0 and ran into this issue. I use getIn() to get to nested values simply without having to do a bunch of chained get() calls. In v4 I notice if an object within the keyPath is null it'll complain

v3
```
> I.Record({foo: null})().getIn(['foo', 'bar'], 'test')
'test'
```

v4
```
> I.Record({foo: null})().getIn(['foo', 'bar'], 'test')
Invalid keyPath: Value at ["foo"] does not have a .get() method: null
This warning will throw in a future version
'test'
```

Is this expected or is this actually an ok use of getIn() (I hope so)

Thanks!

**Comment by leebyron** [comment]
Merging into #1361
