### ISSUE TITLE
Flow error: incompatible types for SetSeq and IndexedSeq

### ISSUE THREAD

**Issue by acusti** [facebook/immutable-js#1379]
### What happened

After upgrading flow-bin to `0.56.0` and immutable to `4.0.0-rc.7`, I get this error when running flow on my repo:

```
Error: node_modules/fbjs/node_modules/immutable/dist/immutable.js.flow:399
399:   static of<T>(...values: T[]): SetSeq<T>;
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. This type is incompatible with
380:   static of<T>(...values: T[]): IndexedSeq<T>;
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type
  This parameter is incompatible:
    399:   static of<T>(...values: T[]): SetSeq<T>;
                                         ^^^^^^^^^ SetSeq. This type is incompatible with
    380:   static of<T>(...values: T[]): IndexedSeq<T>;
                                         ^^^^^^^^^^^^^ IndexedSeq
```

**Comment by leebyron** [comment]
Thanks for the report. Unfortunately there's not much we can do about this until `fbjs` can be updated to the latest version of immutable.js which has since fixed this Flow issue.

I recommend adding `node_modules/fbjs` to the list of ignored directories in your flowconfig

**Comment by acusti** [comment]
Thanks very much, I will do that! I failed to notice that `/fbjs/` was in the file path, sorry to create this issue unnecessarily.

**Comment by mikeaustin** [comment]
Hi, I just started using flow, and also hit this error. I'm using "immutable": "^3.8.2" - do you know which version of immutable fixes the issue? 3.8.2 seems to be the latest npm.

**Comment by acusti** [comment]
The issue is fixed in 3.8.2. When you get this error, does the `error: [file path]` part of the message point to immutable.js.flow inside fbjs/node_modules? If so, you can either try to figure out why fbjs is installing an old version of immutable, or you can just add fbjs/node_modules to the `[ignore]` section in your .flowconfig, like:

```
[ignore]
.*/node_modules/fbjs/node_modules/.* 
```

**Comment by mikeaustin** [comment]
BTW, I'm not using fbjs. It's a minimal app where I'm getting this with "immutable": "^3.8.2":

    Error: node_modules/immutable/dist/immutable.js.flow:406
    406:   static of<T>(...values: T[]): SetSeq<T>;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. This type is incompatible with
    387:   static of<T>(...values: T[]): IndexedSeq<T>;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type

Currently I'm just ignoring immutable itself to prevent the error.

**Comment by babygoat** [comment]
@mikeaustin 
I think #1308 might help.
It works for me as I upgrade my immutable.js pass 4.0.0-rc3
If the immutable is ignored, the module import statement will be blamed.

**Comment by ericsoco** [comment]
@babygoat what in #1308 might help? Only options I see are to bump to a 4.0rc, or use the branch @ndbroadbent offers [here](https://github.com/facebook/immutable-js/issues/1308#issuecomment-332476802).

**Comment by fabiomcosta** [comment]
It's unfortunate this is blocking us from using the Flow definitions on `^3.8.x` and there doesn't seems to have a fix for it other than upgrading to v4, which is not an option for us ATM.
I tried all the mentioned solutions, but none of them worked, I keep having the Flow error.
Please let me know if there is a workaround for this while using `^3.8.x` !

**Comment by fabiomcosta** [comment]
OK I could work around this issue without having to update to 4.0.0, which I can't do ATM.
See my comment on https://github.com/facebook/immutable-js/issues/1308#issuecomment-375846684

**Comment by craigdanj** [comment]
@mikeaustin if you check your node_modules folder you'll probably find fbjs installed.
