### ISSUE TITLE
Cursors and React

### ISSUE THREAD

**Issue by glenjamin** [facebook/immutable-js#138]
Hello, as discussed on IRC earlier - I think cursors are more useful when they act like a wrapping reference type, rather than as immutable values that callback to the root. 

Here's an example of something that I expected to work, but behaves oddly:

http://jsbin.com/boropodo/4/edit?js,output

I think this is because the cursor ends up "stale", and sends an update based on an old version of the root.

**Comment by yashprit** [comment]
@tgriesser or @leebyron guys could you please share some documentation and gist to solve stale cursor issue, I end up in same issues.
