### ISSUE TITLE
Typings flatMap: can't infer the M of flatMap<M>

### ISSUE THREAD

**Issue by cyrilgandon** [facebook/immutable-js#1381]
Version 4.0.0-rc.7

In this code:

```
const flatten = List<List<string>>().flatMap(list => list); // this is List<{}>
const typedFlatten: List<string> = flatten; // error, can't assign {} to string
```

The current signature in the declaration file is

```
flatMap<M>(
  mapper: (value: T, key: number, iter: this) => Iterable<M>,
  context?: any
): List<M>;
```

I guess that typescript can't infer the M in `Iterable<M>`.

**Comment by leebyron** [comment]
To be clear - is this a Flow or TypeScript issue you've encountered?

**Comment by leebyron** [comment]
Can I ask what version of TypeScript (or Flow) you're using?

**Comment by leebyron** [comment]
I've just added this exact test case to our TypeScript tests, which passes - so you may have another issue not captured by this particular test. You can see that set of tests here: https://github.com/facebook/immutable-js/blob/master/type-definitions/ts-tests/list.ts#L259-L284

TypeScript will infer the `M` type in that definition as long as it can infer the return type of your function. If it cannot, then you can use the `<>` syntax to explicitly declare the type you expect.

So your example:

```js
listOfListOfString.flatMap(list => list);
```

Could become more explicitly typed with:

```js
listOfListOfString.flatMap<string>(list => list);
```

**Comment by cyrilgandon** [comment]
Ok, I think I see the problem.
This issue seems to affect only if you are targeting ES5. In this case, the compiler doesn't know `Iterable`, and so nothing will be infer.

It happens that I have installed the typings `@types\node', which has this definition:

``` 
// @types/node/index.d.ts
// Forward-declare needed types from lib.es2015.d.ts (in case users are using `--lib es5`)
interface Iterable<T> { }
```
Which doesn't allow the compiler to infer the usage of flatMap neither.

Whereas if it targets ES2015+, the compiler can use this file `typescript/lib/lib.es6.d.ts`, which contains this definition:
``` 
// 
interface Iterable<T> {
    [Symbol.iterator](): Iterator<T>;
}
```
And this is working fine for inference.

It looks like a ES5 bug, but I'm not sure if it's worst fixing it.

**Comment by leebyron** [comment]
Great! I'm glad you were able to find an answer
