### ISSUE TITLE
Immutable-js newest version -> draft-js incompatible

### ISSUE THREAD

**Issue by markpradhan** [facebook/immutable-js#1382]
### What happened

I updated to 4.0.0-rc.7.
Suddenly i noticed draft-js stopped working. Threw  an unrecoverable error.

### How to reproduce

Install draft-js, install the version of immutable i mentioned. It will happen naturally.

I also posted on [draft-js](https://github.com/facebook/draft-js/issues/1425)

**Comment by leebyron** [comment]
@flarnie has been helping to update draft.js, but at this time draft.js lists its dependencies as an earlier version.

I'm not sure there's action that can be taken on this repo - if you see something that you think is a bug, please reopen with more details.

I suggest following up with the issue on draft-js with more details. What sort of error do you see? Is there code you can share that will reproduce the issue? Could you submit a PR with a test that fails or a suggested fix? Those sorts of things will likely lead to a faster fix

**Comment by flarnie** [comment]
Yup - this is an issue we will fix in Draft. Thanks @leebyron and @markpradhan

**Comment by leebyron** [comment]
@flarnie - If there are breaking changes that are particularly tricky to work around in supporting v3 and v4, let me know so I can work on a smoother migration plan
