### ISSUE TITLE
Map flowtype error different depending on syntax

### ISSUE THREAD

**Issue by athomann** [facebook/immutable-js#1385]
Possible bug in 4.0.0rc.7

I'm attempting to create a `Record` that includes a `Map` inside.  When I define a the `Map` with object syntax like `Map({ key: value })` I get the following error.

```
function call
Function cannot be called on any member of intersection type intersection
Member 1: polymorphic type: function type
Error: property `@@iterator` of $Iterable
Property not found in object literal
Member 2: polymorphic type: function type
Error: property `__proto__`
Property not found in object literal
```

When I change the syntax to `Map([['key', 'value']])`, the error goes away.  I can't tell if this is a bug or user error.

This is the typedef that I'm using `fields: Map<string, RecordOf<FieldsRecordType>>`

I'm on `0.54.0` for flow. I'll attempt to upgrade based on this issue https://github.com/facebook/immutable-js/issues/1360  

Does it make sense to document the minimum required version of flow-bin?

**Comment by leebyron** [comment]
Yep, unfortunately this change was both a fix for v56+ and requires v55+. It's mentioned in the Readme and front page of the docs - https://github.com/facebook/immutable-js#flow--typescript but that's certainly easy to miss. I'll investigate other ways to help people determine a minimum version

**Comment by athomann** [comment]
😅 A bit embarrassing to find the solution minutes after posting an issue. Closing
