### ISSUE TITLE
404 on "dist/immutable.min.js" link on site

### ISSUE THREAD

**Issue by marianoguerra** [facebook/immutable-js#1387]
### What happened

link to download on page gives 404.

where it says:

### How to reproduce

go to the site https://facebook.github.io/immutable-js/

scroll to the paragraph:

    To use Immutable.js from a browser, download dist/immutable.min.js or use a CDN such as CDNJS or jsDelivr.

click the link "dist/immutable.min.js"

it should give you a file, it gives 404

**Comment by leebyron** [comment]
Thanks for the report. We removed the checked-in `dist/` files, so we should relink these to a CDN

**Comment by yveslange** [comment]
Ohh nooo. I'm using Immutable JS in my Polymer application (still using `bower` and waiting for Polymer 3.0 to migrate). I don't want to install gulp and build it by my own :(

Can't you put the `dist/` files back ? :(

**Comment by leebyron** [comment]
Definitely use a specific hash, tag, branch when you use bower to have a stable build. We have an [#npm](https://github.com/facebook/immutable-js/tree/npm) branch which automatically builds the "dist" output specifically intended for those who want to rely on a particular build - I would recommend having your bower config point to this branch if possible.

**Comment by leebyron** [comment]
Here's the issue that tracked that work: https://github.com/facebook/immutable-js/pull/1323
