### ISSUE TITLE
Using flow, OrderedMap#merge cannot be called with a KeyedSeq

### ISSUE THREAD

**Issue by acusti** [facebook/immutable-js#1389]
### What happened

In immutable `4.0.0-rc.7` (and flow `0.57.1`), I’m getting this flow error when trying to merge a KeyedSeq into an OrderedMap:

```
Error: src/model/transaction/removeRangeFromContentState.js:72
 72:   blockMap = blockMap.merge(newBlocks).filter(block => !!block);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^ rest parameter array of call of method `merge`. Has some incompatible type argument with
938:     ...collections: (Iterable<[K_, V_]> | PlainObjInput<K_, V_>)[]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type. See: node_modules/immutable/dist/immutable.js.flow:938
  Type argument `T` is incompatible:
     72:   blockMap = blockMap.merge(newBlocks).filter(block => !!block);
                                     ^^^^^^^^^ KeyedSeq. This type is incompatible with
    938:     ...collections: (Iterable<[K_, V_]> | PlainObjInput<K_, V_>)[]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type application of identifier `Iterable` | type application of polymorphic type: PlainObjInput. See: node_modules/immutable/dist/immutable.js.flow:938
      Member 1:
      938:     ...collections: (Iterable<[K_, V_]> | PlainObjInput<K_, V_>)[]
                                ^^^^^^^^^^^^^^^^^^ type application of identifier `Iterable`. See: node_modules/immutable/dist/immutable.js.flow:938
```

I had expected `KeyedSeq` to be a part of `Iterable<[K_, V_]>`, but it seems that isn’t the case?

### How to reproduce

```js
var newBlocks = blockMap
    .toSeq()
    .skipUntil((_, k) => k === startKey)
    .takeUntil((_, k) => k === endKey)
    .concat(Immutable.Map([[endKey, null]]))
    .map((_, k) => { return k === startKey ? modifiedStart : null; });

  blockMap = blockMap.merge(newBlocks).filter(block => !!block);
```

Full source here: https://github.com/facebook/draft-js/blob/master/src/model/transaction/removeRangeFromContentState.js#L68

**Comment by leebyron** [comment]
Thanks for the report. I'd also have expected `KeyedSeq` to match `Iterable<[K_, V_]>` - I'll try out a flow test for this

**Comment by leebyron** [comment]
Hmm, I just put that exact reproduction case into a flow test (with some mocked values) and saw flow pass. I'm putting up a PR for a simpler test case which is also passing.

Do you mind testing out the master build (`"immutable": "facebook/immutable-js#npm"`) just to see if this issue was fixed on master since the last RC was released? I've been steadily improving flow types, so it's possible this was fixed

**Comment by acusti** [comment]
Running `npm install immutable@facebook/immutable-js#npm` removed that flow error, so it looks like this issue has been resolved. Thanks for the help!

**Comment by leebyron** [comment]
Awesome, thanks for the confirmation! I'll get a build on npm so you can rely on that
