### ISSUE TITLE
asImmutable does not return itself when collection is empty

### ISSUE THREAD

**Issue by myitcv** [facebook/immutable-js#1413]
Using `v4.0.0-rc.9`

### What happened

The [documentation for `asImmutable`](https://facebook.github.io/immutable-js/docs/#/Map/asImmutable) states:

> _Because it [`asImmutable()`] applies to mutable collections, this operation is mutable and returns itself._

But the following Typescript example shows this not to be the case where a collection (list in this case) is empty:

```typescript
let l1 = Immutable.List<number>().asMutable();
let l2 = l1.asMutable();

expect(l2).toBe(l1);

let l3 = l2.asImmutable();

expect(l3).toBe(l2); // FAILS
```

In my opinion `asImmutable` should, per the docs, _always_ return itself. But I raise this issue for discussion on whether the implementation or docs need to change.

Thanks

**Comment by leebyron** [comment]
Maybe we should update the docs for this specific case.

This is an example of two optimizations facing off against each other. Immutable.js has another optimization where the empty List is a singleton, any operation that results in the empty List always returns that same reference. That keeps memory low and comparison super cheap for this really common case. 

Since `asMutable()` needs to make a new reference that will be safe to mutate, `l2 !== l1` must be the case. However if the empty List is a singleton, then `l1 === l3` must be the case. If the result of `asImmutable()` is always expected to return the same reference, then `l3 === l2` must be the case. So we're left with `l1 === l3 === l2 !== l1` which can't be the case - one of these equalities must be broken. 

Tradeoff of costs: an edge case where `asImmutable()` will return a different reference vs no longer having the empty List be a singleton. The former is what this library chose.

**Comment by myitcv** [comment]
@leebyron thanks for the quick response.

> Since asMutable() needs to make a new reference that will be safe to mutate, `l2 !== l1` must be the case.

Apologies, I deliberately wrote my example in a rather obscure way with an additional `.asMutable()`:

```typescript
let l1 = Immutable.List<number>().asMutable(); // note the asMutable() call
let l2 = l1.asMutable();
```

which I think makes your assertion `l2 !== l1` incorrect. But I get what you were trying to highlight.

> Tradeoff of costs: an edge case where `asImmutable()` will return a different reference vs no longer having the empty List be a singleton. The former is what this library chose.

What costs are at play here? We've already created a new reference via `.asMutable()`. Why is it important that the empty list be a singleton? 

> That keeps memory low and comparison super cheap for this really common case.

What sort of comparison are you referring to here? We're using strict equality (`===`) everywhere.

Keeping memory low I can sort of wrap my head around, but I wonder whether that saving is significant in practice in real world applications? Compare the cognitive load of having `.asImmutable()` not return self; it requires everyone to understand and code for the situation when it doesn't (unless I'm missing something?)

**Comment by leebyron** [comment]
> What costs are at play here? We've already created a new reference via .asMutable(). Why is it important that the empty list be a singleton?

Comparison to the empty List happens all over the place internally, and this comparison has a === short-circuit. If there are multiple instances of immutable empty Lists, then this will start to hit the slower path. It's not an uncommon comparison externally as well.

> What sort of comparison are you referring to here? We're using strict equality (===) everywhere.

Exactly this. `===` comparison only works when there's a single version of the empty list.

> Compare the cognitive load of having .asImmutable() not return self; it requires everyone to understand and code for the situation when it doesn't (unless I'm missing something?)

This is one of the least commonly used methods in the whole library. Few bother with transiently mutable instances in the first place, most that do rely on `withMutations()` which handles things like nested mutable copies and further optimizations like checking for alteration. My presumption is that anyone using the `asMutable()`/`asImmutable()` methods are "gloves off" users and can handle the additional cognitive load.

**Comment by myitcv** [comment]
> Comparison to the empty List happens all over the place internally

Thanks; I'm not at all familiar with the implementation so this is interesting.

> This is one of the least commonly used methods in the whole library... (snip) ... My presumption is that anyone using the `asMutable()`/`asImmutable()` methods are "gloves off" users and can handle the additional cognitive load.

That makes sense. 

So perhaps the documentation fix could be roughly something along the following lines:

_"The yin to `asMutable`'s yang. `asImmutable` returns an immutable version of itself. In the case that self represents an empty list or map, an ImmutableJS-maintained singleton empty list or map (respectively) is returned. Otherwise, self is marked as immutable and returned. Hence it is generally not safe to assume that `asImmutable`, even when operating on a mutable collection, will return itself."_

The idea being to deter the caller from assuming that the receiver will be returned (which is what the docs currently do).
