### ISSUE TITLE
4.0-rc9 flowtype: throws an error when trying to use `new` operator

### ISSUE THREAD

**Issue by alexeyraspopov** [facebook/immutable-js#1421]
### What happened

When I try to do `new Map(...)` flow yells at "unused" argument:

```
Error: src/application/__tests__/ApplicationListStore-test.js:9
  9:   const state = new Map({ [id]: application });
                             ^^^^^^^^^^^^^^^^^^^^^ unused function argument
       v-------------------------------------------
  669: declare class UpdatableInCollection<K, +V> {
  670:   setIn<S>(keyPath: [], value: S): S;
  671:   setIn(keyPath: [K], value: V): this;
  ...:
  703: }
       ^ default constructor expects no arguments. See: node_modules/immutable/dist/immutable.js.flow:669
```

### How to reproduce

I use `flow@0.56` and `immutable@4.0.0-rc.9`.

```
npm install flow-bin immutable
./node_modules/.bin/flow init
```

```
touch test.js
```

```javascript
/* @flow */
import { Map } from 'immutable';

const something = new Map({ name: 'Liza' });
```

```
./node_modules/.bin/flow check
```

**Comment by acusti** [comment]
The collections, such as `Map`, `List`, `Set`, etc., are not constructors, and so aren’t intended to be invoked with the `new` keyword.

```js
const something = Map({ name: 'Liza' });
```

will work and not give you any flow errors.

**Comment by alexeyraspopov** [comment]
@acusti, I currently do it as a workaround.

The source code and docs state that `Map`, `List` and others are classes, which means they can be instantiated by using `new` keyword. Since docs describe "JavaScript-first API" it is expected that the same things I can do to native `Map`, `Set` and `Array` are applicable to ImmutableJS. The use of `new` produces the same result and only prohibited by Flow typings.
