### ISSUE TITLE
Overriding Record toJS broke in 4.0.0-rc8+

### ISSUE THREAD

**Issue by tjunnone** [facebook/immutable-js#1446]
Not quite sure if this was ever officially supported, but I have Record's that provide their own toJS() methods, which is very convenient for customizing JSON output.

Example, a coordinate type that becomes a JS array:
```javascript
class Coord extends Record({
  x: 0,
  y: 0
}) {
  toJS() {
    return [this.x, this.y];
  }
}
```

The toJS works fine in all versions of Immutable.js:
`console.log("Coord", new Coord({x: 1, y: 2}).toJS());`
> Coord [ 1, 2 ]

The problem comes in version 4.0.0-rc.8 (including rc.9, latest as of writing) where the Record's .toJS() function no longer seems to be used when converting an entire collection:

In 4.0.0-rc.8:
`console.log("Coord in List", List.of(new Coord({x: 1, y: 2})).toJS());`
> Coord in List [ { x: 1, y: 2 } ]

This was the output in 4.0.0-rc.1-7, which I think makes more sense:
`console.log("Coord in List", List.of(new Coord({x: 1, y: 2})).toJS());`
> Coord in List [ [ 1, 2 ] ]

I think it would be great if the ability to provide a custom toJS could be continue to be supported. Thanks!

**Comment by pulse14** [comment]
I also use this feature. Please do not remove 😞

**Comment by derekpeterson** [comment]
It would be great to get a comment about this. This kind of extension is valuable. If it is being intentionally cut, it would be helpful to have official confirmation of that.

**Comment by leebyron** [comment]
Unfortunately this was never explicitly supported - custom prototype methods on Records that interfere with Immutable.js's own API are not guaranteed to work as expected.

However this behavior probably should *incidentally* work, though you probably need to rename `toJS` to `toJSON`

**Comment by tjunnone** [comment]
Unfortunately even when providing a custom toJSON on the Record, it is not used when converting containers deeply. For example:
```javascript
class Coord extends Record({
  x: 0,
  y: 0
}) {
  toJSON() {
    return [this.x, this.y];
  }
}
const coordinates = List.of(new Coord({x: 1, y: 1}), new Coord({x: 2, y: 2}));
console.log("Coordinates", coordinates.toJS());
```
outputs
```
Coordinates [{x: 1, y: 1}, {x: 2, y: 2}]
```
instead of
```
Coordinates [[1, 1], [2, 2]]
```

That makes the suggestion in the docs to provide a toJSON quite the footgun.

**Comment by SamyPesse** [comment]
Previous implementation of `.toJS` (version < 4.0) was calling `.toJS` for inner values if it existed (https://github.com/facebook/immutable-js/blob/v3.8.2/src/IterableImpl.js#L66)

But now it looks like the newer implementation of `toJS` doesn't test if `value.toJS` is a method. All collections and record depend on this single implementation of `toJS` which doesn't make it easy to add something like `if (value instanceof Record) { return value.toJS() }`

@leebyron is that something that you think should be supported ? Currently I'm not sure this commit https://github.com/facebook/immutable-js/commit/c690ca8235cb397ba1b39a4b1f28acc3440dbafc is valid.
