### ISSUE TITLE
List hashCodes and equality check failing after deep persistent changes

### ISSUE THREAD

**Issue by dangerousdan** [facebook/immutable-js#1450]
Version: 4.0.0-rc.9

### What happened

When an items in a list changes value with `setIn` then changes back again, the hashCode is different from the original List.

The docs state that:

> If two values have different hashCodes, they must not be equal.

### How to reproduce

```javascript
import { List } from 'immutable'

var list1 = List([
  {label: 'foo'}, 
  {label: 'bar'}
])

// change a list value
var list2 = list1.setIn([1, 'label'], 'baz')
// change it back to the original value
list2 = list2.setIn([1, 'label'], 'bar')

console.log(JSON.stringify(list1.toJS()) == JSON.stringify(list2.toJS()))
// returns true

console.log(list1.hashCode())
console.log(list2.hashCode())
// do not match

console.log(list1.equals(list2))
// false (should be true)
```

See a live example on https://codesandbox.io/s/1003kox884

**Comment by ysaaron** [comment]
The reason why you get `false` at the line `console.log(list1.equals(list2))` is that your array contains with object value which is not a immutable object, then Immutablejs will consider that `list1` and `list2` are different.

You have to use `fromJS` to transfer array with object values.

If you use `Map` or `List`, those function only convert first level object to immutable object.
