### ISSUE TITLE
In docs for List, merge is incorrectly listed as an alias of concat

### ISSUE THREAD

**Issue by sebastiancarlsson** [facebook/immutable-js#1457]
### What happened

I don't know if I've misunderstood something but in the docs for `List` I stumbled upon this mistake: `merge` is listed as an alias of `concat`, but it's not.

https://facebook.github.io/immutable-js/docs/#/List/concat

### How to reproduce

I guess it's obvious that this is just a mistake in the docs, but I made an example anyway (look at the console). Concat concatenates and merge merges :)
```
var list1 = new Immutable.List([1, 2, 3]);
var list2 = new Immutable.List([4, 5, 6]);

console.log(list1.concat(list2).toJS());
console.log(list1.merge(list2).toJS());
```
Output is:
```
> [1, 2, 3, 4, 5, 6]
> [4, 5, 6]
```
Codepen with the above:
https://codepen.io/sebastiancarlsson/pen/RjzXKB

I can submit a PR if no-one objects.

**Comment by leebyron** [comment]
Please make sure you're reading the documentation for the correct version of this library - I think you may be reading v4 docs and using v3. - This is one method which changed between the major versions.

https://github.com/facebook/immutable-js/blob/master/src/List.js#L256
