### ISSUE TITLE
When calling from different global contexts

### ISSUE THREAD

**Issue by danschumann** [facebook/immutable-js#1470]
```
  function isPlainObj(value) {
    return value && (value.constructor === Object || value.constructor === undefined);
  }
```

is giving me problems

```
z = {plain: 'object'}
require('immutable').fromJS(z) == z // true
```

Because global.Object isn't the same as my app from the module directory of immutable.

I also reported this as a bug to nw.js, but is there another way you could check for plain object status?

**Comment by danschumann** [comment]
Using nw.js 0.27.3 on debian stretch.  I also had problems with redux-logger, I had to pass it my console, because the global.console of the module wasn't the same.

**Comment by leebyron** [comment]
Unfortunately there is not a performant way to detect realm-exotic object properties, and this function is part of the hot path.

If anyone is aware of one, I would happily entertain a PR
