### ISSUE TITLE
List.prototype.replace

### ISSUE THREAD

**Issue by danschumann** [facebook/immutable-js#1473]
I am using the following to replace the contents of arrays. 
```
Immutable.List.prototype.replace = function (array) {
  this.setSize(array.length).merge(array)
}
```

I use this, in the situation of updating `allIds`.  If I do `state.set('allIds', newArray)`, then allIds changes, even if the contents don't change, however, if I do `state.update('allIds', function(a) { a.replace(newArray) });`, then it only changes if the contents are different.

Is this worth including in the code base, or is there already a better function that doesn't always create a new instance of the list?

**Comment by leebyron** [comment]
Note that `merge` has different behavior in v4, where it has become an alias for `concat`.

Try:

```
return replaceArray.reduce((list, value, index) => list.set(index, value), list)
```

That should return the same list if nothing changes
