### ISSUE TITLE
zip function is not available in typescript

### ISSUE THREAD

**Issue by HK-Zhang** [facebook/immutable-js#1476]
### What happened

zip function is not available in typescript

### How to reproduce

const { OrderedSet } = require("immutable");
const a = OrderedSet([1, 2, 3]);
const b = OrderedSet([4, 5, 6]);
const c = a.zip(b);

**Comment by leebyron** [comment]
Make sure you're using the latest version - I cannot reproduce this issue in the master branch since zip is defined in the types file: https://github.com/facebook/immutable-js/blob/master/type-definitions/Immutable.d.ts#L1848-L1863
