### ISSUE TITLE
Why not make it possible for a immutable object to define its own merge and init behavior?

### ISSUE THREAD

**Issue by TotooriaHyperion** [facebook/immutable-js#1477]
Is there already a alternative method to solve the following problem?

Problem1, merge:
Since we some time need to merge a nested immutable object into current object,  but has different need on special object.

example:
current:
{
a: [1,2],
b: [3,4, 5],
c: [5,6],
d: 'hello',
}

tobeMerged:
{
a:[2,3,4],
b:[1,6],
c:[1,2,3],
d: 'world',
}

I want replace a, mergeIn b, append to c, and concat d;
So the result i desired is
{
a: [2,3,4],
b: [1,6,5],
c: [5,6,1,2,3],
d: 'helloworld',
}

When the height of the tree is not high, its enough to use mergeDeepWith.

But when its high, merger will be very complicated.

So I think if I can specify a merger to a,b,c,d and tell them how to handle merge behavior.

Problem2, init:

This is only about Record because other collection type is not a defined type.
Even with typescript, they can't tell the right type and do the right thing at runtime.

But Record is an already-defined data structure, so when define the properties of a Record, why not also define a initial method to every property(if not defined, use default init method)?

My current solution is to wrapper a constructor and manually invoke them on init.

But i think integrate them into Record will be awesome.

At the end

I noticed that my proposal is more like what a data schema should do rather than a immutable data structure should do.

But the trade-off is, in many cases we don't need a complete data schema.
Create a schema also makes immutable data structure not essential because schema can directly be designed 'immutable'.

And at the same time, integrating these two feature is not difficult, does not need too much  code ,does not break the original behavior or intervene into it.

If you have already considered these feature and decided not to integrate them, I'm glad to know the reason.
If haven't, take a consideration about this issue.

**Comment by leebyron** [comment]
Unfortunately the use cases you propose are beyond the general purpose data structures this library provides - I would suggest writing such a custom merger function which handles your specific cases and calling that directly rather than using this library's generic merge function.
