### ISSUE TITLE
 Order of elements in OrderedMap changes when we delete one of it.

### ISSUE THREAD

**Issue by pumanitro** [facebook/immutable-js#1478]
### What happened

Order of elements in OrderedMap changes when we delete one of it.

### How to reproduce

```
const { OrderedMap } = require("immutable");

let test = OrderedMap({ 
    a: 10, 
    b: 20, 
    c: 30, 
    d: 40
});

test = test.delete('b');

console.log(test);
```
And gets: 
![image](https://user-images.githubusercontent.com/7398214/35733376-81741194-081d-11e8-987d-5a7f1b81977e.png)

I was expecting a, c, d order but I get a, d, c.

**Comment by donkeybonks** [comment]
The `_map` inside is not the actual map. `OrderedMap` is just a `_map` with a `_list` inside that stores the actual order.

So basically you're looking at the wrong thing with your debug tools.

**Comment by leebyron** [comment]
The `_` properties are internal - OrderedMap is built from a _map containing the pairs, and a _list preserving the insertion order, the _list is responsible for the order within the implementation.

It is correct that removing an entry leaves an undefined entry in the list, which could cause unnecessary structure to be created, however this is a tradeoff against a shifting operation in the List, which would convert the `O(log N)` operation into an `O(N)` operation.
