### ISSUE TITLE
Possible Map Memory Leak/Garbage Collection Problem

### ISSUE THREAD

**Issue by dreallday** [facebook/immutable-js#1479]
I have a strange memory leak in my React-Native app, I've narrowed it down to Immutable `setIn` and/or `updateIn`.

My state is normalized, and then converted to an immutable state. There is a sockets handler which updates existing objects in state. This causes the RAM to slowly increase as new messages are updating state.

**State**:

    const state = {
        entities: {
            2000: {
                1: {
                    id: 1,
                    name: "I am normalized",
                    coordinates:[
                        {
                            lat: 0,
                            lng: 0
                        }
                    ]
                },
                2: {
                    id: 2,
                    name: "me too",
                    coordinates:[
                        {
                            lat: 0,
                            lng: 0
                        }
                    ]
                }
            },
            1337: {
                2: {
                    id: 2,
                    name: "me too",
                    coordinates:[
                        {
                            lat: 0,
                            lng: 0
                        }
                    ]
                },
                3: {
                    id: 3,
                    name: "also normalized",
                    coordinates:[
                        {
                            lat: 0,
                            lng: 0
                        }
                    ]
                }
            }
        },
        results: {
            2000: [1,2],
            1337: [2,3]
        },
    };

This is then converted with `fromJS()` to immutable state.

I have a sockets handler, which passes the `action.payload` to a reducer.

    action = {
        payload: {
            message_type: COORDINATES_UPDATE,
            messages: [
                {
                    id: 1,
                    coordinates: [
                        {
                            lat: 180,
                            lng: 180
                        }
                    ]
                },
                {
                    id: 2,
                    coordinates: [
                        {
                            lat: 90,
                            lng: 90
                        }
                    ]
                }
            ]
        }
    }

**reducer that handles the incoming action**: 

    case SOCKET_MESSAGE: {
        let newState = state;
        if(action.payload.message_type == "COORDINATES_UPDATE") {
            action.payload.messages.map((incoming_message) => {
                let id = incoming_message.id;
                let coordinates = incoming_message.coordinates;
                newState.get("results").map((data, entities_id) => {
                    if(data.indexOf(id) > -1) {
                        newState = newState.setIn(["entities", entities_id, "" + id, "coordinates"], fromJS(coordinates));
                    }
                })
            })
            return newState;
        }
    }

This searches the `results` `Map()` for an existing `id`, if it does exist, it updates the entities object. As far as I know, there are no problems with this logic, the state properly updates and is reflected in the `render()` component, altho for debug purposes I am rendering an empty `<View />` as my whole app, and only updating state.

However each `setIn`, or `updateIn` increases RAM ever so slightly, and with the frequency of updates I get it grows to GB in minutes.

[![Steady RAM increase][1]][1]

Relevant Packages:

    "react": "16.0.0",
	"react-native": "0.50.3",
	"immutable": "^3.8.2",
	"normalizr": "^3.2.4",
	"redux": "^3.7.2",

  [1]: https://i.stack.imgur.com/zJn0O.jpg

**Comment by danielran** [comment]
I don't know about the memory leak, but it seems to me you're creating quite a few intermediate objects in the reducer. As it stands, every call to `.map()` and `.setIn()` creates a new instance. Have you tried using `.withMutations()` and `.forEach()`?

```javascript
case SOCKET_MESSSAGE:
    if(action.payload.message_type == "COORDINATES_UPDATE") {
        return state.withMutations(newState => {
            action.payload.messages.forEach(({ id, coordinates }) => {

                newState.get("results").forEach((data, entities_id) => {
                    if(data.indexOf(id) > -1) {
                        newState.setIn(
                            ["entities", entities_id, "" + id, "coordinates"],
                            fromJS(coordinates)
                        );
                    }
                });
              
            });
        });
    }
```

Also, I think you could try a `Seq` for the inner loop, although I'm not yet familiar with them enough to confidently say whether there'd be any performance benefit in this case.

```javascript
newState.get("results").toSeq()
    .filter(data => data.indexOf(id) > -1)
    .forEach((data, entities_id) => {
        newState.setIn(["entities", entities_id, "" + id, "coordinates"], fromJS(coordinates));
    })
```

**Comment by dreallday** [comment]
Thanks, I ended up trying out both of your solutions, they both still have a memory hit. Not as much as my original code tho. Memory usage still grew to ~ 2GB after about an hour. I might just have to take out Immutable from the app.

**Comment by athomann** [comment]
@dreallday check to make sure you're not doing any `toJS()` conversions in `mapStatetoProps` https://redux.js.org/recipes/using-immutable.js-with-redux#never-use-tojs()-in-mapstatetoprops

**Comment by dreallday** [comment]
@athomann None, it was the intermediate states that immutable created.
At the time I updated one map in state ~10 times a second.

**Comment by leebyron** [comment]
Based on the memory report, it looks like you might have something retaining references to the previous instances of the data structure. If you manage to reduce this to a test case that still shows a GC leak outside the context of your app, please let us know.
