### ISSUE TITLE
Incorrect TypeScript declaration of the second argument of Map.mergeIn and Map.mergeDeepIn in 3.8.2

### ISSUE THREAD

**Issue by Rovanion** [facebook/immutable-js#1487]
### What happened

The methods Map.mergeIn and Map.mergeDeepIn have a TypeScript type declaration such that the map must be made of recursively equivalent data structures for the compiler to accept calls to it. For example I originally got that:

```
Argument of type 'Partial<Project>' is not assignable to parameter of type '{ [key: string]: Project; }'.
  Index signature is missing in type 'Partial<Project, "uuid">'.
```

When trying to call `state.mergeIn([action.payload.uuid], action.payload);` where state is a Immutable.js Map. 

In order to solve this issue I had to correct the type declarations distributed with immutable.js and pushed the corrected type declarations to a branch named 3.8.3 on my fork: https://github.com/Rovanion/immutable-js/tree/3.8.3

As to why I'm not running the betas of Immutable 4 the answer is that I have a dependency which depends on 3.8 named *typed-immutable-record* and in addition the move to 4 increased my build times from 2 to 10 seconds.

### How to reproduce
The below works as expected in the dynamic world of JavaScript, in a statically typed world you might find it wierd that the number 1 is so easily replaced with a Map but that is somewhat reasonable in the fully dynamic world:

```
const a = Map({a: 1, b: 2});
const b = Map({b: 3, c: 4});
console.log('Example: ', a.mergeIn(['a'], b));
// Log output:
 Map[2]
{"a" => Map[2]
    {"b" => 3}
    {"c" => 4}}
{"b" => 2}
```

Though when you try to make a merge which should make more sense, one where the value of `a` is a map, the typings for 3.8.2 makes the TypeScript compiler buck:

```
const a = Map({a: {b: 2}}); 
const b = Map({b: 3, c: 4});
console.log('Example: ', a.mergeIn(['a'], b));

// Compiler error:
Argument of type 'Map<string, number>' is not assignable to parameter of type '{ [key: string]: { b: number; }; }'.
  Property 'set' is incompatible with index signature.
    Type '(key: string, value: number) => Map<string, number>' is not assignable to type '{ b: number; }'.
      Property 'b' is missing in type '(key: string, value: number) => Map<string, number>'.
```

Using the relaxed type declarations of the above mentioned branch allows for the code to compile and successfully run:

```
const a = Map({a: {b: 2}}); 
const b = Map({b: 3, c: 4});
console.log('Example: ', a.mergeIn(['a'], b));
// Log output:
 Map[2]
{"a" => Map[2]
    {"b" => 3}
    {"c" => 4}}
{"b" => 2}
```

**Comment by leebyron** [comment]
Unfortunately we're only tracking issues for the v4 release and bugs that reproduce against master. Please file a new issue if you find a similar issue with a latest v4 release candidate
