### ISSUE TITLE
Immutable.js 4.0 increases build times by a factor of 5

### ISSUE THREAD

**Issue by Rovanion** [facebook/immutable-js#1488]
### What happened

The build time of my application based on Create React App TypeScript increased from 2 to 10 seconds, a five fold increase, when switching from Immutable 3.8.2 to 4.0.0-rc.9.

### How to reproduce

1. git clone -b 3.8.2 git@github.com:Rovanion/create-react-app-ts-slowdown-demo.git
2. `npm install`
2. Open three terminals and navigate them all to the newly created
   folder named create-react-app-ts-slowdown-demo.
3. In the first one run: `./node_modules/.bin/tsc --watch --diagnostics`.
4. In the second one run: `npm run start`.
5. Do the manipulation of the repository in the third one as described below:

You are now standing in a repository with three commits. The commit at the
HEAD of *master* includes immutable.js 4.0, the one at HEAD~1 does not,
the commit at the HEAD of the branch *3.8.2* includes immutable.js 3.8.2.

In order to demonstrate the large differences `npm run start` takes to
"compile" the project, open `src/App.tsx` and add a space character
anywhere and save the fil, essentially a NOOP. As you are standing at
the HEAD of master these numbers are _with_ immutable.js.

On my machine such a NOOP takes 0.02s for tsc to compile but the
incremental `npm run start` "compilation" takes 10 seconds.

Then change to the commit with immutable 3.8.2 by:

1. `git checkout -b 3.8.2`
2. `npm install`
3. Restart the build processes.

Now see how performing the same NOOP on `src/App.tsx` only results in only 2s being spent on "Compiling...".

My conclusion is that something changed between 3.8.2 and 4.0 so that the parts of the build process that is not the TypeScript compiler takes five times as long to complete, though I have little or no information to go on as to what this would be.

**Comment by inakianduaga** [comment]
Can you test with the compiler flag in `tsconfig.json`

```"skipLibCheck": true```

(this skips tsc checking the internal immutableJS typedefs

**Comment by Rovanion** [comment]
Tested. This reduces the time spent "Compiling..." to 1s with Immutable 4.0. This is available on the skipLibCheck branch: https://github.com/Rovanion/create-react-app-ts-slowdown-demo/tree/skipLibCheck

Interesting thing: The time spent "Compiling..." seems to match the time spent by tsc on an initial build which would indicate that the CRAT-template does a complete compile each time. 

The initial build time using only tsc goes from 2.61s with 3.8.2 to 9.83s with 4.0.0-rc.9.

**Comment by chrisgbaker** [comment]
Related to 4.0: Is there a schedule for an official 4.x release? I've noticed the milestone has been complete for some time. Apologies if this information is listed elsewhere, but I haven't been able to track it down.

**Comment by leebyron** [comment]
Unfortunately this seems to be a tradeoff with Typescript between correctness and performance. The v4 Typescript definitions are dramatically better, however this results in Typescript spending more time doing type checking.
