### ISSUE TITLE
Immutable.Record with a "size" key causes "merge" commands to fail

### ISSUE THREAD

**Issue by EvHaus** [facebook/immutable-js#1490]
### What happened

Using `Immutable@4.0.0-rc.9`, when you create an `Immutable.Record` instance with a key called `size` it will cause all `merge*()` commands to return `undefined` instead of a new immutable instance of the object.

Seems this is related to #377, #424 and #657. All those tickets are marked as resolved, however, this issue with `merge()` commands still exists. A `set()` and `get()` works as expected, but something about the implementation of `merge()` causes issues.

No warnings or errors were thrown telling me that a `size` key cannot be used.

### How to reproduce

```
const Box = Immutable.Record({
    size: 0
});

const MyBox = Box();

// Returns "undefined". Should return `MyBox({size: 1})` instead.
console.log(MyBox.merge({size: 1}));
```

Live example of the issue: https://jsfiddle.net/gro2zehk/16/

**Comment by acusti** [comment]
@EvHaus I fixed this issue in a fork I’m maintaining to help get v4 over the finish line. If you would find it useful, you can install a build now that includes the fix by replacing your immutable dependency string in `package.json` with:
```json
    "immutable": "brandcast/immutable-js-built#aa94985",
```
Note that I needed to clear out my `yarn.lock` file and `node_modules` and install from scratch to get the proper version.
