### ISSUE TITLE
This regex may be stucked by input strings

### ISSUE THREAD

**Issue by 2bdenny** [facebook/immutable-js#1491]
https://github.com/facebook/immutable-js/blob/7f4e61601d92fc874c99ccf7734d6f33239cec8c/pages/lib/runkit-embed.js#L31

We tested regexes in the project =D, and found this regex may be stucked by input strings like `'\n>t>>>>>>>>>>>>>>>>>>>>>>>>>O>9>Oe39tO>9>>>>\n*'`

**Comment by leebyron** [comment]
Thanks for the report!

As long as such strings don't end up in our documentation source, we should be okay
