### ISSUE TITLE
Typescript Map creation on 4.0 rc9

### ISSUE THREAD

**Issue by kevinsperrine** [facebook/immutable-js#1497]
I've read the Typescript definitions are much better on 4.0 than 3.8, and I'm starting a new project so I wanted to get rolling with 4.0, but keep running into various typing issues that didn't appear before. Are these bugs or does the documentation need updated?

### What happened
Type errors when attempting to create a map from an object or array of data.

### How to reproduce
Attempt to create an immutable Map from an array of arrays on 4.0.0-rc.9 w/ Typescript 2.7.2.

For Example: 
```
import { Map } from 'immutable';

type SimpleObject = { id: string; name: string };

const arrayData = [
  ['ghi789', { id: 'ghi789', name: 'ghi789' }],
  ['def456', { id: 'def456', name: 'def456' }],
  ['abc123', { id: 'abc123', name: 'abc123' }]
];

const mapOne = Map<string, SimpleObject>(arrayData);
```

Will throw a this type error: 
```
src/immutable.ts(11,42): error TS2345: Argument of type '(string | { id: string; name: string; })[][]' is not assignable to parameter of type 'Iterable<[string, SimpleObject]>'.
  Types of property '[Symbol.iterator]' are incompatible.
    Type '() => IterableIterator<(string | { id: string; name: string; })[]>' is not assignable to type '() => Iterator<[string, SimpleObject]>'.
      Type 'IterableIterator<(string | { id: string; name: string; })[]>' is not assignable to type 'Iterator<[string, SimpleObject]>'.
        Types of property 'next' are incompatible.
          Type '(value?: any) => IteratorResult<(string | { id: string; name: string; })[]>' is not assignable to type '(value?: any) => IteratorResult<[string, SimpleObject]>'.
            Type 'IteratorResult<(string | { id: string; name: string; })[]>' is not assignable to type 'IteratorResult<[string, SimpleObject]>'.
              Type '(string | { id: string; name: string; })[]' is not assignable to type '[string, SimpleObject]'.
                Property '0' is missing in type '(string | { id: string; name: string; })[]'.
```

Repo: https://github.com/kevinsperrine/immutable-test

**Comment by TheophileSketo** [comment]
You need to explicitly type your arrayData as [string, { id: string; name: string; }][]. The error message makes it obvious typescript didn't infer the correct type, which is almost always the case with tuples.

**Comment by kevinsperrine** [comment]
Thanks, @TheophileSketo.

**Comment by Ostosis** [comment]
For anyone else running into this issue, adding `"downlevelIteration": true,` to your tsconfig.json compilerOptions also fixes this issue without having to do messy type assertion.
