### ISSUE TITLE
Best practice when use with React

### ISSUE THREAD

**Issue by iShawnWang** [facebook/immutable-js#1498]
I wonder what's the best practice to use `immutable.js` with `React` : 

Few confusions : 

Where should I use the immutable object, should I use convert all my data to immutable object ?
such as : 
- get data from API then convert JSON to an immutable object
- update immutable object with `update`, `setIn` function, and never call `toJS()` for best performance
- In components : <text>obj.getIn( ['foo', 'bar'] )</text>

Is this the best practice? or any other suggestions?

**Comment by ishanyang** [comment]
but if the value is List or Map?

**Comment by iShawnWang** [comment]
@ishanyang sorry, what you mean?

**Comment by leebyron** [comment]
It sounds like you're doing reasonable things so I'll close this issue (trying to use GH Issues to only track bugs)
