### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by benjamingr** [facebook/immutable-js#15]
Hi, I've noticed you use `.toJSON()` to convert to JavaScript objects. 

JSON is a data serialization format, converting it `toJSON` would have been to also call `.stringify` on it. 

The objects produced by this call are also not always valid JSON or are even encodable/decodable as JSON. 

I would recommend renaming `.toJSON`. I don't have any particularly good ideas on what to though.

**Comment by yavuzmester** [comment]
Hi, toJS is confusing to me that we are writing in JS already. A class instance with methods is still a JS object, isn't it?
