### ISSUE TITLE
An error  about Merge was found in the document 。

### ISSUE THREAD

**Issue by lz-lee** [facebook/immutable-js#1508]
### What happened

An error  about [Merge](http://facebook.github.io/immutable-js/docs/#/merge) was found in the document 。

### How to reproduce

```
const { merge } = require('immutable@4.0.0-rc.9')
const original = { x: 123, y: 456 }
merge(original, { y: 789, z: 'abc' }) // { x: 123, y: 789, z: 'abc' }
console.log(original) // { x: { y: { z: 123 }}}
```
![image](https://user-images.githubusercontent.com/22316795/38622304-72cd64c2-3dd5-11e8-909b-516309ab7d9c.png)

In the example , the original value should not be `{x: 123, y: 456}` ? and when i run it , insteadof get `{x: 123, y: 456}`
![image](https://user-images.githubusercontent.com/22316795/38622278-666ba3b0-3dd5-11e8-89bd-c8a689e76987.png)

**Comment by leebyron** [comment]
This is fixed in the master branch.

Thanks for going to the detail of including screenshots, however in the future please direct that effort towards submitting a pull request!
