### ISSUE TITLE
3.8.2 toOrderedMap and toOrderedSet incorrectly flowtyped

### ISSUE THREAD

**Issue by TomiS** [facebook/immutable-js#1510]
In version 3.8.2, flow typings of these functions are:
```
toOrderedMap(): Map<K,V>;
toOrderedSet(): Set<V>;
```
in here:
https://github.com/facebook/immutable-js/blob/v3.8.2/type-definitions/immutable.js.flow#L70
https://github.com/facebook/immutable-js/blob/v3.8.2/type-definitions/immutable.js.flow#L72

OrderedMap and OrderedSet types are even defined but they are not used:
https://github.com/facebook/immutable-js/blob/v3.8.2/type-definitions/immutable.js.flow#L545-L547
https://github.com/facebook/immutable-js/blob/v3.8.2/type-definitions/immutable.js.flow#L587-L589

This seems to cause flow errors anywhere where Immutable 3.8.2 is used with those functions (in latest 0.70 flow-bin versions). I tried to convert draft-js to use 3.8.2 and encountered this. Could we just simply convert to:
```
toOrderedMap(): OrderedMap<K,V>;
toOrderedSet(): OrderedSet<V>;
```

**Comment by TomiS** [comment]
Here's what I mean (I'd make a PR but I can't target current master with this change based on 3.8.2 tag)
https://github.com/TomiS/immutable-js/commit/7521908c61e3c6c8f475dc466f216627a1a7b274

**Comment by leebyron** [comment]
Unfortunately there are no plans to release new builds of v3 - all efforts are going towards a v4 release, where this issue has been fixed.

I believe the third-party flow types repo for immutable-js has corrected this issue?
