### ISSUE TITLE
v4 release ?

### ISSUE THREAD

**Issue by kopax** [facebook/immutable-js#1515]
Hi, I see that v4 https://github.com/facebook/immutable-js/milestone/1 is completed.

We are already using the new `isImmutable`, when will v4 be officialy released ?

**Comment by karland** [comment]
Indeed, maybe @leebyron could help clarify what the strategy with immutable.js is. 

Immutable is a great library and I think we can be thankful for it. Moving forward, however, it would be nice to get some idea on the vision. This repo really feels abandoned and not maintained any longer.

The same feeling was already present in the past:

[https://github.com/facebook/immutable-js/issues/1215](https://github.com/facebook/immutable-js/issues/1215)

[https://github.com/facebook/immutable-js/issues/1295](https://github.com/facebook/immutable-js/issues/1295)

But then, all of a sudden, there was some activity for a couple of weeks or so, before it fell asleep again. 

Could we have some clarity, if there are plans to move this repo forward. That would be great. Thank you.

**Comment by acusti** [comment]
Great question! Though I should point out that it’s a duplicate #1494. Really hope we get some movement on this soon.

**Comment by leebyron** [comment]
Merging into #1494
