### ISSUE TITLE
Immutable deletes any JS properties (V3.8)

### ISSUE THREAD

**Issue by NoMan2000** [facebook/immutable-js#1517]
If you add any custom properties to an Array, it will be destroyed when fromJS is called.  The simple test.

```javaScript
const { fromJS } = require("immutable");

const foo = [
    'one',
    'two'
];

foo.maxLength = foo.length - 1;
foo.offset = 0;

const newState = fromJS(foo);

console.log(newState.toJS());
```

newState will not have `maxLength` or `offset` set as custom properties.

**Comment by juffalow** [comment]
Hi, you are mixing two things - array and object.

If you define it as object and then "extend" the object, the result contains those new properties.

```
const { fromJS } = require("immutable");

const foo = {
    'one': 1,
    'two': 2
};

foo.maxLength = foo.length - 1;
foo.offset = 0;

const newState = fromJS(foo);

console.log(newState.toJS());
```

Result is: `{ one: 1, two: 2, maxLength: NaN, offset: 0 }`

If you define it as an array, then just use `push` method and the result will be with the new item.

```
const { fromJS } = require("immutable");

const foo = [
    'one',
    'two'
];

foo.push('three');

const newState = fromJS(foo);

console.log(newState.toJS());
```

Result is: `[ 'one', 'two', 'three' ]`

**Comment by leebyron** [comment]
Immutable.js's data structures are not a perfect mirror of Javascript's Object and Array and this is one such example. Immutable List can only contain indexed entries and not arbitrary additional properties. If arbitrary properties are important to you, I suggest using a Map, which can also contain numeric keys.
