### ISSUE TITLE
List passed through Redux is not `map` able

### ISSUE THREAD

**Issue by kulicuu** [facebook/immutable-js#1522]
Using version 4.0.0-rc9, I'm making a `List` out of an array from backend `all_users`, passing into component with Redux's `map_state_to_props`, when I try `@props.all_users.map (v, idx) ->` I get the error "TypeError: undefined is not an object (evaluating 'this.props.all_users.map')".
(syntax is coffeescript)

To check, I ran the map function on the Immutable `List` before passing to Redux/component, and it works. I also ran the List.isList(@props.all_users) within the component, and it returns `true`.  

Looks like something is happening in transit through Redux to mangle it.

**Comment by Splace42** [comment]
Check that all_users exist before

**Comment by leebyron** [comment]
Sorry, this isn't an issue with this library.
