### ISSUE TITLE
[FEATURE] allow defaultValue to be passed in for first() and last()

### ISSUE THREAD

**Issue by haxxxton** [facebook/immutable-js#1553]
Currently trying to chain off `first()` or `last()` without having to first check length is causing flow errors about not being able to perform the next action off `undefined`.

e.g.

`foo.last().get('bar')` throws `Cannot call foo.last().get because property get is missing in undefined`

It would be awesome to be able to use `first()` and `last()` in the same way that `get()`, `getIn()`, `updateIn()`, etc. work.

Suggested API:

`foo.last(Map()).get('bar')`

Allow `first()` and `last()` to take an optional single argument to act as a defaultValue when there is no first or last value found.

**Comment by yasserhussain1110** [comment]
I'd like to take this issue up, if that's okay.

**Comment by rgbkrk** [comment]
I think that's a great idea and you should make a PR @yasserhussain1110!

**Comment by yasserhussain1110** [comment]
@rgbkrk I have created a PR. Please let me know if corrections/changes are required.
