### ISSUE TITLE
Operations on Set/Map/List lose concrete type information

### ISSUE THREAD

**Issue by lwouis** [facebook/immutable-js#1563]
This is a follow-up to issue #871. I'm still seeing this problem on immutable@3.8.2 and typescript@2.9.2.

Basically anytime a method such as `filter` or `map` or `concat` is used on a `Set` for example, it returns an `Iterable`. This means I have to litter my code with casts to `Set` to reassure the typescript compiler. This is very bad because every cast is a potential bug later on when code around the cast is updated.

I could also use `toSet()` and the likes, but it's extra runtime work which should not be necessary. And the code is still polluted by all those calls, trying to get back to the concret type.

How to reproduce:

```typescript
Set<string>().map(a => a) === typeof Set<string>;
```

**Comment by bohdanbirdie** [comment]
Hi @lwouis
I had the same issue and decided to use `toSet()` for right now.
By checking type definitions [we can see](https://github.com/facebook/immutable-js/blob/master/type-definitions/Immutable.d.ts#L573) that in version 4 this will no longer be an issue, but in version 3 `List` extends `Iterable`, where actually methods `filter` and `map` are defined
```TypeScript
map<M>(
      mapper: (value?: V, key?: K, iter?: /*this*/Iterable<K, V>) => M,
      context?: any
    ): /*this*/Iterable<K, M>;
```

But I might be wrong 🙂

**Comment by leebyron** [comment]
Unfortunately this is a known problem with v3 but is fixed in the v4 release candidates
