### ISSUE TITLE
Flow error "SetSeq is incompatible with IndexedSeq"

### ISSUE THREAD

**Issue by jmarceli** [facebook/immutable-js#1564]
Hi,
It looks like there is a bug in flow definitions for Immutable@3.8.2. After running `yarn flow` on my project I'm getting this error:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/immutable/dist/immutable.js.flow:406:33

SetSeq [1] is incompatible with IndexedSeq [2].

 [2] 387│   static of<T>(...values: T[]): IndexedSeq<T>;
        :
     403│
     404│ declare class SetSeq<T> extends Seq<T,T> mixins SetIterable<T> {
     405│   static <T>(iter?: ESIterable<T>): IndexedSeq<T>;
 [1] 406│   static of<T>(...values: T[]): SetSeq<T>;
     407│ }
     408│
     409│ declare class List<T> extends IndexedCollection<T> {
```
Is there anything I can do about that?

I'm using latest flow version which is `0.77.0`.

**Comment by oriSomething** [comment]
It's an old one and it seems it won't be fixed until future 4.0 (which is release date seems far away from now).
I've made a script that removed this file on `postinstall`

**Comment by jmarceli** [comment]
Ok. Thanks for your reply, removing file indeed solves this issue.

**Comment by jmarceli** [comment]
How about adding `// $FlowFixMe` to line above mentioned error? It will be easy and quick "solution", possible without waiting for 4.0 release.

**Comment by plumpNation** [comment]
@jmarceli that solution makes more sense than the removal of the file completely, and will help any builds that depend on a successful flow check on a pre commit hook. For instance :D

**Comment by oriSomething** [comment]
@jmarceli Hey, I only see now, when I wrote remove this "file" I meant "line". `$FlowFixMe` might fix it but also might cause casting to `any` in some cases

**Comment by leebyron** [comment]
Known issue - all future development is happening on the v4 builds
