### ISSUE TITLE
Proposal: Integrations with Sequins -- the mutable to immutable's immutable.

### ISSUE THREAD

**Issue by conartist6** [facebook/immutable-js#1573]
As I grow more comfortable with immutable I've found myself using it all the time - for example just because I needed a stable sort, or to flatten or group structured data, or because it provides a convenient object oriented way of managing common functional transforms using iterators in a way that respects key/value pairs when appropriate.

While I usually want all these things, I don't always want immutability. Thus I am creating Sequins, an implementation of the Immutable.js API backed by es6 native data structures. Its Map and Set types are derived from native (or CoreJS) ones (its List type is not derived from array though). It also includes Indexed, Keyed, and Set sequences.

Before I go further I should say that Sequins code is not [yet] at the level of maturity to warrant integration with Immutable. When it is, and I hope to get it there soon (by the time Immutable is ready to release 4.0), I'm happy write the diffs for Immutable. For now I just want to get a start on the discussion of whether integration is reasonable and what problems might be created.

The particular integration I'm thinking of is with Immutable's detection of "data structures" and keyed collections. Sequins exports a set of sentinel properties almost identical to those of Immutable. It has:
`@@__MUTABLE_ITERABLE__@@`
`@@__MUTABLE_SEQUENCE__@@`
`@@__MUTABLE_KEYED__@@`
`@@__MUTABLE_INDEXED__@@`
My proposal is for immutable's [Predicates.js](https://github.com/facebook/immutable-js/blob/master/src/Predicates.js) to consider mutable's sentinels as well for the `is*` methods in that file (excluding `isImmutable`) and renaming the old methods to `isImmutable*`. Then it would just remain to find locations where only Immutable types make sense and change them to `isImmutable*` checks.

I think it makes sense to also include native structures in that reflection. Particularly instances of native `Map` should satisfy `isKeyed`.

The other consideration is whether it would make sense to add any new methods like, say, `Immutable.fromMutable`, which would be a deep conversion converting any mutable/native structures to their immutable counterparts. `Map` and `Set` instances would be converted by such a function, but objects would be ignored. Both `Array` and Sequins `List` instances could be converted. Sequins would also support `Sequins.fromImmutable`.

**Comment by conartist6** [comment]
The most current Sequins code is viewable at: https://github.com/conartist6/sequins/tree/concrete/src

**Comment by conartist6** [comment]
Question: This is insane, you're essentially forking Immutable?
Answer: I'm doing everything I can to keep it from being insane. One big thing is that I'm using method implementations (e.g. `map`, `filter`, `slice`) from [iter-tools](https://github.com/sithmel/iter-tools).

**Comment by lukaswelinder** [comment]
> It seems likely to me that this approach would be less insane than trying to build mutability into immutable directly.

It already is; all structures have `.asMutable()`/`.asImmutable()` and `.withMutations(/* ... */)` methods. The only thing I see missing is what you mentioned above:

> My proposal is for immutable's Predicates.js to consider mutable's sentinels as well for the is* methods in that file (excluding isImmutable) and renaming the old methods to isImmutable*. Then it would just remain to find locations where only Immutable types make sense and change them to isImmutable* checks.

This would be nice to have, however, since mutability support is primarily intended to improve performance when making multiple consecutive transformations (meaning you should avoid mixing mutable w/ immutable instances), the usefulness is marginal.

I do think that building the immutable sequence API on mutable native structures is a novel idea, but that is a bit of a departure from Immutable.js as a project and would likely not blend nicely due to the fact that Immutable.js implements its own versions of said native structures.

**Comment by conartist6** [comment]
I'm definitely familiar with asMutable, but it isn't comprehensive enough to suit my needs.

An obvious problem is that it doesn't have its own name and types. If I'm using a mix of mutable and immutable objects, it should be easy to tell which is which by looking at the type definition or by looking at the imports.

Another limitation is that not all methods are supported when in Immutable's mutable mode.

More problems: since the underlying implementation doesn't change you still have a lot of added weight. A prime example is the List implementation, which is O log32(n) for random access.

Finally my sequences are actually mutable too. That is to say, they're expressed purely as operations on top of a source mutable data structure, and can be recomputed after the underlying data structures has changed. This is true even in the case where the sequence must be cached to run a particular algorithm.

**Comment by lukaswelinder** [comment]
> An obvious problem is that it [sic] doesn't have its own name and types.

True, but your project does not appear to address this issue either.

> If I'm using a mix of mutable and immutable objects, it should be easy to tell which is which by looking at the type definition or by looking at the imports.

In my experience, if you are using a mix of mutable and immutable structures and find yourself in a situation where you don't know which is which, you might want to reconsider how and where you are using immutable structures.

> Another limitation is that not all methods are supported when in Immutable's mutable mode.

While I have never found this to be a significant limitation, this is a great point.

> More problems: since the underlying implementation doesn't change you still have a lot of added weight. A prime example is the List implementation, which is O log32(n) for random access.

Another great point.

> Finally my sequences are actually mutable too. That is to say, they're expressed purely as operations on top of a source mutable data structure, and can be recomputed after the underlying data structures has changed. This is true even in the case where the sequence must be cached to run a particular algorithm.

I think if you can express changes to a mutable structure as an Operational Transform (or something similar) and make that interface compatible with Immutable.js structures then the pairing might work.

However, the next concern would be the performance of converting data between mutable and immutable. While `O(log<sub>32</sub>(n))` is not as fast as `O(1)`, you are likely to lose that gained performance when converting in most cases.

Apologies if I appear negative,  I do like where you are going with this and will be keeping an eye on it.

**Comment by conartist6** [comment]
I think I misrepresented a bit by offering the mixing of mutable and immutable types as a major selling point. I hope that by and large they will not end up being mixed (though I'd like them to play nicely together if they are.)

I intend Sequins more for situations where mutability is important for performance reasons. For example while Immutable excels at holding small state objects, I don't consider it a good choice to implement long lived record stores or caches.

Using objects for those is also a poor experience though, as it lacks all of the great functionality that Immutable brings to the table, and has its own problems. Just for starters, to have O(1) access to size you have to track it yourself. Then either you can use Object.create(null) and lose all your prototype methods (including hasOwnProperty), or you can risk mixing up prototype methods with the data since all accesses theoretically need to do a hasOwnProperty check to be sure they've accessed actual data. That hasOwnProperty is both necessary defensive coding style and possibly unavailable if the other defensive coding style is chosen is a key reason that I can't wait to use Map (or a derivate) for any generic associative storage in my code.

**Comment by conartist6** [comment]
Just an update: a usable (node and webpack) version of Sequins in now published on npm, as well as as much documentation as I could cobble together without authoring and coding a whole doc site. Further test coverage and the doc site will be the upcoming areas of focus, as well as a few of the more complicated features I've intentionally been saving til last.

It is my opinion that though some pieces are missing, and some are untested, even just the tested features make up a useful tool.

The codebase has thus far prioritized legibility and consistency over perf, so I hope it will be easy for new users to contribute.

**Comment by conartist6** [comment]
This isn't going away. I've been working steadily on it. Bugs are being fixed, the test suite is expanding, and [the documentation site](http://burningpotato.com/sequins-docs/docs/#/) is nearing readiness (note: there are still a few things in there that that are still outright wrong, e.g. examples missing new keyword).

@leebyron Any thoughts on whether you would be willing to bring support into Immutable? It's looking like it will be ready for consumption by the time Immutable is ready for 4.0.

**Comment by conartist6** [comment]
Closing in favor of #1668
