### ISSUE TITLE
mergeDeep behavior inconsistent across different versions 

### ISSUE THREAD

**Issue by habibtariq** [facebook/immutable-js#1574]
I am getting inconsistent results for mergeDeep.
I am using version **4.0.0-rc.9**

```javascript
let obj1 = Immutable.fromJS({ x: [{ a: 1 }] });
let obj2 = Immutable.fromJS({ x: [{ b: 1 }] });

let result = obj1.mergeDeep(obj2);

// expected result { x: [{ a: 1, b: 1 }] }
// produced result { x: [{ a: 1 }, { b: 1 }] }
```
if i downgrade to verison **3.8.2** it seems to behave correctly. Has the desired behavior changed or is there some kind of bug with version **4.0.0-rc.9**?

**Comment by lukaswelinder** [comment]
@habibtariq That is the expected result. Concatenating lists on deep merge is a [breaking change](https://github.com/facebook/immutable-js/pull/1344) included in v4.

This issue should be closed.
