### ISSUE TITLE
Destructuring support. getIn looks bad.

### ISSUE THREAD

**Issue by shivwork** [facebook/immutable-js#1613]

**Comment by conartist6** [comment]
This is going to be a wontfix. You're asking for a new feature of the language, not of Immutable.js. You could direct such a proposal to the TC39 committee [here: https://github.com/tc39/proposals]. If indeed the language did provide the ability for libraries to implement custom destructuring behavior I'm sure Immutable would gladly support it.

**Comment by leebyron** [comment]
If only we could change the javascript runtime behavior. Unfortunately JS destructuring requires plain objects
