### ISSUE TITLE
Default value does not save to Immutable structures

### ISSUE THREAD

**Issue by Bacher** [facebook/immutable-js#1624]
Type: Bug (I think it's a bug)

It's example of my problem.
Suppose I've received response for my items list, and in response I have empty array (no items). It's valid response (store in variable `exampleDataFromResponse`).
And I would like to insert data into my Immutable state:

```
const exampleDataFromResponse = [];
const state = Immutable.Map();
const updatedState = state.update('list', Immutable.List(), list => list.concat(exampleListFromResponse));
console.log('state.list:', updatedState.get('list'));
```

Then I make operations like above and I suppose to have my Immutable.Map state like:

```
{
    list: [],
}
```

Actual result:
```
{ }
```

Result will be same and for other operations: `merge`, `mergeIn`, `mergeDeepIn`, ...

But if you will change variable `const exampleDataFromResponse = ['somedata']` all logic will work as expected.

**Comment by Bacher** [comment]
More simple example:
```
const state = Immutable.Map();
updatedState = state.update('list', Immutable.List(), () => Immutable.List());
```

My created in callback List() does not put in my map;

**Comment by leebyron** [comment]
While this can be confusing behavior, it's not a bug because it ensures the constraint that providing an identity function to `update()` results in no changes.

If your intention is to use a default value other than undefined in your update function, then I'd suggest using function argument defaults.

As an example:

```js
const state = Immutable.Map();
updatedState = state.update('list', (list = Immutable.List()) => list.concat([]));
```
