### ISSUE TITLE
Preserve the author of original commit while merging PRs

### ISSUE THREAD

**Issue by trivikr** [facebook/immutable-js#1633]
### What happened
This is related to PR #1621
* The PR was posted on `Oct 18, 2018, 7:48 AM PDT`
* It received the first comment from reviewer on `Oct 26, 2018, 7:14 PM PDT`
* A manual merge was done on `Oct 26, 2018, 7:16 PM PDT`, which override the original author of the commit in 9ea87744446cbbf17fb19ceb1aaa656eae5f4f93

This way the author doesn't get credit for the contribution, and is not welcoming to new contributors.

### How to fix
There are several options:
* Create/Update Collaborator Guide to ensure author information is retained while doing git push. This issue has been discussed online before ([example](https://github.com/python/miss-islington/issues/16))
* Give some time to the author to respond to the review comments.

**Comment by leebyron** [comment]
Sorry about that.

I reverted the commit and reapplied it with the `Co-authored-by:` tag based on your suggestion. Hopefully that resolves things.

I wasn't aware of the Co-authored-by tag, so I'll certainly use that for all manual merges, however to avoid situations like this in the future, if you see CI failures please resolve them before waiting for a maintainer code review.
