### ISSUE TITLE
Map.selectKeys

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/immutable-js#165]
I believe I want something like [Clojure’s `select-keys`](https://clojuredocs.org/clojure.core/select-keys).

The mutable JS equivalent (using Lodash):

``` js
var foo = { bar: 0, baz: 0 };
_.pick(foo, 'bar'); // => { bar: 0 }
```

I can't see anything like this on `Immutable.Map`, but I could be mislead – this is my first time using immutable data structures.

**Comment by glenjamin** [comment]
Personally I think this is common enough to be a first-class API.

Especially as when picking keys from an existing object, we should only need to iterate over the keys to pick.

**Comment by kendagriff** [comment]
+1 to making it first-class.
