### ISSUE TITLE
we need use fromJS(........).set, Whether or not use immutable.is(map1, map2) before it.

### ISSUE THREAD

**Issue by Meow-z** [facebook/immutable-js#1655]
```
import { fromJS, is } from 'immutable'

const state = fromJS({
  a: { b: 1 },
  c: 2
})
const newA = fromJS({ b: 1 })

// need 'is' before 'set', Whether or not optimize 'set'.
const setA = (state, newA) => {
  return is(state.get('a'), newA) ?  state : state.set('a', newA)
}
```

**Comment by Meow-z** [comment]
thanks~
when use redux, it need `state.xxxx.getIn(['a', 'b'], '')` avoid duplicate rendering. Legacy code refactoring is too hard to not do it.

**Comment by conartist6** [comment]
I don't understand what you are saying at all. If there is no bug in Immutable, perhaps you could close this ask questions [on stackoverflow](https://stackoverflow.com/questions/tagged/immutable.js)?
