### ISSUE TITLE
Immutable js is needed only when you have bad state architecture.

### ISSUE THREAD

**Issue by dennisat** [facebook/immutable-js#1659]
Especially with redux, you don't need it at all. Since it is easy to update small parts of the state in clean way.

**Share your thoughts**

**Comment by conartist6** [comment]
@dennisat Would you consider either providing concrete suggestions or simply closing the issue? It does not appear to be actionable. We're not going to delete the library or anything. You are obviously entitled to a philosophy in which Immutable is not necessary, and if you feel strongly I encourage you to go write a blog post explaining your position. If you write it and link it here, I'd be happy to take a look (though I can't promise I'll agree).

**Comment by dennisat** [comment]
Hey.
**Don't get me wrong. This library is awesome, simplifies the updates at a high level. Also, has very good performance.**
After a few months working with it, I realized that we wouldn't need it if the state has different architecture.
With few words: we tend to create states that are close to ui's needs. This makes the update of the state α nightmare. If we organize the data in a more database/indexed way, the updates would be simpler and more generic. The data would be consumed easily from different parts of the app.
