### ISSUE TITLE
TypedArray import/export

### ISSUE THREAD

**Issue by Downchuck** [facebook/immutable-js#167]
Not sure if this is already covered: I'd like a memory safe method for pushing and pulling data into and out of typed arrays. They're a bit more efficient than simply serializing as JSON.

**Comment by louisremi** [comment]
Is there a way to get immutable to still use typed arrays internally? Otherwise we loose the perf benefits of native types.

**Comment by leebyron** [comment]
Not currently, no. A lot of the performance benefits of typed arrays is the ability to be backed by a single buffer - but the data structures used here are trees of small arrays. It's unclear how much performance we could actually gain from using typed arrays.

**Comment by monfera** [comment]
Referring back to the inquiry from @louisremi : there are lots of reasons for which it would be cool to keep stuff as a typed array, way beyond the non-trivial avoidance of conversion costs. In certain situations, your only option is to use typed arrays. To name two: transferring ownership to a web worker (avoids the need of copying) and WebGL. Conceptually, the idea of immutability and the idea of typed arrays are orthogonal, and in certain use cases, you can't not use typed arrays.

**Comment by leebyron** [comment]
Closing this aging issue
