### ISSUE TITLE
Firefox mobile rendering issue with homepage

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#176]
VesaVesQ: @reactjs Kind of buggy header on Firefox Mobile (android) http://t.co/BU8ALznb1r

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by Pointy** [comment]
Not just Firefox Mobile - desktop Firefox (44.0, now that it's 2016) looks exactly the same.

**Comment by leebyron** [comment]
Thanks for the additional report! I'll look into what's going on for FF
