### ISSUE TITLE
Decouple data structures to allow for including subset of API for byte savings.

### ISSUE THREAD

**Issue by infinity0** [facebook/immutable-js#177]
The entire library is currently 51KB unzipped. It would be nice if it were possible to only build a part of it. For example, asmCrypto accomplishes this via the Gruntfile, which lets you do `grunt --with=$components`.

https://github.com/vibornoff/asmcrypto.js/blob/master/Gruntfile.js

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Closing this aging issue. 

This is still something we would like to get to in the future, but won't be able to make it happen soon.
