### ISSUE TITLE
More insights about hashcode needed

### ISSUE THREAD

**Issue by tOkeshu** [facebook/immutable-js#178]
From #84 I get that we can provide a `hashCode(): int` method in objects we want to put in sets, or simply wherever we need to have a hashable property for this object.

It would be nice however to have this behaviour documented somewhere. For instance, is any integer viable? What are the limits? How does that affect perf, etc?

Moreoever, is it conceivable to have something more "friendly" than 'hashCode(): int`? For instance providing a property of the object itself which is hashable (string, number, etc) and having a generic hash function for these would be nice.

The reason I'm asking this is that I consider putting objects in a Set. To differentiate them from one another I plan to provide a 'sha256'. I'm not sure what would be the best way to do that. The `sha256` is already a hash and converting it to an integer seems to be convoluted to me.

**Comment by copy** [comment]
If you do this, you should also export and document some methods from `Hash.js`, so that they can be used as a helper to hash our own objects.

**Comment by leebyron** [comment]
#506
