### ISSUE TITLE
Pretty print

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/immutable-js#191]
I have a map with lots of nested data structures that I want to pretty print (using tabs for indentation). Is this possible? E.g.

```
Map {
    data: Map {}
}
```

**Comment by leebyron** [comment]
I would love to do this, yes.

**Comment by glenjamin** [comment]
I ran into this recently, and decided to throw together a little pretty-print lib for it

https://github.com/glenjamin/pretty-immutable

**Comment by leebyron** [comment]
Closing this aging issue. (nice work, @glenjamin!)

**Comment by glenjamin** [comment]
Is it worth me sending in a PR to have this behaviour in core?
