### ISSUE TITLE
non-mutative methods (e.g. splice) in withMutations should be documented to not work, or not possible

### ISSUE THREAD

**Issue by brenoferreira** [facebook/immutable-js#196]
I'm not sure if this is a bug, or if I'm doing something wrong. But when I try to `splice` one item into a List inside a `withMutations` block, I'm getting an empty list as a result.
For example:

``` javascript
var list = Immutable.fromJS([1,2,3]);
list.splice(1,0,10).toJS() // List [1, 10, 2, 3]
```

But, if I try to do the same thing, but using `withMutations`, it returns an empty list:

``` javascript
var list = Immutable.fromJS([1,2,3]);
list.withMutations(function(l){
  l.splice(1,0,10);
}).toJS() //List []
```

I've also tried this, but it gives the same result.

``` javascript
var list = Immutable.fromJS([1,2,3]);
list.withMutations(function(s){
  s.updateIn([], function(l){return s.splice(1,0,10); });
}).toJS() //List []
```

**Comment by prewk** [comment]
Am I having the same issue?

````js
var menuItems = Immutable.List.of(
  { parent_id: 0, id: 1 },
  { parent_id: 1, id: 2 },
  { parent_id: 1, id: 2 }
);

var results1 = menuItems
  .filter(function(menuItem) { return menuItem.parent_id === 1; }) // Filter out items with parent_id = 1
  .sort(function(childA, childB) { return childA.sort_order - childB.sort_order; }); // Sort them by sort_order

var results2 = menuItems.withMutations(function(list) {
  list
    .filter(function(menuItem) { return menuItem.parent_id === 1; }) // Filter out items with parent_id = 1
    .sort(function(childA, childB) { return childA.sort_order - childB.sort_order; }); // Sort them by sort_order
});

console.log(results1.size); // 2
console.log(results2.size); // 3
````

I'm not so well-versed in the immutable jargon, so I'm not sure if `sort`/`filter` are mutative.

**Comment by leebyron** [comment]
I'm not quite sure what's going on here, but `set` and `push` are the only safe operations to call within `withMutations`. In a future major version of Immutable, this example code will throw an error to make that more clear.

Also just to make sure you're aware of what's built here - you have an immutable list of mutable objects. For the example that you're illustrating here, it doesn't much matter. But if you ever edit any of those objects you are editing them wherever they are referenced since they're mutable.

**Comment by prewk** [comment]
Thank you for your explanation!

Yeah, I know, they're just mutable for illustrating the problem. I have an issue on stackoverflow with the same question, so I'll squash that with a quote from you, if that's alright. Might help someone.

**Comment by leebyron** [comment]
Link?

**Comment by prewk** [comment]
Never mind, someone just answered my question instead: http://stackoverflow.com/questions/28361512/why-do-i-get-different-results-using-withmutations/28474618#28474618

**Comment by Gozala** [comment]
I've run into same issue, took me a while to figure out what was going on. I think it's ok to not support splice in mutable version, but throwing errors there would be nice. Also how about adding some immutable method that would let user insert / remove items into arbitrary position of the collection ?

**Comment by donabrams** [comment]
I had the same issue described above and definitely not in the withMutations documentation here: http://facebook.github.io/immutable-js/docs/#/OrderedMap/withMutations

```
> var toSort = Immutable.OrderedMap({a:1, b:2, c:5, d:3});
undefined
> toSort.sort().toJS()
Object {a: 1, b: 2, d: 3, c: 5}
> toSort.withMutations(function(unorderedMap) { unorderedMap.sort();}).toJS()
Object {a: 1, b: 2, c: 5, d: 3}
```

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by donabrams** [comment]
It is now documented that only `set()` and `merge()` work within a withMutations block:  http://facebook.github.io/immutable-js/docs/#/OrderedMap/withMutations. It'd be nice if the documentation called out that methods besides `set()` and `merge()`, such as `sort()`, fail silently.

**Comment by gfarrell** [comment]
Could I ask *why* `splice()` is not considered mutative (and thus usable within `withMutations()`)? For example, I am trying to write functions to insert items into a list while maintaining order using a binary search. Inserting one item is fine, and I just use `splice()`, but if I wanted to insert N items at once, it seems inefficient to be creating N - 1 immutable intermediaries.

`Array.prototype.splice` mutates the array, so surely `List.prototype.splice()` should also be considered mutative.

**Comment by geakstr** [comment]
Without specifying the documentation this behavior very confusing 😕

**Comment by xMartin** [comment]
What about `setIn` and the like?

I just wrote some working code that uses `deleteIn` in a `withMutations` scope. Confusing...

Also I think the documentation should state that not supported methods fail silently.

**Comment by thieman** [comment]
@leebyron I'm also struggling to understand if/how deep operations like `setIn` operate inside `withMutations`, could you please clarify?
