### ISSUE TITLE
Similar to the concat case, Stack.of().unshiftAll(some_other_stack) === some_other_stack

### ISSUE THREAD

**Issue by tolmasky** [facebook/immutable-js#213]
So I decided to switch to a stack since I noticed all my operations were adding/removing to the front, and so I'm hoping this same optimization could be moved to the stack objects ( https://github.com/facebook/immutable-js/issues/204 )

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
