### ISSUE TITLE
Explainer of Value Equality

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#216]
document `valueOf`, `equals` and `hashCode`.

**Comment by ivan-kleshnin** [comment]
I've got the root of the problem we had here:
https://github.com/Paqmind/twitto/issues/7#event-237480127

I was reading through ImmutableJS documentation and observing a lot of examples with === so it somehow clicked in my head that it is recommended way to compare objects... I actually knew that JS has no operator overloading but I somehow decided that you've implemented this on some memoization technique that same args would always result in the same `Map` object.

But you were describing quite the opposite – how you optimized memory (as much reuse of the same object as possible). You've described Implementation and I've taken that for API...

I I think it's better to shift accents a bit in documentation or add some comments to make it obvious even for fast-readers.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by UnsungHero97** [comment]
any progress on writing up documentation for `valueOf`, `equals` and `hashCode`?
