### ISSUE TITLE
Record.prototype.filter: confusing behaviour

### ISSUE THREAD

**Issue by andreypopp** [facebook/immutable-js#220]
```
> var Immutable = require('immutable')
undefined
> var R = Immutable.Record({x: null, y: null})
undefined
> var r = new R()
undefined
> r.filter(function(v) { return v !== null; });
undefined
```

Accidentally stumbled upon this, though I understand that `filter` probably doesn't make sense for `Record` at all.

**Comment by grav** [comment]
Or that it returns a type Map?

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jimitndiaye** [comment]
This issue is still occurring in v3.8.1

**Comment by BjornMelgaard** [comment]
Even warnings didnt show in v3.8.1

**Comment by leebyron** [comment]
Merging into #505
