### ISSUE TITLE
Construction of custom immutable types

### ISSUE THREAD

**Issue by tgriesser** [facebook/immutable-js#221]
So I'm experimenting with some things around custom Collections and such, and I was thinking it'd be nice if there were a way to be able to create Maps and Lists of custom "types". Objects which inherit directly from `Map` and `List`, potentially adding new/custom methods while retaining the immutable behavior - that somehow the prototype of the constructor would be used in place of the `ListPrototype` and `MapPrototype` in `makeList` and `makeMap` respectively.

At first glance it seems that this might already be somewhat possible by overriding the `__ensureOwner` on both of these objects, and by specifying a custom `List#set`, but this doesn't account for using the correct constructor/prototype in the `emptyMap` (which is used throughout). 

I guess I wanted to see if this was something you had considered or would be interested in supporting, or if there are any difficulties I haven't considered yet when it comes to deep merging, etc.

**Comment by leebyron** [comment]
Merging into #301.
