### ISSUE TITLE
Consider .length rather than .size on List

### ISSUE THREAD

**Issue by tgriesser** [facebook/immutable-js#225]
While the `size` API definitely makes sense for objects such as `Map`, `Set` as there isn't an explicit order, `size` rather than `length` definitely feels clunky for `List` (and perhaps `Stack`?) - especially when working in situations where the input may either be an Array or list.

Would it make sense to have `size` as the property for Keyed collections and `length` for Indexed collections?

**Comment by astorije** [comment]
@pluma, that's a good point, although I would prefer to avoid it for `size`/`length`.
For value equality, right now I am using an awkward:
```js
expect(Immutable.is(list1, list2)).to.be.true;
```

In that case I agree a custom matcher makes sense.

@leebyron, this probably deserves its own issue, but do you think we could have a set of matchers for Chai? Maybe in the `contrib` folder or another third-party intended folder? That could help those who use Immutable and Chai and want to have nice looking tests.
If you agree with this I can work on it.

**Comment by leebyron** [comment]
Sure, go nuts. You might want to start with the ones I've already written for Jasmine.

https://github.com/facebook/immutable-js/blob/master/__tests__/Conversion.ts#L24

**Comment by leebyron** [comment]
The day we can reasonably do array-like bracket access (ex. `myList[2]` instead of `myList.get(2)`) then I think we should support `length`. Otherwise, I fear that Immutable.js Lists would suffer from incompatibility with code that expects a non-zero length to imply that bracket access will work, which I think will be surprising in the worst way. Some minor awkwardness to avoid that pitfall is probably the right thing to do IMHO.

**Comment by tgriesser** [comment]
> Otherwise, I fear that Immutable.js Lists would suffer from incompatibility with code that expects a non-zero length to imply that bracket access will work, which I think will be surprising in the worst way

Yep, agreed :+1:

**Comment by JemarJones** [comment]
Just to note, due to type coercion when someone uses an immutable List and expects it to work like vanilla js they can pretty easily end up with the following bug:

```
if (myList.length > 0) {
  // I'm going to handle the empty list situation, but my list isn't actually empty!
}
```

Wouldn't it be wise to at the very least log a warning when someone tries to access length on a `List`?

**Comment by leebyron** [comment]
There used to be a warning during the transition away from using it - but even that warning resulted in issues with integration in other codebases that sniff for types, such as the dev tool console.

If you're looking to avoid accidental usage issues, I strongly recommend using Flow or TypeScript
