### ISSUE TITLE
updateIn doesn't update a record when given a notSetValue?

### ISSUE THREAD

**Issue by fson** [facebook/immutable-js#226]
I have a nested structure like this:

``` js
var Immutable = require('immutable');
var Record = Immutable.Record;
var Map = Immutable.Map;

var State = Record({
  records: Map()
});
var Item = Record({
  name: null
});
var state = new State();
var notSetValue = new Item({name: 'foo'});
```

I try to set the name of the item at the key `records.foo` to "foo". If the key does not exist, it's first initialized to `notSetValue`. Looks like `updateIn` doesn't update the state record, if the return value of `updater` fn would be equal to `notSetValue`?

``` js
state.updateIn(['records', 'foo'], notSetValue,
               function (value) { return value.set('name', 'foo'); });
// => Record { newRecord: null, records: Map {} }
//                                            ^ no 'foo' here!
```

If I use a different `name` so it's not equal to `notSetValue`, it works correctly, however:

``` js
state.updateIn(['records', 'foo'], notSetValue,
               function (value) { return value.set('name', 'foobar'); });
// => Record { newRecord: null, records: Map { foo: Record { name: "foobar" } } }
```

I'd like to know if this is a bug in `updateIn` or if I'm using it wrong. It seems like an unexpected behavior.

EDIT: fixed `defaultItem` -> `notSetValue` in the example.

**Comment by AsaAyers** [comment]
In the example above it seems like `notSetValue` and `defaultItem` are the same thing. by changing `notSetValue` to `defaultItem` I can reproduce this behavior.

**Comment by AsaAyers** [comment]
https://github.com/facebook/immutable-js/blob/master/src/Map.js#L752-L754
```
    var existingValue = isNotSet ? notSetValue : existing;
    var newValue = updater(existingValue);
    return newValue === existingValue ? existing : newValue;
```

I believe the bug is here. `existingValue` is actually the `notSetValue`, but when comparing the new value to the old value it finds them to be the same, so it returns `existing`. I don't understand why this wouldn't just always return `newValue`. If they're `===` it seems safe to return.

**Comment by leebyron** [comment]
Sorry for the delay in answering here.

I'm not sure what the value of `defaultItem` is, but if it causes the updating function to behave as an identity function, then no update will occur by design.

Since this task was opened, I've updated the documentation of `updateIn` to hopefully explain this behavior a bit more clearly.

**Comment by AsaAyers** [comment]
I see it in the [docs](http://facebook.github.io/immutable-js/docs/#/Map/updateIn) now. This seems like a strange behavior to me.  ¯\\_(ツ)_/¯

> If the updater function returns the same value it was called with, then no change will occur. This is still true if notSetValue is provided.

**Comment by voltprime** [comment]
Mind also updating the docs for `Map.update`. It currently says
> Equivalent to: map.set(key, updater(map.get(key, notSetValue))).

Which is misleading for the same reason as `updateIn` was:
```javascript
var map = Immutable.Map();
map.update('x', 1, function(x) { return x; }) !== map.set('x', map.get('x', 1))
```

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by NickLydon** [comment]
I've just come across this as well. Quite surprising, especially as @voltprime mentions the documentation says that it's equivalent to **map.set.**

**Comment by leebyron** [comment]
Updated the documentation recently to suggest using modern function param default values instead of notSetValue - it helps avoid this API corner case.
