### ISSUE TITLE
.remove() mutations on list returns empty immutable 

### ISSUE THREAD

**Issue by varunarora** [facebook/immutable-js#228]
Just like in the example on the doc about .withMutations(), the immutable returned that end of the multiple .push() mutations on the list works great. However, .remove() mutations diminish the mutable copy inside the function down to an empty immutable object, and not a mutable copy after being mutated.

Do you know why this might be happening?

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by carlsverre** [comment]
@leebyron Why does `delete(2)` result in all the elements being removed while `delete(0)` works as expected?  (see code example above)

**Comment by callin2** [comment]
I have same issue.  List.delete() work only on first and last index. inside withMutation().
