### ISSUE TITLE
Map/filter looses the underlying collection type

### ISSUE THREAD

**Issue by Tvaroh** [facebook/immutable-js#23]
Example:

``` javascript
var v = Immutable.Vector(1, 2, 3)
v.toString() // "Vector [ 1, 2, 3 ]"
var v2 = v.map(function (x) { return x + 1; })
v2.toString() // "Seq [ 2, 3, 4 ]"
v2.delete(0) // TypeError: undefined is not a function
```

So, one must issue `toVector()` after the transformation to get original structure type back. This is very inconvenient for a library user.

I understand this is due to laziness so possible options may be:
- provide strict versions of `map/filter/etc`;
- somehow preserve set of methods and observable behavior of the original data structure;
- provide single method replacing `toVector/toMap/etc` and allowing to get original data structure after transformation back, e.g. `force()`;
- ...

**Comment by hleumas** [comment]
@leebyron why do you like eager behavior more than lazy? I mean, many  languages out there behave lazy: Python, Dart, Clojure.

**Comment by leebyron** [comment]
I like lazy behavior, and have built this library to take advantage of it. Seq is included as the primary tool for doing so.

The reason operations were changed from lazy to eager in v3 is that it was the biggest source of confusion for newcomers to the language. Lots of old github issues are about confusion as to why the operations were not maintaining the type they started with.

**Comment by hleumas** [comment]
I see.
