### ISSUE TITLE
contrib/cursor: Expose cursor types for type checking purposes

### ISSUE THREAD

**Issue by lukasbuenger** [facebook/immutable-js#231]
While it is certainly obvious why it isn't necessary or even inconvenient to have the innards of contrib/cursor exposed to the client, it would be nice to have at least the basic cursor types available for evaluation.  

React scenario:
Imagine a global state represented by *Immutable* data structures that gets passed to a set of nested components using cursors. For testing purposes it would be helpful to define the property that represents the cursor on the component as explicitly as possible:

```
var React = require('react'), 
     Cursor = require('immutable/contrib/cursor');

var MyComponent = React.createClass({
    propTypes: {
        cursor: React.PropTypes.instanceOf(Cursor.KeyedCursor).isRequired
    }
    // ... component definitions.
});
```

What y'all think on that? 
Regards, Lukas

**Comment by RileyTomasek** [comment]
As a note for other people who end up here, this is the updated link to React's own PropTypes: https://github.com/facebook/react/blob/master/src/classic/types/ReactPropTypes.js

**Comment by leebyron** [comment]
Tracking this in #509

**Comment by lukasbuenger** [comment]
@leebyron 
Thanks for keeping this alive. I have to admit that I'm much more familiar with ImmutableJS and the whole [tl;dr](https://en.wikipedia.org/wiki/Immutable_object) behind persistent data structures in general than I was like 7 months ago (me coming from ActionScript  à la 98 and all :dancers:). It just took me some time to digest the approach and apply it on a safe, small scale daily basis.
From my today's point of view, your [answer](https://github.com/facebook/immutable-js/issues/231#issuecomment-66509771) to my original question was 200% legit and right.
But IMHO it still would make sense to expose the complete contrib/cursor API to the public domain. Let's face it, people who even appreciate the possibility of having cursors on immutables are probably somehow involved with at least designing some kind of low level state. I think it is safe to assume that most of these people have a technical background and can handle this additional responsibility of having everything accessible for extending. I had my own go at it and [this is what JS devs have been using] at my company for the last couple of months. What do you think?
