### ISSUE TITLE
Support "JSON pointer" in Cursor.from and cursor.get

### ISSUE THREAD

**Issue by aaronshaf** [facebook/immutable-js#237]
Instead of (or in addition to):

``` javascript
var cursor = Cursor.from(data, ['a', 'b'], newData => {
  data = newData;
});
```

Support:

``` javascript
var cursor = Cursor.from(data, '/a/b', newData => {
  data = newData;
});
```

See http://tools.ietf.org/html/rfc6901 and https://github.com/manuelstofer/json-pointer as an example.

**Comment by gajus** [comment]
What about using https://www.npmjs.com/package/lodash.topath (https://lodash.com/docs#toPath)?

It is a tiny dependency and could be used to convert string value to an array path. This convention is already broadly used within lodash, e.g. https://lodash.com/docs#get

**Comment by leebyron** [comment]
This isn't a question of which dependency to take, but rather that this library seeks to remain dependency-less. 

Also, performance is a primary concern, and in past performance tests we found this parsing step to be a serious perf regression on getting values. 

If it's important to you to use a path notation, then more power to you, it's easy to compose functions together to do just that, but I don't think it's the right trade-off to introduce a performance regression for those who don't need this feature
