### ISSUE TITLE
Expose rootData and/or keyPath of a Cursor

### ISSUE THREAD

**Issue by Dashed** [facebook/immutable-js#242]
I usually find it useful to know the origin path for a cursor via `this._keyPath`. I usually don't want to keep track of both of them external to the cursor. 

I know they're meant to be private: https://github.com/facebook/immutable-js/blob/52db807330bb7786fbe20156aca80fbae47491c5/contrib/cursor/index.js#L43-L44

Can `rootData` and/or `keyPath` be officially public?

**Comment by jeffbski** [comment]
+1

I think that this is very important to provide access to the keyPath, it enables a variety of great uses.

One use case is so that you can serialize the keyPath and updateValue in one piece of code, transmit it to another (possibly on the server), then apply the changes there. Full stack flux could use this approach.

```javascript
var structure = Immutable.fromJS({ a: { b: { c: 'hello' } } });
// somewhere deep in your code, you have a cursor that was passed down to you, maybe through
// subcursors, etc.
// var cursor = ...;  // _keyPath = ['a', 'b', 'c']
// I want to communicate to the server via web socket or ajax that data at cursor keyPath needs to be updated
socket.send({ update: { keyPath: cursor.keyPath, data: 'world' }});

// serialized keyPath and sent to server

// server validates and applies update to db or its own immutable structures and sends update to client
// validate and update server db at keyPath with data
// after all stores have updated, send notification with changed data to client

// client receives the update and applies to local structure
socket.on('update', (obj) => {
  var cursor = Cursor.from(structure, obj.keyPath);
  cursor.update(x => obj.data)
});
```

In the above use case, we did not want to update our local structure directly since we wanted it to be done in a central location after validation, then only if validation succeeds, server would indicate to client to update local cache and views.

**Comment by dariocravero** [comment]
If I didn't get this wrong, another use case could be in traversing a tree-like structure. So through the cursor you could access the parent, siblings, etc. I was actually wondering as to why cursors weren't exposing that kind of functionality and until I found this issue I thought maybe I was trying to misuse them?

**Comment by wmertens** [comment]
I'm working on an app where I need to edit parts of a document and using a cursor for the document part makes for a nicely modular approach.

So two use cases while traversing a tree:
- You may want to render a part of the tree differently depending on the path taken
- You may want to query location-specific calculated document metadata

In the first case you either have to pass the path along with the cursor or move the rendering decisions to the document viewer and have it pass flags to the editor. Neither option seems nice.

In the second case it would cool if the metadata were calculated by the document object itself, which means subclassing Map and proxying the methods via the cursor. Is that feasible?

**Comment by neftaly** [comment]
+1

Hey! I'm recursively rendering a tree in React, and need each element to provide a unique ID.

```js
let tree = [
    [
        [
            [],
            [], // <a href="app.html#0.0.1">tree[0][0][1]</a>
            [
                []
            ]
        ]
    ],
    [
        [],
        []
    ]
];

...

let Node = React.createClass({
    render: function () {

        let cursor = this.props.cursor;

        // Code to end at leaf nodes goes here

        return <div id={cursor._keyPath.join(".")}>
            { cursor.toArray().map((child) => {
                return <Node cursor={child} />;
            }) }
        </div>;

    }
});
```

`_keyPath` works great, and doesn't require baked-in UUID's for each node, or a partial path that gets built & passed down as a prop.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
