### ISSUE TITLE
Cursor.set(value: any): Cursor

### ISSUE THREAD

**Issue by Dashed** [facebook/immutable-js#249]
Can we have a way to set current value of cursor?

```js
Cursor.set(value: any): Cursor
```

It's similar to `update(updater: (value: any) => any): Cursor`, but with being able to set `undefined`.

**Comment by confiks** [comment]
I would like to be able to do this as well. Makes it easy to alter values stashed away in nested structures when passing cursors as props through React.

**Comment by geirsagberg** [comment]
+1, this would be really handy. Shouldn't need a full update method call when I don't care about the current value of the cursor.

**Comment by geirsagberg** [comment]
Added PR #516. 

On another note, would it make sense to have a matching cursor.get()-method? It would basically be an alias for deref(). I have the code, can add it to the PR if you want.
