### ISSUE TITLE
Altering the state with more than one cursor?

### ISSUE THREAD

**Issue by cristiingineru** [facebook/immutable-js#255]
Is there a way to change the state in a consistent way while using more than one cursor?

Let's suppose we have 2 points and we want to vertically align both of them. The initial state is represented like this:

  var state = Immutable.fromJS(
    {points: [{x: 3, y: 0}, {x: 7, y: 0}]}
  );

Reading the x coordinates from both of them using 2 cursors is simple:

  var points = Cursor.from(state, 'points', function(newState) {
    state = newState;
  });
  
  var p1 = points.cursor(0);
  var p2 = points.cursor(1);

  var newX = (p1.get('x') + p2.get('x')) / 2; // newX -> 5

But updating both objects leaves us an inconsistent state:

  p1 = p1.set('x', newX); //state: "Map { points: List [ Map { x: 5, y: 0 }, Map { x: 7, y: 0 } ] }"
  p2 = p2.set('x', newX); //state: "Map { points: List [ Map { x: 3, y: 0 }, Map { x: 5, y: 0 } ] }"

This example is trivial and there are some workarounds for this particular case. But things get ugly with a deeper state and complex operations.

What am I missing? Is there a way to 'synchronize' the cursors?

Thanks!

**Comment by cristiingineru** [comment]
Based on your advice I've created some helper functions that help me dig into a deep hierarchy, make some changes and update all the required parents. They can be used like this:

```js
state = dissect(state,
  select('diagram',
    select('components',
      select('legs', function (leg) {
        if (/* this is the object I'm looking for */) {
          // then do some things here
        }
        return leg;
      })
    )
  )
);
```

The ``` select ``` function is looking to the data type of the current container and if it's a collection then it will call the inner function for each value.

Do you know if there is already support in the immutable library to perform operations like this?

**Comment by cristiingineru** [comment]
This is a silly implementation of the helper functions mentioned in the previous comment:

```js
  dissect = function (root, fn) {
    if (Immutable.List.isList(root) || Immutable.Seq.isSeq(root) || Immutable.Map.isMap(root)) {
      return fn(root);
    }
    return fn(root.state();
  };

  select = function (key, fn) {
    return function (parent) {
      var value = parent.get(key);
      if (value !== undefined) {
        if (Immutable.List.isList(value) || Immutable.Seq.isSeq(value)) {
          value = value.map(fn);
        } else {
          value = fn(value);
        }
        return parent.set(key, value);
      }
      return parent;
    };
  };

  filter = function (key, fn) {
    return function (parent) {
      var value = parent.get(key);
      value = value.filter(fn);
      return parent.set(key, value);
    };
  };
```

**Comment by leebyron** [comment]
You should see if setIn and updateIn will do what you're trying to do.

**Comment by leebyron** [comment]
I'm not sure I understand the purpose of `dissect`, but most uses of `select` can be done via `updateIn` and `map`. 

For your example:

```js
// 1. get the current diagram to operate on as a cursor
var diagramCursor = getTheDiagramToOperateOn(state);

// 2. operate 'under' the cursor
diagramCursor = dissect(diagramCursor,
  select('components',
    select('legs', function (leg) {
      if (/* this is the object I'm looking for */) {
        // then do some things here
      }
      return leg;
    })
  )
);
```

might instead be written as:

```js
// 1. get the current diagram to operate on as a cursor
var diagramCursor = getTheDiagramToOperateOn(state);

// 2. operate 'under' the cursor
diagramCursor = diagramCursor.updateIn(['components', 'legs'], legs => legs.map(leg => {
  if (/* this is the object I'm looking for */) {
    // then do some things here
  }
  return leg;
}));
```

does that work for you?

**Comment by cristiingineru** [comment]
Sorry for not mentioning the purpose of the ```dissect``` and ```select``` functions.
The project I'm working on is in the experimental phase and I needed a way to fast prototype and mitigate the risks of dealing with bugs.

Maybe at some point the underlying implementation will be changed to perform faster or even dropped and replace the initial calls with the ```updateIn``` and ```map``` functions. But at this point the beauty is preferred over performance :)

In the previous example the legs and components are both lists and the ```updateIn``` needs an exact path and it doesn't iterate over an array. So the ```updateIn``` usages need to be alternated with ```map``` calls something like this:

```js
// 2. operate 'under' the cursor
diagramCursor = diagramCursor.updateIn(['diagram', 'components'], function (components) {
  return components.map(function (component) {
    return component.updateIn(['legs'], function (legs) {
      return legs.map(function (leg) { /* ... */ });
    });
  };
});
```

The usages of the ```updateIn``` and ```map``` are also compact and probably fast but they are just a little bit more difficult to be maintained (but it's just a matter of taste). And they were a nice exercise to help me learn how to change the state when 1 cursor is not enough.

**Comment by leebyron** [comment]
Closing this since it's aged
