### ISSUE TITLE
Safe mutability test

### ISSUE THREAD

**Issue by iwehrman** [facebook/immutable-js#257]
I'm writing a small bit of infrastructure to cache values derived from keys of `Immutable.Record` objects, which for invalidation relies on the fact that mutation results in a distinct object. These cached values are actually getters on the prototype of objects that inherit from `Immutable.Record`, so they're accessed just like non-derived properties. I'd like to ensure, though, that the cached values aren't accidentally updated while mutating such an object using `withMutations`. In order to do this, I need a reliable way to determine whether the object is either currently mutable, or has been somehow altered. Currently, I'm doing this with the `wasAltered`, which works fine for my purposes, but I noticed that it isn't officially documented anywhere. Could this become part of the official API? Or, alternatively, could something like `isMutable` be added to `Immutable.Record` objects?

**Comment by leebyron** [comment]
Closing this since it's aging, but caching utilities is still an open area of discussion
