### ISSUE TITLE
Recursive values?

### ISSUE THREAD

**Issue by tolmasky** [facebook/immutable-js#259]
I've been going through and trying to replace my mutable structures with immutable ones, the thing I've run into though is recursive structures. As a simple example:

```javascript
x = { }
x.x = x;
```

How would I do something similar with I.Map? x.set("a", x) doesn't work because it stores the old one. (I'm converting a JS value, and as such fromJS doesn't work, but I can handle the conversion myself as long as I can figure out some way of getting a self reference to begin with)

**Comment by tolmasky** [comment]
So, interestingly enough, I was able to accomplish this using withMutations: https://gist.github.com/tolmasky/8a91af5ac1e0a949b423

Now the only issue is that toString borks and toJS bork (these are much easier to fix). Would you be opposed to having an implementation of toString and toJS that account for circular references (just like log you'd see something like Map { a: [Circular] }). I'm happy to just have them in my code of course, but given that this is "possible", I figured you might want it in mainline as well.

**Comment by tolmasky** [comment]
I've filed this related issue which deals with the same reference in objects (not necessarily circular): #305

**Comment by leebyron** [comment]
Circular references break a lot of promises that immutable data provides, so I don't think I plan on accounting for them. 

You can read a more lengthy explanation of the issues with circular references via manual mutation written up in the "transients" section of the clojure documentation.

**Comment by leebyron** [comment]
Closing this for now - I think this is going to be really hard to do without language features.
