### ISSUE TITLE
Is it possible to obtain an iterator from  a Seq?

### ISSUE THREAD

**Issue by ken-okabe** [facebook/immutable-js#262]
Related Closed (solved) Issue:
https://github.com/facebook/immutable-js/issues/254

For instance, when we have a code like below:

``` js
var _ = require('lodash');
var __ = require('immutable');

var __natural = __.Range(); //infinite natural numbers sequence 
var fibF = _.memoize(function(n) {
  return n <= 1 ? 1 : fibF(n - 2) + fibF(n - 1); //as the math definition of fibonacci
});
var __fib = __natural.map(fibF);
```

Is it possible to obtain an iterator from  sequences like `__natural` or `__fib`?
such as to obtain a value like `a = it.next();` with a certain event in a gradual manner?

Regards.

**Comment by kenokabe** [comment]
I post some other question,
https://github.com/facebook/immutable-js/issues/272

and coincidently, I had an answer

pluma commented 6 hours ago
>You can get an iterator using Range().values().

So I tried.
```
var _ = require('lodash');
var __ = require('immutable');

var __natural = __.Range();
//infinite natural numbers sequence

var __narural10 = __natural.take(10);
//the first 10 sequence (still no calculation)

console.log(__narural10.toArray());//calculate and output

var fibF = _.memoize(function(n) {
  return n <= 1 ? 1 : fibF(n - 2) + fibF(n - 1);
  //as the math definition of fibonacci
});

var __fib = __natural.map(fibF);
//infinite Fibonacci sequence

var __fib100 = __fib.take(100);
//the first 100 sequence (still no calculation)

console.log(__fib100.toArray()); //calculate and output

var it = __fib.values();

console.log(it.next());  //{ value: 1, done: false }
console.log(it.next());  //{ value: 1, done: false }
console.log(it.next());  //{ value: 2, done: false }
console.log(it.next());  //{ value: 3, done: false }
console.log(it.next());  //{ value: 5, done: false }
```

Very cool.

Perhaps, does `.values()` implemented recently?

**Comment by leebyron** [comment]
`values()`, `keys()` and `entries()` exist on all Immutable.js collections, mirroring the same methods on ES6 Map and Set.

However, this is not the same as the "default iterator" function (equivalent to `values()` for indexed collections and Sets, but equivalent to `entries()` for Maps).

These functions also are specific to collections and won't be found on any generic iterable where the `getIterator` function I provided above will always use the default iterator and will work for any generic iterable, not just those found in this library.

**Comment by kenokabe** [comment]
@leebyron 
I see!
Thanks you. Very informative to study.
