### ISSUE TITLE
Infinite loop possible? 

### ISSUE THREAD

**Issue by kenokabe** [facebook/immutable-js#272]
```
var Immutable = require('immutable');
var i = Immutable
  .Range()
  .take(10000)
  .toArray()
  .map(function(x)
  {
    console.log(x);
  });
```

This works to console.log from 0-9999.

```
var i = Immutable
  .Range()
  //.take(10000)
  .toArray()
  .map(function(x)
  {
    console.log(x);
  });
````
This obviously does not work.
>Error: Cannot perform this action with an infinite size.

```
var i = Immutable
  .Range()
  //.take(10000)
  //.toArray()
  .map(function(x)
  {
    console.log(x);
  });
```
This does nothing. Perfectly makes sense.

Everything looks good, and very cool.

However, in some cases, we want to do

```
while(true)
{
   // do something
}
```

and I wonder what kind of method is appropriate to make a thing work like the above in `immutable.js` context.

Using some iterator?

Thanks!
Regards.

**Comment by pluma** [comment]
You can get an iterator using `Range().values()`.

**Comment by leebyron** [comment]
```js
var iterator = myCollectionOrRange.values();
var step = iterator.next();
while (step.done !== true) {
  // do something with step.value
  step = iterator.next();
}
```

**Comment by kenokabe** [comment]
@leebyron 
Thanks for the code! Really appreciated.

Regards.

**Comment by kenokabe** [comment]
@pluma
Thanks! 

Regards.
