### ISSUE TITLE
Map constructor accepts arrays of 2-tuples, but not Immutable equivalent.

### ISSUE THREAD

**Issue by davidmccabe** [facebook/immutable-js#274]
I found this surprising:

    > Immutable.Map([[1,2]])
    Map { 1: 2 }
    > Immutable.Map(Immutable.fromJS([[1,2]]))
    Map { undefined: undefined }

It particular, it's the inside tuples that it needs to be plain arrays:

    > list
    List [ List [ 1, 2 ], List [ 3, 4 ] ]
    > Immutable.Map(list.map(x => x.toArray()))
    Map { 1: 2, 3: 4 }
    > Immutable.Map(list.toArray())
    Map { undefined: undefined }

A bug, or a misunderstanding on my part? What is the preferred way to form a map from an immutable list of 2-tuples? Thanks!

**Comment by leebyron** [comment]
This is a current limitation of the library. Lists aren't consumed as tuples. I agree with you that this should be possible though, so I'll leave this task open until I can investigate.

**Comment by ransanjeev** [comment]
:thumbsup:

**Comment by leebyron** [comment]
This was fixed in the [v3.7.0](https://github.com/facebook/immutable-js/releases/tag/3.7.0) release
