### ISSUE TITLE
API request: empty(seq)

### ISSUE THREAD

**Issue by chenglou** [facebook/immutable-js#275]
`count(infiniteSeq)` obviously doesn't work and I'm not sure how else to check whether it's empty currently. `rest()` keeps returning a valid obj rather than `null` (which I think is right, clojure does this too) but I can't use it to assert emptiness.

**Comment by pluma** [comment]
What about `seq.size`?

**Comment by leebyron** [comment]
Good suggestion @chenglou I'll include this in the next release.

**Comment by chenglou** [comment]
@pluma same as count. Also might not exist until you do `count()` for lazy seqs.

**Comment by chenglou** [comment]
Ah `some`... Right
