### ISSUE TITLE
Event sequences

### ISSUE THREAD

**Issue by kenokabe** [facebook/immutable-js#278]
I wonder how to take advantage of this great library for Event sequences in FRP context.

facebook-react is a great FRP library for UI. That is good.

In addition, I wonder how to take advantage of functional programming aspect, such as map, filter, merge, time-line sequences, that is, Event sequences.

Thanks. Regards.

**Comment by kenokabe** [comment]
Thanks @leebyron 

Actually, yes.

I know RxJS and bacon.js but never liked it.

FRP is simply about sequence not in memory, but in time-line.  

Actually, another lazy evaluation stream library:lazy.js
http://danieltao.com/lazy.js/
implemented and try to integrate the pradigm.

Event sequences
 
```js
// First we define our "sequence" of events.
var mouseEvents = Lazy(sourceElement).on("mousemove");

// Map the Event objects to their coordinates, relative to the element.
var coordinates = mouseEvents.map(function(e) {
  var elementRect = sourceElement.getBoundingClientRect();
  return [
    Math.floor(e.clientX - elementRect.left),
    Math.floor(e.clientY - elementRect.top)
  ];
});
```

I am not sure this way for implementation is the best.

In fact, there's some other approach.

http://falsandtru.github.io/lazychain/

Although I am not big fun of this lazychain, since this uses jQuery, I think this approach is great.

Here's the idea (Google Translate to Jp to En)
https://translate.google.co.jp/translate?sl=ja&tl=en&js=y&prev=_t&hl=ja&ie=UTF-8&u=http%3A%2F%2Ffalsandtru.github.io%2Flazychain%2Fspec%2F&edit-text=&act=url

My own translation for the important point:

>As the default feature, the available feature is merely a little original method and JavaScript Array built-in method, however, this library can be extend by using any other external functional library, such as Undersocre.js or Lo-Dash.

>Since for functional operation, you can take advantage of your familiar methods in those external existing libraries, you can minimize your learning-cost to take advantage of this library.
 
>This library is not a reproduction of an FRP environment, but a transducer or wrapper by adding function to operate sequence in async way, and messaging feature.

I am not using this lazychain library, but the idea to prepare a transducer or wrapper for the existing library such as Undersocre.js or Lo-Dash sounds great.

So, I wonder if it's possible to apply this approach to Immutable.js, this library can use sequence in lazy way already. 

Thanks.

**Comment by leebyron** [comment]
Unfortunately this is a different kind of lazy - asynchronousity. As you pointed out event sequences are lazy in that their values are spread out over time instead of being spread out in computation or memory. Supporting this use case would basically require re-writing all of the higher-order functions like map/filter/reduce to be asynchronous and work on a subscription rather than a computation.

Other than the names of the methods, I'm failing to see the similarity to the Immutable.js library.

For example - if you could produce a `Seq` from an event stream, what would it mean to call `toArray()` on it?

**Comment by kenokabe** [comment]
Thanks.

I would call `compute()` :)
and I actually did that, since I have implemented a conceptual lazy evaluation and FRP library myself; those code is fundamentally opposite, pull and push, in mathematical way. So I agree with you.
https://github.com/kenokabe/spacetimeline

Now, I consider what is the best way to integrate lazy and FRP not re-inventing wheel.

**Comment by leebyron** [comment]
It's usually helpful for me to start with a use case I want to enable to help articulate how the APIs should coincide. I'm not seeing one yet here.

**Comment by kenokabe** [comment]
I understand.

All I know so far is, since event sequences are lazy in that their values are spread out over time instead of being spread out in computation or memory, mathematically, in foundation, in ideal manner, Immutable.js can be somehow connected to FRP seamlessly, or with little gap, other than facebook-react.

One approach is to try to extend the current Immutable.js method, like lazy.js did that.
Another approach is to try to wrap this Immutable.js with another library like lazy-chain.

That is what I am thinking, and wonder how other people think.
I am happy you responded.

Thanks.

**Comment by leebyron** [comment]
I would be curious to see a wrapped version first. Immutable exposes a lot so that it may be extended directly. If you built something like lazy-chain for Immutable that would be a great start to illustrate the usefulness of this.

**Comment by kenokabe** [comment]
Agreed.
I also think the wrapping approach is smarter.
Probably I will start to study this aspect that can apply to Immutable.js.

Thanks for your thought @leebyron

**Comment by leebyron** [comment]
I'm looking forward to seeing what you build

**Comment by kenokabe** [comment]
Right, since I hold another project, (like writing functional programming book to publish :)  ), I wonder how much time I can spend, but this looks very important task. 
I might ask question for you about this `Immutable exposes` or other area later. Thanks again.
