### ISSUE TITLE
Consider versions of get/delete/set methods that throw

### ISSUE THREAD

**Issue by dmnd** [facebook/immutable-js#279]
From #264:

> it's also unclear if the correct behavior is to throw or return the unchanged list.

Both of these behaviours are useful in different situations. 

I've encountered this issue in other places in Immutable too, most frequently with `get`. For example, maybe I want to get a value from a map, but throw if it's not present.

Python's dict has a reasonable solution for this, at least for similar case of lookup: `map[key]` and `map.get(key, default)`. As a reader, if you see square brackets, you know the author is asserting the presence of the key. If instead you see `get(key, None)`, you know that the key not being present is an expected outcome.

If I were to apply this to Immutable's API, I'd probably make `get(key)` throw and force people to use `get(key, null)` when they expect the key might not be present. I'm not sure if this kind of breaking change would be appropriate now, but I wonder if you think this kind of "non-nullable" / "presence-asserting" lookup method is useful.

The same idea applies to deleting by key or value and even `set` or `add` (e.g. set/add when key/value is currently unoccupied, throw if new value will unexpectedly overwrite).

I often use helper functions and `update` to make these assertions, but it would be nice if the API had this baked in.

**Comment by leebyron** [comment]
Interesting!

This has come up once before and I ended up not following this path because using `has()` made things reasonable.

I imagine I will figure out the appropriate API once using more of Flow, as it cares a lot about nullability and having get() always return nullable is probably going to be pretty annoying.

**Comment by dmnd** [comment]
Ah, good point about flow. I haven't started using that yet but I imagine it will also push in the direction of non-nullability.

Thanks for considering this! Please close this issue unless keeping it open will be helpful to you.

**Comment by dmnd** [comment]
Somewhat related: https://twitter.com/garybernhardt/status/555503657215488000

**Comment by dmnd** [comment]
Also related: I starting using this quick implementation of [fetch and fetchIn](https://github.com/dmnd/immutable-sharp/blob/master/index.js) and uncovered 3 bugs in my code

**Comment by leebyron** [comment]
I suggest a utility function for this. I don't think it's the right call to expand the API surface area for this case - especially since many are concerned about byte size of the library.
