### ISSUE TITLE
Provide Map.setIn()

### ISSUE THREAD

**Issue by JannesMeyer** [facebook/immutable-js#28]
What is the preferred way to set a nested value? I see that there is `updateIn()`, which kind of does what I want, but it has two problems:
- It doesn't set new keys, it can only update already existing keys.
- It uses an extraneous function for updating. The value I want to set is independent from the original value (undefined), so I don't need any function to determine the new value.

How would you add a new key 'd' with a single line? What's the API for this?

``` js
var mutableObject = {
  test: { test2: { a:1, b:2, c:3 } }
};
var immutableObject = Immutable.fromJS(mutableObject);

// desired mutation:
// {
//   test: { test2: { a:1, b:2, c:3, d:4 } }
// );

// with mutable objects it's very simple:
mutableObject.test.test2.d = 4;

// with immutable objects it doesn't seem to be possible:
immutableObject = immutableObject.setIn(['test', 'test2', 'd'], 4); // TypeError
```

**Comment by ev1stensberg** [comment]
@leebyron do we still need to use `newMap = oldMap.updateIn(['test1', 'test2'], x => x.set('d', 4));` to add a prop to the object or how do you do this in a "cleaner" way?

**Comment by leebyron** [comment]
Nope, after this diff landed, you can now write:

oldMap.setIn(['test1', 'test2', 'd'], 4);
