### ISSUE TITLE
This library does no such thing

### ISSUE THREAD

**Issue by Fresheyeball** [facebook/immutable-js#280]
The library is called `immutable-js` but its examples all show mutations:

```javascript
    var map = Immutable.Map({a:1, b:2, c:3});
    map = map.set('b', 20); // mutation
    map.get('b'); // 20
```

This makes no sense.

**Comment by leebyron** [comment]
This library implements persistent immutable data structures. You can read about this concept here: http://en.wikipedia.org/wiki/Persistent_data_structure

The core idea is that the immutable collections have a mutative API so they can be made useful in an environment where data needs to change over time, however each mutative call always returns the result as a new object - leaving the original object unchanged.

The key thing happening in the example in your comment is `map = map.set(...)`. Here, `map.set(...)` is returning a *new object* and that new object is getting assigned to the variable `map`.

Here's an example that might better illustrate this core idea:

```js
var map1 = Immutable.Map({a:1, b:2, c:3});
var map2 = map1.set('b', 20);
map1.get('b'); // 2
map2.get('b'); // 20
```

Does that help explain what's going on?

I'm also curious how I could help improve the README if you were confused as to the purpose or operation of the library on first read.

**Comment by Fresheyeball** [comment]
Yes that is much more helpful. This line of code really confusing things:

```javascript
    var map = Immutable.Map({a:1, b:2, c:3});
    map = map.set('b', 20); // this line here
    map.get('b'); // 20
```

Please consider changing the example to:

```javascript
    var map = Immutable.Map({a:1, b:2, c:3});
    map1 = map.set('b', 20); 
    map1.get('b'); // 20
```

**Comment by leebyron** [comment]
Also just updated http://facebook.github.io/immutable-js/ with the same changes.

Thanks again for bringing up this confusing example!

**Comment by Fresheyeball** [comment]
In retrospect, you could go even harder on this by using the new `const` keyword:

```javascript
const map1 = Immutable.Map({a:1, b:2, c:3});
const map2 = map1.set('b', 20);
map1.get('b'); // 2
map2.get('b'); // 20
```
