### ISSUE TITLE
Performances fading

### ISSUE THREAD

**Issue by baskerville** [facebook/immutable-js#281]
I'm logging the execution time of a function that receives a *Cursor* and apply modifications to it via `withMutations`.
Here's the values in milliseconds (executions are triggered by moving a range input):
```
2
1
0
1
1
1
1
1
2
3
2
3
2
3
4
7
4
6
5
6
6
6
6
17
6
6
6
6
7
6
6
7
7
7
8
9
8
8
10
11
13
10
9
14
10
10
10
10
10
12
12
12
13
13
13
14
14
15
16
16
16
18
17
22
18
19
22
20
20
24
28
21
26
25
24
25
26
30
25
26
27
27
27
32
31
33
32
32
35
32
36
34
34
43
36
40
41
44
45
44
43
45
44
43
45
49
45
47
52
47
52
48
56
54
55
60
53
55
59
58
59
64
71
67
62
73
95
66
69
71
74
75
76
83
80
79
75
82
86
82
81
82
90
90
90
89
88
90
96
90
93
97
99
93
102
106
104
109
107
105
115
107
116
114
108
111
114
117
```

**Comment by leebyron** [comment]
Can you post the code used to generate this output so I can reproduce and investigate?

**Comment by baskerville** [comment]
Thanks for asking this: while trying to extract a minimal reproducible example, I realized there was a bug in my code.

It might still be worthwhile to get acquainted with it though:
```
var Immutable = require("immutable"),
    Cursor = require("immutable/contrib/cursor");

var data = Immutable.fromJS({a: {b: {c: {d: 0}}}}),
    cursor = Cursor.from(data, update);

function update (nextData) {
	cursor = Cursor.from(nextData, update);
}

function foo (data) {
	return data.withMutations(function (mutableData) {
		mutableData.setIn(["a", "b", "c"], bar(data.getIn(["a", "b", "c"])));
	});
}

function bar (deep) {
	return deep.withMutations(function (mutableDeep) {
		mutableDeep.set("d", 3);
	});
}

for (var i = 0; i < 1000; i++) {
	var before = Date.now();
	foo(cursor);
	var delta = Date.now() - before;
	console.log(delta);
}
```

**Comment by leebyron** [comment]
I'll investigate any performance issues here, but just a few notes on your test case code:

`withMutations` is only really useful when doing more than one mutation. It avoids creating an intermediate collection for code like `data.set('a', 1).set('b', 2)`. Of course, for a single `set`, there is no intermediate creation to avoid.

`setIn(... getIn(...))` can be replaced with `updateIn`. In your example, these two would be equivalent, but the second line using `updateIn` will be slightly more performant since it only needs to traverse down the key path once instead of twice.

```js
data.setIn(["a", "b", "c"], bar(data.getIn(["a", "b", "c"])));
data.updateIn(["a", "b", "c"], bar);
```

Also, since your updateIn function is simply setting, you could simply further by using setIn directly.

Here is a reduced version of your same test case:

```
var Immutable = require("immutable"),
    Cursor = require("immutable/contrib/cursor");

var data = Immutable.fromJS({a: {b: {c: {d: 0}}}}),
    cursor = Cursor.from(data, update);

function update (nextData) {
    cursor = Cursor.from(nextData, update);
}

function foo (data) {
    return data.setIn(['a', 'b', 'c', 'd'], 3);
}

for (var i = 0; i < 1000; i++) {
    var before = Date.now();
    foo(cursor);
    var delta = Date.now() - before;
    console.log(delta);
}
```

**Comment by leebyron** [comment]
Note: I just realized you're using Cursor which has a more limited API. `setIn` doesn't exist directly, so for now using `withMutations` as you are will work around, but I will add this back soon.

**Comment by leebyron** [comment]
Also, running the above code, I do not see an increase in runtime with each loop. Are you still seeing it for your simplified case? Or is there a more complex case that shows this behavior?

**Comment by baskerville** [comment]
No you won't because you fixed the bug in the simplified case.

The problematic line is the following: `mutableData.setIn(["a", "b", "c"], bar(data.getIn(["a", "b", "c"])));`.

It causes cascading calls to `update`.

**Comment by leebyron** [comment]
Aha, yes. Now I understand the issue.Each call here results in two mutations - the inner set and the outer set. 

I'm not sure if this is something that can be worked around by the library directly or not, I will investigate further

**Comment by baskerville** [comment]
Passing `mutableData.getIn` instead of `data.getIn` to `bar` works for me.

Thanks for your diligence.

**Comment by leebyron** [comment]
Good catch.

What's happening here is that the inner `data.getIn` is returning a cursor and then setting that cursor into the structure in `mutableData.setIn`. So now your cursor contains a cursor :). On the subsequent update you'll have embedded a cursor to a cursor. On the 1000th iteration, you're modifying a cursor of a cursor of a cursor of a cursor etc 1000 times deep.
