### ISSUE TITLE
Map#map() always return a new Map even without changes

### ISSUE THREAD

**Issue by jeanlauliac** [facebook/immutable-js#285]
Consider the following piece of code:

```js
(function () {
  var m = new Immutable.Map({foo: 1});
  var n = m.map(function (e) { return e; });
  console.log(n === m);
})()
```

It prints `false`. However, the map data hasn't changed, meaning we loose the benefit of immutability here. If no element changes, perhaps it would make sense to return the same `Map`. What do you think?

**Comment by leebyron** [comment]
In theory I agree, however I'm not sure how to go about actually doing this.

**Comment by leebyron** [comment]
Currently all of the higher order functions like `map` and `filter` first create iterators, then populate new instances of the same class via that iterator. The new instance has no reference to the previous nor way of making the comparison that nothing has changed.

However, if you have an idea on how to do this, I would very happily take a look at a pull request.

**Comment by jeanlauliac** [comment]
So apparently `withMutations` correctly returns the same object if nothing changes. So one idea could be to use `withMutations` to map all the values. I'll give it a try.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
