### ISSUE TITLE
Logging Immutable-js collections in Chrome devtools console

### ISSUE THREAD

**Issue by Daniel15** [facebook/immutable-js#287]
Is it possible to have better output in the Chrome dev tools when looking at immutable objects? For example, when `console.log`ging a Record, it shows the raw internal state:

```
Record {_map: Object, constructor: function, _defaultValues: Object, _keys: Array[3], size: 3…}
```

It does look like `toString` shows useful debug info though:

```
Record { id: "6012624015168", loadState: "LOADED", name: "awesome2" }
```

I wonder if Chrome's dev tools support a custom debug view for objects (ie. automatically do the `toString` when `console.log`ging it)?

**Comment by leebyron** [comment]
Not to my knowledge. Though if Chrome lets you configure this, I'd love to do so.

**Comment by mczepiel** [comment]
I was about to chime in with a +1 complaining about this, but then realized you can just replace console.log:
```javascript
(function () {
	var _log = console.log;
	console.log = function () {
		var args = Array.prototype.map.call(arguments, function (arg) {
			return typeof arg.toJS === "function" ? arg.toJS() : arg;
		});
		_log.apply(console, args);
	}
})();
```
Might be worth dropping in during development.

**Comment by leebyron** [comment]
Nice utility! Sometimes I use a similar one which calls toString().

I also spotted https://gist.github.com/darwin/2a5651f590a4e8d55c68 which only works in Chrome canary with some flags turned on today, and allows custom formatting of arbitrary objects. Super cool, I hope we can leverage this approach soon.

**Comment by darwin** [comment]
The future is bright. You can write similar a library for immutable.js:
https://github.com/binaryage/cljs-devtools

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by damonmcminn** [comment]
I'd love to have this. The logging disparity between Node and the browser is... unpleasant.

**Comment by spicyj** [comment]
@andrewdavey just released https://github.com/andrewdavey/immutable-devtools!

**Comment by Daniel15** [comment]
The formatter is a pretty small amount of code, I wonder if this could just be bundled with immutable-js directly. 

https://github.com/andrewdavey/immutable-devtools/blob/master/src/index.js
https://github.com/andrewdavey/immutable-devtools/blob/master/src/createFormatter.js

**Comment by andrewdavey** [comment]
I'm happy for it to be bundled – perhaps wait until the formatter API is mainline Chrome?
Also, I suppose you could still have to explicitly `require('immutable/devtools')`, to avoid bloating the main immutable library in production builds.

**Comment by Daniel15** [comment]
> perhaps wait until the formatter API is mainline Chrome?

This is a good idea, especially since the API may change between now and then.

**Comment by rickhanlonii** [comment]
Update: The custom formatters are live Chrome 52 so this can move forward.

**Comment by Daniel15** [comment]
Hm? Custom formatters have been around for months - I've been using a Chrome extension (https://chrome.google.com/webstore/detail/immutablejs-object-format/hgldghadipiblonfkkicmgcbbijnpeog) since March and it's been working well.

**Comment by rickhanlonii** [comment]
Looks like it's been around since Chrome 47, judging by the [README history](https://github.com/andrewdavey/immutable-devtools/commit/47a3a8d9f205afca02b7f4f0d7645b013f1cad11#diff-04c6e90faac2675aa89e2176d2eec7d8) for that project.  
  
Does it even make sense to build this into the immutable library?

**Comment by leebyron** [comment]
Closing this aging issue - I'd love to see a separate npm package for this. Seems like `immutable-devtools` is a good start
