### ISSUE TITLE
.toJS doesn't change nested records to map

### ISSUE THREAD

**Issue by ekarlsso** [facebook/immutable-js#291]
This can be my misunderstanding about the toJS. Based on the documentation I thought that the toJS would change the structure deeply to corresponding native JS objects.

However, if I put immutable record, that itself contains immutable record into immutable list and call .toJS(); to the immutable list I get list and object as I expected but the nested immutable record in the parent immutable record doesn't get converted.

Something like this

ImmutableList[ Record{x:Record{y:1}}]

The list and the first record gets converted nicely.

**Comment by leebyron** [comment]
Thanks for the report, I'll look into this

**Comment by leebyron** [comment]
Can you clarify a bit with code you're using that's producing this case?

I assembled a small example which works this way:

```
var R = Immutable.Record({ x: null, y: null });
var data = Immutable.List.of( R({ x: R({ y: 1 }) }) );
// List [ Record { x: Record { y: 1 } } ]
var js = list.toJS();
// [ { x: { y: 1 } } ]
```

Were you expecting something else, or are you doing something else and expecting this?

**Comment by ekarlsso** [comment]
I'm really sorry. This is my mistake. My case was more like this:

var R = Immutable.Record({ x: null, y: null });
var data = Immutable.List.of( R({ x: [R({ y: 1 })] }) );

As you can see, it was purely my mistake. I had put a normal list inside the Record and not a immutable list. Sorry for taking your time.
