### ISSUE TITLE
[Feature Request] Long, Bignum

### ISSUE THREAD

**Issue by boopathi** [facebook/immutable-js#296]
Can big numbers, int64, Integers fit into Immutable js ?

So we can have

    var i = Immutable.Bignum(Number.MAX_SAFE_INTEGER).add(Number.MAX_SAFE_INTEGER);

    var i = Immutable.Long(Number.MAX_SAFE_INTEGER), 
         end = i.add(Number.MAX_SAFE_INTEGER);
    while( /* i < end */ i.lt(end)) {
      i = i.add(1);
    }

Can it fit into Immutable JS ?

**Comment by leebyron** [comment]
I'm not sure this makes sense to add to a data collections library, but certainly could be awesome as it's own library! Sharing conventions with Immutable would allow them to interop as necessary (e.g. implementing `hashCode()` and `equals()`)

**Comment by nicolasbrugneaux** [comment]
Hey, I would love to give it a try, as part of its own lib as suggests @leebyron. Can I have more details about the conventions it has to respect? :)

**Comment by leebyron** [comment]
#506 hints at the semantics necessary for object types to masquerade as value types from Immutable's point of view.
