### ISSUE TITLE
Documentation should include explanation of notation used

### ISSUE THREAD

**Issue by sfeldkamp** [facebook/immutable-js#298]
The documentation uses a notation I'm not familiar with.  Example: 
    List<T>(): List<T> 
    List<T>(iter: IndexedIterable<T>): List<T> 
    List<T>(iter: SetIterable<T>): List<T> 
    List<K, V>(iter: KeyedIterable<K, V>): List<any> 
    List<T>(array: Array<T>): List<T> 
    List<T>(iterator: Iterator<T>): 
    List<T> List<T>(iterable: Object): List<T>

What is this notation and could there be a link placed in the Docs API introduction explaining it in depth.  It's rather difficult to get good google results explaining what it might mean.

**Comment by pluma** [comment]
It's just plain old postfix type annotation (as in most mainstream statically typed languages):

* `List(): List` means `List` is a function that returns a `List` instance and takes no arguments
* `List(iter: SetIterable): List` means `List` is a function that returns a `List` instance and takes an argument called `iter`, which is an instance of `SetIterable`
* and so on.

There are multiple type signatures to explain that the function treats its arguments differently depending on their type. In this case it explains that it knows how to deal with the three types of iterables, as well as a plain old array, a plain old object and an ES6 iterator, but can also be called with no arguments (presumably to create an empty list).

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by stkrzysiak** [comment]
@pluma can you clarify this statement:

> It's just plain old postfix type annotation (as in most mainstream statically typed languages)

 I think I'd like to add something about this to the docs but I don't entirely understand this, and my google efforts have not turned up much. It seems like this is a term some people are very comfortable with('postfix type annotation') yet there is very little out there explaining what it is.  Is it type annotations that originated with the postfix project?  ....

While writing this I figured it out(i think), so if anyone else ends up here and experiences the initial confusion I experienced, I believe the answer lies in the definition of postfix: 'append as a suffix'.  It is my understanding now that a way of annotating a language by putting the types at the end: 

toLowerCase(String myString) vs. toLowerCase(myString String)

 This article on 'reverse' typed languages helped me gain some understanding, hope someone else finds it useful. [http://blog.joda.org/2011/07/reversed-type-declarations_4524.html](http://blog.joda.org/2011/07/reversed-type-declarations_4524.html )

**Comment by pluma** [comment]
Yes, by "postfix" I just meant "suffix".

Basically type annotations generally take one of two forms:

Prefix: `List List(Array array)`

Suffix: `List(array: Array): List`

In this case it's using the latter, which is also what Flow and TypeScript are using. Since this is a Facebook project, I'm guessing the type annotations are based on Flow.

"Most mainstream statically typed languages" was actually inaccurate. Both Java and C# seem to prefix types and they're pretty much the most mainstream languages I can think of.
