### ISSUE TITLE
fromJS should accept objects with no prototypes (?)

### ISSUE THREAD

**Issue by tolmasky** [facebook/immutable-js#302]
Seems like require("immutable").fromJS(Object.create(null)) should return Map{} not the original {}. I'm thinking this because Object.create(null) is used for maps (since it has no properties).

**Comment by dmnd** [comment]
I ran into this same problem while testing with jest which does some stuff with vm context that makes checking the constructor unreliable: facebook/jest#228

**Comment by leebyron** [comment]
Good call, I'll check for null prototype as well.
