### ISSUE TITLE
type definition for setIn() is wrong

### ISSUE THREAD

**Issue by besherman** [facebook/immutable-js#306]
The type definition for `setIn()` is 
```typescript
setIn(keyPath: Array<any>, value: T): List<T>;
```

which states that `value` should be of type `T`. I humbly suggest that it should be of type `any`.

Forcing `value` to be of type `T` makes little sense because it says that you can have as deeply nested structures as you like, as long as everything is of type `T`.

The point of `setIn()`, as I see it, is that it can reach inside a structure and change a specific value - very useful when using immutable objects. Lets say that I have an interface called `Block` and a `List` of blocks. I want to change the property `comment` of block on index 3 in the list. 

```typescript
interface Block {
    comment: string;
}

var list: List<Block>;
list.setIn(List.of<any>(3, "comment"), "new comment");
```
This is a useful pattern in javascript, but it is not possible in typescript because the type definition says that `comment` must be of type `T`.

The workaround is to use `updateIn()` which use `any`, but at the cost of having to supply a function.

**Comment by leebyron** [comment]
You're spot on. Thanks for your careful reading and spotting this slip-up.
