### ISSUE TITLE
What's the differences among Seq, List, Collection, Iterable?

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/immutable-js#308]
Being write JavaScript which only uses Array, I'm not quite into types of ES7 and TypeScript. Is there any tutorials that guide people like me to types in immutable-js ?

**Comment by leebyron** [comment]
I would start with the documentation at http://facebook.github.io/immutable-js/docs/

You'll find descriptions of each of these types.

**Comment by jiyinyiyong** [comment]
@leebyron I've read that one. But is there any plan adding some more examples in JavaScript?

I mean, although I can understand most part of that documentation, there's still some barriers when I want to use it, due to my weakness in static typed languages.

**Comment by leebyron** [comment]
Yes I have an existing task to add more example code to the documentation.

For now, you probably only need to pay attention to List. It's also the most well documented.

**Comment by jiyinyiyong** [comment]
Good news for me :+1:
