### ISSUE TITLE
Strict equality between maps

### ISSUE THREAD

**Issue by mczepiel** [facebook/immutable-js#311]
Is this expected behavior?
```javascript
var a = Immutable.Map();
var b = a.clear()
a === b // true
```

I was not expecting this in a similar situation: ``Immutable.Map() === Immutable.Map()``` and certainly not in the `clear` situation (or any other persistent api call) since the api does indicate the behavior I'd expect: "Returns a new Map containing no keys or values."

Though I see there's some special case for `emptyMap()`

**Comment by leebyron** [comment]
Yes, this is expected. Immutable.js has optimizations in its methods to return `this` when the method would be a no-op, enabling reference equality checking to determine if no change was made.

It makes more sense when using `set` as the example:

```js
var a = Immutable.Map({key: 'value'});
var b = a.set('key', 'value')
a === b // true
```

**Comment by mczepiel** [comment]
Ok, hmm. Guess I need to manually force a change in react when replacing an immutable object with another; I was expecting the new immutable object to be picked up as different than the old one when changing that property in state.

FWIW, a child had received the original immutable object, ended up with a different one in its state after modifications, and I'm trying to pass the new immutable object via props to put it back into its initial state.
