### ISSUE TITLE
Include cursors in dist or add a separate file dist for cursors

### ISSUE THREAD

**Issue by Gozala** [facebook/immutable-js#312]

**Comment by leebyron** [comment]
Cursors will likely find their way into a separate file for distribution in the next version bump.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Closed with #1137
