### ISSUE TITLE
constructor.name for a custom Record isn't accurate

### ISSUE THREAD

**Issue by jeanlauliac** [facebook/immutable-js#313]
Because [of the way a Record class is built](https://github.com/facebook/immutable-js/blob/master/src/Record.js#L21-L26), the constructor name is always "Record":

```js
var MyRecord = new Immutable.Record({ foo: null });
var rec = new MyRecord();
console.log(rec.constructor.name);
//=> Record
```

This is unfortunate for systems that try to type-check given the constructor name. There are two solutions that could fix that:

1. Declare custom records with good ol' constructors
2. Use a similar technique to what is [described in on this stackoverflow answer](http://stackoverflow.com/a/22880379/941001).

Example of how it could look like for (1), in ES6:

```js
class MyRecord extends Immutable.Record {
  constructor(values) {
    super({ foo: null }, values);
  }
}

var rec = new MyRecord({ foo: 'bar' });
```

But I'm not totally sure of the technical feasibility, and that's bulkier. On the other hand, that's more of what we expect in the ES6 world, and that would allow people to customize the constructor arguments. I know there have been other discussions about improving `Record` as well. I think I'll give it a try.

What do you think about the higher-level issue, anyway?

EDIT: I forgot quite a drawback about (2): it's not backward compatible, meaning a version-major change.

**Comment by leebyron** [comment]
Yeah, I agree that type-checking when used with Record feels crummy right now. It's a combination of the capabilities of the type-checkers (requires a lot of dynamism) and how Record classes are built.

I'm inclined to investigate any changes in the API for Record if it can help support better type definitions. I'm open to more ideas.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
