### ISSUE TITLE
Is there a way to deeply find a keyPath in a Map? (deep Map.keyOf)

### ISSUE THREAD

**Issue by vpavkin** [facebook/immutable-js#315]
Hi, awesome library!
I'm considering migrating my model on Immutable-JS, but it looks like I miss some API. Or concept understading :smile:
I have a deeply nested trie dynamic model, with components referencing various nested nodes. 
So if I have a node, and the root, but no `keyPath`, is there a way to figure out the node `keyPath`, to make updates to the root via `updateIn`?

Or should I instead store that `keyPath` somewhere during initial traversal, when I create my components based on the model.

Thanks!

**Comment by mukeshsoni** [comment]
You can use cursors - https://github.com/facebook/immutable-js/tree/master/contrib/cursor

**Comment by vpavkin** [comment]
@mukeshsoni Awesome, thank you! :smile: :+1:
