### ISSUE TITLE
Font rendering problems in docs on Linux

### ISSUE THREAD

**Issue by freiksenet** [facebook/immutable-js#319]
Fira Sans / Mono family has rendering problems on Linux in Firefox and Chrome, so some users will see blank code blocks instead of examples. Even though there are some workarounds, I think it's easier to just switch to the font that works out of the box on all platforms.

**Comment by leebyron** [comment]
Huge bummer, but thanks for the report. What browser and version are you seeing this in, or if it's all of them, what cut of Linux?

**Comment by leebyron** [comment]
What workarounds are you aware of?

**Comment by freiksenet** [comment]
On ArchLinux installing Fira font package on the system solves the problem, but the issue here is that most people won't try to check what font is used and will just consider website broken.

**Comment by freiksenet** [comment]
It's on ArchLinux, Firefox 35 and all 3 current Chrome channels.

**Comment by nbostrom** [comment]
Just fyi: works well on ubuntu (14.04)

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by freiksenet** [comment]
Seems to work fine for a while now, so I'll close.
