### ISSUE TITLE
Map.merge not working as expected with integer keys

### ISSUE THREAD

**Issue by adamschoenemann** [facebook/immutable-js#320]
I'm new to your library, and may be using it incorrectly, but when use Map.merge with a integer-indexed object, I do not get expected results. Map.toJS works as expected however.

```javascript
var m = Immutable.Map();
m = m.merge({2: 'foo', 3: 'bar'});
m.has(2); // false
m.get(2); // undefined
m.toJS(); // {2: 'foo, 3: 'bar'}
```

**Comment by hydRAnger** [comment]
@adamschoenemann 
try this:
m.has('2');
m.get('2'); 

keys are string.

**Comment by adamschoenemann** [comment]
Of course!

**Comment by leebyron** [comment]
Same as #282 where there is more info
