### ISSUE TITLE
Metadata API

### ISSUE THREAD

**Issue by tgriesser** [facebook/immutable-js#322]
Likely easier to accomplish as a plugin or similar with any changes that may come from #301, but this would be a super nice to have.

Currently I'm using a custom metadata API on my fork to signal specific properties on a map used in triggering a change at a path (sort of an observable cursor type deal). Other cases I'm using are to store temporary info related to the data but which shouldn't change the actual shape of underlying value - the "type" of a filtered result, whether a map has been "validated", etc.

Setting metadata on an Immutable object would return a new value which would be considered value equal but not referential equal.

**Comment by leebyron** [comment]
Interesting. So you use meta as a marker interface to see if some data has been validated or not already. What other common uses take advantage of meta?

**Comment by leebyron** [comment]
@swannodette I'm sure you can provide some good advice here. What are the benefits and pitfalls of meta in practice in most clojure apps?

**Comment by swannodette** [comment]
@leebyron the only real pitfall for metadata is accidentally losing it, internally most Clojure(Script) data structures preserve metadata across all operations that make sense. The other problem is how to transit metadata over the wire. Got no ideas about that.

The benefits are many in Clojure(Script), people use it for all kinds of things - everything from annotating Clojure(Script) source code itself to providing provenance information on runtime data.

**Comment by janmarek** [comment]
I would also appreciate some kind of metadata API. I don't know where to store state (such as loading, error, ok) and error messages in react app using immutable.js now.

I have implemented my own "library" which wraps immutable.js structures and provides method like updateDataAndMetada, getErrors, getState (+ shortcuts isLoading, isOk, ...). It also has methods like get, getIn, set, setIn which behaves the same way like immutable.js methods. So if you call set on "my" object, it returns a new instance with value set on the inner immutable.js object. But I don't think it is a best approach.

**Comment by janmarek** [comment]
Metadata would be super easy to add to mutable data structures. Adding a field to an object would done the thing. However with immutable objects we need to be sure it is copied with every object change.

**Comment by leoasis** [comment]
Yeah, I'm using it in a custom collection of models (records with ids and client ids), where you can have metadata as @janmarek mentioned of setting if that collection is currently being fetched. Anyway, I implemented it by making my custom collection have a record of metadata attributes. Would be really great to see how an API for metadata attributes could look like

**Comment by madebyherzblut** [comment]
:+1: on metadata for all immutable objects. We need a flag to indicate if our record object is only partially fetched (= only the identifier field is set). Right now we work around this by checking if all values are `undefined` (= default values) expect the identifier field(s).

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Closing this aging issue - perhaps something we could consider in the future.
