### ISSUE TITLE
computational complexity of Set operations

### ISSUE THREAD

**Issue by ameliusg** [facebook/immutable-js#323]
Hello, I'm wondering what is the computational complexity of doing Set intersection and union under the special circumstances where the two sets are almost equal?

I'm asking this because I'd like to perform fast set-difference operations on large sets, where I know beforehand that the sets are almost equal. In my case, both operands are derived from the same large set, but one of the operands has undergone some (small number of) mutations.

It seems to me that this should be implementable using functional data-structures, but I'm not sure if immutable-js actually implements it such that this is fast.

**Comment by leebyron** [comment]
has() and set() are both O(1) while union() and intersection() are O(N) in the current implementaion. 

If you can point me to research in making these ops faster than order N, I would love to see it.

**Comment by ameliusg** [comment]
Hi Lee, I don't have any pointers to actual research. But I imagine if the Set is implemented by, for instance, a red-black tree, then a computation of the intersection of two sets (two red-black trees) could simply walk through both trees, and look for nodes which are identical (have the same address), and skip the subtrees rooted at those nodes. Those identical nodes could be found by looking up the keys, I suppose. Anyway, I realize this is not a proof, just a sketch of how this could work :)

**Comment by leebyron** [comment]
Sure. That's probably still O(N) but may have a better performance factor. Sets are actually backed by the same structure as Map, a HAMT. It has a similar tree shape. I have an outstanding task to make an optimized version of map merge or set union that follows this. I'm not sure that will do much for intersection though. If you have more info let me know!

**Comment by ameliusg** [comment]
Well actually I'm looking for something that is more like O(M) or O(M log N), where M is the number of mutations between the operands set1 and set2. Thinking a little deeper, the algorithm I would consider (based on red-black trees) goes through set1 and set2 simultaneously, and whenever there is a difference in set2 wrt set1, it looks up the mismatching node of set1 in set2 (this costs O(log N)). If found, then that subtree can be added to the current intersection using the fast-union. If not found, continue comparing along the tree. It seems that this algorithm is O(f*M log N), where f is a factor that takes into account the time for the fast-union.

I suspect that the union of the common subtrees can be fast, because by design, they don't intersect. But not quite sure about the computational complexity.

I'm also not sure how this would apply to the HAMT structure.

A similar algorithm could be used to perform set-difference directly (perhaps this is even simpler).

**Comment by leebyron** [comment]
I'm interested in seeing reference implementations of this. If they're actually referential the same data then yes I believe you could get O(log N) union/intersection. However if they are simply value equal then there is no way to escape O(N) as you need to actually visit every node to determine a union or intersection.

**Comment by leebyron** [comment]
Consider creating the union of:

```
      13
    /    \
   8      17
 /  \    /  \
1   11 15   25
 \         /  \
  6      22   27
```

and

```
      13
    /    \
   8      17
 /  \    /  \
1   11 15   25
 \         /  \
  7      22   27
```

Despite only one value being different, you have to at least crawl the tree to 
find it. You can't determine from seeing that both trees have an "8" node that
you can stop crawling the tree. You must spend O(N1 + N2) time to determine the
union.

In a Red Black Tree, you also must then balance the result of the merge, which
is itself O(M * log N)

HAMT might yield a different outcome considering that it doesn't care about ordering so it doesn't require a rebalance, but I think simply determining the union/intersection will require a full traversal of both trees with the exception of the case where both trees are structurally sharing common subtrees. For example, if the `17` branch in both trees was *literally the same memory*, e.g. `===` then we could shortcut and be O(1) for that subtree.

**Comment by ameliusg** [comment]
Hi (sorry for replying so late, I haven't been at my computer for about a week),

The idea is that there IS structural sharing, because both sets are considered to be coming from the same source, although the sets might have both changed (slightly). To see this, consider that since an update to a set has computational complexity far smaller than O(N), both sets *must* have structural sharing.

And indeed, using the fact that there is structural sharing, you can identify identical nodes, and eliminate complete subtrees. That was already an assumption I made in my previous posts, but I should have been more clear about it.

By the way, this form of doing set-operations is important for "diffing" of data structures, so that updates can be efficiently performed by determining which parts of a data-structure has changed with respect to a reference version. So I really hope these fast operations become part of the library :)

**Comment by leebyron** [comment]
Tracking this now in #507
