### ISSUE TITLE
Recommended way to update a Map

### ISSUE THREAD

**Issue by emmenko** [facebook/immutable-js#324]
Hi,

I'm experimenting a bit with immutables and I'm not sure what I'm doing is actually correct or if there is a better way to do it.

So let's say I have a Store like this

```javascript
var store = Map({
  customers: Map({
    count: 0,
    total: 0,
    results: List()
  })
})
```

Now when I get new customer data I want to update the store and dump the new data in it

```javascript
var newData = {
  count: 2,
  total: 2,
  results: [
    {id: 1, name: 'Alice'},
    {id: 2, name: 'Bob'}
  ]
}

store = store.setIn(['customers'], fromJS(newData))
```

Any help would be much appreciated, thanks :)

**Comment by leebyron** [comment]
That looks just fine to me. Is it doing what you want?

Since your setIn key path is short, you can also do:

store = store.set('customers', fromJS(data))

**Comment by emmenko** [comment]
Hey, thanks for the quick answer!

Yes, it does what I expect, just wondering if it's the right way to do it ;)

Because if I just pass the JS object and don't convert it back with `fromJS` then `customers` is not an immutable map anymore

```javascript
console.log(store.set('customers', newData).get('customers'))
// => Object {count: 2, total: 2, results: Array[2]}

console.log(store.set('customers', fromJS(newData)).get('customers'))
// => Object {size: 3, _root: ArrayMapNode, __ownerID: undefined, __hash: undefined, __altered: false…}
```

I thought it would be implicitly converted on `set`, so I just wanted to make sure :)

**Comment by leebyron** [comment]
That's correct

**Comment by emmenko** [comment]
Cool, then I can close this. Thanks for the help and your time :+1:
