### ISSUE TITLE
[Feature Request] typed immutable collection javascript api

### ISSUE THREAD

**Issue by daniellewissc** [facebook/immutable-js#326]
I know there is built in support for using typescript for doing this, but it would be great if there was an idiomatic javascript api for defining types, maybe something like 
```
var CustomList = Immutable.List.ofType(Number);
var immutableStuff = CustomList([1,2,3]);
var changedStuff = immutableStuff.push('6'); // Throws an Error with informative message
```
or 
```
var CustomMap = Immutable.Map.ofType(String, Immutable.List.ofType(String));
var moreStuff = CustomMap({
    a: Immutable.List(['q','w','e']),
    b: Immutable.List(['t','y'])
})
```
or
```
/*
  this is admittedly sort of wonky, maybe could join
  type and default in a tuple like [Number, 4]
*/
var CustomRecord = Immutable.Record.ofType({
    thing: Number, 
    other: String
})({
    thing: 0,
    other: ""
});
var evenMoreStuff = CustomRecord({thing: 6})
```

This gets to be really powerful when you add the idea of union types 
`Immutable.Seq.ofType([String, Number])`
and fromJS-ing-with-type (also wonky)
`Immutable.fromJS.withType({f: ['z','x','v'], l: ['i','o','p']}, CustomMap)`

it would also be nice if we could somehow set up the typescript compiler to use this api so that the javascript generated could be safe if used by other non-typescript javascript code, but i dont know if thats possible.

**Comment by leebyron** [comment]
I explored this not too long ago, thanks to some help from members of this community and found that it's quite difficult as soon as you have operations that map from one type to another type, namely `reduce` and `map`. You could imagine how calling `map` on a `List.ofType(Number)` with a mapper like `num => num + " many"` List would either have to lose it's typing, or find some way to infer the type of the new list.

I think this fits into the category of things that are difficult and awkward to do without language or compiler support.
