### ISSUE TITLE
fromJS force parameter

### ISSUE THREAD

**Issue by tolmasky** [facebook/immutable-js#329]
Could there possibly be a "force" parameter for fromJS. I'm running into an issue using it alongside jsdom, where the === Object test is failing because the object was created in a different context (thus value.constructor === outside_context's Object). I could implement my own fromJS, but I'd prefer to then not have to track the official implementation, and I feel like its a somewhat common case to just want to unconditionally convert things to Map as well.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Merging into #1050 - sorry for the massive delay
