### ISSUE TITLE
Extend record classes

### ISSUE THREAD

**Issue by madebyherzblut** [facebook/immutable-js#334]
Is there a way to extend record classes? I do have a record class as a base and want to add more keys.

```js
var MyRecord = Record({a: 1, b: 2});
var MyExtendedRecord = MyRecord({c: 3});
```

**Comment by leebyron** [comment]
There is not at this time. You need to always define the whole key set when you define a record.

**Comment by madebyherzblut** [comment]
Ok, good to know. Thanks!

**Comment by gmaclennan** [comment]
I was doing this:

```js
var BaseRecord = function (defaultValues) {
  return Record(Object.assign({
      a: 1,
      b: 2
    }, defaultValues))
}

var ExtendedRecord = BaseRecord({ c: 3 })
```

I think that works.

**Comment by justinko** [comment]
```javascript
import { Record } from 'immutable'

const Base = defaultValues => class extends Record({
  id: undefined,
  links: {},
  errors: {},
  ...defaultValues
}) {

}

class User extends Base({
  firstName: undefined,
  lastName: undefined
}) {
  fullName() {
    return this.firstName + ' ' + this.lastName 
  }
}
```

**Comment by yavuzmester** [comment]
What about this approach?
`    const PersonMixin = Base => class extends Base {
        grew(years) {
            return this.set("age", this.age + years);  //returns a new Person, which is fine
        }
    };

    const PersonRecord = new Immutable.Record({name: null, age: null});
    class Person extends PersonMixin(PersonRecord) {}

    const AcademicanRecord = new Immutable.Record({name: null, age: null, title: null});
    class Academician extends PersonMixin(AcademicanRecord) {
        constructor({name, age, title}) {
            super({name, age, title});
        }
    }

    var a = new Academician({name: "Bob", age: 50, title: "Assoc. Prof"});
    console.log(a);
    console.log(a.grew(10).age); //grew works
    a.title = "Prof";   //the error "Cannot set on an immutable record" received.`

We do not extend PersonRecord, but use a PersonMixin to define base methods.

**Comment by th3fallen** [comment]
@justinko very late question but im using your suggestion and it works very well except i CANNOT test a method in that thing to save my life? have you found a way around it by chance? what i've got atm https://gist.github.com/th3fallen/92491b889485961cc97938c306f0836c#file-model-spec-js-L28
