### ISSUE TITLE
Integer values becomes strings in construction but not when calling `set`

### ISSUE THREAD

**Issue by TryingToImprove** [facebook/immutable-js#337]
When creating a `Immutable.Map` and passing a object-map of integer keys it transforms the keys to strings, but when calling `map.set`, it does not transform the integer to string and instead creates a duplicate..

    var items = Immutable.Map({ 1: "hi" })
    console.log(typeof(items._root.entries[0][0]) === "string"); //= true (should be a number?)
    items = items.set(2, "hello");
    console.log(typeof(items._root.entries[1][0]) === "string"); //= false

Is this a issue? A solution is to use .toString() when calling `set` or `get`, but I think it is weird that it choose change the type in the first place..

**Comment by leebyron** [comment]
This is very similar to #282 which I suggest you read. 

The TLDR is that object keys are *always* strings. Javascript lets you omit quotes for keys when writing the literal form, but they are still read and stored as strings.
