### ISSUE TITLE
should withMutations() offer a context?

### ISSUE THREAD

**Issue by sebastienbarre** [facebook/immutable-js#340]
Should `withMutations()` offer a `context` parameter, so that `this` can be set in the context of the `mutator`?
i.e.
```
  withMutations(mutator: (mutable: Map<K, V>) => any): Map<K, V>
```
becomes:
```
  withMutations(mutator: (mutable: Map<K, V>) => any, context?: any): Map<K, V>
```
to match signatures such as `Map:map()`
```
map<M>(
mapper: (value?: V, key?: K, iter?: Iterable<K, V>) => M,
context?: any
): Iterable<K, M>
```

Thanks

**Comment by leebyron** [comment]
Is there a particular use case you have in mind here? I would suggest using arrow function or bind if you need the immediate surrounding context at the present moment. 



—

**Comment by sebastienbarre** [comment]
I guess in the context of a React component's method, `this` is set to `window` inside `withMutations()`, preventing any other component's method from being called?  But reading more about the arrow function it appears its biggest benefit is that it does not alter `this`. Sorry, not completely used to ES6. Thanks for the pointer. Maybe for consistency with the sequence methods, it would a useful addition...

**Comment by leebyron** [comment]
Good suggestion, I'll look into it



—

**Comment by MatthewHerbst** [comment]
:+1:  to this. I'm building a complex structure using `withMutations` and I have some generation code in helper methods. I would like to be able to reference them directly rather than having to save local copies above the `withMutations` call.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Deciding against this in favor of encouraging arrow functions to keep API simple.
