### ISSUE TITLE
An ergonomic way to generate a subset of a Map

### ISSUE THREAD

**Issue by nhunzaker** [facebook/immutable-js#342]
For React projects, I'm finding myself wanting to send down a subset of a record to a child component to avoid re-rendering when an unused attribute of that record is changed. Right now I am doing this like:

```javascript
subset() {
    return Immutable.Map({
        prop1 : record.get('prop1'),
        prop2 : record.get('prop2'),
        prop3 : record.get('prop3')
    })
}
```

This is fairly straightforward, and I could probably generalize it further, but I'm curious if there is a more ergonomic way to achieve I want. For example, something similar to slice but for keys:

```javascript
map.subset("prop1", "prop2", "prop3")
```

**Comment by leebyron** [comment]
Will the recipe for "pick" do what you need?

https://github.com/facebook/immutable-js/wiki/Predicates

**Comment by nhunzaker** [comment]
Oh this is lovely!

**Comment by nhunzaker** [comment]
It completely slipped my mind that `filter` was applicable. Thanks!

**Comment by tusharmath** [comment]
+ 1 of vanilla support. This feature is quite commonly used I feel and why should everyone implement their own `keyIn` filter function?

**Comment by D1plo1d** [comment]
+1 to @tusharmath's point. Asking everyone to copy and paste `keyIn` for a common use-case like pick violates DRY.

**Comment by maxjiang23326** [comment]
Hi @leebyron, I was wondering why you won't consider adding vanilla support for this feature? I have seen quite a few people asked for it:

https://github.com/facebook/immutable-js/issues/224
https://github.com/facebook/immutable-js/issues/165

Like @tusharmath and @D1plo1d have said, it is a commonly used feature, and asking everyone to implement their own `keyIn` filter function violates DRY. 

Thanks

**Comment by rhagigi** [comment]
It's worth noting that the above solution (keyIn) only makes sense for *small* Maps, as it has to iterate the entire thing. 

It is faster on small Maps, by about 50%, so definitely useful in some cases if you know the size of your map.

If you're using this on a large map of (for example) normalized entries, it's way slower than mapping the keys directly to the object. Using BenchmarkJS with a 1000 key map of random string keys (`TEST_MAP`), and an array of 5 random keys in that map (`TEST_SET_OF_KEYS`),  and this code... 

```
var keysToPick = TEST_SET_OF_KEYS;
var data = Immutable.Map(TEST_MAP);
function keyIn() {
  var keySet = Immutable.Set(arguments);
  return function (v, k) {
    return keySet.has(k);
  };
}

function pickUsingKeyIn() {
  return data.filter(keyIn.apply(null, keysToPick));
}

function pickUsingMap() {
  var keySet = Immutable.Set(keysToPick).toMap();
  return keySet.map(function(key) {
    return data.get(key);
  });
}
```
this is the output
```
[ '7ahFz', '69REj', 'ZURMt', '3AZDL', 'EAzmg' ]
Map { "7ahFz": "JPQ66", "69REj": "dUnQb", "ZURMt": "z4OSR", "3AZDL": "EYxkS", "EAzmg": "kEHL5" }
Map { "7ahFz": "JPQ66", "3AZDL": "EYxkS", "69REj": "dUnQb", "EAzmg": "kEHL5", "ZURMt": "z4OSR" }
Using Predicate for Filter to Pick x 3,312 ops/sec ±1.59% (72 runs sampled)
Using Map to Pick x 81,357 ops/sec ±2.17% (64 runs sampled)
```
