### ISSUE TITLE
[Documentation] Difference between size and count()

### ISSUE THREAD

**Issue by astorije** [facebook/immutable-js#343]
The documentation mentions the existence of the [`size` property](http://facebook.github.io/immutable-js/docs/#/Collection/size) for `Collection` elements (that I understand as an equivalent to the `length` property of `Array` elements, as discussed on #236), but it doesn't say anything about it.

It also features a [`count()` method](http://facebook.github.io/immutable-js/docs/#/Collection/count) on `Collection` elements and from the documentation I do not understand when one should use `count()` over `size`.

What is the difference between these two? Could the documentation be updated with the answer?

**Comment by leebyron** [comment]
size and count() are almost always equivalent. However some lazy Seq cannot know their size until being fulfilled so size will be undefined for those cases and calling count() will fulfill the lazy Seq to determine its size. 

Thanks for reminding me to update docs with this. I'll leave this task open until it's done

**Comment by astorije** [comment]
Thanks @leebyron! Does that mean that, in general, `count()` should be used instead of `size`?

My use case is in tests, when trying to assert how many elements are in my immutable collections should I test against `count()` or `size`?

**Comment by leebyron** [comment]
If you're making use of Seq in your code then I definitely suggest sticking to count(). If not, there's nothing wrong with using size directly.

**Comment by hleumas** [comment]
@leebyron wouldn't it be better if `Seq`s didn't have `size` property? It can lead to bugs and adds no substantial benefit.

**Comment by leebyron** [comment]
There are a number of places where it's very beneficial to know the size of a Seq without having to iterate through it - for example when slicing slices. You can reap very real performance benefits from this.

I definitely recognise the potential for causing trouble though - I'll consider this not just a detail to be documented, but an API to improve in future versions that maintains the ability to write highly performant code, but also doesn't present these kinds of potential bugs.

**Comment by lacker** [comment]
This seems sufficiently answered, so I am going to close this issue!

**Comment by BrunoQuaresma** [comment]
I agree with @hleumas. Developing a homogeneous API seems to me the best option. Even if the size property in Seq only works as an interface.
