### ISSUE TITLE
Pick only some keys with toJS/toObject

### ISSUE THREAD

**Issue by klimashkin** [facebook/immutable-js#349]
How to convert to plain object only some keys from Map?

**Comment by leebyron** [comment]
Use filter() before toJS()

See this recipe for a pick filter: https://github.com/facebook/immutable-js/wiki/Predicates

**Comment by klimashkin** [comment]
Thanks, Lee!

четверг, 26 февраля 2015 г. пользователь Lee Byron написал:

> Use filter() before toJS()
>
> See this recipe for a pick filter:
> https://github.com/facebook/immutable-js/wiki/Predicates
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/immutable-js/issues/349#issuecomment-76225193>
> .
>


-- 
*С уважением, Климашкин Павел.*
