### ISSUE TITLE
Immutable model?

### ISSUE THREAD

**Issue by klimashkin** [facebook/immutable-js#351]
Hello!
In JS we often have some entity models. For example, User.
We have User constructor and some helper methods in it prototype. So, creating myUser instance, we get object with data and methods.
Is it possible to do something like that with Immutable? Record looks suitable, but I have feeling something wrong here: is it right to have functions in it as methods?

**Comment by leebyron** [comment]
It sounds like Record is exactly what you're looking for.

**Comment by klimashkin** [comment]
I got you.
Now I think, do we need inheritance as in example? 
```
class ABRecord extends Immutable.Record({ a:1, b:2 }) {
  getAB() { return this.a + this.b; }
}
```
Perhaps enough to extend prototype of created record class (prototype is created together with the creation of class)?  Less intermediate objects in property resolution.
```
var ABRecordClass = Immutable.Record({ a:1, b:2 });
ABRecordClass.prototype.getAB  = () => { return this.a + this.b;  }
var ABRecord = new ABRecordClass();
```

**Comment by dminkovsky** [comment]
Perhaps related: https://github.com/facebook/immutable-js/issues/334

**Comment by dminkovsky** [comment]
And this: https://github.com/facebook/immutable-js/issues/124#issuecomment-75932667

**Comment by leebyron** [comment]
Records can already be extended via normal prototypal inheritance, however the storage mechanism cannot.

I'm not sure I'm understanding what's being asked for here. Please re-open if this doesn't resolve the task.

**Comment by tokland** [comment]
@klimashkin, check #384
