### ISSUE TITLE
Interleave with infinite Seq

### ISSUE THREAD

**Issue by teawaterwire** [facebook/immutable-js#352]
Hi!

Just started to play with Immutable, and I'm wondering why this line is returning me `undefined`:
`I.Repeat('I love').interleave(I.Repeat('doge')).get(3)`

And not `'doge'` instead?

Cheers

**Comment by leebyron** [comment]
Thanks for reporting this (and I'm so sorry for getting to it so late!)

**Comment by teawaterwire** [comment]
No worries :)
It seems that `interleave` is not part of the documentation anymore though. Is it going to be added back?

**Comment by lacker** [comment]
I think this is fixed, so I am going to close it, but if not please feel free to reopen this issue!
