### ISSUE TITLE
Immutable.Stack#last() returns undefined

### ISSUE THREAD

**Issue by Zenwolf** [facebook/immutable-js#353]
**Version:**
3.6.2

**Bug:**
Stack should return the last value when `last()` is called.

**Example:**
```javascript
var l = Immutable.List([1, 2, 3, 4]);
var s = Immutable.Stack(l);
s.first(); // 1
s.last(); // undefined
s.size; // 4
s.get(3); // 4

**Comment by Zenwolf** [comment]
I checked the docs, and it mentions both `first()` and `last()` functions for Stack. However, there are no special notes that state that `last()` should behave differently for the Stack object. Can you clarify if it is intended that Stack should not return a `last()` value?

**Comment by leebyron** [comment]
Thanks for finding this bug! I'll dig in to fix it
