### ISSUE TITLE
Typo; possible also secondary issue

### ISSUE THREAD

**Issue by JonathanHayward** [facebook/immutable-js#354]
The typo I picked up was on List#min():

Returns the **max**imum value in this collection. If any values are comparatively equivalent, the first one found will be returned.
min(comparator?: (valueA: V, valueB: V) => number): V

The secondary concern I noticeed was that I tried briefly to navigate to the master copy, fork, change it, and issue a pull request. But I couldn't immediately find where

**Comment by JonathanHayward** [comment]
Sorry, dumb me hit the wrong button.

I couldn't immediately find where to navigate to the file in question; perhaps facebook / immutable-js / docs could be created with a stub saying "If you want to change the docs, they're over at _______."

**Comment by leebyron** [comment]
Hey @JonathanHayward thanks for the report.

For future reference, if you scroll to the bottom of any of the pages in the docs, there's a red box explaining that they are autogenned with links to the relevant files.

**Comment by JonathanHayward** [comment]
Thanks!

On Mon, Mar 2, 2015 at 2:44 PM, Lee Byron <notifications@github.com> wrote:

> Hey @JonathanHayward <https://github.com/JonathanHayward> thanks for the
> report.
>
> For future reference, if you scroll to the bottom of any of the pages in
> the docs, there's a red box explaining that they are autogenned with links
> to the relevant files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/immutable-js/issues/354#issuecomment-76816073>
> .
>



-- 
[image: Christos Jonathan Seth Hayward] <http://jonathanscorner.com/>
Jonathan S. Hayward, a full stack web developer with Python/Django and
AngularJS/jQuery.

Articles on Technology <http://jonathanscorner.com/technology/> • Book: *Django
JavaScript Integration*
<http://www.packtpub.com/django-javascript-integration-ajax-and-jquery/book>
 • *Email <jsh@jsh.name>* • Github <http://github.com/JonathanHayward> •
LinkedIn <http://www.linkedin.com/in/jonathanhayward> • Main Website
<http://jonathanscorner.com/> • *Professional Site <http://jsh.name/>*

I invite you to visit my professional site! <http://jsh.name/>
