### ISSUE TITLE
Links to headers in docs

### ISSUE THREAD

**Issue by haf** [facebook/immutable-js#356]
Hello!

Thanks for a great lib! We've just started using it.

Could you please add links to each heading of the docs? E.g. say I wanted to link to the `set(at, val)` in `List()`; with github READMEs I can just find the link next to the heading -- could you do something similar?

It would help me share docs with my team! =)

Thanks again for the library!
Henrik

**Comment by leebyron** [comment]
This works today, but I'll keep this task open to make it a bit more obvious.

If you click on a header from the table of contents on the left side, you'll get a link to that location. In your example: http://facebook.github.io/immutable-js/docs/#/List/set

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
To any contributors looking to help: it would be great if you could click the headers in the docs to get anchor links

**Comment by liubinyi** [comment]
Hi @leebyron I am new to immutable code base. I am giving this a try. hopefully i read the problem correctly. please let me know if this pr needs any update. Thank you!
