### ISSUE TITLE
[FAQ] Listeners

### ISSUE THREAD

**Issue by kuraga** [facebook/immutable-js#357]
Good day!

Can I set a listener to observe object's updates?

Thanks.

**Comment by leebyron** [comment]
You cannot because immutable objects have no updates to observe!

Perhaps you could share some example code of what you're looking for and how you expect it to behave and I might give a better suggestion.

**Comment by kuraga** [comment]
@leebyron I want something like Raynos/observ-struct

**Comment by kuraga** [comment]
They has no updates but they are (re)`set`ed :smile:

**Comment by leebyron** [comment]
Perhaps `Cursor` would suffice?

**Comment by kuraga** [comment]
Maybe. But is it for parts? Why?

Maybe https://github.com/omniscientjs/immstruct. Don't know.

**Comment by Dashed** [comment]
@kuraga `immstruct` is your way to go as an initial implementation to observing by paths/cursor has been implemented: https://github.com/omniscientjs/immstruct/pull/30

Observing by `Cursor.from` is limited in some capacity where you won't be able to detect changes of a `keyPath` if an ancestor has changed its subtree. 

This is also handicapped in `immstruct`, as there are event capturing semantics to consider (cursor event capture/bubbling). See: https://github.com/omniscientjs/immstruct/issues/37

I'm experimenting this externally, and will eventually working towards a PR to revamp observation on cursor references.

**Comment by kuraga** [comment]
@Dashed thanks!

**Comment by steida** [comment]
@kuraga Maybe you are looking for this: https://github.com/steida/este-todomvc/blob/23601e1f9460327bd05b0b90643029900e8fdcf3/src/lib/state.js

**Comment by kuraga** [comment]
Yeah, nice idea! Just wrap it up!

**Comment by steida** [comment]
Take a look at whole Este.js TodoMVC demo. It's full of ideas ;-)

**Comment by kuraga** [comment]
@steida I want (just for fun as an academic aim) make something like https://github.com/Raynos/mercury but with more mainstream libraries (as such as `immutable-js`) :smile:

**Comment by steida** [comment]
Este.js TodoMVC consists of only mainstream libraries. steida/este will be deprecated soon (today I hope).

**Comment by kuraga** [comment]
P.S. The answer was to use cursors. Thanks to everybody!
