### ISSUE TITLE
[Question] Shouldn't seq.filter(() => true) return the same reference?

### ISSUE THREAD

**Issue by abergs** [facebook/immutable-js#358]
Hey,

This is more of a question than an actual issue, I might be getting things backwards.

If I have a snippet like this:

```
var items = Immutable.List([1,2,3]);

var filtered = items.filter(() => true); // filter matches all items, list is unmodified

// this doesn't work
filtered === items // should be true? But it is false

// while this works
Immutable.is(filtered, items) // this is true
```

So - is this a bug or am I missing something very obvious?

**Comment by pluma** [comment]
It's not a bug. It's just a bit confusing.

See #305 for another discussion about this.

**Comment by janmarek** [comment]
This should be easy to implement because filtered collections are equal if their sizes are equal.

**Comment by samwgoldman** [comment]
I think the documentation is confusing this issue by showing reference equality after certain transformations. While reference equality is much faster than value equality calculation by other means, consumers shouldn't depend on it.

In the filter example, providing reference equality after a no-op filter would involve a trade-off that (I suspect) is worse most of the time. Filters are performed lazily, so when you compare `filtered === items`, the filter hasn't actually been "applied."

To figure out if the filter is a noop, the library would need to run the filter eagerly on each element, which would break the laziness/stream-like performance characteristics we currently enjoy.

**Comment by leebyron** [comment]
@samwgoldman is completely correct. Reference equality is a shortcut used in some places but can never replace value equality, which is what you want here. 

This is the case for very similar reasons to why:

var a = []
a.filter(() => true) !== a

**Comment by leebyron** [comment]
I'll keep this open as a note to myself to improve the docs to make this point more clear

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
