### ISSUE TITLE
cursor documentation

### ISSUE THREAD

**Issue by faassen** [facebook/immutable-js#363]
Immutable.js advertises that it has cursor support in its changelog, and I've seen references to it elsewhere like in Omniscient, but documentation for the cursor implementation is difficult to find. Basically it seems to live in a README file only reachable through github and is very minimal:

https://github.com/facebook/immutable-js/tree/master/contrib/cursor

The API documentation doesn't seem to get published anywhere.

I took it from another issue that Cursor support is still experimental (maybe; the issue is a few months old..), though I don't see the documentation saying even that. 

Finally a note about contrib you are free to ignore. I myself am critical about making something live in the limbo of "contrib":

http://blog.startifact.com/posts/against-contrib.html

In this case, if cursor support is indeed still experimental, instead of trying to signal that obscurely by placing the code in "contrib", publish documentation about it in the normal place for Immutable.js and then say it's still experimental there.

**Comment by Dashed** [comment]
The API/code seems pretty easy to read once you grokked the Immutable library (hint: every type pretty much have the same methods): https://github.com/facebook/immutable-js/blob/master/contrib/cursor/index.d.ts

I agree that it's considered "experimental". To elaborate, it's not battle tested. There's consideration for a custom cursor implementation or something that extends Immutable cursors to add usable features: https://github.com/omniscientjs/immstruct/issues/41

**Comment by faassen** [comment]
My point is that its documentation should be part of the public documentation, with an 'experimental' marker on top if it's experimental. That's a lot more clear than putting code in a contrib directory of unclear status and telling people to read the code.

According to the immstruct issue @leebryon isn't interested in maintaining this code. If indeed nobody is willing to maintain it, I'd argue it shouldn't be in Immutable.js in the first place, but in some other package, where someone else can take over maintenance. It being in contrib sounds like the worst place for it to be in; nobody external can take over its maintenance, and it's just going to sit there in limbo status.

I'm only starting to explore immutable.js, and it took me a while to *find* the code; I expected this to be part of the documentation. I looked left and right for documentation on cursors in the Immutable.js docs, but found nothing, even though the changelog makes mention of it.

**Comment by tcoopman** [comment]
> According to the immstruct issue @leebryon isn't interested in maintaining this code.

Is that really the case? It would be nice if @leebyron could confirm this.
If it is really the case, I agree with @faassen and believe that a different package with a different maintainer would be a nice thing to do.

I'm in the middle of exploring cursors for some of my applications and it would be nice to know what's the official status is.

**Comment by confiks** [comment]
From the changelog of [v3](https://github.com/facebook/immutable-js/wiki/Upgrading-to-Immutable-v3#cursors-in-contrib):

> Cursors are no longer part of the core Immutable library, however the existing implementation lives on as the first addition to the contrib/ directory. (...) The included Cursor implementation does not deserve first-class treatment. I hope to see this open up development of other state-management APIs. The included implementation of Cursor has no internal dependencies, illustrating how you can extend Immutable in your own libraries.

So @leebyron hasn't said that he won't maintain Cursors anymore (as he has maintained them until now), but rather that the community could take more initiative to shape the future for it, as the library is really only a 250-line wrapper.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Closing this aging issue
