### ISSUE TITLE
Record documentation

### ISSUE THREAD

**Issue by faassen** [facebook/immutable-js#366]
The Record documentation in the API docs is rather incomplete. I had to look at the source to find out that Record has a "merge", which is very handy if you are extending record with other immutable methods -- I had implemented a "clone" method to do that before I realized merge was actually available.

**Comment by steida** [comment]
+1

**Comment by AlgoTrader** [comment]
+1

Records are of great use, but the doc is incomplete. The records are convertible to maps using Immutable.Map(record) and then I have a rich world of full-featured interface.

**Comment by BurntCaramel** [comment]
Yes, Record has some advantages over Map, but then appears to have barely any methods.

**Comment by mockdeep** [comment]
Same here. I went digging around in the source and discovered that it inherited a lot from `Map`.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by iansinnott** [comment]
Any update on this? The Record docs still seem to be a bit lacking

**Comment by leebyron** [comment]
Note to anyone who would like to attempt this PR - most of the documentation for Record has already been written, however the documentation generator chokes on the Record definition.

The bulk of the PR to solve this issue will be in the documentation generator codebase in `pages/`

**Comment by alexandrebodin** [comment]
Hi @leebyron 

I just tweacked arround a little and made a simple modification to the type def that brings the Instance type definition to the doc. 

Have a look and let me know what you thing #1229

**Comment by leebyron** [comment]
Thanks for the help!
