### ISSUE TITLE
Unenumerable in Map#toObject and Map#toJSON

### ISSUE THREAD

**Issue by quangbuule** [facebook/immutable-js#372]
How do I return unenumerable from Map#toObject and Map#toJSON

```js
var foo = new Map({
  bar: true,
  qux: true
});

var obj = foo.toObject();

console.log(obj);
```

It would output:
```
{ bar: true, qux: true }
```

When I want the `bar` property not to be enumerable, I want the output to be:
```
{ qux: true }
```

But the `obj.bar` still exist. Like when I implement:
```js
var obj = new Object;

Object.defineProperty(obj, 'bar', {
  value: true,
  enumerable: false
});

Object.defineProperty(obj, 'qux', {
  value: true,
  enumerable: true
});

console.log(obj);
```

So, How can I implement this?

**Comment by leebyron** [comment]
Unfortunately this is not possible using this library. You may be better off using Object.freeze() and Object.seal() on a JS object with properties configured as needed.

This library's immutable Map collection is not analogous to JS Object, but to ES6 Map. As such, it doesn't have a concept of properties (nor property enumerability) but instead has a concept of key->value entries, where keys can be of any type (whereas property names must be strings). The toObject() and toJSON() methods exist as a convenience only, they can be lossy and do not work on all Maps.

In the case that you want to use Immutable Map, but want to ensure some entries are not iterated over as a way of emulating enumerability, you can use `filter` to exclude the keys you don't want to be included in the iteration. A good example of this case is highlighted in the wiki: https://github.com/facebook/immutable-js/wiki/Predicates#pick--omit

The code you might use for toObject could then look like:

```js
myMap.filter(myOmitFunction).toObject();
```

However you will later need to define the non-enumerable properties.
