### ISSUE TITLE
immutable 3.6.3 release is broken on npm

### ISSUE THREAD

**Issue by urish** [facebook/immutable-js#374]
the `dist` folder is missing, which renders the release unusable

**Comment by shakyShane** [comment]
Yep - broken for `3.6.3`, working correctly on `3.6.2`

**Comment by volak** [comment]
:+1:

**Comment by leebyron** [comment]
Arrghh. Thanks for flagging it.

**Comment by leebyron** [comment]
v3.6.4 is released now which is not broken. Thanks for stickin' with me.
