### ISSUE TITLE
Record can clobber prototype methods

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#377]
Immutable's common operations like `Immutable.is()` and prototype methods make assumptions about their input having prototypes of a certain form. This is potentially problematic in some edge and corner cases.

If an individual Immutable collection has an altered prototype, the behavior could change.

If a Record introduces a prop key with the same name as a prototype method/prop, the behavior could change.

**Comment by ellbee** [comment]
Your approach of not assigning property descriptors when the key is in the prototype chain does seem better than an invariant. I guess people will still be able to add things directly to the prototype chain or introduce a clashing method name when subclassing Record but that is also true of my invariant approach. Your point that people may deliberately want to clobber the prototype was a good one, I have to admit that hadn't occurred to me. Maybe public properties that are also used internally like size could be a getter pointing to an internal property like _size that the internals use? That way it doesn't really matter if it gets clobbered (obvious drawback is that it won't work for IE8).

In the meantime, how worried are we about size, Record types and Immutable.is()? As it stands Immutable.is() will likely give the wrong answer when size is clobbered. Unless the value of size matches the actual size of the collection it will return false.

```
const Shirt = Immutable.Record({
  size: 'XL',
  style: 'stripes',
});

var a = new Shirt({});
var b = new Shirt({size: 'XL', style: 'stripes'});

Immutable.is(a, b); // returns false
``` 

Maybe it is an edge case not to be overly worried about until the next major release? I've spent a bit of time messing around with Records with weird size keys and not found any other problems.

**Comment by zerkms** [comment]
> Either way, this will be a breaking change that will need to go into the next major version bump of immutable.js, and we may also need to include some way to opt out of this behavior in the case that you want to clobber the prototype.

That was my exact first thought as well. After some background thinking I've got into confusion (that may be resolved by someone who knows internals):

If it's impossible to use `Record` with `size` (or any other attribute that is used for internal purposes) - then if someone used it - they already have had their code broken. You literally just cannot run it.

So, why this change is a "breaking" one then?

**Comment by leebyron** [comment]
@zerkms certainly the code is not un-runnable, there just may be dangerous caveats. For example, Immutable collections have a method called "map". If you define

```js
var WorldMap = Immutable.Record({
  map: "flat"
});
var flatMap = WorldMap();
console.log(flatMap.map);
```

This works today and will log the string "flat". However, if the change I proposed earlier was added, then this code will behave differently and log "[Function]". That's why it's breaking.

However, now that I've thought about it a bit more, I'm not sure just not adding the property descriptors is a good idea because it will defy the expectations of the developer. Certainly in your example of Shirt, you would expect `myShirt.size` to be "XL" and not "2". It would be especially weird for `myShirt.size` and `myShirt.get("size")` to not be the same value.

I think what's more important is ensuring that internals cannot be squashed which can cause some issues, as pointed out by the task that spawned this one. I'm not 100% sure what the right strategy is there quite yet, but surely it can be solved. I'll think about it more.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by lincolndbryant** [comment]
I lost an hour or two try to use `size` as a Record attribute today, which results in the error the error `Cannot set on an immutable record.` when constructing an instance.  Its not possibly to successfully use size.  While it seems stupid/obvious now, its seems like a pretty common attribute name.

How about throwing a warning if someone passes a reserved prop in when invoking/extending Record rather than waiting until an instance is constructed?

I suppose I'll change my backend schema to a different attribute name because thats still an option now, but not always possible.  Is there a clean way to do attribute aliasing/translation with Records, as in `Backbone.Model.parse/toJSON`?

**Comment by robin-ambachtsheer** [comment]
I have the exact same problem. Wanted to use size as an attribute name on a Record but got the error `Cannot set on an immutable record.`. Would love to see a solution without having to rename attributes at the source.

**Comment by mesteche** [comment]
Couldn't ES6 Symbols be used to name the properties that are specific to immutable (like the size property).
I know it would probably require a lot of work but it would guaranty that there is no collision.

**Comment by leebyron** [comment]
Fixed in master - now throws clear Errors instead of mysteriously breaking.

Unfortunately no, symbols can't be used because they're public API methods and accessors.
