### ISSUE TITLE
Custom Chai assertions for Immutable

### ISSUE THREAD

**Issue by astorije** [facebook/immutable-js#378]
[I mentioned some time ago](https://github.com/facebook/immutable-js/issues/225#issuecomment-69242344) that I wanted to centralize some Chai assertions for Immutable, to make test writing more natural.

As opposed to what I was mentioning, I didn't end up writing code here directly, but [came up with a separate Chai plugin](https://github.com/astorije/chai-immutable), because I think it makes more sense. Although I do my best to keep it clean and fully tested/covered, It is highly unstable for now, but [I just sent a PR on the Chai doc repo](https://github.com/chaijs/chai-docs/pull/79) so that it appears on the [plugin page](http://chaijs.com/plugins).

I have 3 questions here:

1. Right now I only provide 3 assertions. Do you have any preference over the semantics and wording of the current ones? I am completely willing to change them to match your expectations.

2. I have plans for a few others assertions, but I will quickly run out of ideas as I am myself using only a small subset of the Immutable data structures you provide. Do you have any requirements/requests you'd like me to implement?

3. Do you think there could be a link to this plugin (either the GitHub page or the Chai plugin page) to guide people willing to test their code involving Immutable? If you allow me to, I'd love to send a PR to add a section in the README, maybe after "Documentation", or wherever you see it fit.

**Comment by leebyron** [comment]
This looks great! Thanks for building this. For basic use, what you have made is valuable. If you're looking to expand the API, I would suggest looking at the whole chai API for objects and arrays and writing similar assertions for Immutable collections. The has/includes are certainly valuable assertion methods as well. 

Nice work!

**Comment by astorije** [comment]
Hi @leebyron, thanks for your support, that's appreciated! I'll try to keep it in shape to match your library's quality :-)

Good advice regarding `contains`/`includes` (`has` is just a noop keyword though) and I am planning to add [support for value retrieval](https://github.com/astorije/chai-immutable/issues/9) too. That'd be great if you can give your 2 cents on the latter thread by the way.

If you tell me the API (aka, the wording/grammar for the assertions, always better to have this approved by a native speaker!) is what you'd expect, then I'dd like to go to version 1.0.0 whenever I add a new feature.

Finally, what do you think about a link in the README (item 3)?

Thanks!

**Comment by astorije** [comment]
@leebyron, do you mind taking a look at my previous comment? I'd be happy to release my plugin in version 1.0.0 if you agree with the current API.

Thanks a lot in advance!!

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by astorije** [comment]
Oops, forgot to link back here: related PR is #549

**Comment by astorije** [comment]
This was added to README some time ago, closing.
