### ISSUE TITLE
Record's toString format has artefacts

### ISSUE THREAD

**Issue by AlgoTrader** [facebook/immutable-js#383]
```
record.toString()
" { a: 1, b: 2 }"
```
There is a first space character. toString is useful only for inspection, it is not a valid JSON as it has no quotes for keys and strange spaces

I certailnly want record.toJS(), I want to switch to the old JS world when I need

**Comment by AlgoTrader** [comment]
Got it. When name is empty, the output is space prefixed

**Comment by leebyron** [comment]
Thanks for finding this, it is a bug. When the name is empty, it should default to "Record"

**Comment by ellbee** [comment]
Hi @AlgoTrader, I am not able to get record.toString() to fail in the way you are seeing. When name is empty I get Record, and I also get quotes around the keys. 

```javascript
> var Test = Immutable.Record({a: 1, b: 2});
> Test().toString();
'Record { "a": 1, "b": 2 }'

> var Test2 = Immutable.Record({a: 1, b: 2}, 'Test2');
> Test2().toString();
'Test2 { "a": 1, "b": 2 }'

> var Test3 = Immutable.Record({a: 1, b: 2}, '');
> Test3().toString();
'Record { "a": 1, "b": 2 }'
```

Am I missing any steps to reproduce this?
