### ISSUE TITLE
Records and methods

### ISSUE THREAD

**Issue by AlgoTrader** [facebook/immutable-js#384]
It seems, Records are of great interest and it is one of killer features of Immutable.js. I start to use it, but unfortunately ES6 is not yet there for extending Records with methods and ES5 inheritance is pain.

For now, I "embed" methods into Records like this:

```
var Complex = Immutable.Record({real:0, image:0, magnitude:function() { return Math.sqrt(this.real*this.real+this.image*this.image);}});

var num = new Complex({real:1, image:2})

num.magnitude()
2.23606797749979
```

In reality, there is for example isNull method that shows the record has no real value. It would be useful to allow prototype extending in Record constructor, not sure it is acceptable for functional programming purists though.

I also heavily support the idea of making Records efficient (https://github.com/facebook/immutable-js/issues/286). Records can be lightweight structures, they are often used for small "value" types and they never change keys

**Comment by kentor** [comment]
I do this for adding methods to record instances:

```javascript
var Person = Immutable.Record({ name: '' });
Person.prototype.sayHi = function() {
  return this.name;
});
```

**Comment by copy** [comment]
For now, you can also get an efficient structure and methods by defining your own objects with `equals` and `hashCode` like so:

```javascript
function Complex(p)
{
    this.real = p.real;
    this.image = p.image;
}

Complex.prototype.equals = function(other)
{
    return this.real === other.real && this.image === other.image;
};

Complex.prototype.hashCode = function()
{
    return util.hash_int32array([
        this.real,
        this.image,
    ]);
};

Complex.prototype.magnitude = function()
{
    return Math.sqrt(this.real*this.real + this.image*this.image);
};
```

**Comment by leebyron** [comment]
@copy, I'm glad you've caught onto this pattern! I haven't documented it anywhere yet, but in the next major version, I will document this as a way to define "value" objects that work in the Immutable.js ecosystem (eg, can be used as keys, and are considered values by Immutable.is())

**Comment by leebyron** [comment]
Methods can be added to Record classes as @kentor describes. Simply add methods to the prototype. It is probably not a good idea to add them as values in the Record.

Some ES6 transpilers support extending expressions, in which case you can write:

class Complex extends Record({real:1, image:1}) {
  magnitude() { return ...; }
}

For the transpilers that don't support subclassing an expression, but support an identifier, you can write:

var _Complex = Record({...})
class Complex extends _Complex {
...
}

I personally prefer just adding methods to the prototype.

**Comment by mschipperheyn** [comment]
So, we can add hashCode and equals like @copy describes using the way @kentor describes? This would basically work using an immutable Set to guarantee unique Record based object in the Set?

**Comment by turnerhayes** [comment]
Can we return altered versions of records from Record methods? I have the following:

    class MyRecord extends Record({...}) {
        updateIssues = (issues) => this.mergeDeepIn(["items"], Map(issues.map(issue => [issue.id, issue])));
    }

as a method of a Record class, and when I call it, I get back something that the debugger claims is an instance of MyRecord, but there is no `updateIssues()` method on it anymore.

**Comment by semireg** [comment]
@turnerhayes 

I found that declaring methods as properties like that, it works OK within the same file. But the methods do not appear when accessed outside this file.

I had luck rewriting as actual methods:
```
class MyRecord extends Record({...}) {
    updateIssues(issues) {
        return this.mergeDeepIn(["items"], Map(issues.map(issue => [issue.id, issue])));
    }
}
```
