### ISSUE TITLE
Records and nested structures

### ISSUE THREAD

**Issue by AlgoTrader** [facebook/immutable-js#385]
I tried Records nesting and results are really embarrassing. It seems. Record structures are now limited to be flat (or contain Map/List/etc), no Record nesting is allowed in any way. Record nesting is very desired. For example

```
var Location = Record({code: ..., timezone:..., name:...});
var Flight = Record({origin: Location, destination: Location, ...})
```

This is in fact related to https://github.com/facebook/immutable-js/issues/334, extending records. Extending is simple case, the composition of complex types is more complex.

We can do following, If a record's key is another Record, then instantiate that Record and put it there. Now we put it's constructor function instead:

```
var Rec = Immutable.Record({id:123, subrecord:Immutable.Record({name:'John', lastname:'Smith'})})
var rec = new Rec()

rec.id
123

rec.subrecord
function (t){return this instanceof r?void(this._map=Mn(t)):new r(t)} 
```

That's nonsense! It seems, nesting Records should be easy enough.

PS Sorry for spamming lots of issues about Record feature, I just want them to be really useful. Maybe, I have a chance to try improve them?

**Comment by AlgoTrader** [comment]
Well, I have found a way to nest Records

```
var Rec = Immutable.Record({id:123, subrecord:new (Immutable.Record({name:'John', lastname:'Smith'}))})
var rec = new Rec()

rec.subrecord.toString()
" { name: "John", lastname: "Smith" }"
```

even setIn works ok.  As record is immutable, instantiating records with single subrecord is legal.

I would suggest syntax sugar to allow put record constructor instead of record instance.

**Comment by AlgoTrader** [comment]
Another experiment

```
var Rec = Immutable.Record({id:123, subrecord:new (Immutable.Record({name:'John', lastname:'Smith'}))})
var rec = new Rec({subrecord: {name:'James', lastname:'Bond'}})

rec.subrecord
Object {name: "James", lastname: "Bond"}
```

The problem is constructor replaced record with plain object. The proper behavior was to instantiate another Record and put it to subrecord. 

Default record can be asked for constructor, then the constructor is to be called with proper init data.

**Comment by leebyron** [comment]
Records definitely support nesting today, the full set of nested get/set methods exist on Record instances. 

The initial object provided to the Record class factory are the default values, so if you want an empty version of the sub-record as a default value, you must supply it there. You want to supply instances as default values and not record classes.

**Comment by leebyron** [comment]
What I believe you're referring to here is a way to parse a nested JS object into nested Records. The Record constructors will not do this for you, as it is equally valid to provide a regular JS object as a key. Instead, you should use Immutable.fromJS() with a custom reviver function which is written in a way that relates to your data schema.

**Comment by ericwooley** [comment]
I know this issue is closed, but I was hoping to get your opinion on a solution like this

```es6
import Immutable from 'immutable'

let NestedRecord = Immutable.Record({
  foo: 'bar'
})

class MetaData extends Immutable.Record({
  meta: 'data',
}){
  constructor(){
    super()
    this.map = {
      NestedRecord: NestedRecord
    }
  }
}

class LiveEvent extends Immutable.Record({
  id: null
}) {
  constructor(){
    super()
    this.map = {
      MetaData: MetaData
    }
  }
}


function using(type){
  var t = new type();
  return (key, value) => {
    if(type.map[key])
      t.set(key, using(type.map[key])(value))
    else
      t.set(key, value)
  }
}


Immutable.fromJS({
  id: 1,
  MetaData: {
    meta: 'some other data',
    NestedRecord: {
      foo: 'baz'
    }
  }
}, using(LiveEvent))
```
I am trying to find a good way to do this on a large scale project, and was hoping you could tell me if you see any obvious flaws with this approach.

**Comment by leebyron** [comment]
I'm not sure I follow how it even works if you override the constructor and have it not accepting any values.

But FYI - I'm working on Record sub-type declarations as part of v4.0.0 in the branch of the same name. See https://github.com/facebook/immutable-js/commit/35c2af0fe5bb8c879c7beba09025966518d68995

**Comment by chrishoage** [comment]
@leebyron That 4.0 branch looks very neat. Excited to try it out when ever it releases. In your mind what would be "best practice" to achieve a similar result with the current version of Immutable? 

Right now I have the following, but am not sure if it is the best way to go about it: 

````javascript 
const LiveEventData = Immutable.Record({
  title: '',
  description: null
})

const RandomizerEventData = Immutable.Record({
  query: '',
  display: null,
  categories: Immutable.List()
})

const VideoEventData = Immutable.Record({
  title: '',
  description: null,
  assetId: null,
  previewURL: null,
  thumbnailURL: null,
  display: null,
  categories: Immutable.Seq()
  status: null
})

const EventRecord = Immutable.Record({
  eventId: null,
  scheduleId: null,
  type: null,
  duration: 0,
  start: (new Date()).toISOString(),
  metadata: null
})

function EventRecordFactory (type, scheduleId, start, duration, metadata) {
  const typeMap = {
    "VIDEO": VideoEventData,
    "LIVE": LiveEventData,
    "RANDOM": RandomizerEventData
  }
  const MetaType = typeMap[type]
  let createdEvent = new EventRecord({
    scheduleId, type, start, duration
    metadata: new MetaType(metadata)
  })

  return createdEvent
}

let liveEvent = EventRecordFactory('LIVE', 1, 'TIMESTAMP', 200, {title: 'foo'})
````

Thank you for you time!

**Comment by leebyron** [comment]
So definitions of Records just set up default values. I know some people also define custom factory functions to go along-side them like you've done with EventRecordFactory. That may be useful as well for something like your `EventRecord` which sets a default "start" time to be when you defined the record - so all event records will have the same default start time, that's probably not what you want.

Having those factory functions are nice because you can define whatever behavior you like in them, including calling other factory functions to produce the kind of nested records originally brought up in this thread.

See this super contrived example of nested records with factory functions.

```js
var _RecordA = Immutable.Record({
  b: null // RecordB or null.
});

function RecordA(obj) {
  return new _RecordA({ b: obj.b ? RecordB(obj.b) : null });
}

var _RecordB = Immutable.Record({
  a: null // RecordA or null.
});

function RecordB(obj) {
  return new _RecordB({ a: obj.a ? RecordA(obj.a) : null });
}

var abab = RecordB({ a: { b: { a: { b: null } } } });
console.log(abab.toString());
```

**Comment by AndrewBestbier** [comment]
Super late to the party here, but I also wanted to have Record nesting like @AlgoTrade. The problem, as he said, is 

> 'The problem is constructor replaced record with plain object. The proper behavior was to instantiate another Record and put it to subrecord' 

I'm not sure if this is the optimal way to do it, but the following is my solution:

I wanted to parse the following nested JS object to nested Records:

```
let data = {
  name: 'Andrew',
  email: 'andrew@gmail.com',
  car: {
    type: 'Ford',
    cost: 10,
    usageDetails: {
      distanceTravelled: 0,
      averageMileage: 0
    }
  }
}
```

Step 1 is to define the structure of your nested records as follows. Note how UsageDetails is at the top (most deeply nested) and User at the bottom. If this is not done, the console will tell you that the Record does not exist.

```
var UsageDetails = Record({
  distanceTravelled: 0,
  averageMileage: 0
});

var Car = Record({
  type: '',
  cost: 10,
  usageDetails: new UsageDetails()
});

var User = Record({
  name: '',
  email: '',
  car: new Car()
});
```

It works fully when you haven't passed through data:
```
let user = new User();
user.get('car').get('cost'); //10 the default value
```

However if you pass through the data you get the following:
```
let user = new User(data);
user.get('car').get('cost'); //user.get(...).get is not a function
user.get('car').cost; //40, the nested Records are now normal objects, This passed value of 40 is accessed through dot notation.
```

So then following the advice of @leebyron:   

> Instead, you should use Immutable.fromJS() with a custom reviver function

I found this solution:

```
Record.constructor.prototype.fromJS = function(values) {
  var nested = fromJS(values, function(key, value){
    //See https://facebook.github.io/immutable-js/docs/#/fromJS for docs on custom reviver functions
    if(this.prototype[key] && this.prototype[key].constructor.prototype instanceof Record){
      return this.prototype[key].constructor.fromJS(value.toJS()); //use toJS() here if nest more than once
    }
    else {
      return value;
    }
  }.bind(this));
  return this(nested);
};
```

You can then call:

```
let user = new User();
user.get('car').get('cost'); //The default value of 10 works as normal

//This now works
User.fromJS(raw).get('car').get('cost'); //40. Note our new function: {Model}.fromJS()
```

**Comment by benneq** [comment]
Just wanted to share what I'm doing using TypeScript:

1. Create a single .ts file per Immutable Class
2. Only export the TypeScript class. Keep the Immutable Record secret
3. Every class is responsible for creating / mapping it's values
(4. Nested objects/lists will get created by their own class)

```
contact.js:
import { Record } from 'immutable';
import { Address } from './address';

let InternalRecord = Record({
    name: "",
    address: null
});

export class Contact extends InternalRecord {
    name:string;
    address:Address;

    constructor(args:any = {}) {
        super(Object.assign({}, args, {
            address: args.address && new Address(args.address)
        }));
    }
}
```

The same works for `List`:
```
export class ContactList extends InternalRecord {
    content:List<Contact>;

    constructor(args:any = {}) {
        super(Object.assign({}, args, {
            content: List(args.content && args.content.map(val => new Contact(val)))
        }));
    }
}
```

Hope this might help someone 😃

**Comment by poyannabati** [comment]
Yet another alternative, 

```
class SubModel extends Immutable.Record({}) {}

class Model extends Immutable.Record({name: null, subModels: new SubModel()}) {
  constructor(values) {
    const record = super(values);
    return record.set('subModels', record
      .subModels
      .map(subModel => new SubModel(subModel)
      )
    );
  }
  
}
```

**Comment by micimize** [comment]
Thought I'd add my approach for deep record in typescript in case anyone finds it useful:
```typescript
function shouldBeRecord(value): boolean {
  return (typeof value === 'object') &&
    !Array.isArray(value) &&
    !Record.isRecord(value)
}

function DeepRecord<T extends {}>(raw: T): Record.Factory<T> {
  for (let key in raw){
    let value = raw[key]
    if(shouldBeRecord(value)){
      raw[key] = DeepRecord(value)()
    }
  }
  return Record(raw)
}

// usage example
const Configuration = DeepRecord({ /*... nested object literals ...*/ })()

// user can configure the system with a deep partial
type DeepPartial<T> = {
  [P in keyof T]?: DeepPartial<T[P]>
}
let partial: DeepPartial<typeof Configuration> = { foo: {bar: 'biz'} }
configure(Configuration.mergeDeep(partial as Configuration))
```
I found it important to return a `Record.Factory` from `DeepRecord`, and to avoid `return class DeepRecord extends Record(defaults) {}` from inside of `DeepRecord` because otherwise the record's type is mangled.

**Comment by Zzortell** [comment]
My need was to recover Immutable Record and List nested structures saved in raw data or json.
You can use it to generate new data too.
Here is my approach:

```js
/*
 * Reviver to pass to JSON.parse
 */
export function JSONreviver(key, value) {
  if (Array.isArray(value)) {
    return List(value);
  }
  if (value !== undefined && value !== null && value.constructor === Object) {
    return new (Record(value));
  }
  return value;
}

/*
 * Reviver to pass to Immutable.fromJS
 */
export function reviver(key, value) {
  return isKeyed(value) ? Record(value.toObject()) : value;
}
```
