### ISSUE TITLE
Get first key from OrderedMap

### ISSUE THREAD

**Issue by Daniel15** [facebook/immutable-js#389]
The `.first()` method returns the first *value* in an OrderedMap. How do I get the first *key*?

**Comment by hufeng** [comment]
```javascript

var Immutable = require('immutable');

var m = Immutable.OrderredMap({a:1, b:1});

//get first key
m.keySeq().first(); //a

```

**Comment by leebyron** [comment]
@hufeng is correct. Get the key sequence and pull the first item from it. 

In a future major version update, I will likely change this API to return an entry tuple instead of a value, which adheres to Map's iteration behavior.

**Comment by justincui** [comment]
still not changed?

**Comment by haxxxton** [comment]
Would be great to get `firstKey` and `lastKey` options in the API, or have `first` and `last` return an entry tuple as discussed above :)
