### ISSUE TITLE
how to reset a Map?

### ISSUE THREAD

**Issue by hufeng** [facebook/immutable-js#393]
Dear all, 

```javascript

var m = Immutable.fromJS({
   form: {
    username: 'test',
    email: 'test@test.com',
    address: {
      country: 'xx',
      city: '**'
    }
   }
});

how to reset m as:

var m = Immutable.fromJS({
   form: {
    username: '',
    email: '',
    address: {
      country: '',
      city: ''
    }
   }
});

```

//a little boring
m.set('username', '')
m.set('email', '')
....

**Comment by kentor** [comment]
Keep the empty map around and reassign variables to that empty map when you want to "reset".

**Comment by hufeng** [comment]
@kentor  3ks

**Comment by leebyron** [comment]
Agreed. You should keep a reference to the "resetted" collection. Because Immutable.js collections are treated as values, you can simply reuse this important initial collection to represent the "reset", similarly to how you would "reset" a String or a Number back to some initial value.

**Comment by hufeng** [comment]
@leebyron thank you very much.  Immutable is really awesome.
