### ISSUE TITLE
Filtered sequence + take + react 0.13 hangs

### ISSUE THREAD

**Issue by kentor** [facebook/immutable-js#394]
Wasn't sure if I should file this here or at the react project.

Very bizarre, this code crashes in latest Chrome and Firefox for me:

```javascript
var data = Immutable.List([1])
  .toSeq()
  .filter(_ => true)
  .take(1)

React.createElement('div', null, data);
```

Using react 0.13 and immutable-js 3.6.4

JSBin: http://jsbin.com/qoyimuneqo/2/edit?html,js,output (might crash tab, firefox handles it better for me)

Taking out the line with `filter` or the `take` will work as usual.

edit: removed 6to5/jsx dependency

**Comment by kentor** [comment]
From my debugging, it gets stuck in the while loop.

```javascript
  } else if (node) {
    var iteratorFn = getIteratorFn(node);
    // Entry iterators provide implicit keys.
    if (iteratorFn) {
      if (iteratorFn !== node.entries) {
        var iterator = iteratorFn.call(node);
        var step;
        while (!(step = iterator.next()).done) {
          if (ReactElement.isValidElement(step.value)) {
            validateExplicitKey(step.value, parentType);
          }
        }
      }
    } else if (typeof node === 'object') {
```

**Comment by leebyron** [comment]
Thanks for the report! I'll dig into this
