### ISSUE TITLE
Can I work around toJS returning new objects every time?

### ISSUE THREAD

**Issue by gambit3** [facebook/immutable-js#395]
When using toJS() to convert Immutables back to plain JS objects their internal references are lost even it the object did not in fact change.
From what I understand they are reused internally but toJS() works differently (by creating new objects every time).

    a = Immutable.fromJS({x:{y:1}});
    a.toJS().x === a.toJS().x;
    false
    a.get('x') === a.get('x');
    true
    
I have an 3 party lib that can only use plain JS objects as arguments and checks shallowly (by ref) if the passed in objects/arrays have changed. I was hoping to use Immutable to construct such arguments and having it do the work of keeping the references intact if the values did't change. 
Something like this:

    //in consutructor
    this.propsMap = Immutable.map();

    //in render
    props = {
      latLng: [a[1], b[0]],
      other: 'props' 
      //...
    }
    this.propsMap = this.propsMap.deepMerge(props);

    extrenalLib(this.propsMap.toJS());

    //and having inside external lib 
    props.latLng === this.oldLatLng; //true
    //if 'a' didn't change

But toJS fails in this case. Is there some other way to go about it? Or or do I have to rely on Immutable only informing me if the object did mutate but I have to do the references book keeping myself. 
Like this:

    oldPropsMap = this.propsMap;
    this.propsMap = this.propsMap.deepMerge(props);
    if(this.propsMap !== this.oldPropsMap) {
      this.prevProps = this.propsMap.toJS();
    }
    props = this.prevProps;

    extrenalLib(props);

Which seems a little tedious and maybe overkill for Immutable since I can use something like loDash.isEqual.

**Comment by louisremi** [comment]
I think you need to do the book keeping yourself. Expecting Immutable to return the same plain JS object through `.toJS()` implies that it should keep a reference to every Object returned, which would cause an important memory leak.

**Comment by leebyron** [comment]
Louis is correct that retaining the created JS object produces a memory leak that would be unacceptable for uses other than this proposed use.

Another thing to consider is that the resulting JS object is mutable and may be changed after created, so retaining it to return again would not be safe. 

Imagine, from your first example:

var aObj = a.toJS();
aObj.x = "edit";
console.log(a.toJS());

Either this will log an incorrect result, or it will have to carefully track edits to aObj which would be very expensive, or it will have to always return a new object. 

Your example code at the bottom, the simple memoization, is exactly what I would recommend. It doesn't look overkill to me, it's O(1) at runtime. By comparison, Lodash's isEqual (and Immutable.is) are O(N) at runtime.

**Comment by gambit3** [comment]
Thanks for the reply. I can now clearly see the reasoning here. 

I'm  just staring out my React and Immutable coding and was probably hoping to kind of ease into the immutable part. I thought I could only use it where I can rally see the performance benefits as a helper 'thingy' to maybe avoid some problems mentioned here: [http://noredinktech.tumblr.com/post/107617838018/switching-from-immutable-js-to-seamless-immutable] (like having to use get/set and being very disciplined in naming things to not mix up vanilla vs immutable vars).
I was thinking this would be a premature optimisation to really use it everywhere and wrap the whole way of writing around it.

But now I think it's the whole point: either you go all in or it doesn't really do you any good. Unfortunately it's not a win / win. Fox example I was really hoping to be able to escape from getters and setters for example after moving to react :) . I'm giving it a go regardless and I'll see where it gets me. Maybe it will get too tedious and annoying or maybe I will never be able to go back to the mutable way.

**Comment by tusharmath** [comment]
@leebyron
I think we should be able to do it via setters and getters without worrying about memory leaks see as follows —

```javascript
var Immutable = require('immutable')
var fromJS = Immutable.fromJS

var i = fromJS({a: {b: {c: 1}}})

function wrap (immutable) {
  if (immutable instanceof Immutable.Map === false) {
    return immutable
  }
  var obj = {}
  for (var i of immutable.keys()) {
  Object.defineProperty(obj, i, {
    enumerable: true,
    set: function (value) {
      immutable.set(i, value)
    },
    get: function () {
      return wrap(immutable.get(i))
    }
  })
  }
  return obj
}

var js = wrap(i)


console.log(js.a.b.c) // access them easily like any other JS object

```

**Comment by tusharmath** [comment]
@leebyron Ping!
