### ISSUE TITLE
new Immutable.Map() === new Immutable.Map() // true

### ISSUE THREAD

**Issue by narak** [facebook/immutable-js#396]
I noticed this
```
function emptyMap() {
    return EMPTY_MAP || (EMPTY_MAP = makeMap(0));
}
```

I'm trying to understand the reasoning behind this.
I'm currently having issues where I'm storing meta data on Immutables.
Eg: 
```
var item = new Immutable.Map();
...

if (item.state !== 'LOADING') {
    // metadata 
    item.state = 'LOADING';
}
```

Now, every time ```new Immutable.Map()``` is run it returns the the same object reference. So, all subsequent runs will have ```state === 'LOADING'``` because they point to the same object.
To get around this, I'm having to do the following to force a new object:
```
var item = new Immutable.Map({__new: true});
item = item.delete('__new');
```

This was obviously intentional since there is code explicitly for it and not a bug. But why?

**Comment by danielstreit** [comment]
Note that if `item` is an `Immutable.Map`, `item.state = 'LOADING'` would not mutate `item`, it would have to be something like: 'item = item.set('state', 'LOADING')`

**Comment by leebyron** [comment]
Daniel has the right idea. It is *not safe* to mutate an Immutable collection in the way you have described. Memoization is just one of the reasons for this.

New empty collections are always memoized to save GC churn.

**Comment by leebyron** [comment]
Also, I should note that the use of "new" is a bit misleading. The Immutable.Map function is *not* a class constructor, but a factory function. You can prefix with "new" if it helps your code legibility, however the new'd object is never used and may contribute to GC churn.

**Comment by narak** [comment]
@danielstreit Right. Which is what I'm expecting. I don't want it to mutate, its just some metadata that I need to store on the object until i figure out a better way to store the metadata associated with those items.

**Comment by narak** [comment]
@leebyron I see. Well, I was under the impression that they were classes. I'll fix that.
What's confusing is I expected Immutable.Map() to always return a new object. I'm unable to articulate why it feels wrong, but thanks anyway. I'll figure out a different way of doing this.

**Comment by leebyron** [comment]
For now, the best way to store that metadata is in the map itself. Perhaps prefix with an underscore or something to illustrate it not being part of your application data. A true metadata API will be part of a future major version update to the library which should help this kind of use case.

**Comment by arcanis** [comment]
@leebyron Wouldn't it be both more idiomatic and more efficient to expose base objects as properties instead of through factory calls? Ie `Immutable.map` instead of `Immutable.Map` (which has some linting issues) or `new Immutable.Map()` (which creates an unused object).
