### ISSUE TITLE
Cursor.size not available from cursor.cursor()-created cursors

### ISSUE THREAD

**Issue by wmertens** [facebook/immutable-js#398]
What happens is that when makeCursor is called from subCursor, it will always have 4 arguments and https://github.com/facebook/immutable-js/blob/257b92c6887ae787da9c94fbabe34056014ffc93/contrib/cursor/index.js#L223 doesn't get run and thus size is undefined.

So either the check has to be `if (typeof value === 'undefined')` or the subCursor has to to do call magic.

**Comment by jeroencranendonk-wf** [comment]
See #318

**Comment by wmertens** [comment]
I think you meant #381 :grin:
