### ISSUE TITLE
Sort does not update mutable collections

### ISSUE THREAD

**Issue by joewalnes** [facebook/immutable-js#401]
Example:

``` javascript
Immutable.List().withMutations(l => l.push(3).push(2).push(1).sort());
// Expected: [1, 2, 3]
// Actual  : [3, 2, 1]
```

**Comment by leebyron** [comment]
This is by design, `sort` is unavailable within withMutations.

A future API change will hopefully make this far more clear as it's a very common point of confusion.

**Comment by joewalnes** [comment]
I think throwing a exception would help

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by rhys-vdw** [comment]
I agree with @joewalnes. I think an Error would be helpful.
