### ISSUE TITLE
Feature request: insert()

### ISSUE THREAD

**Issue by joewalnes** [facebook/immutable-js#402]
For convenience: `insert()` would be nice. Basically just a convenience wrapped around `slice()`, similar to `remove()`.

**Comment by leebyron** [comment]
Good suggestion

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
