### ISSUE TITLE
List merge doesn't work with sparse arrays

### ISSUE THREAD

**Issue by iwehrman** [facebook/immutable-js#403]
```
a = Immutable.List.of("w", "x", "y", "z");
b = [];
b[1] = "i";
b[3] = "j";
console.log(a.merge(b).toArray());
> [ undefined, "i", undefined, "j" ]
```

CC @mcilroyc

**Comment by hleumas** [comment]
@iwehrman what do you expect as behavior?

**Comment by iwehrman** [comment]
Call me crazy, but:
```javascript
[ "w", "i", "y", "j" ]
```
Or is there some other, preferred way to sparsely update a list?

**Comment by tgriesser** [comment]
Probably just using `.set`

```js
console.log(Immutable.List.of("w", "x", "y", "z").set(1, "i").set(3, "j").toArray())
// [ "w", "i", "y", "j" ]
```

Or you could define custom merge behavior using `mergeWith`

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by crossman** [comment]
For what it's worth I just ran into the same thing and expected the behavior that @iwehrman did (except with a deep array). Should a list really be treated as an opaque value if Immutable is supposed to be all about handling collections?

**Comment by alexmcmillan** [comment]
+1 Any news on this?

**Comment by leebyron** [comment]
Closing this aging issue - Immutable.js doesn't support holey Arrays (Note the ECMAScript board is trying to phase out holey Arrays as well as they're a constant source of confusion)

**Comment by json2d** [comment]
+1 challenges aside, support for holey Arrays somehow would make `merge` and `mergeDeep` more consistent in how it treats Objects and Arrays.

You could achieve similar behavior with `mergeWith` and `mergeDeepWith`:

```js
const { merge, mergeWith } = require('immutable')
const original = { foo: [ "w", "x", "y", "z" ] }
const other = { foo: [ undefined, "i", undefined, "j" ]

mergeWith(
  (oldVal, newVal) => {
    if(isHoleyArray(newVal)) {
      return oldVal.map((el,i) => isHole(newVal[i]) ? el : newVal[i]) // desired "merging" behavior
    }else{
      return merge(oldVal, newVal) // current "appending" behavior
    }
  },
  original,
  other
) // { foo: [ "w", "i", "y", "j" ] }
```

Of course you'll need to specify your own `isHoleyArray` and `isHole` predicate functions here.
