### ISSUE TITLE
set.union() fails inside withMutations

### ISSUE THREAD

**Issue by AsaAyers** [facebook/immutable-js#405]
you can check this in a console

    > Immutable.Set().withMutations(function(set) {
        set.union([ 'a' ]);
        set.add('b');
    }).toString()
    "Set { "b" }"

it works outside of a `withMutations` though.

    > Immutable.Set().union(['a']).toString()
    "Set { "a" }"

**Comment by leebyron** [comment]
Thanks for the report!
