### ISSUE TITLE
mergeDeep clobbers List items; concatDeep isn't implemented

### ISSUE THREAD

**Issue by appsforartists** [facebook/immutable-js#406]
`merge` appears to operate by key, which means merging two Lists together clobbers values (rather than appending them):

``` javascript
Immutable.List([1, 2, 3]).merge(Immutable.List([4, 5])).toJSON()
// [4, 5, 3]
```

`concat` doesn't have this problem; however, there's no `concatDeep`.

@leebyron, how do you feel about adding `concatAll`?  It would be a nondestructive union of any Immutable iterables, like so:

``` javascript
Immutable.fromJS(
  {
    "a":  [
            1
          ],
    "b":  {
            "fruits": [
                        "banana",
                      ],

            "place": "ireland",
          }
  }
).concatDeep(
  Immutable.fromJS(
    {
      "a":  [
              3
            ],
      "b":  {
              "fruits": [
                          "apple",
                        ],

              "author": "seuss",
            }
    }
  )
).toJSON()

// {
//   "a":  [
//           1,
//           3
//         ],
//   "b":  {
//           "fruits": [
//                      "banana",
//                      "apple",
//                     ],
// 
//           "place":  "ireland",
//           "author": "seuss",
//         }
// }
```

**Comment by tgriesser** [comment]
This can currently be accomplished with a custom `mergeWith`:

```js
var isList = Immutable.List.isList
var fromJS = Immutable.fromJS

function merger(a, b) {
  if (isList(a) && isList(b)) {
    return a.concat(b)
  }
  if (a && a.mergeWith) {
    return a.mergeWith(merger, b)
  }
  return b
}

fromJS({
  "a": [1],
  "b": {
    "fruits": ["banana"],
    "place": "ireland"
  }
}).mergeWith(merger, fromJS({
  "a": [3],
  "b": {
    "fruits": ["apple"],
    "author": "seuss"
  }
})).toJSON()
```

produces:

```js
// {
//   "a": [
//     1,
//     3
//   ],
//   "b": {
//     "fruits": [
//       "banana",
//       "apple"
//     ],
//     "place": "ireland",
//     "author": "seuss"
//   }
// }
```

**Comment by leebyron** [comment]
The root of this issue is what merge does on Lists, right @appsforartists? You expected merge to be the same as concat? I'm just trying to unpack the concerns listed here, I'm sure there's some API evolution we can do to make these ops easier to discover and viscerally understand.

**Comment by appsforartists** [comment]
I think you've got it, @leebyron!

**Comment by grabbou** [comment]
Yeah, same thing here. When merging two Maps that have a List on a nested property, the second List overwrites the first one completely instead of the values being merged as well. 

So, the following:
```
{todos: {list: [1, 2, 3]}} 
{todos: {list: [3, 4, 5]}}
// gives
{todos: {list: [3, 4, 5]}}
```

**Comment by gabrielecirulli** [comment]
I also definitely would love to see something to perform a deep concat!

**Comment by leebyron** [comment]
merging by index isn't really useful behavior anyway, I think it should work as you propose @appsforartists but this will be a breaking change and need to wait for a version bump.

**Comment by AppShipIt** [comment]
Ping for next major version!

**Comment by stephencelis** [comment]
Rather than add `concatDeep`, I think the functional expectation is that `concat` should be called deeply by default (monoids of monoids and all that).

One typical example is [the Validation type](https://github.com/folktale/data.validation):

``` js
Failure(
  Immutable.Map({
    username: Immutable.List.of("required")
  })
).concat(Failure(
  Immutable.Map({
    password: Immutable.List.of("is too short")
  })
)).concat(Failure(
  Immutable.Map({
    password: Immutable.List.of("must contain a special character")
  })
))

// expected:
Failure(
  Immutable.Map({
    username: Immutable.List(["required"]),
    password: Immutable.List(["is too short", "must contain a special character"])
  })
)

// actual:
Failure(
  Immutable.Map({
    username: Immutable.List(["required"]),
    password: Immutable.List(["must contain a special character"])
  })
)
```

``` diff
-    password: Immutable.List(["is too short", "must contain a special character"])
+    password: Immutable.List(["must contain a special character"])
```

**Comment by renanbandeira** [comment]
I've just faced an issue related to this fix. I have some merge calls on my code that merges maps with lists inside (those maps came from a normalisation using normalizr). The issue I face now is that everytime I merge, it duplicates the references for the other objects. I tried to change my `reviver` function on `fromJS` calls to transform those lists on `Set`, but I had another issue: `Set`doesn't contain `pop()` or `push()` .

What do you guys suggest for this? Maybe a new Collection?
