### ISSUE TITLE
Setting value pointing to sub-records should update with sub-record

### ISSUE THREAD

**Issue by Gozala** [facebook/immutable-js#408]
Here is an illustration of the issue:

``` js
var Field = Immutable.Record({
  value: '', isFocused: false
})

var Login = Immutable.Record({
  user: Field(),
  password: Field()
})

JSON.stringify(Login({
  user: {value: "gozala"}
})) // => {"user":{"value":"gozala"},"password":{"value":"","isFocused":false}}
```

I expected that `.user` will be instance of `Field` and there for it would have `isFocused: false`.

In fact this is a more general issues that make it difficult to serialise / parse non flat records.

**Comment by Gozala** [comment]
I imagine this should be easy enough to do, records `set` would just need to invoke present / default values constructor with a passed input. Although I have not looked at the implementation so it may turn out to be more difficult than this.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by alexandrebodin** [comment]
Hi @Gozala 

I believe what you are asking would be a really big change in the library as it would imply checking nested values recursively and diffing with the current one.

I honestly believe you can do some fine job with factories like so:

```js
var Field = Immutable.Record({
  value: '', isFocused: false
})

var Login = Immutable.Record({
  user: Field(),
  password: Field()
})


const makeLogin = ({ user, password }) => {
 return new Login({
    user: new Field(user),
    password: new Field(password),
 });
}
```

It does need some boilerplate but Ignoring the values in a record makes it perform way better ;)

**Comment by leebyron** [comment]
Unfortunately this proposal will also make flow and ts typing much more difficult, which is something we've been trying to improve.
