### ISSUE TITLE
Incorrect version of Immutable.js on http://facebook.github.io/immutable-js

### ISSUE THREAD

**Issue by limelights** [facebook/immutable-js#414]
Version on site is `3.3.0` while NPM version is `3.6.4`  which means the website is missing some APIs like `Immutable.Map#deleteIn`.

To reproduce:
Go to http://facebook.github.io/immutable-js
Open console and enter the following

```
m = Immutable.Map()
m.deleteIn
// undefined
```

**Comment by leebyron** [comment]
Thanks for the heads up! Fixed
