### ISSUE TITLE
Bad links on documentation

### ISSUE THREAD

**Issue by maxdow** [facebook/immutable-js#418]
All links are pointing to http://facebook.github.io/ . For example fromJS() is tageting http://facebook.github.io/fromJS which doesn't exist resulting a redirection to code.facebook.com

**Comment by cesarandreu** [comment]
+1, same issue

**Comment by leebyron** [comment]
Sorry all, looks like I got ahead of the CDN and the JS file for the docs didn't load. I just fixed it, should work for you now.

**Comment by maxdow** [comment]
Good for me thanks :)

**Comment by cesarandreu** [comment]
Thanks!

**Comment by tabakd** [comment]
Having the same problem now. 😮
