### ISSUE TITLE
set.intersect() fails inside withMutations if sharing elements with set.add/intersect

### ISSUE THREAD

**Issue by yetanotherhacker** [facebook/immutable-js#419]
Running this in node

```
Immutable.Set(['a', 'd']).withMutations(function(set) {
      set.add('b');
      set.union(['c']);
      set.intersect(['b', 'c', 'd']);
})
```

will fail with a `TypeError: Cannot read property '1' of undefined`. It seems that `intersect()` does not play well when `add()` or `union()` calls before it that share similar elements.

**Comment by yetanotherhacker** [comment]
I thought I'd check up on this - could I get feedback / acknowledgement that this has been seen?

**Comment by leebyron** [comment]
Seen. Certainly there shouldn't be a TypeError, I'll look into that. But this is also not legal code. Union and Intersection always return new collections - even within a withMutations block, so this should result in the Set ['a', 'b', 'd'].

**Comment by yetanotherhacker** [comment]
I see. Thanks!

**Comment by magnus-madsen** [comment]
A possible suggestion, inside src_Set__Set.prototype.intersect, should the inner call back return false to stop the iteration?

    src_Set__Set.prototype.intersect = function() {var iters = SLICE$0.call(arguments, 0);
        if (iters.length === 0) {
            return this;
        }
        iters = iters.map(function(iter ) {return SetIterable(iter)});
        var originalSet = this;
        return this.withMutations(function(set ) {
            originalSet.forEach(function(value ) {
                if (!iters.every(function(iter ) {return iter.includes(value)})) {
                    set.remove(value);
                    // <--- return false here?
                }
            });
        });
    };

**Comment by magnus-madsen** [comment]
Suggestion, inside src_Set__Set.prototype.intersect, the values to be removed inside the callback could be locally accumulated and then removed. For example:

src_Set__Set.prototype.intersect = function() {var iters = SLICE$0.call(arguments, 0);
        if (iters.length === 0) {
            return this;
        }
        iters = iters.map(function(iter ) {return SetIterable(iter)});
        var originalSet = this;
        return this.withMutations(function(set ) {

            var acc = [];

            originalSet.forEach(function(value ) {
                if (!iters.every(function(iter ) {return iter.includes(value)})) {
                    acc.push(value)
                }
            });

            acc.forEach(function (value) {
                set.remove(value);
            })
        });
    };

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
@magnus-madsen you were right all along. #1083 implements that approach for the fix. Better late than never!
