### ISSUE TITLE
Immutability detection.

### ISSUE THREAD

**Issue by ziflex** [facebook/immutable-js#421]
Hi there,
how can I detect whether the instance is immutable data structure created with Immutable.js?

**Comment by astorije** [comment]
Right now I am checking that [`obj instanceof Collection`] for https://github.com/astorije/chai-immutable.

Probably not the best way to do it, but I didn't investigate much. I'll keep an eye on this thread and will add a Chai matcher to my plugin when a better answer comes in.

**Comment by ziflex** [comment]
But I need to avoid having any direct references to Immutable.js.
It's for external library.

**Comment by leebyron** [comment]
Detect that the obj is an Object, both "hashCode" and "equals" properties are functions. 




This will be included formally in the next major version as Immutable.isValue() but you can write it yourself as a cheap detection.




If your library is calling any methods on Immutable collections (like perhaps, "get") then it's good practice to check to ensure those properties are also functions.




Does that make sense?



—

**Comment by ziflex** [comment]
@leebyron hope so, thanks!

**Comment by nobodysfool** [comment]
Albeeert

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
