### ISSUE TITLE
Record typing support

### ISSUE THREAD

**Issue by dmitriiabramov** [facebook/immutable-js#423]
Using records is a great way to structure your data in the project, but sometimes it does not give enough type enforcement. e.g. record like
```js
var Message = Record({
  from: null,
  to: [],
  subject: null,
  body: null
});
```
dose not give much information about the fields and their types. And any value can be assigned to any field.
```js
var message = new Message({to: .199});
```
Is there any way to have typed records? maybe in the way React uses `propTypes`
```js
var Message = Imutable.Record({
  from: Immutable.Types.string,
  to: Immutable.Types.array,
  // ...
});

var message = new Message({to: .199}); // throw 'type missmatch'
```

**Comment by Gozala** [comment]
I think this is very much related to #407 and #408

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
