### ISSUE TITLE
Can't use "size" as record field anymore

### ISSUE THREAD

**Issue by arian** [facebook/immutable-js#424]
I used something like this, using `size` as a field.

```js
var Grid = Record({size: 10});
var grid = new Grid().set("size", 4);
```

But I think since https://github.com/facebook/immutable-js/commit/347d2efb this broke.

Executing the code results in this error:

```
Error: Cannot set on an immutable record.
    at invariant (/home/arian/www/test/node_modules/immutable/dist/immutable.js:932:27)
    at Record.Object.defineProperty.set (/home/arian/www/test/node_modules/immutable/dist/immutable.js:3892:9)
    at new Record (/home/arian/www/test/node_modules/immutable/dist/immutable.js:3758:36)
    at Object.<anonymous> (/home/arian/www/test/test.js:10:12)
```

I made a new issue, but just close it if it's already covered by #377 or #362.

**Comment by conradz** [comment]
Can confirm this was a change between v3.6.4 and v3.7.0. If it was intentional it definitely should be in the release description as it is a breaking change. Also, it happens when just creating the record, no need to call `.set`. The following code throws this error:

```js
var R = Record({ size: 1 })
new R();
```

@leebyron is this a supported use case or should we change the code to use something other than `size`?

**Comment by leebyron** [comment]
This was an unintentional breakage but the use of "size" as a key in a record has always been problematic. I'm working on simplifications and improvements to Record which should fix this issue once and for all.

**Comment by leebyron** [comment]
Merging into #377.

**Comment by JacksonGariety** [comment]
I still get this on `3.7.6` & `3.8.1`. What happened?

**Comment by oliverturner** [comment]
Still an issue: 
```
var Foo = new Immutable.Record({id:'', size:0})
var Bar = new Foo({id:'wut'}) // <-- Error: Cannot set on an immutable record.
```

**Comment by vojtatranta** [comment]
Still trouble with `size`

**Comment by oliverturner** [comment]
@vojtatranta per @leebyron, `size` is never going to be supported in Records and using it will raise an exception in v4

**Comment by sangguk2** [comment]
It's because Record supports getting by dot notation..
