### ISSUE TITLE
Converting Nested Map of Records to Array of Objects

### ISSUE THREAD

**Issue by sergelerner** [facebook/immutable-js#425]
Hi! First of all Awesome library!
Is it possible to convert a nested Map of Records (or Maps) to Array of Objects? 
Currently if I do `someMap.toArray()` the outcome is `[Record, Record]`, id like it to be: `[{},{}]`.
Thanks!

**Comment by leebyron** [comment]
You want toJS() which deeply converts

**Comment by sergelerner** [comment]
Yea I've tried toJS(). Thing is the output is not exactly what I need. I'll explain.

I'm using a data structure which is a Map of Records so I can get and set to it by the key which is an ID in my case, example:

```javascript
var _nodes = Immutable.Map();

var nodesRecord = Immutable.Record({
  id : null,
  text : 'some text'
});

function add(node) {
 _nodes = _nodes.set(node.id, new nodesRecord({id : node.id, text: node.text }));
}

function update(id, updates) {
_nodes = _nodes.set(id, _nodes.get(id).merge(updates));
}

function delete(id) {
_nodes = _nodes.delete(id);
}
```
Now I need to convert this to an Array of Objects (Not Object of Objects) for some external decoupled d3 module, so the way I figured to do this is:

```javascript
var _nodesJS = _nodes.toArray().map(function(item) {
       return item.toObject();
});
```
Is this a correct approach when using immutable.js ?
