### ISSUE TITLE
Best way to batch update a list ?

### ISSUE THREAD

**Issue by smnplk** [facebook/immutable-js#428]
Hi!

Firstly, @leebyron , thank you for creating this awesome library. 

I am a total noob here, so bare with me. 

I have the following collection:

```javascript
var array = [ {id: 1, approved: false}, {id: 2, approved: true}, {id: 3, approved: false}..];
var my_list = Immutable.fromJS(array);
```

So this should create the following structure (List (Map), (Map), (Map)..)

Now let's say I have another array with list of ids: 

```javascript
var ids = [1, 2, 3...]
```

Now I want to get a new version of my_list where approved value is changed(to true or false) only for Map's with ids in ids array. This is how I am doing it now, but I am wondering if there is a better way to do this.

```javascript
var new_list = my_list.map(function(obj) {
  if (_.includes(ids, obj.get('id'))) {
    return obj.set('approved', approved_bool);
  } else {
   return obj;
}});
```

**Comment by Gijsjan** [comment]
From one noob to another: looks good to me. :)

Depending on `my_list.size`, you could consider using batch mutations<sup>1</sup>. You'd loop `ids` instead of mapping `array`.

<sup>1</sup> http://facebook.github.io/immutable-js/#batching-mutations

**Comment by camspiers** [comment]
I don't think that using `fromJS` is as good as constructing your own data structure for this.

```javascript
var array = [ {id: 1, approved: false}, {id: 2, approved: true}, {id: 3, approved: false}..];

// A record to represent your objects
var MyRecord = Record({id: null, approved: false});

// ideally you can avoid this function altogether and instead create the better representation in the first place
function convertArray(arr) {
  return Map().withMutations(map => {
    arr.forEach(item => map.set(item.id, new MyRecord(item)));
  });
}

// If you can't have the appropriate data structure created in the first place, then convert what you have
var map = convertArray(array);

var approved_bool = true; // the following code should be abstracted out

// Use withMutations to avoid the many intermediate maps that this process may create
map = map.withMutations(map => {
  ids.forEach(id => {
    if (map.has(id)) { // this is more efficient that looping over a list
      map.update(id, record => record.set('approved', approved_bool));
    } else {
      // depending on how you want this to function, you could throw an exception here
      // (as an id that isn't recognized has been provided), or alternatively you can add a new record
      map.set(id, new MyRecord({id: id, approved: approved_bool});
    }
  });
});
```

**Comment by leebyron** [comment]
If you need targeted updates, then you may consider using `Map` instead of `List`. `OrderedMap` if the iteration order of the items is important.

> Now I want to get a new version of my_list where approved value is changed(to true or false) only for Map's with ids in ids array.

This will be an O(N) operation where N is the size of `my_list`. It could instead be an O(M) operation where M is the number of ids to update instead.

If you wish to use a List, then the code you originally post looks like it will work just fine. If you wish to use a Map, then the code @camspiers posted looks great.
