### ISSUE TITLE
Rename withMutations => await

### ISSUE THREAD

**Issue by natew** [facebook/immutable-js#429]
Wondering thoughts on this. I know we have await coming in es7, it seems to me to read better:

```js
store.await(store => {
 store.push([1]).push([2]);
});
```

**Comment by natew** [comment]
On other hand could be *more* confusing, not sure.

**Comment by leebyron** [comment]
Await already means something very specific as an ES7 proposal that is very different from what withMutations does. I think this would be more confusing, and not adding enough value to be worth the pain of having to migrate all existing users of this library through a change to a pretty common API.
