### ISSUE TITLE
Cursor.from onChange callback not available when used with withMutations 

### ISSUE THREAD

**Issue by natew** [facebook/immutable-js#430]
If a user runs:

```
store().withMutations(store => {
  // multiple mutations
});
```

And you have an onChange listener in your cursor, it just returns an empty array:

``` js
    Cursor.from(data, function (newData, oldData, keyPath) {
        state = cursor(newData);
        debugger; // keyPath === []
        action(state, keyPath);
      });
```

**Comment by leebyron** [comment]
Could you please write up a jsfiddle or gist or something which illustrates the issue? I can't figure out how to reproduce the problem from just this description.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Closing this aging issue
