### ISSUE TITLE
Tests fail with "jestPreprocessor.js: Object #<Object> has no method 'emitFiles'"

### ISSUE THREAD

**Issue by andrewluetgers** [facebook/immutable-js#431]
I just forked the project, ran npm install and grunt build, then grunt test and all but two tests failed. When I look at the tests folder those two tests are in .js, the rest are in .ts. I think this commit has something to do with it https://github.com/facebook/immutable-js/commit/952cfc4bd152fd029f9367b59afdcdf6bd798ec6

**Comment by andrewluetgers** [comment]
I can confirm all tests passing when using tag https://github.com/facebook/immutable-js/tree/3.6.4

**Comment by leebyron** [comment]
Which two tests failed? Can you confirm what version of typescript you are using?

**Comment by andrewluetgers** [comment]
Sorry thats, all but two tests failed.
MultiRequire.js and RecordJS.js were the only ones that worked.

**Comment by andrewluetgers** [comment]
I'm running node v0.10.35 if it matters

**Comment by leebyron** [comment]
Sounds very much like an issue with your local version of typescript. Can you ensure the version of typescript you're using matches the version required by the package.json of this library?

**Comment by andrewluetgers** [comment]
hmm it pulled in "version": "1.5.0-alpha",

**Comment by leebyron** [comment]
I just updated package.json to restrict anything above 1.4.x until typescript wraps up their work on 1.5.0 and I can verify it doesn't break anything. Hopefully this fixes things for you.

**Comment by andrewluetgers** [comment]
works great thanks!
