### ISSUE TITLE
Iterable#toObject shall use Object.defineProperty

### ISSUE THREAD

**Issue by XeCycle** [facebook/immutable-js#432]
This does something weird:
`Map().set("__proto__", null).toJS()`

**Comment by leebyron** [comment]
Yes, any Map key that means something specific in the context of an Object property will be dangerous to convert to a JS object.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
