### ISSUE TITLE
Working with d3.js mutable data

### ISSUE THREAD

**Issue by sergelerner** [facebook/immutable-js#434]
Hi, In my application I use d3.js for some visualizations... 
Now D3 works with **mutable** native js data structures. 
Some data marshaling would be necessary for this to work with immutableJs. 

I also use Reflux with React, so in my Store I manage an Immutable Map. Since this Map becomes a new thing on every change I cannot just pass it to D3 Force Layout because it works with mutable data so each time it recalculates everything from scratch. 

I end up with managing both Immutable and mutable data structures but this feels very wrong. 

I found this article: [Practical Time Series Visualization using D3 + OM](http://blog.getliquidlandscape.com/2015/01/08/practical-time-series-visualization-using-d3-om/) 
which seems to touch on the subject, and suggest to use *Cursors*. Thing is it uses Clojure(Script) when Im using just JavaScript.

I understand its very Abstract without code examples but any suggestion on the subject of working/syncing both immutables and mutables will be appreciated  !

**Comment by krulik** [comment]
:+1:

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Unfortunately any library which *requires* mutation will not work well with immutable data.
