### ISSUE TITLE
Tuple / Pair / Triple structures

### ISSUE THREAD

**Issue by astorije** [facebook/immutable-js#437]
_Disclaimer: I am using JavaScript only, so I don't know the potential specifics of TypeScript for this topic_

Scala defines `Tuple` structures, from [`Tuple1`](http://www.scala-lang.org/api/current/index.html#scala.Tuple1) to... [`Tuple22`](http://www.scala-lang.org/api/current/index.html#scala.Tuple22)!

Along the way, [`Tuple2`](http://www.scala-lang.org/api/current/#scala.Tuple2) and [`Tuple3`](http://www.scala-lang.org/api/current/#scala.Tuple3) are pretty nice, they come with extra methods (like `swap` for `Tuple2`. These two are so common that they respectively are aliased to [`Pair`](https://github.com/scala/scala/blob/2.10.x/src/library/scala/Predef.scala#L256) and [`Triple`](https://github.com/scala/scala/blob/2.10.x/src/library/scala/Predef.scala#L262) (were actually, since they got deprecated in favor of a syntax we unfortunately cannot use here).

Right now, if I want to make a pair, I can either use an `Array` (and therefore be mutable) or a `List` (and therefore abuse the types):

``` js
var a = ['foo', 42];
var l = List.of('foo', 42);
```

Isn't the second one a violation of the types?

I think it'd be nicer to have specific data structures like:

``` js
var p = new Pair('foo', 42);
var t = new Tuple2('foo', 42);
```

Among other things, a nice consequence of this, for those who are using JavaScript and [JSDoc](http://usejsdoc.org/) is that the former version has to be documented with `{List.<*>}`, while the latter one can be documented with `{Pair.<string, number>}`, which is much more precise and useful documentation!

Am I completely missing the point here?

**Comment by samwgoldman** [comment]
Both TypeScript and Flow have support for tuple types, which are based on array values, but the type checker verifies the number and type of elements.

Overall, I agree that tuple structures are handy. Materialized (`new Tuple(a, b)`) and functional (type Tuple<A,B,C> = (a: A, b: B) => C`) representations are useful. The later is already useful in `zipWith`.

What kind of code are you writing that you want a tuple structure?

**Comment by astorije** [comment]
> Both TypeScript and Flow have support for tuple types, which are based on array values, but the type checker verifies the number and type of elements.

Well, I didn't know that, and it makes sense. Points to them then. I see why it's not implemented in this library because of that, but any chance to consider it for those using the library in plain JavaScript?

> Materialized (`new Tuple(a, b)`) and functional (`type Tuple<A,B,C> = (a: A, b: B) => C`) representations are useful.

I was merely talking about the former one. Can the latter one still be considered a tuple, if it's essentially a function?

> What kind of code are you writing that you want a tuple structure?

I opened this issue after faking a tuple structure [here](https://github.com/w3c/echidna/blob/a8936b7c044dbc7acc592c0a01f554ab2da177de/lib/orchestrator.js#L86) and [there](https://github.com/w3c/echidna/blob/a8936b7c044dbc7acc592c0a01f554ab2da177de/lib/orchestrator.js#L326), but this code is going to evolve soon to actually use a `List` for what it's purposed.

However, I am using an `Array`-based tuple [here](https://github.com/w3c/echidna/blob/f63e8c384defb95d4ec3446d07b1040bb253ebc7/lib/document-downloader.js#L43). I'd happily switch to a nicer `Pair`/`Tuple2` structure. And oftentimes I feel like using such thing, increasingly since starting to use `Promise` objects.

**Comment by samwgoldman** [comment]
Sure, the functional variant is a kind of "final encoding," where if you know how you will use the tuple, you can structure your code a bit differently. Say I know I am going to use the second half of a tuple and ignore the first, I can pass `(a, b) => b` as my "tuple."

Of course, you could also name the fields of your tuple and use an object/record with two properties.

**Comment by myitcv** [comment]
I'm also after a `Tuple`, but a special instance of one, one that represents an "entry" in a `*Map`. Let's call this type a `MapTuple` for the sake of what follows.

A `MapTuple` would be a tuple (two values), `(K,V)`. In addition to the regular `Tuple` interface, a `MapTuple` would also expose the interface `.key()` and `.value()` that allows you to extract the key (type `K`) and value (type `V`)

In this way you could (as I need to do) convert a `*Map` into a `List/Seq` of `MapTuple` entries.

For now we are working around this by converting to a `List/Seq` of `Seq` which has two entries, `0/1` indexed. But having a `.key()` and `.value()` interface would be more explicit.

I note it's not currently possible/desirable to extend Immutable types https://github.com/facebook/immutable-js/pull/368

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gf3** [comment]
i'm also abusing `List`s for this functionality

**Comment by leebyron** [comment]
Closing this aging issue

However It would be really exciting to see someone make this happen in a PR

**Comment by dobesv** [comment]
Could you use `Record<[f1,f2]>` ?

**Comment by tobiasBora** [comment]
Why close this issue? It's still very relevant 10 years later.

**Comment by jdeniau** [comment]
Re-opening even if this is an old issue. I think Tuple might be an interesting addition for immutable
