### ISSUE TITLE
Cursor on Set

### ISSUE THREAD

**Issue by karlguillotte** [facebook/immutable-js#439]
Hi, 

I have been using Cursor and I am really enjoying it. Thanks for putting it as _contrib_. 

I never had problems using Cursors on `Map` or `List`. However, using them on `Set` does not seem to work. `Cursor.from` returns a `KeyedCursor`. Not sure if it should return a `KeyedCursor` or a `IndexedCursor`, however it should implement the `Set` interface. 

Thanks

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Closing this aging issue

Cursor isn't under active development
