### ISSUE TITLE
`Map.set(key, Object)` doesn't maintain immutability

### ISSUE THREAD

**Issue by longlho** [facebook/immutable-js#441]
If I set an `Object` to a key in a map, I can manipulate that object freely. Should this be allowed?

```node
> var i = require('immutable')
undefined
> var a = i.Map()
undefined
> a = a.set('key', {foo: 1, bar: 2})
Map { "key": [object Object] }
> a.get('key')
{ foo: 1, bar: 2 }
> a.get('key').bar = 3
3
```

**Comment by leebyron** [comment]
Another way to phrase this is that it maintains the existing mutability of the plain JS object. This is by design. Immutable collections can contain any values including references to mutable objects.

**Comment by leebyron** [comment]
A future major version of immutable will have a way to determine if a collection is "deeply immutable" and contains no references to mutable objects

**Comment by longlho** [comment]
@leebyron oh ok, so for now some operations can produce false positive or false negative (like `===` or `.set`) when mutable object is involved?
