### ISSUE TITLE
The best practice for using immutable data with React.js

### ISSUE THREAD

**Issue by ghyonimor** [facebook/immutable-js#442]
Hello. 
Lately in a project we stumbled upon the following issue: what is the best practice for extracting data out of an immutable object to be rendered in a React.js component.
In the following TodoMVC the creator uses the toJS() method, which feels kind of unnatural : https://github.com/hoppula/react-immutable-todomvc

In another example, however, a get() method is used directly on the immutable object: https://github.com/facebook/immutable-js/wiki/Immutable-as-React-state

What way would you suggest? 
Thanks in advance.

**Comment by tcoopman** [comment]
There has been a discussion about this on https://reactiflux.slack.com/messages/immutablejs/ on the 6th of April. I'm not sure how to link to the discussing directly.

From the discussion, it's not clean cut about what's the best way either, but it using Immutable objects all the way down has advantages.
Maybe it would be good to list both advantages and disadvantages of both approaches?

**Comment by madebyherzblut** [comment]
We use immutable objects all the way down and it is working great. `.get()` is used every time we want to render a value, like in the given example.

Note: `toJS()` is no longer necessary since Rect 0.13 (see https://github.com/facebook/react/pull/2376)

**Comment by leebyron** [comment]
The best practices are to use `.get()` when you need a specific value, and make use of the `.filter()`, `.map()` and other higher-order functions to convert to react children.

I'll update that wiki page.

**Comment by leebyron** [comment]
Wiki page updated to match this info.
