### ISSUE TITLE
Map() factory coerces number keys to strings

### ISSUE THREAD

**Issue by lukewestby** [facebook/immutable-js#443]
I'm using a `Map` to point number ID properties to config objects, and I'm creating the `Map` from an object with the same structure, like so:

```javascript
const options = Map({
    13000: { /* ... */ },
    13004: { /* ... */ }
});
```
Later on I'm checking for the existence of IDs in the `Map` by calling, for example, `options.has(13000)`, which returns `false` because the keys are being coerced to strings upon creation.

As a faster example, simply trying `Immutable.Map({ 1: true }).has(1)` will return `false` as well.

My question is simply whether this is the intended behavior, and if so can it be documented more clearly?

Thanks!

**Comment by camspiers** [comment]
Objects coerce to string keys. So these objects you are using actually have string keys not number keys. Hence why you can't get the values our when you use `has` or `get`.

**Comment by camspiers** [comment]
Stated another way, immutable-js does support non-string keys, but in this case, the misunderstand that JavaScript objects have string keys is leading you astray.

```
Map().set(1, "s").has(1); //true
```

**Comment by lukewestby** [comment]
Okay, that makes sense - I can see that `Object.keys({ 1: true })` returns `["1"]`. Thanks for clarifying, I'll close this. Thanks!

**Comment by rymohr** [comment]
> the misunderstanding about JavaScript object keys is leading you astray

It's a misunderstanding of the internal implementation of object keys though, not the interface.  This works just fine:

```
var map = {1: true};
map[1]; // true
```

**Comment by leebyron** [comment]
Note that `map[1]` first coerces `1` to `"1"` and then does a look-up in the JS object, which is why this is a commonly misunderstood behavior of JavaScript.

**Comment by FaiChou** [comment]
Yeah, it gives me a great help.
