### ISSUE TITLE
Empty slice throws exception when iterated over

### ISSUE THREAD

**Issue by ariofrio** [facebook/immutable-js#444]
I haven't been able to construct a simple example, since I don't really understand in what cases __iteratorUncached is used, and how React iterates over lists of elements. However, it seems clear to me that if `sliceSize = 0`, iterator will be zero, and the line which calls `iterator.next()` will cause an exception to be thrown whenever skipped is not zero.

    sliceSeq.__iteratorUncached = function(type, reverse) {
      if (sliceSize && reverse) {
        return this.cacheResult().__iterator(type, reverse);
      }
      // Don't bother instantiating parent iterator if taking 0.
      var iterator = sliceSize && iterable.__iterator(type, reverse);
      var skipped = 0;
      var iterations = 0;
      return new src_Iterator__Iterator(function()  {
        while (skipped++ < resolvedBegin) {
          iterator.next();
        }
        if (++iterations > sliceSize) {
          return iteratorDone();
        }
        var step = iterator.next();
        if (useKeys || type === ITERATE_VALUES) {
          return step;
        } else if (type === ITERATE_KEYS) {
          return iteratorValue(type, iterations - 1, undefined, step);
        } else {
          return iteratorValue(type, iterations - 1, step.value[1], step);
        }
      });
    }

(From immutable.js line 1344.)

**Comment by leebyron** [comment]
Can you illustrate the user-land code you wrote that resulted in the exception? I can start with that to turn into a test case.

**Comment by leebyron** [comment]
I started with:

```js
var iterator = Immutable.List.of(1,2,3).slice(0, 0).values();
expect(iterator.next).to.deepEqual({ done: true, value: undefined });
```

And this currently passes and does not throw.

**Comment by leebyron** [comment]
Thanks for surfacing this area - a bug and repro was found
