### ISSUE TITLE
Is there any way to spliceIn value

### ISSUE THREAD

**Issue by deser** [facebook/immutable-js#447]
Hi, i have deep structure such as 
{
   ...
   items: [{
       ...
    },{
       ...
       items: [...]
    }]
}

And I want to splice item into 'items' array at any level of hierarchy. Is there any solution to do that?
Thanks

**Comment by leebyron** [comment]
Yes, `splice` is supported and works very similar to Array.prototype.splice - http://facebook.github.io/immutable-js/docs/#/List/splice

For making edits deeper in a structure, `updateIn` is your friend - http://facebook.github.io/immutable-js/docs/#/Map/updateIn

You can of course combine the two. In fact all of the short-hands like `setIn` are just 1-line implementation functions which combine `set` with `updateIn`.

Here's what that might look like for you:

```js
deepData.updateIn(['deep', 'path', 'to', 'items'], list => list.splice(position, 0, itemToAdd));
```

**Comment by deser** [comment]
Thanks Lee)
