### ISSUE TITLE
is it possible in reactjs to map OrderedMap?

### ISSUE THREAD

**Issue by Oleksandr-Silin** [facebook/immutable-js#448]
Main idea:
We have pagination therefore I need "slice" on items. From beginning items is OrderedMap where key is id of item, and value is object or undefined(data of item). Data is loaded later on demand.
It is worked as expected when I use toArray on "slice" result. But I want to pass OrderedMap into itemView function, to have key and value(which can be undefined). And there is a bug...
It draws additional "span" elements , but (according to log) itemView method is called only for my "li" items  in OrderedMap - therefore I can't to filter those unexpected elements.
Can anybody sugest or explain what is going on? I hope it is possible to use OrderedMap directly instead of toArray.
Thanks for help!

This is what I receive - extra "span" items, but there should be only "li" items...
```html
<ul id="se-pl-projects" data-reactid=".0.2.0.2.0.2">
    <span data-reactid=".0.2.0.2.0.2.$size:0"></span>
    <span data-reactid=".0.2.0.2.0.2.$_map:0:$size:0"></span>
    <span data-reactid=".0.2.0.2.0.2.$_map:0:$_root:0:$entries:0:0:0"></span>
...
    <span data-reactid=".0.2.0.2.0.2.$_map:0:$_root:0:$entries:0:3:1"></span>
    <span data-reactid=".0.2.0.2.0.2.$_list:0:$size:0"></span>
    <span data-reactid=".0.2.0.2.0.2.$_list:0:$_origin:0"></span>
    <span data-reactid=".0.2.0.2.0.2.$_list:0:$_capacity:0"></span>
    <span data-reactid=".0.2.0.2.0.2.$_list:0:$_level:0"></span>
    <span data-reactid=".0.2.0.2.0.2.$_list:0:$_tail:0:$array:0:0:0"></span>
    <li data-reactid=".0.2.0.2.0.2.$_list:0:$_tail:0:$array:0:0:1"></li>
    <span data-reactid=".0.2.0.2.0.2.$_list:0:$_tail:0:$array:0:1:0"></span>
    <li data-reactid=".0.2.0.2.0.2.$_list:0:$_tail:0:$array:0:1:1"></li>
    <span data-reactid=".0.2.0.2.0.2.$_list:0:$_tail:0:$array:0:2:0"></span>
    <li data-reactid=".0.2.0.2.0.2.$_list:0:$_tail:0:$array:0:2:1"></li>
    <span data-reactid=".0.2.0.2.0.2.$_list:0:$_tail:0:$array:0:3:0"></span>
    <li data-reactid=".0.2.0.2.0.2.$_list:0:$_tail:0:$array:0:3:1"></li>
</ul>
```
This is not production code :). Just to show main idea.
On project we are using Flux architecture.
```javascript
var _items = Immutable.OrderedMap();
var getState = function () {
	_items = Immutable.OrderedMap().withMutations(map=> [5, 1, 4, 6].forEach(id=>map.set(id, _items.get(id))))

    return {
            pageItems: _items.slice(1, 3)
    };
};

React.createClass({
    getInitialState() {
        return getState();
    },
    render(){
        var itemView = function (value, key) {
            logger.info(' Mapping item ', value, key);
            return (
                <li onClick={this._openProject.bind(this, key)}>
                    <MyItemView id={key} info={value} key={key}/>
                </li>
            )
        };
        var view =
            <div>
                <ul id="se-pl-projects">
                {this.state.pageItems.map(itemView, this)}
                </ul>
            </div>;

        return (view);
    }
});
```

**Comment by leebyron** [comment]
You can use the `.map()` directly in React v0.13 or later (v0.13.1 is the last release, v0.14-beta is also out), v0.12 requires children to be an Array but v0.13+ can accept an Iterable. All Immutable.js collections are Iterables.

If you're stuck using v0.12 for some reason, just write `.map().toArray()` to convert to an Array.

**Comment by Oleksandr-Silin** [comment]
Thank you,
Updating from 0.12 to 0.13 helped.
