### ISSUE TITLE
Is there any way to check if data is immutable?

### ISSUE THREAD

**Issue by deser** [facebook/immutable-js#450]
Does immutablejs have method isImmutable? If no how to check if data is immutable?
Thanks

**Comment by leebyron** [comment]
You can check if something is an Iterable immutable collection with Iterable.isIterable()

**Comment by deser** [comment]
Thanks)

**Comment by mAiNiNfEcTiOn** [comment]
Well, I tested on Node this comparison:

```javascript
var Immutable = require('Immutable');
var myMap = new Immutable.Map({});

console.log( myMap instanceof Immutable.Map ); // true
```

**Comment by leebyron** [comment]
It's on my plate to make a nicer API for this, but you can use Immutable.Iterable.isIterable() to see if an object is any of the Immutable.js collections. Otherwise each type has a Map.isMap() or List.isList() etc that you can use if you're checking just one kind of collection.

**Comment by mAiNiNfEcTiOn** [comment]
Yeah, that's true. But there aren't that many kinds of collections :) But yeah, a 'isImmutable' method would be just fine :)

**Comment by abritinthebay** [comment]
Just ran into this issue would put a +1 as there are so many uses where you'd want to check this.

**Comment by madebyherzblut** [comment]
I do not recommend to use `instanceof` because when you (or another library you use) require different copies of Immutable.js (by not having a shared node_module directory) it returns `false`.

module-a.js
```js
var Immutable = require('immutable');
module.exports = Immutable.Map({foo: "bar});
```

module-b.js
```js
var Immutable = require('immutable');
var moduleA = require('moduleA');
moduleA instanceof Immutable.Map // will be false
```

@leebyron Should this behavior be documented? (related to #421)

**Comment by leebyron** [comment]
Yes, I agree. I added a task to track at #566

**Comment by fingermark** [comment]
Are there propTypes for immutable.js?  Every example I see online uses `React.PropTypes.instanceOf(Immutable.Iterable)`, but I just read above that it's not recommended to use instanceOf.

**Comment by madebyherzblut** [comment]
@fingermark There is [react-immutable-types](https://github.com/HurricaneJames/react-immutable-proptypes#react-immutable-proptypes) which does not [suffer from the instanceof problem](https://github.com/HurricaneJames/react-immutable-proptypes/blob/master/src/ImmutablePropTypes.js#L22).

**Comment by gajus** [comment]
[`Iterable.isIterable(maybeIterable: any): boolean`](https://facebook.github.io/immutable-js/docs/#/Iterable/isIterable)
