### ISSUE TITLE
Small improvement for deep methods

### ISSUE THREAD

**Issue by deser** [facebook/immutable-js#451]
As for me it would be convenient  to pass not only array in 'getIn, updateIn, setIn' methods.
https://monosnap.com/image/3fIhtzRKIFP3um0vCF0eSmrzqBPc05

**Comment by leebyron** [comment]
You can use the variants without "In" suffix in this way. 

For the example you gave, if you instead call props.get("items") it will return the value you expect.

**Comment by deser** [comment]
Ok, thanks for answer :)

**Comment by tgriesser** [comment]
Actually in 4.0 could calling a deep method without a valid key be changed to throw?

**Comment by leebyron** [comment]
Good idea, Tim!

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
