### ISSUE TITLE
Reduce file size or break apart?

### ISSUE THREAD

**Issue by matthewmueller** [facebook/immutable-js#453]
Not interested in starting a discussion about the relative importance of filesize, more just curious if it's possible to take just the object implementation or just the array implementation out of immutable? 

Right now I have a 200 LOC library that I'd like to keep as tiny as possible and I really just need `.set` and `.get` functions from the Map. Would something like this be possible or does it require everything else for handling nested arrays and other things?

**Comment by camspiers** [comment]
I think this is being tracked here: https://github.com/facebook/immutable-js/issues/317

**Comment by matthewmueller** [comment]
Oh yep, good call!
