### ISSUE TITLE
Immutable.fromJS() with non-plain object

### ISSUE THREAD

**Issue by quangbuule** [facebook/immutable-js#454]
Is there any solution to convert non-plain object in to Immutable?

```js
class B {
    constructor() {
        this.c = "d";
    }
}

var a = { b: new B };

Immutable.fromJS(a);
```

**Comment by leebyron** [comment]
You want to convert the class B instance into an Immutable Map?

You could write a function to do this deeply like:

```js
function fromJSGreedy(obj) {
  if (Array.isArray(obj)) {
    return Immutable.List(Immutable.IndexedSeq(obj).map(fromJSGreedy));
  }
  return Immutable.Map(Immutable.KeyedSeq(obj).map(fromJSDefault));
}
```

**Comment by leebyron** [comment]
Beware of converting non-plain objects - any enumerable property will become a key in the map. In some cases on some browsers that can include keys from a prototype. Also some non-plain objects don't have any enumerable properties and will result in an empty Map.

**Comment by nativot** [comment]
I have Immutable.js version 3.8.1 and don't find functions KeyedSeq and IndexedSeq.

What to do?
