### ISSUE TITLE
How to merge a map deep and remove deleted fields?

### ISSUE THREAD

**Issue by hfjallemark** [facebook/immutable-js#455]
Let us say that I have two objects:

```javascript
var js1 = {
    name: 'John',
    age: 30
};

var js2 = {
    name: 'John'
};

var map1 = Immutable.fromJS(js1);
var map2 = map1.mergeDeep(js2);

console.log(map1.toString()); // Map { "name": "John", "age": 30 }
console.log(map2.toString()); // Map { "name": "John", "age": 30 }
console.log(map1 === map2); // true
```

Is there any way to *remove* fields that does not exist on the returned map? E.g:

```javascript
console.log(map1.toString()); // Map { "name": "John", "age": 30 }
console.log(map2.toString()); // Map { "name": "John" }
console.log(map1 === map2); // false
```

**EDIT**

Arrays exhibits the same behavior, and is quite unexpected to me (or simply that I do not understand Immutable data properly :smile:):

```javascript
var js1 = {
    name: 'John',
    age: [1, 2]
};

var js2 = {
    name: 'John',
    age: [1]
};

var map1 = Immutable.fromJS(js1);
var map2 = map1.mergeDeep(js2);

console.log(map1.toString()); // Map { \"name\": \"John\", \"age\": List [ 1, 2 ] }
console.log(map2.toString()); // Map { \"name\": \"John\", \"age\": List [ 1, 2 ] }
console.log(map1 === map2); // true
```

Shouldn't the new map be: ```Map { \"name\": \"John\", \"age\": List [ 1 ] }``` here?

**Comment by leebyron** [comment]
For your second example, if you `merge()` instead of `mergeDeep()` then you will get the result that you expected. `mergeDeep()` attempts to merge at every level it can, including within lists.

Merge never removes fields - you can think of merge as analogous to "union". If you want to remove fields, you should explicitly use `delete()`
