### ISSUE TITLE
How to search/update using child-key as Key?

### ISSUE THREAD

**Issue by dgtlmonk** [facebook/immutable-js#457]
Hi, 

I'm having problem on how to search/update using child-key. Consider the following code:

var _data = {
      Name: 'Joel',
      Phones:[
        {Home: '11111'},
        {Office: '2222'},
        {Work: '3333'},
      ]
   };

How do I update the Office field? Based on documentation:
`getIn(searchKeyPath: Array<any>, notSetValue?: any): any`

my trouble is that 'Office' key is inside Phones, How do i do this? 

Appreciate the help. Many thanks!

**Comment by Elergy** [comment]
It'll be better if you'd have an object like that:
```
var _data = {
    Name: 'Joel',
    Phones: {
         Home: 111111,
         Office: 222222
    }
};
```

If it is impossible you can access to object which contains 'Office' key by index. 
```
immutableData = immutableData.setIn(['Phones', 1, 'Office'], '123');
```

**Comment by srph** [comment]
I think this should be closed now as this has been solved. If I'm right, the OP's the guy I've talked to days ago, not unless it's just coincidental that their examples are the same :smile:

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
