### ISSUE TITLE
Zipping uneven iterable

### ISSUE THREAD

**Issue by dkingman** [facebook/immutable-js#458]
Immutable currently will only zip iterables up to the shortest length of the set. So for something like this:

```
var a = Seq.of(1, 2, 3);
var b = Seq.of(4, 5;
var c = a.zip(b)
```

`c` will be `Seq [ [ 1, 4 ], [ 2, 5 ] ]`. Is this intended? This seems like the least useful case. Lodash for example will fill in, "missing" values with `undefined`.

**Comment by mduvall** [comment]
I believe this is intended, consider a pathological case where `a` in your example is a stream and you know that `b` is a finite sequence. The `Seq` returned should close over the finite sequence.

Other language examples include:

The documentation for Scala's `List.zip` says it will return: `a new list containing pairs consisting of corresponding elements of this list and that. The length of the returned collection is the minimum of the lengths of this list and that.`

In both Scala and Haskell this is true:

```scala
scala> val a = List(1,2,3)
a: List[Int] = List(1, 2, 3)

scala> val b = List(1,2)
b: List[Int] = List(1, 2)

scala> a zip b
res0: List[(Int, Int)] = List((1,1), (2,2))
```

```haskell
Prelude> let a = [1,2,3]
Prelude> let b = [1,2]
Prelude> zip a b
[(1,1),(2,2)]
```

**Comment by dkingman** [comment]
Fair enough. Wasn't thinking about the case of infinite sequences. Might be nice to have a function like Scala's `zipAll` which takes up to the longest list, filling in with a default as it goes. Not sure how well that would play with the existing interface in Immutable. 

Another option would be to pass in a length parameter and take up to that length, filling in with a default. This would avoid the infinite sequence issue.

**Comment by leebyron** [comment]
This is a great suggestion. Other libs call this "zipLongest" but I kinda like "zipAll"

**Comment by mduvall** [comment]
@leebyron Ah interesting, did not know that!

**Comment by mduvall** [comment]
@leebyron @dkingman I gave it a swing over in https://github.com/facebook/immutable-js/pull/460, would love feedback!

**Comment by dkingman** [comment]
Great work @mduvall! Thanks for taking this on. Scala and [Python](https://docs.python.org/2/library/itertools.html#itertools.izip_longest) both provide the option to fill with a default value. I know doing it that way would involve diving into the iterator so I'm not sure if it's worth it. Ruby and others don't allow specified defaults and just fill with nil/null/etc. I can see how allowing a specified default would be useful though. What do you all think?

**Comment by leebyron** [comment]
Nice work @mduvall! This is definitely a good start where undefined is the default value. Let me review your diff a bit closer, but at first glance it looks great

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
zipAll is now included
