### ISSUE TITLE
output has trailing commas - breaks oldIE compatible minfiers

### ISSUE THREAD

**Issue by abritinthebay** [facebook/immutable-js#462]
Especially when using Browserify - if I'm pulling in this script and the build chain has (for various reasons) a minifier that MUST support oldIE (IE8 and lower) then the trailing commas produce errors.

I know that _technically_ this is valid (or rather, acceptable) in newer browsers... but is there any way to not do this for compatibility reasons (toolchain compatibility not the browsers specifically).

Right now this basically means it's impossible to use ImmutableJS in an IE<9 compatible toolchain.

**Comment by leebyron** [comment]
Can you please point to where you're seeing the trailing commas? I'm happy to correct this - I definitely want to preserve IE8 support.

**Comment by abritinthebay** [comment]
Sure! Specifically in the `KeyedIterable`, `IndexedIterable`, and `SetIterable` mixins. Also at the end of the Immutable var declaration (line ~4900, the `fromJS: fromJS,` property.

I think that's all of them, but can't be 100% sure.

**Comment by abritinthebay** [comment]
oh - found another - at the end of the `hashCode` function declaration.

A short cut to finding them is running through the Google Closure Compiler - it complains by default.

**Comment by leebyron** [comment]
Thanks for the report - at least uglify strips them by default, so the minified source will be IE8 safe. I'll clean up the rest.

**Comment by abritinthebay** [comment]
Yeah, it's mostly a problem for browserify builds tbh (that's how I ran into it) as those pull in the NPM module.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jeffchan** [comment]
I believe this is fixed in #510 and 3565850
