### ISSUE TITLE
Referential Equality Across calls to List.map()

### ISSUE THREAD

**Issue by aldendaniels** [facebook/immutable-js#464]
**Hypothetical Scenario**
I have a list of items - people for example. A person looks like this:

```javascript
{
  firstName: 'John',
  lastName: 'Smith',
  phoneNumber: 123456789
}
```

I have a generic React "list" component that wants a list of items to display where each item looks like this:
```javascript
{
   text: 'John Smith',
   hoverText: '123456789'
}
```

So... we need to map people into list items like so:
```javascript
render() {
  return (
    <MyList items={people.map((person) => {
      text: person.get('name'),
      hoverText: person.get('number')     
     })} />
  );
}
```

**Problem**
Assuming `MyList` to be a pure component, React is still going to re-render it every time the parent component is rendered whether or not the Immutable `people` list has changed. 

Since `map()` returns a new object every time it's called, equality will not be preserved across calls to `.render()`.

**Proposed Solution**
A `pureMap` method that maintains referential equality:

```
people.pureMap('a-hard-coded-key', (person) => {
  text: person.get('name'),
  hoverText: person.get('number')     
});
```

ImmutableJS then will keep a cache of the last value returned for `'a-hard-coded-key'` and (if `people` hasn't changed), return the cached data structure.

The main downside with this approach is that `'a-hard-coded-key'` MUST be globally unique. It would be pretty trivial, however, to add a build step that would inject random, unique keys.

Thoughts?

**Comment by aldendaniels** [comment]
Note that this same approach could be used to provide optimized "pure" variants of other transformations such as `sort`, `slice`, etc.

**Comment by leebyron** [comment]
I would suggest that rather than passing in a result of `map`, that you instead pass in the original list, and allow the component's render function to perform the `map` - that way you can rely on the equality of that original list.

Otherwise, what you're describing is a memoization function, which should be independent of what operation you're doing (map, sort, slice, anything). Such a memoization function is beyond the scope of Immutable.js, but certainly something that you build yourself with very little amount of code.

**Comment by leebyron** [comment]
The reason Immutable.js doesn't contain memoization like this is that it makes referential vs value equality even more observable than it already is, which is something we're trying to avoid. - It also can lead to memory leaks if the memoization cache doesn't clear over time - and that behavior is usually application specific rather than library specific.

**Comment by leebyron** [comment]
Also I should note that referential equality is a performance optimization to be used by value equality - which is the recommended way to compare equality of immutable collections.

The rule of thumb usually being:

Use value equality to determine if two immutable values are equal or not - for whatever purpose you need. If you're concerned that comparing value equality will be expensive for some reason, and you're only using equality to shortcut some work (e.g. memoization), then use referencial equality as that shortcut. It will guarantee you that you'll never get a false positive (unequal things claiming to be equal) but you will often get false negatives (equal things claiming to not be equal).

**Comment by aldendaniels** [comment]
Thanks for the quick and detailed response!

> I would suggest that rather than passing in a result of map, that you instead pass in the original list, and allow the component's render function to perform the map - that way you can rely on the equality of that original list.

Yep. This is what I've done in the past. It's not ideal mainly because it's easy to forget to do. Also passing around mapping functions a lot is a bit inelegant. Still, this does work.

 > Otherwise, what you're describing is a memoization function, which should be independent of what operation you're doing.

Good point. Baking the common-cases into the library, however, would make this more convenient and help to clarify the need to memoize where performance is critical.

> It also can lead to memory leaks

Yes, I was about to post a follow-up comment mentioning this. Obviously cleanup methods can be provided, but it does add to the conceptual overhead.

>  The reason Immutable.js doesn't contain memoization like this is that it makes referential vs value equality even more observable than it already is.

Not sure I follow. Are saying you'd like library consumers to just call `.equals()` without thinking too hard about whether referential equality is being used vs. a deep compare?

-------

Whether or not adding memoization to ImmutableJS is a good idea, it's a very fair point that I can easily write my own generic `memoize` function.

**Comment by leebyron** [comment]
> Not sure I follow. Are saying you'd like library consumers to just call .equals() without thinking too hard about whether referential equality is being used vs. a deep compare?

Correct. If you want to know equality, use `.equals()` or `is()`. If you're writing a memoization function and you're wanting to think about the tradeoff for false-negatives and re-running whatever you're memoizing, then you can use `===`.

**Comment by leebyron** [comment]
Basically, reference equality is just a performance optimization for `.equals()` - so I want to avoid any API changes or performance hits just to enable this performance optimization more often.

**Comment by aldendaniels** [comment]
@leebyron - Makes perfect sense. Thanks again for your thoughtful and detailed reply. Please feel free to close.
