### ISSUE TITLE
[Documentation] Sibebar scrolling is inaccessible on Laptop

### ISSUE THREAD

**Issue by vkbansal** [facebook/immutable-js#467]
The sibebar in documentation cannot be scrolled on Laptop. This causes a terrible experience.

**Comment by leebyron** [comment]
Can you let me know what browser version and OS version you're encountering this?

**Comment by vkbansal** [comment]
My Browser is Chrome  43.0.2357.52 beta-m (64-bit) on WIndows 8.1

**Comment by mackenza** [comment]
I am also on Chrome 43 on Win 8.1, but I believe the same thing happens in Chrome 43 on Linux Ubuntu. There is no scrollbar for the left nav panel. If I put my cursor over it, I can wheel scroll or arrow scroll but it's not good. Also, it gets totally "lost" when it expands to a sub item.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
