### ISSUE TITLE
[Documentation] Source example not visible in all my browsers

### ISSUE THREAD

**Issue by DawidLoubser** [facebook/immutable-js#468]
Hi,

In all the browers at my disposal on my Arch Linux machine, the code snippets in the `http://facebook.github.io/immutable-js/` site is not visible. I don't have any user-defined style sheets installed. For example, on latest Firefox:

![Screenshot](http://dawidloubser.name/tmp/screenshots/immutable-docs-blank.png)

**Comment by leebyron** [comment]
Hmm bummer - seems like perhaps an issue with using web fonts. Do you encounter this on any other websites with the same Browser/OS?

**Comment by DawidLoubser** [comment]
No, never encountered with any other site. Being a web developer myself, I have curiously not been able to explain why the code is invisible - it's there in the DOM, and no CSS analysis seems to show an obvious reason for them to be invisible.

**Comment by mpal9000** [comment]
+1

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jiewmeng** [comment]
+1 this seems to happen on Linux (Arch Linux). It will be great if this can be fixed. At least use a different font if one is not working?

**Comment by mpal9000** [comment]
Maybe there is something wrong with "Fira Mono" and "Fira Sans" font families in some linux distros (Arch Linux for sure), because I have the same problem with http://blog.keithcirkel.co.uk/, which also uses those.

**Comment by robjens** [comment]
Same here. ArchLinux user. I installed `ttf-fira-mono` and `ttf-fire-sans` which triggered removal of `google-fonts-git` package. Closed browser and re-opened and the problem is gone. Thanks for the tip on which fonts to pick, seems this did the trick.

**Comment by mpal9000** [comment]
yeah, seems `ttf-google-fonts-git` has broken Fira fonts:
https://github.com/google/fonts/issues/10
https://code.google.com/p/googlefontdirectory/issues/detail?id=368
https://aur.archlinux.org/packages/ttf-google-fonts-git/

**Comment by leebyron** [comment]
Still broken?

**Comment by DawidLoubser** [comment]
@leebyron Working perfectly fine for me over the past couple of months - sorry for not closing this earlier, I'll close it not. Running latest `firefox`, and latest `ttf-google-fonts` on Arch linux.
