### ISSUE TITLE
Combination methods are not available for OrderedSet

### ISSUE THREAD

**Issue by endragor** [facebook/immutable-js#474]
OrderedSet has a guaranteed iteration order, and therefore methods like zip(), interleave(), interpose() and other combination methods make perfect sense for it. But they are only available for IndexedIterable which OrderedSet does not inherit.

**Comment by leebyron** [comment]
Great point! I'll try to figure out a way to include these kinds of methods on OrderedSet and OrderedMap

**Comment by tgriesser** [comment]
Not sure if `.indexOf` makes sense to include on OrderedMap, but I noticed recently that was missing there as well

**Comment by leebyron** [comment]
I don't think so... as it's not indexed, it just has a fixed and specified iteration order vs non-ordered `Map`'s unspecified iteration order.

**Comment by gasi** [comment]
> @leebyron I don't think so... as it's not indexed, it just has a fixed and specified iteration order vs non-ordered Map's unspecified iteration order.

Is that why there is no `OrderedSet::get(index)`?

**Comment by fenduru** [comment]
@leebyron `indexOf` would be useful to be able to take advantage of `slice` (since slice deals with indexes). While OrderedMap has the ability to sort, it lacks the ability to insert somewhere in the middle. Typically I wan't to say "Insert key `foo` before key `bar`". Right now, the best I can come up with is something like:

```
omap.takeUntil((val, key) =>key === 'foo').concat(OrderedMap({ bar: 'barValue' }).concat(omap.skipUntil((val, key) => key === 'foo'))
```

**Comment by leebyron** [comment]
Closing this aging issue - note that you can always convert OrderedSet and OrderedMap to various kinds of Seq to access different kinds of lazy indexed APIs at O(N) cost.
