### ISSUE TITLE
Immutable.List#sortBy does not work with withMutations

### ISSUE THREAD

**Issue by bunkat** [facebook/immutable-js#477]
The following code will not sort the list:

````
var items = items.withMutations(list => { list.sortBy(...).sortBy(...).reverse() });
````

But this works as expected:

````
var items = items.sortBy(...).sortBy(...).reverse();
````

Does it not makes sense to use `withMutations` for these types of changes?

**Comment by leebyron** [comment]
This is intentional - only a select few methods can be used in `withMutations` for List those are `set`, `push`, `pop`, `unshift`, and `shift`.

I'm adding these to the documentation now.
