### ISSUE TITLE
Array splice inside a cursor 

### ISSUE THREAD

**Issue by rajrahul** [facebook/immutable-js#479]
I am trying to manipulate an Immutable(3.6.4) cursor by adding and inserting an entry to a list:
```
var data = Immutable.fromJS({a: {b: [0, 1, 2]}});
var cursor = Cursor.from(data, ['a', 'b'], function(newData){
    data = newData;
});

cursor = cursor.push(3);
var newList = cursor.splice(1,0,11);
cursor.update(function(x){return newList;});

console.log(data.toJS().a.b); //Result [0, 11, 1, 2, 3]
```
Why is it that the cursor.splice is not updating the 'data'?

Now, using withMutation, splice does not seem to work. I have added the results next to the log statements.

```
var data = Immutable.fromJS({a: {b: [0, 1, 2]}});
var cursor = Cursor.from(data, ['a', 'b'], function(newData){
    console.log("Setting Data");
    data = newData;
});

cursor.withMutations(function(c){
    console.log(c.toJS()); //[0, 1, 2]
    c.push(3).toJS();
    console.log(c.toJS()); //[0, 1, 2, 3]
    var newList =  c.splice(1,0,11);
    console.log(newList.toJS()); //[11]
    console.log(c.toJS());//[]
    c.update(function(x){return newList;});     
});
```
What is the right way to achive this?

**Comment by mindjuice** [comment]
See #196 for a discussion of this.  I don't follow why ``splice()`` is considered non-mutative though.  It operates on the array in-place, whereas ``slice()`` makes a copy.

**Comment by rajrahul** [comment]
What is the right way to insert into an array using Cursors? Set overwrites the existing elements.

**Comment by leebyron** [comment]
`splice()` operates similarly to `map()` and `filter()` - it cannot be used within a withMutations and also cannot be used to update a cursor.

The right way to insert within an array when using cursors is to refer to the referencing element:

```js
// instead of 
parentCursor.get('mylist').splice(...);
// do:
parentCursor.update('mylist', list => list.splice(...));
```

That same pattern will work for other kinds of map/filter operations as well.
