### ISSUE TITLE
Support .set(object) for Immutable.Map

### ISSUE THREAD

**Issue by tracker1** [facebook/immutable-js#483]
It would be nice if you could set multiple properties, or even deep setting properties in a map.

What happens now:

```js
> var m = Immutable.Map({a:1,b:2,c:3})
undefined
> m.toJS()
Object {a: 1, b: 2, c: 3}
> m = m.set({a:5,b:6})
> m.toJS()
Object {a: 1, b: 2, c: 3, [object Object]: undefined}
```

It would make more sense for `m = m.set({a:5,b:6})` to result in `{a:5,b:6,c:3}` ...

As an extension it would make sense for nested objects to become maps themselves, and set the nested properties.

**Comment by leebyron** [comment]
You should check out [`merge`](http://facebook.github.io/immutable-js/docs/#/Map/merge). It has exactly the API you're after. `mergeDeep` will handle the nested values.

**Comment by tracker1** [comment]
@lebyron thanks... I was mainly just playing with what I saw for the first time, and thought the behavior was a bit odd.

**Comment by leebyron** [comment]
It's also perfectly fine to use an object (mutable or immutable) as a key, so the `set` API accepting a JS object is a supported use case
