### ISSUE TITLE
OrderedMap: remove and sort inside withMutations

### ISSUE THREAD

**Issue by umphy** [facebook/immutable-js#485]
Hi, I'm trying to perform `remove()` and `sort()` inside a `withMutations()`. Now the documentation says that only `set()` and `merge()` can be used with a mutable collection. However, [this post] (https://github.com/facebook/immutable-js/issues/228) suggests that `remove` is safe to use with a mutable Map.

Can someone please let me know whether I can use `remove()` and `sort()` for an OrderedMap in `withMutations`? Thank you.

**Comment by leebyron** [comment]
remove() is not safe on OrderedMap, but is on Map within a withMutations block. Sort is not safe within withMutations block. 



—

**Comment by umphy** [comment]
Thanks for your very quick reply. So if `remove()` is not safe on OrderedMap, would you recommend me to use `filterNot()` instead, or another approach?

**Comment by leebyron** [comment]
remove() is perfectly safe on OrderedMap, just not within a withMutations block. Only set and merge are safe there.

**Comment by leebyron** [comment]
And sorry, "safe" isn't really the right word here. It's of course perfectly safe to use that method - but just be clear as to the behavior. remove() never performs a mutation on a mutative collection (e.g. Within a withMutations block) it always returns a new collection.

**Comment by umphy** [comment]
Thanks. Really appreciate your time in answering my questions.

So what would be the best practice when removing a bunch of entries from an OrderedMap? I'm guessing that `filter()` or `filterNot()` will be more efficient than multiple calls of `remove()`. Also, I'm assuming the filter methods, like the `remove()`, will return a new collection, is that correct? Does that reuse the existing map entries or does it clone the existing entries?

**Comment by leebyron** [comment]
`remove` is actually implemented as a `filter` for ordered map. Removing multiple times will be `O(MN)` where N is the size of the collection and M is the number of keys you remove. Writing a single `filter` will be `O(N)` which will be nice if you're moving a number of things.

The wiki has a nice feature on this exact operation, often called `omit` by other libraries: https://github.com/facebook/immutable-js/wiki/Predicates#pick--omit
