### ISSUE TITLE
Support a Mongo style update command method

### ISSUE THREAD

**Issue by dantman** [facebook/immutable-js#488]
I'm pleased to see immutable-js has a bunch of methods that use keypaths (so I don't need to write messy verbose code to update one property deep in a nested structure.

But has anyone considered also supporting the same syntax as the [update](https://facebook.github.io/react/docs/update.html) addon to React? Which itself is based on the MongoDB query language.

It's fairly simple yet flexible. And I have a feeling that without it Immutable is going to be stuck either endlessly adding even more keypath methods or shunning users who want to simplify a simple but unsupported mutation.

For example. I see #406 asking for concatDeep or concatAll because mergeDeep clobbers lists. And #331 asking for a similar pushIn.

**Comment by leebyron** [comment]
Do you have a suggestion for what the method name should be that would be familiar and idiomatic to mongo users?

**Comment by vtambourine** [comment]
It's great idea, I believe. MongoDB-style queries are simple, convenient and quite usual, since they are used both in Mongo and React.

I suggest those queries should be supported not separate methods, but by *In-functions signatures. For example, for data like:
```js
var data = Immutable.fromJS({cat: {isDead: false}})
``` 
`Map#setIn` method could be called by two equivalent methods:
```js
data.setIn(['cat', 'isDead'], true)
```
```js
data.setIn({cat: {isDead: {$set: true }}})
```

What do you think about it?

**Comment by estk** [comment]
+1

**Comment by botinko** [comment]
+q

**Comment by WhatFreshHellIsThis** [comment]
+1

**Comment by vtambourine** [comment]
@leebyron I can prepare a prototype PR for this feature, if you don't mind.

**Comment by leebyron** [comment]
Closing this aging issue

However if someone would ever like to resurrect this, I think it would be cool to see a PR illustrating what this would take.
