### ISSUE TITLE
`deleteIn` fails for Set within Map

### ISSUE THREAD

**Issue by danielberndt** [facebook/immutable-js#489]
I would expect this code to work:

```
new Map().set("decks", new Set([1, 12, 2])).deleteIn(["decks", 12])
```

instead it throws: `Uncaught Error: invalid keyPath`

**Comment by rickhanlonii** [comment]
+1. Since Set and Map both expose a delete function, I would expect this to work. Even if it doesn't though, it should return a more descriptive error. Something like:

`Uncaught error: deleteIn invalid for type Set`

**Comment by axefrog** [comment]
This bug is over a year old and remains unacknowledged and unfixed... any comment from the devs would be appreciated.
