### ISSUE TITLE
Custom hash implementations?

### ISSUE THREAD

**Issue by matthewwithanm** [facebook/immutable-js#490]
Are there any plans to allow objects to define their own hashing algorithms a la Python's [`__hash__`][1]? It seems like it would just require making `UID_HASH_KEY` public (though I can also see an argument for not wanting to introduce new equality semantics into JS).

[1]: https://docs.python.org/2/reference/datamodel.html#object.__hash__

**Comment by leebyron** [comment]
You can do this if your object has a "hashCode()" method. It just needs to return an int. objects that implement hashCode also need to implement "equals(other)" and return true if the two are equivalent. Two equivalent MUST return the same hash code, but the same hashCode doesn't need to guarantee equality. 




This hasn't been formally documented yet, but I don't think it will change. 



—

**Comment by matthewwithanm** [comment]
Perfect! I had looked in the source but somehow missed that line!

**Comment by cytrowski** [comment]
> Two equivalent MUST return the same hash code, but the same hashCode doesn't need to guarantee equality. @leebyron 

That single phrase just saved my day! I encountered weird case with hash collision of two different objects. It turns out {x: 10, y: 20} and {x:20, y:10} give the same hashCode. I discovered that the hashCode is not safe but that summary you gave cleared it out for me. It should be documented.

**Comment by agaurav** [comment]
I don't think the collisions are because of the limited range of hashing method used. It seems in `rc3` its simply ignoring the values of field even in first level. E.g. here https://github.com/facebook/immutable-js/issues/1326
