### ISSUE TITLE
Immutable as State in JSBin

### ISSUE THREAD

**Issue by MoonTahoe** [facebook/immutable-js#491]
I took the sample from the WIKI page and pasted it into a JSBin.  I added script tags with CDN links to React, and Immutable.js.  So the only changes I made to this code removes Common JS and prefixes Map and List with Immutable.

[Link to sample on Bin](http://jsbin.com/hipazukede/2/edit?js,output)

The issue is when I run the sample the count does not update.  Is this sample supposed to work this way?  The count always being 0?

### Sample Output

Count: 0
Saved counts:
* Saved: 0
* Saved: 0
* Saved: 0
* Save count

```javascript
var Component = React.createClass({

  getInitialState() {
    return {
      data: Immutable.Map({ count: 0, items: Immutable.List() })
    }
  },

  handleCountClick() {
    this.setState(prev => ({
      data: prev.data.update('count', v => v + 1)
    }));
  },

  handleAddItemClick() {
    this.setState(prev => ({
      data: prev.data.update('items', list => list.push(prev.data.get('count')))
    }));
  },

  render() {
    var data = this.state.data;
    return (
      <div>
        <div onClick={this.handleCountClick}>
          Count: {data.get('count')}
        </div>
        Saved counts:
        <ul>
          {data.get('items').map(item => 
            <li>Saved: {item}</li>
          )}
          <li onClick={this.handleAddItemClick}>Save count</li>
        </ul>
      </div>
    );
  }

});

React.render(<Component />, document.body);
```

**Comment by sampepose** [comment]
Clicking on "Count: ##" will increment the count. Clicking "Save Count" will add the current count to a `List`.

The example is supposed to work in this way. It may be better to have "Count: ##" and "Save Count" be hyperlinks or buttons to make it more clear if this functionality wasn't apparent from the code.

**Comment by leebyron** [comment]
Thanks for this feedback! I wanted to keep the example as simple as possible but understand why this was confusing. I made some modifications to make them buttons, https://github.com/facebook/immutable-js/wiki/Immutable-as-React-state
