### ISSUE TITLE
Negative flatten

### ISSUE THREAD

**Issue by AlexeyFrolov** [facebook/immutable-js#492]
`[ [ 'a', 'b' ], [ [ 'c', 'd', 'f' ] ] ]`

What I need to get is `[ [ 'a', 'b' ], [ 'c', 'd', 'f' ] ]` regardless of deepness of the input.

Maybe I'm loosing something and I can easily archive this with existing functionality.. Atm I think that `list.flatten(-1)` would be natural way to do such thing.

**Comment by AlexeyFrolov** [comment]
Also I think about `list.flatten(untilPredicate)`

**Comment by samwgoldman** [comment]
What about `list.map((inner) => inner.flatten())`?

**Comment by AlexeyFrolov** [comment]
@samwgoldman your point is valid, but

![screen shot 2015-06-05 at 9 08 25 pm](https://cloud.githubusercontent.com/assets/547167/8012097/42d21350-0bc7-11e5-841f-013cc72df00c.png)

**Comment by leebyron** [comment]
Alexey, I don't fully understand the behavior you're looking for. Could you supply some various examples of arbitrary nesting and the expected output of this operation? I'm curious for more examples of data of type:

type NestedValue = Array<NestedValue> | String

**Comment by leebyron** [comment]
That should be Array< NestedValue >

**Comment by AlexeyFrolov** [comment]
@leebyron I want to flatten list to List<String> and not , Array< NestedValue > . I think it's obvious from my examples.

**Comment by leebyron** [comment]
Sorry, I meant List<NestedValue>, not Array<NestedValue>. But also, it's not yet obvious to me from your examples, so please humor me with more input to understand the pattern.

Here are the examples you've provided so far:

```js
[ [ 'a', 'b' ], [ [ 'c', 'd', 'f' ] ] ] => [ [ 'a', 'b' ], [ 'c', 'd', 'f' ] ]
[ [ [ 'a', 'b' ], [ [ 'c', 'd', 'f' ] ] ] ] => [ [ 'a', 'b' ], [ 'c', 'd', 'f' ] ]
```

I'm curious about:

```js
[ [ 'a', [ 'b' ] ], 'c' ] => ?
[ [ [ 'a' ] ], 'b' ] => ?
[ [ [ 'a' ] ], 'b' ] => ?
[ 'a', [ [ 'b' ] ], 'c' ] => ?
[ 'a', [ 'b', [ 'c', [ 'd' ], 'e' ], 'f' ], 'g' ] => ?
```

**Comment by AlexeyFrolov** [comment]
For my concrete case I want
[ [ 'a', [ 'b' ] ], 'c' ] => [ [ 'a', [ 'b' ] ], 'c' ]
[ [ [ 'a' ] ], 'b' ] => [ [ [ 'a' ] ], 'b' ]
[ [ [ 'a' ] ], 'b' ] => [ [ [ 'a' ] ], 'b' ]
[ 'a', [ [ 'b' ] ], 'c' ] => [ 'a', [ [ 'b' ] ], 'c' ]
[ 'a', [ 'b', [ 'c', [ 'd' ], 'e' ], 'f' ], 'g' ] => [ 'a', [ 'b', [ 'c', [ 'd' ], 'e' ], 'f' ], 'g' ]

But I just propose, I think it would be useful if it could be controlled by list.flatten(untilPredicate). 
If you know any other solution for my case, I will appreciate a lot..

**Comment by leebyron** [comment]
What is your predicate in this case?

We would likely need a different kind of method or utility function for this sort of operation, since the flatten function is "greedy" to maintain an optimal O(N) performance.

**Comment by AlexeyFrolov** [comment]
list.flatten((v) => "List contains not Lists") . The predicate could signal on witch point it should stop flatten.

**Comment by AlexeyFrolov** [comment]
My real-life case is

```javascript
static getMapPaths(map) {
        map = fromJS(map);
        getPaths = (map, result = new List([])) => (
            (!Map.isMap(map) || map.isEmpty()) && result.toArray() ||
            map.flip().toList().reduce(
                (res, k) => res.push(getPaths((map.get(k)), result.push(k))),
                new List()));
        return fromJS(getPaths(map).flatten().toArray());
    }
```

Maybe there is a better way to implement that kind of function, but in this particular implementation I get nested Lists and I need to flatten it somehow, but I don't want to loose separate paths, which are represented as Lists. Which is why I was required to separate actual "paths" by JS Arrays from nested Lists and convert it to Immutable data structures.

Original idea was:
```javascript
static getMapPaths(map) {
        map = fromJS(map);
        getPaths = (map, result = new List([])) => (
            (!Map.isMap(map) || map.isEmpty()) && result ||
            map.flip().toList().reduce(
                (res, k) => res.push(getPaths((map.get(k)), result.push(k))),
                new List()));
        return getPaths(map).flatten(-1); // or .flatten((v) => "List that contains not Lists")
    }
```

**Comment by leebyron** [comment]
I'm having trouble following the purpose and behavior of the `getMapPaths` function, but I think I better understand now what you're looking for from a flattening point of view.

Hopefully this code will help you out:

```js
import { List, Iterable } from 'immutable';

function flattenIf(pred, list) {
  var flatList = List();
  function flatDeep(_list) {
    _list.forEach(function (item) {
      if (Iterable.isIterable(item) && pred(item)) {
        flatDeep(item);
      } else {
        flatList = flatList.push(item);
      }
    });
  }
  flatDeep(list);
  return flatList;
}

function isListOfLists(list) {
  return list.every(Iterable.isIterable);
}

var customFlatten = flattenIf(myDeepList, isListOfList)
```

**Comment by leebyron** [comment]
I studied your `getMapPaths` function a bit and I think I understand what you're trying to do here, please correct me if I'm mistaken:

You want to provide a Map of Maps, like 

```js
var deepMap = { a: { b: true, c: true }, d: true, e: { f: { g: true } } };
```

And then produce a list of all paths to leafs, like

```js
[ [ "a", "b" ], [ "a", "c" ], [ "d" ], [ "e", "f", "g" ] ]
```

If this is the goal, then you should be able to write a recursive reducer for doing this without a need for flattening afterwards. You should also avoid going back and forth between native JS arrays and objects and Immutable collections by using `fromJS` and `toArray` within utility methods like this - those require full copies and will add up to be quite poor on performance and should not be necessary.

Here's a recursive reducer version of `getMapPaths` which expects Immutable collections as input and returns Immutable collections as output without producing deeply nested lists.

```js
function getMapPaths(deepMap) {
  return _reducePath(List(), deepMap, List());
}

function _reducePath(paths, map, path) {
  return !Map.isMap(map) || map.isEmpty() ?
    paths.push(path) :
    map.reduce(
      function (paths, subMap, key) { 
        return _reducePath(paths, subMap, path.push(key)) 
      },
      paths
    );
}
```

Then to use it:

```js
var deepMap = fromJS({ a: { b: true, c: true }, d: true, e: { f: { g: true } } });
var paths = getMapPaths(deepMap);
console.log(paths.toString());
// List [ List [ "a", "b" ], List [ "a", "c" ], List [ "d" ], List [ "e", "f", "g" ] ]
```

**Comment by AlexeyFrolov** [comment]
@leebyron Great! ) It recalled me on SICP courses ). Also I recognized that I need different algorithm and different output data structure for my problem.. Your explanation and examples did great job for me to understand it. ATM believe that my concrete request was provoked by wrong approach which was leaded to ~maybe~ wrong need (I'm about negative flatten param and/or predicate). If someday I catch myself on it I'll think twice until I'll be dead sure that we need it.

Thank you and your colleagues for what you're doing for open source, it's huge )

**Comment by leebyron** [comment]
Thanks, I'm closing this task out since we're in a better place :)
