### ISSUE TITLE
Question on the correct way of updating nested Maps in Lists

### ISSUE THREAD

**Issue by Robert-W** [facebook/immutable-js#493]
I want to update one of my components to use Immutable.js and was curious the best way to update nested Maps.  I have a relatively simple data structure with nested objects and children and it could potentially go very deep.  It is a json structure used for a Tree component.  The data looks like this:

<pre><code>
[
  {id:'A', label: 'A', checked: true},
  {id:'B',label: 'B'},
  {id:'C',label: 'C',
    children: [
        {id:'C-A',label: 'C-A'},
        {id:'C-B',label: 'C-B', checked: true},
        {id:'C-C',label: 'C-C',
          children: [
              {id:'C-C-A',label: 'C-C-A'},
              {id:'C-C-B',label: 'C-C-B'},
              {id:'C-C-C',label: 'C-C-C', checked: true}
          ]
        }
    ]
  },
  {id:'D',label: 'D'}
]
</code></pre>

This is a controlled component and so when the user interacts with the tree, I update the appropriate checked value in the data with the corresponding id.  So for example, I may change the checked attribute from true to false for the node with id 'C-C-C'.  I am attaching a link of a JSFiddle that I used and it works but I am not sure if the same can be achieved in a better way using setIn or something.

JSFiddle link: http://jsfiddle.net/yk2y2hhu/1/

**Comment by leebyron** [comment]
What you're doing is about as good as you can do with the data structure as it's currently designed, but it's also a pretty expensive operation since you need to search through the list of children. 

If the "id" of the children are unique, then I would suggest modeling the children as a Map, or OrderedMap if the iteration order is important. Then you can use the much simpler and more performant setIn and updateIn methods.

**Comment by Robert-W** [comment]
Ah ok.  Yes the id's will be unique so I will go ahead and try to model them as an OrderedMap and see how it works.  The order does not necessarily matter in this particular example but there are cases where people using the component may want it in a specific order or to have the ability to reorder it.

Thanks.

**Comment by Robert-W** [comment]
Hey sorry to bother you again.  I seem to be having some trouble getting this set up correctly and am hoping you could point me in the right direction.  How would I take something like the above data structure and model the children as an OrderedMap.  I was thinking something like this:

<pre><code>
var data = new Immutable.OrderedMap({
  'A': { label: 'A', checked: true },
  'B': { label: 'B', checked: false },
  'C': { label: 'C', children: Immutable.OrderedMap({
    'C-A': {label: 'C-A', checked: true, children: Immutable.OrderedMap({
      'C-A-A': {label: 'C-A', checked: true}
    })}
  })}
});
</code></pre>

but when I try to retrieve deep values with this, I get undefined:
<code>
data.getIn(['C','children','C-C'])
</code>

Im sure Im missing something obvious or setting this up wrong but I was hoping you could point me in the right direction.  I put this in an updated fiddle as well in case it's easier to look at it there.

http://jsfiddle.net/yk2y2hhu/3/

**Comment by kentor** [comment]
The value of 'C' is a plain object, not another immutable structure, i.e. `data.getIn(['C', 'children']) === undefined`

If you have a nested object that you want to convert to a Map use `Immutable.fromJS`, https://github.com/facebook/immutable-js#nested-structures

**Comment by Robert-W** [comment]
Ah awesome thanks.  I got it figured out now.  I appreciate the help.

**Comment by ashraffayad** [comment]
I need to use the solution with deeply nested maps and lists. The problem with the Solution of @Robert-W http://jsfiddle.net/yk2y2hhu/1/ is that it always returns a new structure event if nothing changed!. I guess this is because ```.map``` always produces a new collection. 
Is there another good way to [update, set , merge] deeply nested maps and lists?

**Comment by leebyron** [comment]
`setIn` and methods like it (e.g. http://facebook.github.io/immutable-js/docs/#/Map/setIn) are best for applying updates in deeply nested locations.

The methods will always return a value of the same shape (nested maps and lists in the same form) and if nothing actually changed as a result of the method call, then it just returns itself, so you can use `===` to see if nothing changed.

**Comment by ashraffayad** [comment]
Thanks. I could easily use ```setIn``` or ```mergeIn``` or ```updateIn``` if my data structure is maps all the way down. But is it possible to use ```setIn``` in a structure like the following? for example to set ```active = true``` on the deepest item with id 356 . If it's possible, please show me how to do that.
```
[
            {id:123, active:false, children:[]},
            {id:134, active:false, children:[
                {id:212, active:false, children:[
                    {id:245, active:false, children:[]},
                    {id:256, active:false, children:[]}
                ]},
                {id:145, active:false, children:[]},
                {id:156, active:false, children:[]},
                {id:213, active:false, children:[
                    {id:313, active:false, children:[]},
                    {id:314, active:false, children:[
                        {id:345, active:false, children:[]},
                        {id:356, active:false, children:[]}
                    ]}
                ]}
            ]}
        ]
```
As I said, I tried to use @Robert-W 's old solution (before he changed his lists into orderedMaps). It works but it always creates a new copy of the whole data structure even if nothing changed!!

**Comment by leebyron** [comment]
Lists share the same `*In` methods, so to do what you asked you would write:

```
var newData = data.setIn([1, 'children', 3, 'children', 1, 'children', 2, 'active'], true);
```

You should also see that if you were to have set a value where nothing has changed, that you will get back the same original value. So for example, if you were to set true again:

```
var sameData = newData.setIn([1, 'children', 3, 'children', 1, 'children', 2, 'active'], true);
sameData === newData // true
```

**Comment by ashraffayad** [comment]
Got it. Thanks :)

**Comment by eromoe** [comment]
How to partial update ? Do I have to call multiple times `data.setIn` ??

**Comment by ashraffayad** [comment]
No. Just once. 
data.setIn (pathArray, { name: 3, pic: 4, desc: 5, meta:6 })
