### ISSUE TITLE
Javascript getters in Immutable.Record, this is an empty Record

### ISSUE THREAD

**Issue by KeKs0r** [facebook/immutable-js#494]
I am heavily using Records for most of my Data that is passed around in my app.

I came across some weird behaviour with ES6 Javascript Getters. 
Let's say I have a Product Record:

``` javascript
var Product = new Record({
    'id': 0,
    'name': null,
    'moneyPrice': null,
     getMoneyPrice() {
        console.log(this);
        if (this.moneyPrice) {
            return (`${this.moneyPrice}`).replace('.', ',');
        }
    },
    get needsPayment() {
        console.log(this.moneyPrice);
        return (this.moneyPrice && this.moneyPrice > 0);
    }
});

var shoe = new Product({id: 1, name:'Super Sneaker', moneyPrice: 59.00})
shoe.getMoneyProce();
shoe.needsPayment;
```

In my real function (getMoneyPrice), this.moneyPrice is correctly set to 59.00, but using the getter this.moneyPrice is null. Actually in needsPayment this is an empty product and not populated with my shoe data.

I have read in #21 that @leebyron is using getters with Immutable.Record.

**Comment by leebyron** [comment]
This is an interesting suggestion - such usage isn't currently supported. Right now, the input to the `Record` function should be a list of keys and their default values, so this is actually creating a record type where `getMoneyPrice` is a possible key, and the function 

```
   function () {
        console.log(this);
        if (this.moneyPrice) {
            return (`${this.moneyPrice}`).replace('.', ',');
        }
    }
```

is the default value for that key in the record.

I'm not entirely sure of what's going with get property, I've never actually tested doing that.

I'm working on a revamp of Record to simplify the API and improve it's flexibility for v4.0, and this sort of usage which currently sort of works will out-right fail in that version. I'll ensure there's a reasonable API for doing this though, tagging with enhancement.

With today's Record API, you could add these functions by altering the prototype of `Product` directly:

```js
var Product = new Record({
    'id': 0,
    'name': null,
    'moneyPrice': null
});

Product.prototype.getMoneyPrice() {
    console.log(this);
    if (this.moneyPrice) {
        return (`${this.moneyPrice}`).replace('.', ',');
    }
},

Object.defineProperty(Property.prototype, 'needsPayment', {
    get() {
        console.log(this.moneyPrice);
        return (this.moneyPrice && this.moneyPrice > 0);
    }
});

var shoe = new Product({id: 1, name:'Super Sneaker', moneyPrice: 59.00})
shoe.getMoneyPrice();
shoe.needsPayment;
```

**Comment by KeKs0r** [comment]
What I ended up doing is splitting it in 2 classes. It supports a constructor and having get functions on my Records.

´´´javascript
var RecordClass = new Record({
    'id': 0,
    'team1': null,
    'team2': null,
    'scoreT1': null,
    'scoreT2': null,
    'date': null,
    'gamegroup': null,
    'myBet': new GameBet()
});

export default class Game extends RecordClass {
    constructor(game) {
        if (game.gamebets) {
            var myBet = game.gamebets[0];
            game.myBet = new GameBet(myBet).set('game', game.id);
            delete game.gamebets;
        }
        super(game);
    }

    get result() {
        return this.scoreT1 + ':' + this.scoreT2;
    }

    getDate() {
        return new Moment(this.date, 'YYYY-MM-DD HH:mm Z');
    }

}
```

**Comment by leebyron** [comment]
What you've done there is perfectly supported as well.

**Comment by mockdeep** [comment]
@leebyron is there a way to override existing values? I want to do something like this:

```js
var Task = new ImmutableRecord({
  title: null,
  estimate_seconds: null
});

Object.defineProperty(Task.prototype, 'estimate_seconds', {
  get: function () {
    return this.get('estimate_seconds') || 1800;
  }
});
```

But what is odd is that other properties no longer turn up:

```js
t = new Task({ title: 'foo' })
> Record {_map: Object}
t.title
> undefined
t.estimate_seconds
> 1800
```

It seems to work fine if I just give the property another name.

**Comment by leebyron** [comment]
Hmm, this is pretty weird and maybe a bug. I'd recommend using different names for derived values for now, if only to avoid confusing behavior between get() and property access.

**Comment by mockdeep** [comment]
Yeah, that's what I ended up doing.

**Comment by coodoo** [comment]
There's a tiny type in @leebyron's example, `Property.prototype` should be `Product.prototype` :)

Btw, any update on when v4 will hit the shelf?

**Comment by leebyron** [comment]
Closing this aging issue - the best solution here is adding methods to the prototype of the Record, or using class extension.
