### ISSUE TITLE
Handling Nested Maps

### ISSUE THREAD

**Issue by AlesJiranek** [facebook/immutable-js#495]
Hello,

I'm trying to figure out the best way to handle nested objects.
I have packages, pages and widgets. 1:n relations.
Each item has compound id from its parents (widget's primary  is "id_package,id_page,id_widget")
I can't figure out, if it is better to have multiple Maps, one for each Record type - Map of Page Records, Map of Widget Records, or if it is better to use one large Map with tree structure, where for example page record has member widgets which is map of widgets.

In both cases, i think that it's good to use maps indexed with id's of each item to have constant time to update items so i can update it with `updateIn([id_package,id_page,id_widget])`, but when I use it this way, i get warning "Using Maps as children is not yet fully supported."

And are there any performance differences between maps and records? Is it better to use Records for each item or map?

What is the best solution, how to handle tree structures like this?

**Comment by rogeriopvl** [comment]
@AlesJiranek I'm curious, were you able to find a solution for this?

**Comment by diegoddox** [comment]
+1

**Comment by cristian-sima** [comment]
Anything on this?
