### ISSUE TITLE
'includes' method is missing from Iterable prototype

### ISSUE THREAD

**Issue by fkuril** [facebook/immutable-js#499]
According to docs `includes` method should be available on `Iterable` and other classes extending it.
http://facebook.github.io/immutable-js/docs/#/Iterable/includes
However, its alias `contains` is working.

**Comment by leebyron** [comment]
The documentation represents the latest version of the library. `includes` was added in v3.7.1 in response to changes made in the ES6 spec around the same time. Please ensure you're using the latest version of the library.

**Comment by ghigt** [comment]
Could you please update the library included inside the doc website?
(it's useful to easily test there but the version is 3.6.4)
