### ISSUE TITLE
where to get the http://facebook.github.io/immutable-js static source ?

### ISSUE THREAD

**Issue by suhaotian** [facebook/immutable-js#500]
I want to read it's doc compontent, but I didn't find it

**Comment by leebyron** [comment]
You can find the source documentation here: https://github.com/facebook/immutable-js/blob/master/type-definitions/Immutable.d.ts - it's all generated from that file.

**Comment by leebyron** [comment]
The code that does the generation is in the gh-pages branch. https://github.com/facebook/immutable-js/tree/gh-pages?files=1

**Comment by suhaotian** [comment]
tks
