### ISSUE TITLE
Cursors

### ISSUE THREAD

**Issue by kalken** [facebook/immutable-js#504]
I'm trying to set up cursors with immutable.js (nested) to get some sort of state-like-handeling in my react components. I want using the immutablejs/contrib/cursor. But the lack of documentation on how to use it makes this almost impossible. Can somebody give me a short example on how to implement cursors with states and a correct shouldComponentUpdate()?

my setup is like this:
class Test has the "global" cursor. It should send some part of it to Field, that should send some part of it to Input. 

I don't want to use anything unnecessarily like some other cursor library or flux or anything. I suspect this can be done if i just understand how to use the "cursor"-thingy.

This is basically what it looks like:

```
let data = Immutable.fromJS(
  { "categories": ["Book"], 
     "fields":[
           {"label":"Title","value":"Cats & Dogs"},
           {"label":"Author","value":"Steve Jenkins"}
     ], 
     "id": "b0ac28e632bc4e2e889cbf57ccff0a29"}
);

let cursor = Cursor.from(data, ['fields'], newData => {
   data = newData;
});

class Test extends React.Component { 
  render () {
    return <Field cursor=???/>
  }
}

class Field extends React.Component {
  render() { 
    return <Input name='value' cursor={this.props.cursor}>;
  }
}
class Input extends React.Component { 
   render()
     return <input type='text' value={this.props.cursor.get('value')} onChange=???/>;
```

ANY help would be really appreciated at this point.

/K

**Comment by kalken** [comment]
Ok. I (think) i solved it myself by reversengineering the cursor test file :) I i really want your opinion on this. 

What i do is that i send a "cursor" down as prop, and in the class i want to change it i set it to a state. The class that has the main state has the original cursor, and it triggers an update of its state if any of the cursors that relies on it changes. People who have complex data structures, and wants to use part of a state in nested classes in a long chain tend to have a very hard time with writing functions that only sends data "up the chain".

With this solution none of this is needed:

/K

<b>Please let me know what you think about my solution. (Any pointers on if and how i need to implement componentupdates would be extra helpful).</b>

```
let data = Immutable.fromJS(
  {
    "categories": ["Book"],
    "fields":[
      {
        "label":"Title",
        "value":"Cats & Dogs"
      },
      {
        "label":"Author",
        "value":"Steve Jenkins",
      }
    ],
    "id": "b0ac28e632bc4e2e889cbf57ccff0a29"
  }
);

class Field extends React.Component {
  constructor(props) {
    super(props);
    this.state = { cursor: this.props.cursor };
  }
  onChange(evt) {
    this.setState({
      cursor : this.state.cursor.update(evt.target.name,x => evt.target.value)
    });
  }

  render () {
    console.log('field: rendering');
    let cursor = this.state.cursor;
    return (
      <div>
        <label>{cursor.get('label')}</label>
        <input
          type='text'
          name='value'
          value={cursor.get('value')}
          onChange={this.onChange.bind(this)} />
      </div>
    );
  }
};

class Test extends React.Component {
  constructor(props) {
      super(props);
      this.state = {data: data};
      this.InitCursor();
  }
  InitCursor() {
    this.cursor = Cursor.from(this.state.data, newData => {
      this.setState({data: newData});
    });
  }
  render() {
    console.log('test: rendering');
    let style = {
      paddingTop: Spacing.desktopKeylineIncrement
    }
    return (
      <div style={style}>
      <Field cursor={this.cursor.cursor(['fields',0])}/>
      <div>{this.state.data.toString()}</div>
      </div>
    );
  }
};

//do the render either as React.render or something else. I use react router so i do this:
export default Test
```

**Comment by kalken** [comment]
This is the final solution where i added should component update too, and it seems to work:

```
let data = Immutable.fromJS(
  {
    "categories": ["Book"],
    "fields":[
      {
        "label":"Title",
        "value":"Cats & Dogs"
      },
      {
        "label":"Author",
        "value":"Steve Jenkins",
      }
    ],
    "id": "b0ac28e632bc4e2e889cbf57ccff0a29"
  }
);

class Field extends React.Component {
  constructor(props) {
    super(props);
  }
  shouldComponentUpdate(nextProps) {
        // This is as easy as it gets
        let shouldChange = !this.props.cursor.equals(nextProps.cursor);
        console.log('Should',this.props.cursor.get('label'),'update?', shouldChange)
        return shouldChange;
  }
  onChange(evt) {
    this.props.cursor.update(evt.target.name,x => evt.target.value);
  }

  render () {
    console.log(this.props.cursor.get('label'),': rendering');
    let cursor = this.props.cursor;
    return (
      <div>
        <label>{cursor.get('label')}</label>
        <input
          type='text'
          name='value'
          value={cursor.get('value')}
          onChange={this.onChange.bind(this)} />
      </div>
    );
  }
};

class Test extends React.Component {
  constructor(props) {
      super(props);
      this.state = {data: data};
  }
  getCursor(path) {
    return (
      Cursor.from(this.state.data, path, newData => {
        this.setState({data: newData});
      })
    );
  }
  render() {
    console.log('test: rendering');
    let style = {
      paddingTop: Spacing.desktopKeylineIncrement
    }
    return (
      <div style={style}>
        <Field cursor={this.getCursor(['fields',0])}/>
        <Field cursor={this.getCursor(['fields',1])}/>
        <div>{this.state.data.toString()}</div>
      </div>
    );
  }
};
```

**Comment by kalken** [comment]
The original problem it solves is that we don't have to send a bunch of properties and set a bunch of states. Imagine the "Field"-class being 3-4 steps down in a chain (as it easily could be if we treat each individual component in a form as its own instance), and it's easy to see how complicated things get without this (e.g i would have to set a lot of function in each class down the chain just to handle a state change at the top level...

Also note that implementing some kind of history state would be a one-liner because
```
getCursor(path) {
    return (
      Cursor.from(this.state.data, path, newData => {
        //triggers everytime a child cursor updates.
        //access to both this.state.data (old state) and newData (new state).
        this.setState({data: newData});
      })
    );
  }
```

**Comment by Dashed** [comment]
One issue I have with `shouldComponentUpdate(nextProps)` implementation detail is that `this.props.cursor.equals(nextProps.cursor)` does do a trivial equality. More details here: https://github.com/omniscientjs/omniscient/issues/104#issuecomment-109889726

**Comment by kalken** [comment]
My thought on the matter is along the lines of @mikaelbr https://github.com/omniscientjs/omniscient/issues/104#issuecomment-109889726

I was not sure how to do a proper comparison of pointers and i thought that equals did this (did not look at the source code though).

the code right now is based of https://www.npmjs.com/package/immutable-cursors which has a much richer documentation on how to use this cursor-thing.

questions @Dashed 
1. Would it be okay do always do === comparison in the shouldcomponentupdate method?
2. If you like my example can you please put something similar (and maybe some more examples up on the contrib/cursor-page so people know how to use it properly in the future? I think there are a lot of people out there who would like to use immutable as a state with cursors pointing to it from other components.

thanks guys for all your help so far! immutable is amazing, and cursors are a very good addition to this if its used right!

/K

**Comment by kalken** [comment]
Ok so i now have updated it to:
```
 shouldComponentUpdate(nextProps) {
        // This is as easy as it gets
        let shouldChange = !(this.props.cursor.deref() === nextProps.cursor.deref());
        //let shouldChange = !this.props.cursor.equals(nextProps.cursor);
        console.log('Should',this.props.cursor.get('label'),'update?', shouldChange)
        return shouldChange;
  }
```
It seems to work but i don't really know if this is the correct way of handeling it...

/K

**Comment by clouddra** [comment]
I have use the following snippet for to do a shallow compare for props that are passed down.
```
shouldComponentUpdate(nextProps) {
  for (const i in nextProps) {
    shouldUpdate = shouldUpdate || !Immutable.is(nextProps[i], this.props[i]);
  }
}
```
Immutable.is() does a reference comparison followed by a valueOf() comparison (a cursor dereference) if the references are found to be different. Therefore this should work for both cursors and immutable objects.

**Comment by mikaelbr** [comment]
@clouddra For the record, in Omniscient.js we've found `Immutable.is` to be far more expensive then a simple reference check. https://github.com/omniscientjs/omniscient/issues/104#issuecomment-109815813
