### ISSUE TITLE
Remove homogeneous collection API from records

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#505]
Records should not have the map/filter/reduce and other API methods useful for homogeneous collections like List and Map. Their operation does not do what is expected.
#220 #268

**Comment by negativetwelve** [comment]
I just ran into this issue and spent a while trying to debug it. Is there any way we can add this to the docs so that future developers don't spend a while debugging this issue? I'd be more than happy to make that change

**Comment by andrinealver** [comment]
:+1:

**Comment by anjianshi** [comment]
I found all methods that called `recordType.constroctor()` has problem, includes `merge` (actully `mergeIntoCollectionWith`).

```js
var R = Immutable.Record({});
var r = new R();
r.merge({});   // no problem, return "r" itself
r.merge({a: 1});  // return undefined
```

**Comment by AlexGalays** [comment]
Why remove them altogether though ? Record.map seems very useful for instance.

**Comment by leebyron** [comment]
Note when tackling this, ensure `isImmutable()` still returns true for record instances
