### ISSUE TITLE
React propTypes library for Immutable

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#509]
React's propTypes have a well defined API that allows for extension. Because `PropTypes.instanceof` does not play well with value types, It would be excellent to have a sister library of Immutable.js specific PropTypes.

**Comment by vtambourine** [comment]
Can you please explain a bit more what is wrong with `PropTypes.instanceof` validation? 

I use it my project as simple is:
```js
var Product = Immutable.Record({name: undefined});
var product = new Product();
product instanceof Product // true
product instanceof Immutable.Record // true
product instanceof Object // true
```

Hence, it work the same in React:
```js
class Cargo extends Component {
    static propTypes = {
        product: PropTypes.instanceOf(Product)
    }
}
```

**Comment by leebyron** [comment]
That specific example works, but not all examples work.

* A variation of `arrayOf(SomeType)` for `immutableListOf(SomeTime)` for example.
* Support for cursors.
* Support for the more basic interface types like `KeyedIterable`

**Comment by moretti** [comment]
@leebyron Have you tried https://github.com/HurricaneJames/react-immutable-proptypes?

**Comment by cesarandreu** [comment]
+1

**Comment by lacker** [comment]
I am going to close this issue under the theory that if it did not happen in Year 1, it will not happen. Feel free to object if there is some alternate theory for how this issue may become one day useful :P
