### ISSUE TITLE
Add JSCS tests

### ISSUE THREAD

**Issue by vtambourine** [facebook/immutable-js#512]
Since contributing guide mentions [code style rules](https://github.com/facebook/immutable-js/blob/master/CONTRIBUTING.md#coding-style), it worth to add JSCS style checking:

```
{
    "esnext": true,
    "validateIndentation": 2,
    "maximumLineLength": 80,
    "validateQuoteMarks": "'",
    "requireSemicolons": true,
    "requireCommaBeforeLineBreak": true
}
```

**Comment by lacker** [comment]
Since this is a "stylistic suggestion" and super old I am going to close the issue. Thanks for bringing this up!
