### ISSUE TITLE
Produce a diff from immutable objects?

### ISSUE THREAD

**Issue by steida** [facebook/immutable-js#52]
I would like to use immutable-js as diff for app state in the same manner as React diffs DOM state. Is this even posible? Can you direct me to the proper/better approach? I would like to store app state diff into localStorage and sync with server. Thank you for the awesome library.

**Comment by slorber** [comment]
@steida hi

Have you been successful with json patch?
I'm looking at how json state transitions can be recorded.
This is related to a video I just published: https://www.youtube.com/watch?v=zxN8FYYBcrI

**Comment by pedroteixeira** [comment]
I've using: https://github.com/intelie/immutable-js-diff e https://github.com/intelie/immutable-js-patch

**Comment by slorber** [comment]
thanks @pedroteixeira I didn't know about these projects

**Comment by Lendar** [comment]
Another lib for immutable.js diffs: https://github.com/elierotenberg/remutable — it's more polished, but currently supports only Map.

**Comment by ActiveObject** [comment]
@slorber, you can try [transit-js](https://github.com/cognitect/transit-js). I used it to serialize the history of application state for next transfering over the wire. You can add a cache on top of this library to serialize  immutable data structures efficiently. David Nolan wrote a post about this feature of transit - [Transit-js Caching](http://swannodette.github.io/2015/02/19/transit-js-caching/).

**Comment by granmoe** [comment]
It's been over a year. Any new resources for this? I have a similar need.

**Comment by jareware** [comment]
@granmoe FWIW, I'm using https://github.com/intelie/immutable-js-diff and it works really nicely.
