### ISSUE TITLE
Add `Map.of` and `OrderedMap.of`

### ISSUE THREAD

**Issue by hleumas** [facebook/immutable-js#523]
So it is consistent with other collections.

**Comment by leebyron** [comment]
Could you explain how you expect these static methods to act via example code? 

The same named static method on List or Stack accepts a variable list of arguments and builds a collection like `List.of(1, 2, 3)`, as a convenience to the slightly noisier `List([1, 2, 3])`.

**Comment by hleumas** [comment]
Well, instead of 

    Map([["a", 3], ["b", 4], ["c", 5]])

you would be able to write

    Map.of(["a", 3], ["b", 4], ["c", 5])

Just for convenience, it would be nice if every collection has `of` and it behaved like this:

    Coll.of(...val) => Coll(val);

**Comment by leebyron** [comment]
Just curious why you would prefer typing `Coll.of(...val)` instead of `Coll(val)`?

**Comment by leebyron** [comment]
We can do significantly more optimizations with `Coll(val)`, including structural sharing, which can't be done with `Coll.of(...val)` so I'm nervous about encouraging that sort of use.

**Comment by hleumas** [comment]
Of course, I would not type `Coll.of(...val)`. That was just implementation code:)

The same way I would prefer to type `List.of(1, 2, 3)` instead of `List([1, 2, 3])`, I would also prefer typing `Map.of(['a', 1], ['b', 2], ['c', 3])` instead of `Map([['a', 1], ['b', 2], ['c', 3]])`. I don't see much difference between those two cases and I just want them to be consistent.

**Comment by leebyron** [comment]
I'm actually leaning towards removing the `of` method in a future version. It was added for parity with [`Array.of`](https://gist.github.com/rwaldron/1074126#arrayof--variable-arity-) but notably `Array.of` serves a purpose that isn't particularly relevant for `List`.

**Comment by lacker** [comment]
It looks like the conclusion here is to leave as is, so I am going to close this issue. Thanks for bringing this up and sparking some discussion!
