### ISSUE TITLE
Let map accept optionally other collections

### ISSUE THREAD

**Issue by hleumas** [facebook/immutable-js#524]
Similarly to Python or Clojure way.
https://docs.python.org/3.5/library/functions.html#map
https://clojuredocs.org/clojure.core/map

    collA.map(f, collB, collC)
    // [f(collA[0], collB[0], collC[0]), f(collA[1], collB[1], collC[1]), ...]

It is backward compatible change, it is nice convenient and we don't need `zipWith` anymore.

**Comment by leebyron** [comment]
This is unfortunately not backwards compatible because the second argument of `map()` is the context `this` which will be passed to the mapping function, mirroring the `map()` API found elsewhere in the built in JS collection - hence the need for `zipWith` to handle this case.

**Comment by hleumas** [comment]
I see.
