### ISSUE TITLE
What is the point of update with single argument?

### ISSUE THREAD

**Issue by hleumas** [facebook/immutable-js#525]
I don't see a benefit of

```
update(updater: (value: Map<K, V>) => Map<K, V>): Map<K, V>
```

If I am right

```
map.update(f)
```

and

```
f(map)
```

Do the very same thing and the latter makes more sense.

**Comment by leebyron** [comment]
Correct. This is a relic of an earlier version of the API which had deeper integration with a specific cursor implementation but should now be considered deprecated.
