### ISSUE TITLE
Allow variadic number of arguments for update

### ISSUE THREAD

**Issue by hleumas** [facebook/immutable-js#526]
This would be nice

```
update(key, notSetValue, updater, ...args)
```

where `args` are additional arguments for `updater`.

It would basically be implemented like:

```
update(key, notSetValue, (v) => updater(v, ...args))
```

Nice thing is it enables composition of operations nicely. See how they use it in Clojure.
Also, it is backward compatible.

**Comment by leebyron** [comment]
Can I ask for some examples of when this is useful in practice? It seems reasonable, but currying arguments like this can often present a performance issue, so I want to ensure I'm supporting the use case you have in mind.

**Comment by hleumas** [comment]
Yes, let's say I have bought some new item and I am gonna update max cost I paid per item.
I could do it this way

    coll.update('maxCost', undefined, Math.max, itemCost)

Instead of

    coll.update('maxCost', undefined, (cost) => Math.max(cost, itemCost))

I find the former more readable.

**Comment by leebyron** [comment]
Thanks :)

**Comment by hleumas** [comment]
I could create a pull request, if you like:)

**Comment by lacker** [comment]
Thanks for the suggestion! We're going to pass on this for now while we focus on fixing broken and embarassing things but if a number of people end up clamoring for this then we are open to reconsidering.
