### ISSUE TITLE
Allow variadic number of arguments for set

### ISSUE THREAD

**Issue by hleumas** [facebook/immutable-js#527]
It would be nice if could just use

```
map.set(key1, val1, key2, val2, key3, val3, ...)
```

Instead of

```
map.set(key1, val1).set(key2, val2).set(key3, val3)
```

The former is bit more readable. Also, it is backward compatible.

**Comment by lacker** [comment]
Thanks for the suggestion! We're going to pass on this for now while we focus on fixing broken and embarassing things but if a number of people end up clamoring for this then we are open to reconsidering.
