### ISSUE TITLE
Introducing immutablejs in an existing application

### ISSUE THREAD

**Issue by b-3-n** [facebook/immutable-js#530]
Scenario: Introduce immutable js into an existing application. Data from the server is received, should be rendered immutable and then be used throughout the app. Using fromJS() on the received data is conceptually fine, however the application contains a lot of code accessing the received data via '.' for objects and [] for arrays. Thus a large refactoring would be required, introducing .get() calls everywhere.

Is there a simple way that would not require to refactor all the read accesses?

**Comment by phillipCouto** [comment]
My personal suggestion would be to have a local variable representing the data at the top of a function. There you can use the .toObject, .toArray, .toJS methods to maintain the '.' access pattern but guarantee that your code in the function can't mutate the variable outside of the local instance.

Example:
```js
function processData() {
   var result = restData.toObject();

   console.log(result.ID);
}
```

This does not prevent your code within the function mutating the local result variable but at least the mutation is contained and won't pollute the external reference.

**Comment by lacker** [comment]
Sounds like this question is answered, so I am going to close the issue. Thanks!
