### ISSUE TITLE
Record merge should return same record if unchanged

### ISSUE THREAD

**Issue by mockdeep** [facebook/immutable-js#536]
I'm testing this out in the console and `Record` does not seem to behave the same way as `Map` when merged with unchanged attributes:

``` js
Reclass = Immutable.Record({a: '1', b: '2'})
> function Cr/r()
r1 = new Reclass()
> Object { _map: Object }
r2 = new Reclass()
> Object { _map: Object }
r3 = r1.merge(r2)
> Object { _map: Object, __ownerID: undefined }
r3 === r1
> false
```

Whereas with a `Map`:

``` js
m1 = Immutable.Map({a: '1', b: '2'})
> Object { size: 2, _root: Object, __ownerID: undefined, __hash: undefined, __altered: false }
m2 = Immutable.Map({a: '1', b: '2'})
> Object { size: 2, _root: Object, __ownerID: undefined, __hash: undefined, __altered: false }
m3 = m1.merge(m2)
> Object { size: 2, _root: Object, __ownerID: undefined, __hash: undefined, __altered: false }
m3 === m1
> true
```

**Comment by mockdeep** [comment]
It's unclear to me how to tell the type of the object being created, but as near as I can tell, calling `merge` on a `Record` actually returns a `Map`.

**Comment by jareware** [comment]
@mockdeep it does. :+1: for this!

**Comment by jareware** [comment]
Should I open a separate issue for the 2nd point in my above comment..?

**Comment by lacker** [comment]
It looks like this issue has been fixed by the referenced PRs so I am going to close it.
