### ISSUE TITLE
Record constructors should throw an error when receiving undefined value

### ISSUE THREAD

**Issue by vitalybe** [facebook/immutable-js#537]
Per [documentation](https://facebook.github.io/immutable-js/docs/#/Record):

> Values provided to the constructor not found in the Record type will be ignored

This behavior makes it very easy to change the constructor and forgetting to change the type itself. The leads to unnecessary and long debug cycle, in which one tries to understand why the value on the object is "undefined", even though it was set.

Is there a reason to this behavior? What are the disadvantages of throwing an exception right away?

**Comment by threehams** [comment]
Throwing an error as default behavior could be _very_ risky as default behavior - take the case where data is pulled from an API and sent into a record. Adding a new property to an API response would become a breaking change to a production site, when normally, the extra property would just be ignored.

However, I've also been burned by the silent ignores, especially when writing tests which do comparisons against records, so it would be great as an opt-in feature. I'm currently wrapping records to check for extra properties and log a warning when extra attributes are sent in, but it's be much cleaner to add warn/error as an optional third argument to the Record constructor itself. Something like:

`Record({}, null, { strict: 'warn' })`
`Record({}, null, { strict: 'error' })`
(note, there's a second argument marked "name", although I'm not sure exactly what it does)

I can work on a pull request, but it'd be nice to know if there's enough interest before putting in the work.

**Comment by leebyron** [comment]
Closing this aging issue

It's not uncommon to create Records from a larger input data source.

For type safety concerns like this where a typo can cause a huge headache, I strongly recommend static type checking tools like Flow or TypeScript.
