### ISSUE TITLE
Implementing the transducers protocol

### ISSUE THREAD

**Issue by acdlite** [facebook/immutable-js#538]
Would you accept a PR to update ~~Map and~~ List (and any other types that make sense) to support the transducer protocol? Like this: https://github.com/jlongster/transducers.js#the-transducer-protocol It should be a minimal addition.

Sorry if this has been asked and answered already. I did a search and only found this comment https://github.com/facebook/immutable-js/issues/23#issuecomment-60796072

**Comment by leebyron** [comment]
Go for it!

**Comment by KyleAMathews** [comment]
:100:

**Comment by acdlite** [comment]
@leebyron Great! I'll add it to List, Set, and Stack. Keyed collections like Map don't make sense, unless I mistaken.

**Comment by Dashed** [comment]
@acdlite Any Immutable collection that is iterable should work (this includes Map).

For Map, the merge operation would probably be suitable for the `@@transducer/step` protocol.

**Comment by DaleJefferson** [comment]
@acdlite What are the advantages in using transducer.js over using immutable.Seq?
If transducer.js is better than Seq should it be replaced? Or do they do different things?

**Comment by dnalot** [comment]
Stumbled on this and wondered why it stagnated? The PR looks superficially solid besides needing feedback for tests,

**Comment by leebyron** [comment]
I still think this one is a pretty cool idea - though I've been out of the loop on how often transducers are being used.

**Comment by mhelmer** [comment]
Seems like the PR got closed due to lack of tests. If `transducers.js`or `transducers-js` was added as a `devDependency`, it wouldn't be hard to test it using `transduce`, `into` and so on. Could definitely look into it.

**Comment by leebyron** [comment]
Better late than never
