### ISSUE TITLE
.setSize() retains values previously discarded with .slice()

### ISSUE THREAD

**Issue by vlinder** [facebook/immutable-js#540]
```js
Immutable
    .fromJS([1,2,3,4,5])
    .slice(0,2)
    .setSize(5)
    .forEach(function(val){console.log(val)});
```
Outputs:
```
1
2
3
4
undefined
```

One would not think that you get the values removed by slice back again by setting size. Somehow the last value is the only one which actually gets removed.

From the documentation of setSize()
>If size is greater than this List's size, the new List will have undefined values for the newly available indices.

Same output when using using .setSize() twice instead of slice().
```js
Immutable
    .fromJS([1,2,3,4,5])
    .setSize(2)
    .setSize(5)
    .forEach(function(val){console.log(val)});
```

Might be browser specific?
### Tested with
* Chrome Version 43.0.2357.130 (64-bit) on OS X 10.10.
* Firefox 38.0.5 on OS X 10.10
* Firefox 39.0 on OS X 10.10
* Chromium 43.0.2357.132 on Arch Linux

**Comment by leebyron** [comment]
Thank you for the report
