### ISSUE TITLE
Error in documentation for Map.toList()

### ISSUE THREAD

**Issue by nidu** [facebook/immutable-js#557]
Hello,

Documentation for [`Map.toList()`](http://facebook.github.io/immutable-js/docs/#/Map/toList) method says:

> Note: This is equivalent to List(this), but provided to allow for chained expressions.

However these approaches give different results (example [here](https://jsfiddle.net/jzysqg41/)):

``` js
var map = Immutable.Map({a: 1, b: 2});
Immutable.List(map); // List [ a,1, b,2 ]
map.toList(); // List [ 1, 2 ]
```

Is it documentation incorrectness, wrong behavior or my misunderstanding?

**Comment by tphyahoo** [comment]
I'm a newbie, but I think you're misunderstanding.

Looks like the behavior is to construct a list out of the values in your dictionary, which would make sense.

Recommend closing this issue.

**Comment by nidu** [comment]
@tphyahoo Behaviour is clear. I'm just saying that these operations don't look equivalent as documentation states.

**Comment by tphyahoo** [comment]
I see what you mean now.

I think documentation should read

This is equivalent to List(this.values())

**Comment by tphyahoo** [comment]
(untested)

**Comment by leebyron** [comment]
Thanks for the report, @tphyahoo - you're correct that the documentation isn't correct here. I'd actually like to change the behavior in 4.0 to match the documentation as a simplicity force.

**Comment by kuailingmin** [comment]
@leebyron 
      Hello, I was a novice, I looked Immutable.js period of time, did not know specifically what to do? Just the data processing? What are its benefits? Can you give me explain?
