### ISSUE TITLE
Splice with negative index crashes on a filtered seq

### ISSUE THREAD

**Issue by medmunds** [facebook/immutable-js#559]
This code generates an infinite recursion in sliceFactory, on the `splice` call with a negative index. 

```javascript
    var dog = Immutable.Seq(['d', 'o', 'g']);
    var dg  = dog.filter(c => c !== 'o');
    var dig = dg.splice(-1, 0, 'i');
```

The filter step is required to see the problem. And an index >= 0 in splice works just fine.

Results:
```
 RangeError: Maximum call stack size exceeded
        at wholeSlice (/immutable-js/dist/immutable.js)
        at sliceFactory (/immutable-js/dist/immutable.js:1292:9)
        at sliceFactory (/immutable-js/dist/immutable.js:1303:14)
        at sliceFactory (/immutable-js/dist/immutable.js:1303:14)
        ...
```

(Aside: TypeScript doesn't seem to believe the result of the filter allows splice, which also seems wrong. But even adding an explicit toIndexedSeq to keep TypeScript happy doesn't solve the issue.)

Maybe related to #459?

[Immutable 3.7.4; seems to still be true in master]

**Comment by leebyron** [comment]
It definitely is related, thank you for the report!
