### ISSUE TITLE
Inheriting from Immutable object with ES6

### ISSUE THREAD

**Issue by FredyC** [facebook/immutable-js#562]
This is really odd, I've made really simple example: http://codepen.io/FredyC/pen/vOVmwK?editors=001

In console you can see "Maximum call stack size exceeded" which is rather weird. Does that mean that it's impossible to use ES6 inheritance with ImmutableJS?

I think it would be very helpful if source code would be part of NPM. That way we could transpile the code with Babel too.

**Comment by leebyron** [comment]
ImmutableJS in fact does not support class-based inheritance. The current source class syntax is really misleading and I apologize for that, it's not actually creating an ES6 class. I'm working on a set of changes that will allow us to move away from the non-standard class syntax.

**Comment by AsaAyers** [comment]
Is `Immutable.Record` an exception here? This code seems to work:

```
const R = Immutable.Record({a: 1})
class TGRow extends R {
}
```

**Comment by FredyC** [comment]
Yeah, I believe this is exception. Looking at the [source code](https://github.com/facebook/immutable-js/blob/master/src/Record.js#L42-L45) it just returns standard constructor function.

**Comment by mntnoe** [comment]
@leebyron Did you make any progress in supporting inheritance?

It would be very valuable for us to create `List` subclasses with domain specific methods, for instance

- `MyList.byAuthorId(id)` (to support lookup via a cache in O(1))
- `MyList.getTotal()`
- `MyList.updateSomething(x) `

Using rich models enables us to encapsulate domain behavior into the model layer (or stores/reducers etc), easing the complexity on the view. This way we could combine the best things from OOP and functional programming.

**Comment by philpl** [comment]
Sorry, for commenting on such an old issue, but this was being discussed in #301. I've written a library that makes extending Immutable.js possible, but it doesn't look like this will be a goal for Immutable itself.

> For anyone who's still interested in this, I wrote an extendable-immutable package, similar to @jdfreder's one, but with complete expected behavior: it can be extended multiple layers deep, it doesn't break the prototype chain at all (f.e. Map.isMap and x instanceof Map would pass), it doesn't break mutable operations etc.

https://github.com/philpl/extendable-immutable
