### ISSUE TITLE
Preserving shallow copy when performing Immutable.fromJS()?

### ISSUE THREAD

**Issue by yaru22** [facebook/immutable-js#563]
Is there a way to preserve shallow copy when performing Immutable.fromJS()?

For example,

``` js
a = [1, 2, 3]
b = { copy1: a, copy2: a}
console.log(b.copy1 === b.copy2);  // true

immB = Immutable.fromJS(b);
console.log(immB.get('copy1') === immB.get('copy2'));  // false
```

I'd like to convert `b` to an Immutable Map so that `immB.get('copy1') === immB.get('copy2')`. Is it possible to do that?

Thanks!

**Comment by leebyron** [comment]
At present, no this is not possible. Doing so would be a pretty significant performance penalty on `fromJS()`. 

It's also not recommended to rely on object identity when inspecting Immutable value equality. You might want to use `Immutable.is()` to compare the two values.

**Comment by lacker** [comment]
It looks like this question is answered so I am going to close the issue!
