### ISSUE TITLE
Support extensible destructuring

### ISSUE THREAD

**Issue by hleumas** [facebook/immutable-js#568]
What do you think about supporting extensible destructuring described here:
https://github.com/vacuumlabs/es-proposals/blob/master/extensible-destructuring.md

There is currently babel plugin for that:
https://www.npmjs.com/package/babel-plugin-extensible-destructuring

**Comment by hleumas** [comment]
Or at least, it would be nice to mention that in docs:)

**Comment by leebyron** [comment]
Closing this aging issue - sorry for letting it sit. Excellent work, @hleumas! Please feel free to add the package to the wiki on this repo!
