### ISSUE TITLE
Most efficient way of building an indexed collection

### ISSUE THREAD

**Issue by jsilvestre** [facebook/immutable-js#57]
Hello and thank your for the work here. It works like a charm with React and Flux :)

While the documentation is complete, it kinda lacks real life examples, and since I'm new to the immutable world, I have a hard time figuring out which structure I should pick in which case.

I'm not sure it's a good thing I open a new issue each time I struggle with something (that is going to happen) so maybe I could ask them all here and then bundle your answers in a PR so it can help other newbies.

I think my main use case (and many real life use cases) is: I get JSON from the server, it looks like:

``` json

[
  {
    "id": "aze12",
    "someField": "someValue",
    ....
  },
  {
    "id": "67azea",
    "someField": "someValue",
    ....
  }
]
```

I think the natural way of storing with Immutable is using OrderedMap. But what is the best way of building the map with "id" or "someField" as the index?
Currently I create an empty OrderedMap, then iterate over my parsed data, and set them one by one within a `withMutations`. It doesn't feel intuitive, what do you think?

Thank you in advance.

**Comment by jardakotesovec** [comment]
This thread was very helpful :+1: 

I adjusted code to use it as reviver, so it automatically detects arrays with objects having id property:
```
var imm = Imm.fromJS(dummyData, function (key, value) {
    var isIndexed = Imm.Iterable.isIndexed(value);
    if (isIndexed) {
        if (value.getIn([0,'id'])) {
            return value.toKeyedSeq().mapKeys((_, v) => v.get('id')).toOrderedMap()
        }
        else {
            return value.toList();
        }

    }
    else {
        return value.toMap();
    }
});
```

Its pretty hard see what exactly is going on behind the scene. So if there is better way to do that, please let me know, so I don't waste performance :-).

Thanks!

**Comment by bsr203** [comment]
@leebyron how the original requirement can be done now. Your one liner, `Imm.Sequence(data).mapKeys((_, v) => v.id).map(v => Imm.Map(v)).toOrderedMap();`, not work now due to api change. I don't see any reference of `mapKeys` in public api, is it supported? Also, `Sequence -> Iterable` ?

**Comment by jsilvestre** [comment]
It still exists, but is now part of Map: https://facebook.github.io/immutable-js/docs/#/Map/mapKeys

That means OrderedMap also has it.

**Comment by bsr203** [comment]
Apologies. I did a ctrl +F and didn't find. Anyway, this what I tried, `Imm.Iterable(data).mapKeys((_, v) => v.id).map(v => Imm.Map(v)).toOrderedMap();`, just changing `Sequence -> Iterable` as per the API upgrade doc. it gave error Iterable doesn't have mapKeys. so,  what is the most efficient way to do what you asked in the functional style? thanks gain for quick response.

**Comment by jsilvestre** [comment]
You could try `Imm.**Keyed**Iterable(data).mapKeys((_, v) => v.id).map(v => Imm.Map(v)).toOrderedMap()`
You mispelled forgot the "Keyed" of "KeyedIterable".

**Comment by bsr203** [comment]
thanks. it worked great. the doc says `Note that OrderedMap are more expensive than non-ordered Map and may consume more memory. `. Do you know any numbers on this, and when should I worry using OrderedMap, and consider Map?

**Comment by jsilvestre** [comment]
I will let @leebyron answer that since it goes beyond my knowledge. I'm quite interested in the answer too. Also, how does an OrderedMap perform vs a List with a Map kept in sync (where the List maintains the order, and the Map is for quick access by key)./

How would perform an OrderedMap vs a List with a Map kept in Sync (where the List would

**Comment by bsr203** [comment]
Indeed, I was using the same pattern of keeping a separate index prior to the use of immutable.js.

**Comment by bsr203** [comment]
sorry, my changes didn't reflect, `Imm.**Keyed**Iterable(data).mapKeys((_, v) => v.id).map(v => Imm.Map(v)).toOrderedMap()` didn't really work. probably because KeyedIterable expects a `iterable-likes of [K, V] tuples if not constructed from a KeyedIterable or JS Object.`. so can't use it with a javascript array of input.

**Comment by jsilvestre** [comment]
Maybe you could create `Imm.OrderedMap` directly. I think, when built from a JS object it uses "0", "1", ... as index.

**Comment by bsr203** [comment]
![screen shot 2015-05-25 at 8 38 34 am](https://cloud.githubusercontent.com/assets/1966521/7797410/a6c1e51e-02b9-11e5-865d-53e23f7d1765.png)

:-) not sure why KeyedIterable not found!

**Comment by kentor** [comment]
Resurrecting: isn't something like this more readable and faster:

`Immutable.OrderedMap(data.map(o => [o.id, Immutable.Map(o)]))`

http://jsperf.com/immutable-ordered-map-construction

**Comment by Sebdevar** [comment]
Thx for the thread, really interesting info that was useful for my work.
