### ISSUE TITLE
hasIn works differently when Maps are created with the fromJS method

### ISSUE THREAD

**Issue by Carlsson87** [facebook/immutable-js#572]
My problem is best explained with code.

````
var mapOne = Immutable.Map({one: []});
var mapTwo = Immutable.fromJS({one: []});

mapOne.hasIn(['one', 'two']); // false
mapTwo.hasIn(['one', 'two']); // true
````

Am I missing something obvious here? If so, educate me please.

**Comment by volkanunsal** [comment]
The first example creates a shallow Map. The second one creates a deep map, converting the array into a List. That's why you are getting different reads from hasIn. This is explained in the [wiki.](https://github.com/facebook/immutable-js/wiki/Converting-from-JS-objects)

**Comment by Carlsson87** [comment]
Thanks @volkanunsal =)
