### ISSUE TITLE
mapEntries mutates immutable records

### ISSUE THREAD

**Issue by kire321** [facebook/immutable-js#574]
This test fails:

```
        var Range = Immutable.Record({
            from: null,
            to: null,
        })
        var range = new Range({from: 0, to: 1})
        assert.strictEqual(range.from, 0)
        assert.strictEqual(range.to, 1)
        var returnValue = range.mapEntries(() => {})
        assert.strictEqual(range.from, 0) //fails here
        assert.strictEqual(range.to, 1)
```

using immutable version 3.7.4. Based on the docs, I expect that `range` will be unchanged and `returnValue` will be created based on the map function. What actually happens is that range is modified based on the map function.

**Comment by cassus** [comment]
:+1:

**Comment by charliematters** [comment]
+1

This applies to the filter function as well

**Comment by notatestuser** [comment]
Bump. Encountered this today. This is very strange.

**Comment by notatestuser** [comment]
Here is a quick patch that solves this (in pseudocode - I haven't looked at this project's sources):
```js
mapEntries(mapper) {
  return new this.constructor(this.toMap().mapEntries(mapper))
}
```

**Comment by leebyron** [comment]
Merging into #505 

The `map` family should not belong on Records at all - `map` is for homogenous collections with Record is not.
