### ISSUE TITLE
Facebook Community Bot Messages

### ISSUE THREAD

**Issue by mindjuice** [facebook/immutable-js#576]
I've got like 100 messages in my inbox saying:

"Thank you for reporting this issue and appreciate your patience. We've notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed."

Are these repeated messages really necessary or helpful?  Especially since this project is so actively maintained.

I can certainly filter them out, but why force thousands of people to filter them when you could just not send them.

Thanks.

**Comment by leebyron** [comment]
I apologize for this. Unbeknownst to me, the open-source bot had a well-intentioned change recently that resulted in this noisiness. I will make sure this feedback is carried on to the responsible team.

**Comment by mindjuice** [comment]
Thanks.  Just FYI, I got another batch of 20 or so of these all received at 11:03am today (Pacific Time).

**Comment by leebyron** [comment]
Thanks for letting me know. I got them as well and the team responsible for the bot is trying to make it more helpful and less noisy.
