### ISSUE TITLE
Just want to say thanks

### ISSUE THREAD

**Issue by nathanjsharpe** [facebook/immutable-js#580]
A Github issue is probably not the right place for this, but I've had such a great experience using Immutable over the last few weeks that I'm compelled to say thank you somehow. 

I've been moving an existing React app to Immutable, and I've seen significant performance gains and much simpler, cleaner, easier to understand code as a result. Immutable has just been a pleasure to use in so many ways, and I think I'm a better (certainly happier) developer for having used it. 

So to @leebyron and all the other contributors, **thank you** for your hard work on a wonderful project! I really appreciate what you've done with Immutable and hope to contribute myself someday, even if just documentation patches (step 1: move past feeling like I have nothing to contribute).

**Comment by jareware** [comment]
Not sure if this is the right place, either, but... I fully agree. :smile:

**Comment by leebyron** [comment]
![](https://media.giphy.com/media/1guRIRO0SdOsRBDfL2M/giphy.gif)

![](https://media.giphy.com/media/Z9LMuhfk8iRuU/giphy.gif)

![](https://media.giphy.com/media/krOVpoDFxXgc0/giphy.gif)

![](https://media.giphy.com/media/a3IWyhkEC0p32/giphy.gif)

![](https://media.giphy.com/media/OtbZhLpNLxDoc/giphy.gif)
