### ISSUE TITLE
Get non-string key from Map

### ISSUE THREAD

**Issue by colindresj** [facebook/immutable-js#581]
I'd like to take advantage of Maps not requiring strings as key. Is it currently possible to declaratively get a value in a Map by key of type tuple? IE, something like `map.get(['something', 1]) // => my value`

**Comment by leebyron** [comment]
Yes, this works today!

```js
import { List, Map } from 'immutable';
var map = Map();
map = map.set(List(['something', 1]), "pair");
console.log(map.get(List(['something', 1]))); // "pair"
```

The Map keys are looked up based on *value*. This means you cannot create a new array to set and get from a Map. This will not work the way you expect:

```js
import { List, Map } from 'immutable';
var map = Map();
map = map.set(['something', 1], "pair");
console.log(map.get(['something', 1])); // undefined
```

For the same reason:

```js
var a = ['something', 1];
var b = ['something', 1];
console.(a === b); // false
```

This is also exactly how ES6 maps work:

```js
var map = new Map(); // ES6 map
map.set(['something', 1], "pair");
console.log(map.get(['something', 1])); // undefined
```
