### ISSUE TITLE
Making immutable function closures

### ISSUE THREAD

**Issue by jannavarro** [facebook/immutable-js#583]
To create an immutable it needs an object. e.g: var map1 = Immutable.Map({a:1, b:2, c:3});

With ES6 comes classes that when transpiled becomes function closures. Is there current or upcoming support to create a way to pass in a class and make its properties immutable? e.g: 

let rm = new RoleManager; //where RoleManager is an ES6 class
var immutableRoleM = Immutable.makeImmutable(rm); //sample method

A use of this that I can think of is similar to what clojure immutable global app state. From this [blog](http://blog.circleci.com/local-state-global-concerns/): "all components store their state in a global data structure."

**Comment by leebyron** [comment]
You should check out [Record](http://facebook.github.io/immutable-js/docs/#/Record) which can work well as a Class substitute.
