### ISSUE TITLE
Document operation complexity and/or performance

### ISSUE THREAD

**Issue by rattrayalex** [facebook/immutable-js#584]
While premature optimization is the root of all evil, and developers should typically profile their own application and optimize from there, it can be frustrating to go into a project without knowing the basics of the performance profiles of Immutable's `Map` v. `List`, say, or whether `splice` will perform dramatically different performance than `pop`. 

Having a rough, basic understanding of these things can be helpful when a developer is setting out to architect part of an application. It could be even more helpful, perhaps, when optimizing: "okay, so the profiler tells me this operation I'm performing is slow, what could I use instead that would be faster?"

**Comment by rattrayalex** [comment]
For example, the `List` docs include this helpful section: 

```
   * Lists are immutable and fully persistent with O(log32 N) gets and sets,
   * and O(1) push and pop.
   *
   * Lists implement Deque, with efficient addition and removal from both the
   * end (`push`, `pop`) and beginning (`unshift`, `shift`).
```

It would be lovely to also have the methods documented like so: 

```
    /**
     * Returns a new List with the provided `values` appended, starting at this
     * List's `size`.
     * O(1).
     */
    push(...values: T[]): List<T>;
```

**Comment by derfloscher** [comment]
+1

**Comment by AbrahamAlcaina** [comment]
@rattrayalex really good idea +1

**Comment by rattrayalex** [comment]
Thanks! I also mentioned this [on hn](https://news.ycombinator.com/item?id=10060770), where user chenglou had these helpful counterpoints: 

> Listing complexity doesn't really help here. There's a huge difference in practical complexity than the theoretical one. Saying that "insert" has log(n) complexity is misleading when you realize the branching factor is 32. Likewise, "compare" has log(n) or mostly constant complexity in most real-life settings where you're comparing against a value that was calculated from the one you're comparing against (so shares lots of subtrees by reference). You're not e.g. sending back a fresh new copy of the data from the server to compare against. Immutable-js _could_ put "it's linear theoretically but most of the time it's really almost constant time", but that doesn't help much either.

> Is it blasphemous to say that looking at runtime complexity is gradually becoming more of a premature optimization (thanks to better hardware)? You can argue all day long that your js object has constant insertion time, but the underlying implementation makes it an order of magnitude slower than array for a limited number of fields. And if you accidentally trigger the hidden class deopt that turns it into a hash map that's another order of magnitude slower. No amount of ordinary complexity analysis will help you here. Vice-versa, when Babel gradually starts supporting constant lifting for collections (somehow), you can look at a piece of code in your editor, reason that a comparison is linear, but then have the transpiler lift it out (`const liftedA = []; function foo() {return liftedA;}` instead of `function foo() {return [];}`) and not realizing yourself that the comparison is actually constant time (reference comparison). And then, if you write some overly clever optimization for that piece of code yourself, you might ironically get worse perf because the transpiler can't lift the collection anymore.

I'd leave it to the maintainers to say whether this is a good idea or not after all.

**Comment by leebyron** [comment]
Maybe @chenglou should write that up in a wiki page here, good stuff!

But generally I agree with the suggestion here to add more detail on runtime expense, at least with a time order and ideally a little more flavor on the typical vs worst case vs amortized. 

I would be happy to entertain PR on these!

**Comment by chenglou** [comment]
You know what'd be great? If lazy seq cached so that get would be amortized O(1) instead of O(n).

Just trolling =) I'll put a rephrased version in the wiki later.

**Comment by rattrayalex** [comment]
Cool. I'd be happy to help if there's any grunt work that could be offloaded to someone who doesn't know the codebase (let alone the perf characteristics).

**Comment by leebyron** [comment]
This task is definitely still high value for any contributors.

The source of truth for documentation are the comments in type-definitions/Immutable.d.ts
