### ISSUE TITLE
List unshift bug

### ISSUE THREAD

**Issue by olgabanis** [facebook/immutable-js#585]
List unshift adds the unshifted item in root and not in tail.
I believe that this is not the desired behavior, as this way we don't have access to the new item in the list. 

Example: 
```
let x = new Immutable.List(['b','c','d']);
let y = 'a';
x = x.unshift(y);
````
Now the array in x is still ['b','c','d'] and 'a' has been added somewhere deep inside root. 

Best

**Comment by dozoisch** [comment]
I just tried in babel-node and here is my output

```
> let x = new Immutable.List(['b','c','d']);
> let y = 'a';
> x
List [ "b", "c", "d" ]
> y
'a'
> x = x.unshift(y)
List [ "a", "b", "c", "d" ]
````

It seems to be alright. So I'm not sure I understand what the problem is.
