### ISSUE TITLE
forEach for OrderedMap doesn't return interator param

### ISSUE THREAD

**Issue by globexdesigns** [facebook/immutable-js#586]
Consider:

```
Immutable.OrderedMap(...).forEach(function (item, i) {
	// Here I'm expecting 'i' to be 0, 1, 2, 3 etc...
	// However, it's actually the value of whatever the OrderedMap is keyed off
});
```

Why is this? In regular Javascript, when you iterate using forEach, the second param is always the iteration index.

**Comment by kentor** [comment]
It makes sense for Maps, and it matches the spec: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach. My question is why do you care about the index?

**Comment by globexdesigns** [comment]
Ok that makes sense. I guess I'm still struggling with the different between OrderedMaps and Lists and when to use what. In my head, I way to create a collection (array) of objects (maps). In ImmutableJS it seems the best way to do this is to create an OrderedMap (a map) or Records (another map). At one point, I want to loop over the OrderedMap and render each item (say in a table). For this I need an index.

I suppose I can just use `MyOrderedMap.toArray.forEach` instead.

**Comment by leebyron** [comment]
I would suggest:

```js
var index = 0;
myOrderedMap.forEach(function (item) {
  // do what you need to do with item and index
  index += 1;
});
```

As this will reduce the need to build a new structure, as `toArray` would.

Also, you may re-evaluate your use case and prefer to use a `List` if your primary need is to iterate over in a specific order with incrementing indices akin to an Array. `OrderedMap` is designed to mirror the behavior of the native `Map` and in many ways is similar to the native `Object`. Both of these native collections are not indexed, however happen to iterate over their entries in the order in which they were inserted (insertion order). Immutable.js's unordered `Map` does not make this iteration ordering guarantee, but has considerably better performance at nearly all operations and lower memory usage, as maintaining insertion ordering is not free.

**Comment by leebyron** [comment]
Another way to think of this is:

Would I usually use an Array? Use an `Immutable.List`.

Would I usually use an Object or ES6 Map? Use an `Immutable.Map`

But I need to preserve that insertion-ordering iteration order quirk JavaScript Objects have! Use an `Immutable.OrderedMap`

**Comment by globexdesigns** [comment]
Thanks for that @leebyron. The most common use case for us are lists like this:

```
var collection = [{
	id: 1,
	key: 'val'
}, {
	id: 2,
	key: 'val'
}]
```

And our requirements are:
- Good performance for looking up objects via 'id' - as that will be very common (therefore `Immutable.Map` is probably best)
- Order of objects is important, as these objects may be reordered by the user via a UI (therefore `Immutable.OrderedMap` sounds better)
- To allow for custom re-ordering we want ability to get the order index of an item by id, ie. User drags object id 2 into position 1, therefore we want ability to do `collection.indexOf({id: 1})` to get it's index (therefore `Immutable.List` sounds closer to what we need).

Hence the confusion. But it sounds like OrderedMap is still the way to go for this based on what I'm reading. We'll just have to convert it to an array whenever we need index values.

**Comment by leebyron** [comment]
Depending on how long these lists actually are, you may be better off sticking with a `List` and using the `find` method if you need to lookup by `id`.

Another thing you may consider is keeping both a `List` and `Map` together in parallel. Use the `List` when you need to work with orderings, use `Map` as a lookup from `id` to value. This is roughly how `OrderedMap` works.

**Comment by Kay2dan** [comment]
Apologies for bringing this up again now, I was confused by this & raised a question on SO to seek clarification. My impression was that immutable.js follows closely the convention that native functions have. Ala, `map` & `filter`, `forEach` should also follow the convention.

In my current use-case, I need a Map, which is also used in a function to identify which of its properties has a particular value, the function returns the index of the object holding the property. 

My understanding was that post `for` loop time, the new method to use for side-effect loop is `forEach`.
