### ISSUE TITLE
Record objects always empty unless accessed via _map

### ISSUE THREAD

**Issue by globexdesigns** [facebook/immutable-js#587]
I'm a bit confused about Record objects. Consider this:

```javascript
var Car = Immutable.Record({});
var Honda = new Car({test: 1});

console.log(Honda.get('test'))
// => null

console.log(Honda.toJS())
// => {}

console.log(Honda._map.get('test'));
// => 1

console.log(Honda._map.toJS());
// => {test: 1}
```

Why are all the properties and methods not working unless I use the '_map' property?

**Comment by leebyron** [comment]
Records are defined with an explicit set of allowed keys.

So when you write:

```
var Car = Immutable.Record({});
```

You're defining `Car` as a kind of Record that always has 0 keys.

**Comment by globexdesigns** [comment]
Ah, that makes sense. The documentation definitely didn't make this clear.

Overall, I'm finding documentation very difficult for this library. It's really great at describing the inner working details of each data type, but what's missing are examples of how and when to use the various methods. I have no idea when to use Maps vs OrderedMaps vs Records vs Lists, etc...
