### ISSUE TITLE
Immutable.Map().get() does not treat integers the same as {}[]

### ISSUE THREAD

**Issue by jlucas91** [facebook/immutable-js#588]
Hi all,

I'm fairly new to JS so I might be missing something, but it seems like Immutable.Map().get() should treat integers the same way as standard object access. For example:

> Immutable.Map({1:2}).get(1)
undefined

> var x ={1:2}
undefined
> x[1]
2

You need to convert to a string to use .get() which seems error prone and cumbersome.
> Immutable.Map({1:2}).get('1')
2

**Comment by leebyron** [comment]
The issue here is not in Immutable, but JS objects. JS object properties are *always* strings.

```js
var x = { 1: 2 }; // { "1" : 2 }
var keys = Object.keys(x); // [ "1" ]
```

When you access a property using square-bracket notation, that value first gets coerced into a string before looking it up in the JS Object.

**Comment by leebyron** [comment]
Map, on the other hand, does not coerce to string first. Maps (ES6 Maps and Immutable.js Maps) allow you to store any kind of value as keys, strings, numbers, other Objects.

**Comment by jlucas91** [comment]
Ah, that makes sense. Thank you for the clarification!

**Comment by samwgoldman** [comment]
Just from watching this repo, I feel like this confusion is pretty common. I looked to see if there was anything in the docs calling it out as a common pitfall, but couldn't find anything. I'd be happy to contribute the documentation, but I'm not sure where it should go. The README? The docs for the [Immutable.Map constructor](http://facebook.github.io/immutable-js/docs/#/Map/Map)?

**Comment by leebyron** [comment]
I would love to entertain that kind of change to the docs!

**Comment by alvaromb** [comment]
Sorry to re-open this issue, but I have a question. If we fetch a JSON from an API and create a ``Map`` from it, all keys will be converted to string, am I right? There is no easy way to automatically parse a JSON to an Immutable structure without having all object keys as strings really?

**Comment by leebyron** [comment]
That's mostly right. I should point out that "all keys will be converted to string, am I right?" is not quite right - specifically there is no conversion happening as JSON object keys are *always* strings.

For example:

```js
// Examples of valid JSON
{ "foo" : "bar" }
{ "true" : true }
{ "123" : 456 }

// Examples of invalid JSON
{ foo : "bar" }
{ true : true }
{ 123 : 456 }
```

**Comment by leebyron** [comment]
Added 59028b5e8552339acbdaab0c3f6547bd131f8f54 to help clarify further

**Comment by alvaromb** [comment]
Many thanks for clarifying @leebyron! Yes you're absolutely right that all JSON keys are strings, I put a wrong example because I was mocking data with JavaScript objects and I didn't realised at that moment that the keys I'll receive will be all strings. Thanks for being so helpful! :smiley:

**Comment by leebyron** [comment]
No problem at all. Thanks for the good questions, that led to better README!

**Comment by hckrmoonc** [comment]
So the conclusion is that if I put key in forms of Integer, I should use `toString` method for getting that value ?

**Comment by leebyron** [comment]
It's totally fine to use integers as keys - in fact that is a very common practice. However if you wish for an integer key and a string which happens to include that integer to both access the same value, then yes, you need some normalization between them - this is the same behavior as ES6 Map and Set.
