### ISSUE TITLE
Can you end up losing object identity by placing an item into a collection?

### ISSUE THREAD

**Issue by tolmasky** [facebook/immutable-js#590]
In other words, can any combination of collection.set(key, value) result in collection.get(key) !== value (but still I.is value?)

**Comment by leebyron** [comment]
Nope, this should not be possible.

**Comment by tolmasky** [comment]
K, must be something I'm doing (no old bugs in 3.6.2 ;) ?). Separately, didn't see it in the docs and happy to open a new question, but how "fast" is I.is? Namely, if you are recursing down a tree and comparing every node to another tree (so imaging { a: { b: { c: 6, d: 7} } } compared to { a: { b: { c: 6, d: 7} } }, and due to the incidentals of the program first you compare a to a, then b to b, then c to c, etc, do you end up in N^2 since a also internally requried checking b,c,d, and b required c,d, etc? Or is there some sort of has value equality magic going on?

**Comment by leebyron** [comment]
`Immutable.is` is at worst O(N), where N is the number of values in the tree, as it would need to compare every value in a tree. However, in practice often it is able to take short-cuts.

One short-cut is object identity, as you point out. If two sub-trees have object equality, `Immutable.is` does not recurse down them.

Another short-cut is short-circuiting on first mismatch. As soon as `Immutable.is` encounters an inequality, the algorithm halts and returns.

So the only time you the runtime is truly O(N) is when you have two value equal collections which contain  no object-identity subcomponents.
