### ISSUE TITLE
List.of() doesn't work properly on an array of objects

### ISSUE THREAD

**Issue by binarykitchen** [facebook/immutable-js#591]
$ var results = [Object, Object, Object]

`Immutable.List.of(results).toArray()` will return

```
[Array[3]]
  0: Array[3]
    0: Object
    1: Object
    2: Object
```

why the array of objects nested in an array?

**Comment by leebyron** [comment]
This is behaving correctly. `List.of()` is a convenience method for creating a List from a list of arguments:

```js
List.of(1, 2, 3)
```

If you want to create a List from an array, just call the List constructor directly:

```js
List([1, 2, 3])
```

**Comment by binarykitchen** [comment]
then you should document this. confusing at https://facebook.github.io/immutable-js/

**Comment by leebyron** [comment]
Any suggestions on how you would like the documentation to be more clear? The primary landing page there has a number of examples of using `List.of()` throughout, and there is also the complete documentation at https://facebook.github.io/immutable-js/docs/#/List/of

**Comment by binarykitchen** [comment]
Sorry, too busy right now to solve a problem here ...

**Comment by leebyron** [comment]
Thanks for bringing this to my attention anyhow. I'll mark this as needing better documentation in the future.
