### ISSUE TITLE
getIn is returning inconsistent values

### ISSUE THREAD

**Issue by ddaza** [facebook/immutable-js#594]
``` javascript
var test = Immutable.List([1, {'a':1}]);

test.getIn([0]) //  1
test.getIn([1]) // Object {a: 1}
test.getIn([1, 'a']) // undefined 
```
I was expecting the last stament to be `1`. Am I doing something wrong?

**Comment by leebyron** [comment]
The second item in your List is a JavaScript object, not an Immutable collection. You might instead want to type:

```js
var test = Immutable.List([1, Immutable.Map({'a':1})]);
```

At which point your tests will do what you expect.

You may also want to use `fromJS()` to deeply convert from the inner JS structure you've defined. It will always produce List from Array and Map from Object.

**Comment by ddaza** [comment]
Thanks!

**Comment by ddaza** [comment]
I had one other question thought. 

```javascript
var test = Immutable.fromJS([1, { 'a':  [1,2,3] }]); 
test.getIn([1, undefined], 'hello') // "hello"
test.getIn([1, 'a', 0], 'hello') // 1
test.getIn([1, 'a' ,undefined], 'hello') // undefined
```

The last statement should return `"hello"` but it return `undefined`.

**Comment by leebyron** [comment]
Could you open a separate issue documenting this? It may be a bug

**Comment by ddaza** [comment]
sure, thanks!
