### ISSUE TITLE
Imports not working with Wepback + Babel

### ISSUE THREAD

**Issue by rattrayalex** [facebook/immutable-js#596]
Hi, 

I am trying to `import Immutable from 'immutable-js'` with the following webpack settings:
```
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: ["babel-loader"],
      },
```
This results in the following error: 
```
ERROR in ../~/immutable-js/dist/immutable.js
Module parse failed: /Users/alex/myproject/node_modules/immutable-js/dist/immutable.js Line 190: Unexpected token =>
You may need an appropriate loader to handle this file type.
|    */
|   function mixin(ctor, funcs) {
|       var copier = key => { ctor.prototype[key] = funcs[key]; };
|       Object.keys(funcs).forEach(copier);
|       Object.getOwnPropertySymbols && Object.getOwnPropertySymbols(funcs).forEach(copier);
 @ ./components/Quiz.js 21:19-42
```
When I stop excluding `node_modules` in my webpack config: 
```
ERROR in ../~/immutable-js/dist/immutable.js
Module build failed: SyntaxError: /Users/alex/djcode/patient-health-questionnaire/node_modules/immutable-js/dist/immutable.js: Line 350: Derived constructor must call super()
  348 |   var COLLECTION_TYPEDEF = '[Iterable Collection]';
  349 |   class Collection extends Iterable {
> 350 |       constructor() {
      |       ^
  351 |           throw TypeError('Abstract');
  352 |       }
  353 |   }
```
I am currently using the following workaround in my `webpack.config.js`: 
```
  resolve: {
    alias: {
      'immutable-js': 'immutable-js/dist/browser/Immutable.js',
    },
  },
```
although this seems to result in a misbehaving Immutable, eg; `Immutable.fromJS([{someKey: 1, anotherKey: 2}, {someKey: 3, anotherKey: 4}])` is not resulting an `Immutable.List` of `Immutable.Map`'s (admittedly this may  be a separate issue). 

I think the solution is likely to have the `dist` code either be valid ES5 (no more `=>`s, etc) or completely valid ES6 (call super() in constructor's, etc). The former would likely be preferred, probably through a tool like Babel.

**Comment by madebyherzblut** [comment]
Looks like you are importing the "wrong" package. You are including [this package from jbiasi](https://www.npmjs.com/package/immutable-js) and not [immutable](https://www.npmjs.com/package/immutable) from Facebook (confusing, I know).

Imports with "immutable" should work fine with the webpack config above, if you are looking for immutable-js you should open an [issue](https://github.com/janbiasi/immutable/issues) there.

**Comment by rattrayalex** [comment]
...Well if that's not embarrassing I don't know what is! Thanks for the gentle correction @madebyherzblut

**Comment by leebyron** [comment]
> Looks like you are importing the "wrong" package. You are including this package from jbiasi and not immutable from Facebook (confusing, I know).

That's unfortunate :(
