### ISSUE TITLE
get should accept multiple keys

### ISSUE THREAD

**Issue by peleteiro** [facebook/immutable-js#603]
It would be nice if get accepts multiple keys.

So it would be easier to extract data from it, like: `let [id, name] = map.get("id", "name")`

**Comment by leebyron** [comment]
This would break the behavior of the second argument to `get`. It would also break Typescript and Flow integration which expect a function to have a single return type. This would cause `get` to return either a value, or an array of values. This could lead to ambiguity. Should `get("id", undefined)` return one value? A list of one? A list of two with a second value of undefined?

Unfortunately I think this would break too many things to be considered.

**Comment by colindresj** [comment]
I think there's a pretty high convenience that comes from being able to destructure a get. Agree that `get`, as it is, is predictable and should stay that way. How about introducing a `getMany`, which would always return an array and always take in a spread of strings representing keys to get values for? 

IMO, get is the inverse of set, so I feel like there would naturally be a `setMany` method, and that could get complicated.

In addition, it's unclear to me whether something like `getMany` would be a method on its own (with logic, etc.) or really just sugar around multiple gets for the same Iterable.

Wanted to add my two cents, as it has crossed my mind when destructuring native structures and then having to resort to either multiple gets or weird `withMutations` code for Immutable Iterables.

**Comment by leebyron** [comment]
Destructuring would be awesome, ideally without having to use get.

I'm looking for the right way to support:

```js
let { id, name } = myMap;
let [ first, second ] = myList;
```

**Comment by tgriesser** [comment]
Related discussion:
https://esdiscuss.org/topic/extensible-destructuring-proposal

https://github.com/vacuumlabs/es-proposals/blob/master/extensible-destructuring.md
https://github.com/vacuumlabs/babel-plugin-extensible-destructuring

**Comment by leebyron** [comment]
Thanks Tim :)

**Comment by leebyron** [comment]
Also, I believe I'm mistaken and `let [ first, second ] = myList;` works today, as this uses iteration rather than property access.

**Comment by colindresj** [comment]
I can confirm that destructuring works on Lists because of iteration. In the same way, it can be used for any Immutable Iterable, including Map, if iterators are used.

`let [ id, name ] = OrderedMap({ id: 1, name: "John" }).values();`

Of course you have make sure match the key name to the order it was set.

**Comment by kun-zhou** [comment]
I am hoping for something like `var listOfRelevantContents = someMap.get([listOfRelevantKeys], other parameters)`. Essentially, I suppose we can have `get` also accepts `Array` as its first argument to signal multiple gets at once.

**Comment by philipp-spiess** [comment]
@kun-zhou Unfortunately this won't work since an Array is a valid type for the key of a Map. In order to avoid breaking arrays as keys, the method you proposed must have a different name. 

```js
const a = new Map();
const key = [1, 2];
const b = a.set(a, "val");
b.get(key); // => "val"
```
