### ISSUE TITLE
Operator precedence error in VNode::removeBefore and VNode::removeAfter

### ISSUE THREAD

**Issue by zerkms** [facebook/immutable-js#604]
```javascript
if (index === level ? 1 << level : 0 || this.array.length === 0) {
  return this;
}
```

the condition runs as `index === level ? 1 << level : (0 || this.array.length === 0)`

**Comment by RReverser** [comment]
And unclear why is `1 << level` is needed in condition at all...

**Comment by zerkms** [comment]
Oh I see it was fixed at https://github.com/facebook/immutable-js/commit/c7c4ddc20267e0eed9d68d70c6e438c57f32a8f7 already

**Comment by RReverser** [comment]
Still unclear to me why is `1 << level` needed there...

**Comment by RReverser** [comment]
Nevermind, got it now :)
