### ISSUE TITLE
Question: How do I know if the object has changed?

### ISSUE THREAD

**Issue by tusharmath** [facebook/immutable-js#606]
I have an immutable global object which is being changed from multiple components directly. Everytime the object changes I need to re-render the complete page, unfortunately I am not able to figure out if the object has changed. Is there a `subscribe` func thru which I can subscribe for all the changes that are happening on this immutable?

Or could this be a wrong design altogether?

**Comment by smnplk** [comment]
How are you changing your immutable ? 
Is that object part of the state of your top level component ? 
How do you call .setState({..}) ?
Do you use a "flux pattern" for managing state ? (If not, checkout reflux.js or google for "react flux")

Some code snippets would be helpful.

**Comment by tusharmath** [comment]
I only have one immutable global store which contains everything.

1. I am changing the immutable via `setIn()` method.
2. No its not truly a part of the top level component, its a completely different store (Is that the problem?)
3. I don't call setState because I am not setting the root component's state, instead a global immutable obj. (How can I use the immutable obj to persist state in a component?)
4. I am using [redux](http://rackt.github.io/redux/)

**Comment by smnplk** [comment]
I am not familiar with redux, but skimming docs for a sec I found http://rackt.github.io/redux/docs/api/Store.html#dispatch 

Dispatches an action. **This is the only way to trigger a state change.**

Also the way you create redux store seems strange. Looking at docs,  shouldn't you call a createStore function  and pass it an object ?

I am sorry I can not be more helpful, maybe someone more familiar with redux can help you here, but you will have more luck on stackowerflow.

**Comment by tusharmath** [comment]
Thanks!

**Comment by leebyron** [comment]
Immutable collections do not change, so there are no methods for subscribing to changes. When you call a method like "setIn", that method will return a *new* collection with that change having been applied, and the original collection will not have changed at all. 

If you want to send updates to React components when you have new data to provide, you need to ensure you're doing that directly with the result of the updated data store. 

For example, in your Link click handler, you're not using the return value of "store.set('aa', 100)" which would be the updated version of "store".

It's very much encouraged to use a "flux" like pattern or helping library when using Immutable with React. Redux is a great one. This pattern helps manage data flow so when you perform an update, you're doing so at the top level so there only needs to be one mechanism for re-rendering your app.
