### ISSUE TITLE
request: allow usage of es6 Set for fromJS and toJS

### ISSUE THREAD

**Issue by jaredly** [facebook/immutable-js#607]
Currently `fromJS(new Set([1,2,3]))` bails, just returning the original es6 set, not an immutable set as I would expect.
Also, I'd love for `Immutable.Set([1,2,3]).toJS()` to return an es6 Set, but I realize that this would be a breaking API change, and probably unacceptable.

Of course, I could just write my own implementations, which is what I have currently.

**Comment by leebyron** [comment]
Note that you can convert between the two explicitly by passing to the constructor:

```
var es6Set = new Set([1,2,3]);
var immSet = Immutable.Set(es6Set);
var es6Set2 = new Set(immSet);
```
