### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kentor** [facebook/immutable-js#609]
There have been fixes to regressions since 3.7.3 that haven't been released as of 3.7.4. Specifically https://github.com/facebook/immutable-js/issues/480. Wondering if we can get a new version out?

**Comment by leebyron** [comment]
Thanks for the reminder - I'll get these bug fixes out in a new version today

**Comment by leebyron** [comment]
v3.7.5 is now on NPM

**Comment by kentor** [comment]
Thanks :+1:
