### ISSUE TITLE
orderSet.toSet().equals() is not returning correctly

### ISSUE THREAD

**Issue by gillesruppert** [facebook/immutable-js#614]
When converting an `OrderedSet` to a `Set`, the `equals()` method returns false when comparing to a `Set` that should be considered equal.

```javascript
// example
var orderedSet = Immutable.OrderedSet([1,2]);
var set = Immutable.Set([1,2]);
orderedSet.toSet().equals(set); // false (expected true)
set.toOrderedSet().equals(orderedSet); // true (expected)
orderedSet.toSeq().toSet().equals(set); // true (expected)
```

**Comment by rawls238** [comment]
what makes you think that this is in fact not the case?

I added the following test case and it seems to be passing the tests locally:

```javascript
  it('casts to set correctly', () => {
    var orderedSet = OrderedSet([1,2]);
    var set = Set([1,2]);
    expect(orderedSet.toSet()).toEqual(set);
    expect(orderedSet.toSet().equals(set)).toBe(true);
    expect(set.toOrderedSet().equals(orderedSet)).toBe(true);
    expect(orderedSet.toSeq().toSet().equals(set)).toBe(true);
  });
```

**Comment by gillesruppert** [comment]
@rawls238 I just double-checked: go to the Immutable.js website, open web inspector and copy my code in it (the last 3 lines you have to copy separately): you will see that what passes locally for you breaks on the current site.
Maybe this is fixed on master and the site uses an old version (as I might do).

**Comment by kentor** [comment]
Dupe btw, https://github.com/facebook/immutable-js/issues/508

**Comment by rawls238** [comment]
thanks @kentor, looks like https://github.com/tgriesser/immutable-js/commit/23bc0f3905701701cf233fe4e9f0018cee311443 should have fixed this issue
