### ISSUE TITLE
Confusion around equality testing in the documentation

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/immutable-js#625]
[Here](http://facebook.github.io/immutable-js/#the-case-for-immutability) it says: 

> Immutable always returns itself when a mutation results in an identical collection, allowing for using === equality to determine if something has changed.
> 
> ```
> var map1 = Immutable.Map({a:1, b:2, c:3});
> var map2 = map1.set('b', 2);
> assert(map1 === map2); // no change
> ```

However, on the [documentation for `is`](http://facebook.github.io/immutable-js/docs/#/is) it says:

> ```
> var map1 = Immutable.Map({a:1, b:1, c:1});
> var map2 = Immutable.Map({a:1, b:1, c:1});
> assert(map1 !== map2);
> assert(Object.is(map1, map2) === false);
> assert(Immutable.is(map1, map2) === true);
> ```

Surely both `assert(map1 === map2)` and `assert(map1 !== map2)` cannot both be true?  Very confusing!

**Comment by ellbee** [comment]
`map1` and `map2` are created in different ways in the two examples.

In the first example, `map2` is created by calling the `set` method on `map1`. As the property 'b' is already 2 there is no change to make, so `set` returns a reference to the same Immutable object that `map1` refers to and so `map1 === map2`

In the second example, `map1` and `map2` are created by separate calls to Immutable.Map, returning two separate Immutable objects, so `map1 !== map2` in the same way that `{a: 1, b: 1} !== {a: 1, b: 1}`

**Comment by johnnyreilly** [comment]
Thanks @ellbee - I see what you mean.  That makes sense now you've explained it.  

I would say it's a little confusing for a newbie to see these similar yet different things in the docs though.  Generally people will want to check for value equality using `Immutable.is` or `equals` and so I wonder if this example may actually hinder people ie lead to them using `===` where they should be using `Immutable.is`?

By the way, slightly off topic, `equals` doesn't appear to feature in the main documentation - unless I've missed it...

**Comment by ellbee** [comment]
I think you are right about it being a little confusing. 

Equality is probably the biggest source of confusion I notice around the library and in particular the fact that set/merge returns the same Immutable object if a mutation results in an identical collection but map/filter/reducer **always** returns a new Immutable object (it doesn't matter whether the collection ends up identical or not).

**Comment by leebyron** [comment]
#928
