### ISSUE TITLE
Use Immutable as prefix for all data types

### ISSUE THREAD

**Issue by tomkis1** [facebook/immutable-js#626]
Using `Map` collides with ES6 `Map`, and explicit renaming of every `Map` inside import is not ideal. Besides, in JS world `Map` is mutable by default and therefore naming `Immutable.Map` just as a `Map` is a bit tricky.

This of course applies to all types (List, Range...)

**Comment by oriSomething** [comment]
you can:
```js
import { Map as IMap } from 'immutable';
// or
const IMap = Immutable.Map;
```

**Comment by tomkis1** [comment]
I know that I can, yet neither one solution seems ideal, and taking the vague naming into consideration `ImmutableMap` by default makes biggest sense to me.

**Comment by leebyron** [comment]
Closing this aging issue
