### ISSUE TITLE
Should the constructor be invoked each time an immutable instance is mutated

### ISSUE THREAD

**Issue by aglemann** [facebook/immutable-js#627]
The constructor appears to only be invoked once when the first instance is created. When mutating the instance it appears as though I've created another instance but the constructor is not called again, should it?

Example fiddle: https://jsfiddle.net/fuLq02vc/

The use-case is if my instance wants to compute internal values derived from the external properties - it needs a hook to know when those properties have changed.

**Comment by leebyron** [comment]
Immutable collections are not really classes, even though some of the syntax tries to articulate them that way. Instead each Immutable collection type is both a factory function and an instance type. The difference from this and classes, is that there is no constructor function.

Extending a Record as a class is a fine shortcut for adding prototype methods, but the constructor itself will not be called consistently and is probably unsafe to use.
