### ISSUE TITLE
updateIn using RegExps or traversing Lists

### ISSUE THREAD

**Issue by fab1an** [facebook/immutable-js#631]
I often find myself in a situation where I would like to update a nested structure where I don't know all the keynames of a sub-structure or a sub-structure is a list. In short i'd need a function like

`obj = obj.updateIn(["key1","key2", /.*/, "key3", function() {})`

The third argument could be a RegExp to match all keys of an object, or a filter-function returning matching indices or keys, if it's a list.

Would such a thing be feasible?

**Comment by leebyron** [comment]
Unfortunately not
