### ISSUE TITLE
invalid keyPath errors are very cryptic and hard to debug

### ISSUE THREAD

**Issue by kyldvs** [facebook/immutable-js#635]
For example when running this code:

``` javascript
Immutable.Map().set('foo', undefined).setIn(['foo', 'bar'], 1)
```

You get a generic error without much information:

```
Uncaught Error: invalid keyPath
```

It would be great if this helped you out a bit more and said something along the lines of:

```
Uncaught Error: Attempting to set the path "foo, bar" but "foo" has already been set.
```

Or whatever is most appropriate.

**Comment by jtadmor** [comment]
+1

In addition, the documentation should probably make clear that the above code will produce an error, rather than making no mention of it:

> Returns a new Map having set value at this keyPath. If any keys in keyPath do not exist, a new immutable Map will be created at that key.

**Comment by jtadmor** [comment]
I just checked, and it also appears that Immutable will silently swallow the following code:

`console.log(Immutable.Map().set('foo', Immutable.List().setIn(['foo', 'bar'], 1))

// foo is an ImmutableList of size 0 with no property 'bar' `

But

`console.log(Immutable.Map().set('foo', Immutable.List().mergeIn(['foo', 'bar'], 1))

// TypeError: Expected [K, V] `

And

`console.log(Immutable.Map().set('foo', Immutable.List().updateIn(['foo', 'bar'], val => 'baz'))

// foo is an ImmutableList of size 0 with no property 'bar'`

I'm not entirely sure what the intended behavior is for each of these methods / what the logic is for handling these cases this way.

I would expect in each case that an error be thrown or that 'foo' would be converted into an Immutable.Map / OrderedMap with { bar: 'baz' }.

If you let me know what the desired behavior is, I would be happy to attempt a PR with some more clear error messages.

**Comment by gasi** [comment]
:+1: for better error messages / documentation around `setIn`:

```javascript
$ node
> var Immutable = require('immutable')
> var foo = Immutable.Map({})
> foo
Map {}
> foo.setIn(['bar', 'baz'], 'hello')
Map { "bar": Map { "baz": "hello" } }
> var foo2 = Immutable.Map({bar: null})
> foo2
Map { "bar": null }
> foo2.setIn(['bar', 'baz'], 'hello')
Error: invalid keyPath
    at invariant (~/node_modules/immutable/dist/immutable.js:872:27)
    at updateInDeepMap (~/node_modules/immutable/dist/immutable.js:1962:5)
    at updateInDeepMap (~/node_modules/immutable/dist/immutable.js:1968:23)
    at Map.updateIn (~/node_modules/immutable/dist/immutable.js:1266:26)
    at Map.setIn (~/node_modules/immutable/dist/immutable.js:1244:19)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:412:12)
```

**Comment by santiagoaguiar** [comment]
Related, so I'll add it here.

Validate `keyPath` to actually be an array (or at least not a string ;))

It's probably me, but I tend to write the following:
```
m.updateIn('key', a => a.push(1))
```

The above obviously fails, but with a:

`TypeError: Cannot read property 'push' of undefined`

Which usually makes me look somewhere else.

(I could use `update` but I think the lack of symmetry between `merge`/`update` (`merge` does not take a key, `update` does), make me use `xIn` for any op that takes some kind of path (even if it's a single key); on my reducers I basically use `merge`/`mergeIn`/`updateIn`, hardly a `set`.)

**Comment by nktssh** [comment]
Any updates on this?

**Comment by eric-burel** [comment]
I have a use case on this subject, I was transforming an array into an hashmap in a redux reducer, but I forgot to transform the object into immutable Map.


Given the following code:

```javascript
  case LOAD_FOOS_SUCCESS:
    {
      const foosAsObject = _.keyBy(action.foosAsArray, foo => foo.id)
      return state
      .set('foos', foosAsObject)
    }
```
When you forget the `fromJS`, and run  `state.updateIn(['foos', action.key, 'someNestedObject, 'val'], val=> action.newValue)`, you get the cryptic `keyPath` error.

A clearer message would indeed help, like `Did you try to update a nested plain object ?`
