### ISSUE TITLE
Weak containers

### ISSUE THREAD

**Issue by myitcv** [facebook/immutable-js#639]
Are there plans to offer weak versions of containers, e.g. a `WeakMap` equivalent of [`Map`](https://facebook.github.io/immutable-js/docs/#/Map)?

**Comment by leebyron** [comment]
Unfortunately not since it's not possible to do within JavaScript. WeakMap requires knowledge of the garbage-collection state which isn't available outside of the VM itself.

**Comment by myitcv** [comment]
Not even using the new experimental [`WeakSet`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet) and [`WeakMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) under the covers?

**Comment by leebyron** [comment]
Not that I've been able to figure out. I'm happy to take suggestions on how to do this, but every approach I've considered would either be very inefficient (copy the whole structure on every mutation) or leak memory (use a DAG with WeakMap leafs, but no way to know when to clean up without access to GC)



—

**Comment by leebyron** [comment]
Actually, I'm not sure a copy of a WeakMap is even possible as that would require interation which they do not support as that would leak GC state. So leaking memory would be the only path forward



—

**Comment by guybedford** [comment]
It would be worth investigating how far the current WeakRefs proposal enables immutable Weak Container primitives, and then also to incorporate any feedback for these immutable use cases into that spec process. It seems important that this use case is given adequate consideration in the specification process there.

Having a custom merge function seems like it won't be possible, as conflicts can't be detected for both WeakMap and WeakSet merges, but perhaps the design could factor in that limitation.

**Comment by guybedford** [comment]
(or does WeakRefs get this problem no further forward as well...? Would be good to know either way!)
