### ISSUE TITLE
Immutable.fromJS cannot convert object from different frame

### ISSUE THREAD

**Issue by happypoulp** [facebook/immutable-js#641]
Hi,

I know there is currently a PR addressing this issue but it doesn't seem like it will be merged: https://github.com/facebook/immutable-js/pull/452/files

Re-explaining what I commented [there](https://github.com/facebook/immutable-js/pull/452#issuecomment-143726079), I faced this issue when using a JS SDK that would provide me a plain JS object produced in a different frame than the one calling `Immutable.fromJS`. As a result, [this test](https://github.com/facebook/immutable-js/blob/master/src/fromJS.js#L39) fails and the plain JS object cannot be converted using `Immutable.fromJS`.

Here is a fiddle demonstrating the issue when testing if an object is a plain JS Object using `.constructor === Object`: https://jsfiddle.net/u7b5m6f8/1/

And here is a fiddle demonstrating the issue calling `Immutable.fromJS` with an "alien" plain JS Object: https://jsfiddle.net/pdjvvbxg/1/

I could propose a PR replacing:

``` javascript
function isPlainObj(value) {
  return value && (value.constructor === Object || value.constructor === undefined);
}
```

by

``` javascript
function isPlainObj(value) {
  return value && (Object.prototype.toString.call(value) === "[object Object]" || value.constructor === undefined);
}
```

if you think that this fix is correct and won't hurt performances.

Thanks.

**Comment by dfguo** [comment]
Saw the same issue that when we pass an immutable object from parent iframe to child iframe, isPlainObj doesn't work anymore. I did some profiling and found this:

![screen shot 2016-11-21 at 2 05 20 pm](https://cloud.githubusercontent.com/assets/857372/20472297/8e5c53c2-aff3-11e6-8a60-4b50539b7fb8.png)
