### ISSUE TITLE
Supporting immutable in Tonic

### ISSUE THREAD

**Issue by tolmasky** [facebook/immutable-js#650]
Hi, I'd like to add out-of-the-box support for immutable in Tonic (tonicdev.com). Currently, it is treated like a JS object:

![screen shot 2015-10-05 at 3 34 42 pm](https://cloud.githubusercontent.com/assets/23753/10295621/bb25412e-6b76-11e5-953d-82ca9012a535.png)

Now, ideally I'd do this by identifying that it is an immutable on the server, adding a special flag, and then entirely on the client displaying it the correct way, as opposed to determining it is an immutable on the server and special case serializing it. This way there is no custom serialization, and additionally you can select to view it as a js object as well on the client. However, this would require me to infer the information from the internal structure (iterate through arraymapnodes or whatever). I am happy to do this -- however, I am willing to not do it if the idea is that this will actually change and it is thus unsafe to do it this way.

If that's the case and I should just be appending something like key = map.keys() etc, I'm curious if there is a non-mutative way to do so. That is to say, when we serialize objects on the backend we have a strict policy of not calling any functions that could possibly have side effects (including changing a cache for example). Is I.Map.prototype.keys.apply(theMap) safe (the same way Object.getOwnpropertyDescriptors is?)

**Comment by leebyron** [comment]
Sorry for dropping this super aging issue - I hope you were able to build something awesome and your approach sounds great
