### ISSUE TITLE
Immutable.js fails on Safari <= 5.1

### ISSUE THREAD

**Issue by detrandix** [facebook/immutable-js#651]
Hello, 

I found an error which appears on Safari <= 5.1. The problem is at the line: https://github.com/facebook/immutable-js/blob/master/src/IterableImpl.js#L471 - Safari has error.stack in version 6 or newer. 

To reproduce this error you just need to require Immutable library and that's it. I guess there are some internal calls for .length in the source code of the library which makes fatal error.

As a temporary solution I've downgraded Immutable to 2.6.2, but it's not a great long term solution. It would be great if you can fix it.

**Comment by jskvara** [comment]
I have the same problem and needed to downgrade to 2.6.2 version.

Any chance this will by fixed soon?

**Comment by pedroteixeira** [comment]
Getting exception error due to use of 'Error.prototype.stack' also in Qt browser (4.8).
In my case, it happens on the definition of `Object.defineProperty(IterablePrototype, 'length'`.

**Comment by leebyron** [comment]
Closing this aging issue which should have been fixed with the v3 release. Please re-open if you see it again.
