### ISSUE TITLE
Using a number as a key in a Map returns undefined.

### ISSUE THREAD

**Issue by csaintc** [facebook/immutable-js#652]
```
var map = Immutable.Map({
    1: 'bacon',
    2: 'eggs'
})

map.get(1);
// undefined

map.get('1')
// 'bacon'
```

**Comment by tomwidmer** [comment]
This isn't a bug, since your code hasn't used a number as a key. In object literal syntax, keys are treated as strings (since object keys can only be strings (and/or Symbols in ES6 I think)), so your code is the same as:

    var map = Immutable.Map({
        '1': 'bacon',
        '2': 'eggs'
    })

If you want to use number keys, you need to do either:

    var map = Immutable.Map().set(1, 'bacon').set(2, 'eggs');
or

    var map = Immutable.Map([[1, 'bacon'], [2, 'eggs']]);
