### ISSUE TITLE
Immutable.fromJS: Detect cycles (RangeError: Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by gasi** [facebook/immutable-js#653]
When trying to convert circular data structures using `Immutable.fromJS`, it currently throws `RangeError: Maximum call stack size exceeded`. Instead of this, could `fromJS` follow the semantics of `JSON.stringify` and throw a more meaningful error, similar to `TypeError: Converting circular structure to JSON`?

Pardon if this is a duplicate, but I searched the existing issues for this and couldn’t find it.

Please let me know if you need any more details and thanks for building _Immutable.js_ :smile: 

**Repro:** https://jsbin.com/kupavixuhe/edit?js,console

**Comment by gscottolson** [comment]
:+1:

**Comment by paramsingh88** [comment]
Any solution ??
