### ISSUE TITLE
Sliced sequence bug

### ISSUE THREAD

**Issue by ayrton** [facebook/immutable-js#655]
Currently I've stumbled upon a somewhat annoying problem in an application using Immutable.js (3.7.5) & React.js (0.14.0).

The following code works as expected:

``` js
import Immutable from 'immutable';
import React from 'react';

export default React.createClass({
  render() {
    const seq = new Immutable.Seq([0, 1, 2, 3, 4]);
    const ids = seq.take(10);

    const divs = seq.map((id) => (
      <span key={id}>{id}</span>
    ));

    return (
      <div>{divs}</div>
    );
  },
});
```

But instead of numbers (`[0, 1, 2, 3, 4,]`) I'm using instances of `Immutable.Record` in my project and the code above raises:

`Uncaught TypeError: Cannot read property '1' of undefined`

This does not happen when the Seq size of the records is > than the n amount I take via `.take(n)`.

[Changing the following lines from](https://github.com/facebook/immutable-js/blob/7c4483e30e8b9528562f6ef34f66bee6bfb3538d/src/Operations.js#L458-L465): 

``` js
var step = iterator.next();
if (useKeys || type === ITERATE_VALUES) {
  return step;
} else if (type === ITERATE_KEYS) {
  return iteratorValue(type, iterations - 1, undefined, step);
} else {
  return iteratorValue(type, iterations - 1, step.value[1], step);
}
```

to:

``` js
var step = iterator.next();
if (useKeys || type === ITERATE_VALUES) {
  return step;
} else if (step.value === undefined || type === ITERATE_KEYS) {
  return iteratorValue(type, iterations - 1, undefined, step);
} else {
  return iteratorValue(type, iterations - 1, step.value[1], step);
}
```

Fixes the issue but it feels like this is being solved at the wrong level.

What is there that I can do to help here?

<img width="1440" alt="screen shot 2015-10-13 at 15 34 08" src="https://cloud.githubusercontent.com/assets/440926/10456137/ee3c4054-71bf-11e5-9f08-c6fc33280496.png">

**Comment by roganov** [comment]
Just bumped into this
@ayrton Have your resolved the issue?

**Comment by ayrton** [comment]
I was not, I was fortunate enough not having to use `.slice()` in that particular case anymore, but this still feels like a weird edge case we should try and solve.

**Comment by leebyron** [comment]
Thanks for this investigation, please feel free to open a PR applying your fix and adding a test that documents the original issue!

**Comment by arian** [comment]
For me calling `cacheResult` after the `take` (or `slice`) seemed to fix the iterator. Of course you have to take the notes of https://facebook.github.io/immutable-js/docs/#/Seq/cacheResult into account...

**Comment by leebyron** [comment]
I believe this was the result of an older bug with slice that has since been fixed. A new release is coming very soon which will resolve this for everyone
