### ISSUE TITLE
Why immutable.js has so magic power？

### ISSUE THREAD

**Issue by szhclaye** [facebook/immutable-js#656]
What is the reason we introduce immutable.js？
Where the immutable's power from？

**Comment by jurassix** [comment]
No magic - just less mutation. 

Research __Persistent data-structures__ for a complete picture of what this library offers.

[_From the docs:_](https://facebook.github.io/immutable-js/)
> ## The case for Immutability
> 
> Much of what makes application development difficult is tracking mutation and maintaining state. Developing with immutable data encourages you to think differently about how data flows through your application.
> 
> Subscribing to data events throughout your application, by using Object.observe, or any other mechanism, creates a huge overhead of book-keeping which can hurt performance, sometimes dramatically, and creates opportunities for areas of your application to get out of sync with each other due to easy to make programmer error. Since immutable data never changes, subscribing to changes throughout the model is a dead-end and new data can only ever be passed from above.
> 
> This model of data flow aligns well with the architecture of React and especially well with an application designed using the ideas of Flux.
> 
> When data is passed from above rather than being subscribed to, and you're only interested in doing work when something has changed, you can use equality. Immutable always returns itself when a mutation results in an identical collection, allowing for using === equality to determine if something has changed.
> ```js
> var map1 = Immutable.Map({a:1, b:2, c:3});
> var map2 = map1.set('b', 2);
> assert(map1 === map2); // no change
> var map3 = map1.set('b', 50);
> assert(map1 !== map3); // change
> ```
> If an object is immutable, it can be "copied" simply by making another reference to it instead of copying the entire object. Because a reference is much smaller than the object itself, this results in memory savings and a potential boost in execution speed for programs which rely on copies (such as an undo-stack).
> ```js
> var map1 = Immutable.Map({a:1, b:2, c:3});
> var clone = map1;
> ```

**Comment by Dashed** [comment]
Also, check this out; this provides context in relation with react: http://jlongster.com/Using-Immutable-Data-Structures-in-JavaScript

**Comment by leebyron** [comment]
https://www.youtube.com/watch?v=I7IdS-PbEgI
