### ISSUE TITLE
Records can't have key called "size"

### ISSUE THREAD

**Issue by nabana** [facebook/immutable-js#657]
I was trying to create a new Record class similar to this one:

```
var Jeans = Record({brand: 'noname', size: 'M'});
var j1 = new Jeans({brand: 'Levis'});
```

It won't work because `size` is kind of a reserved property (on the record class's prototype) to reflect the number of allowed keys.

I think this at least should be more obvious from the docs (well, it appears in one of the examples) but could it be turned into a method instead?

**Comment by anjianshi** [comment]
same as #377
