### ISSUE TITLE
Operational Transformation for concurrent edits

### ISSUE THREAD

**Issue by khankuan** [facebook/immutable-js#658]
Hey, just wondering if there is a possibility to add OT to immutable. The use case can be a common async editing of data. For example, user deletes something and then edit other stuff that mutates the data. The delete ajax call fails and now we need to undo that mutation. Any thoughts?

**Comment by leebyron** [comment]
Sorry for letting this issue go stale.

There are plenty of great libraries out there that help implement OT - I don't think this data structures library is the appropriate place to add another
