### ISSUE TITLE
Add getPath method to every record

### ISSUE THREAD

**Issue by vojtatranta** [facebook/immutable-js#661]
I've been listing through some articles and lots of issues here on Github but I haven't found answer to idea I've got.

If I edit some record in the list somewhere deep in structure tree and pass it on to some store / action creator, in the store I have to somehow find this record again to edit something inside it or maybe delete it. Sure, I can use cursor to simplify this step but I would have to loop through records in the list in order to find that particular record according to ID or something.

Passing on index of this record along with ID (which is needed for API fetch) seems kind a strange to me...

So I got and idea that it would be nice if I had some getPath() method on record, or just record.path because then I could just do in my store something like:
```
updateById(id, record.getPath(), {name: 'john doe'})

updateById(id, path, updateObj) {
   state = state.updateIn(path, prev => prev.merge(updateObj))
}
```
Instead of:
```
updateById(id, {name: 'john doe'})

updateById(id, updateObj) {
  state = state.updateIn(findPathWithLoopById(id), prev => prev.merge(updateObj)))
}
```

Since we have to loop through whole json or some other structure when we do immutable.fromJS() there would be no impact on performance, right?

Or I would appreciate if you point me to some other solution for this which is already out there and I miss it.

Thank you so much for all the great work you have done!

**Comment by tomwidmer** [comment]
A single record can be used in many different lists and immutable structures, so which path to return? If you move the record, do you want to change the path in the *immutable* record?

If you want a simpler lookup, you could maintain a separate map from id to path. Or you could change your data structure so you have an ordered map from id to record rather than a list (you can always get the list back if you need it using toList()).

**Comment by vojtatranta** [comment]
@tomwidmer thank you for your reply!
Well yes, yes and yes:)
I think that most of the use cases are that you want to map your immutable state to some react components, get some update action and than find entity to be updated back in the tree using id.
Well maybe I am just looking for some best practices in this area.

And to you note with map with ids as keys: I would love to do it, but we have JSON here, which does not allow to have explicitly indexed arrays nor I can't use object with ids in keys because they don't maintain order :(

**Comment by leebyron** [comment]
The records themselves do not know where they exist within a parent (or multiple parents!)
