### ISSUE TITLE
How does mergeIn decide if a property needs to be removed/added/updated?

### ISSUE THREAD

**Issue by tusharmath** [facebook/immutable-js#662]
```javascript
var first = Immutable.Map({
  d: {
    a: 1,
    b: 2,
    c: 3
  }
})
var second = Immutable.Map({
  a: 1,
  c: 3
})

console.log(first.mergeIn(['d'], second).toJS())
console.log(first.mergeDeepIn(['d'], second).toJS())


/*
* Output
{ d: { a: 1, c: 3 } }
{ d: { a: 1, c: 3 } }
*/

```

How did I end up loosing the `b` property?  How can I have it back? It works fine if I am using simple merge.

**Comment by danielstreit** [comment]
The issue may be that `Immutable.Map` does not create a deep Immutable Map. The value associated with d is a vanilla JavaScript Object. Using `Immutable.fromJS` to get a deeply converted Map may give you the expected result.

**Comment by tusharmath** [comment]
@danielstreit Thanks!
Now what if I want to control this behaviour? Like if `b` is as a falsey value, I would like to delete the key otherwise merge it. Can that me done?

**Comment by danielstreit** [comment]
Try using [updateIn](https://facebook.github.io/immutable-js/docs/#/Map/updateIn).

**Comment by tusharmath** [comment]
Thanks!
