### ISSUE TITLE
withMutations without using set in mutator safe to use?

### ISSUE THREAD

**Issue by Almenit** [facebook/immutable-js#663]
We have noticed that you don't have to use set withing your withMutations mutator

``` javascript
car.withMutations(t => {
  t.color = "red";
  t.brand = "Volvo";
});
```

The benefit for us is that we get the typing since we use typescript. But Is this safe to use?

**Comment by tomwidmer** [comment]
It appears to be a safe, but currently undocumented, feature. Under the hood it just calls 'set'.

**Comment by leebyron** [comment]
Specifically only for Records, yes it is an experimental feature
