### ISSUE TITLE
getIn more preformant then get

### ISSUE THREAD

**Issue by Almenit** [facebook/immutable-js#664]
Is getIn more performant then using get? It feels like it should be...But I don't have any good arguments when telling my collegue to use it.
```javascript
var obj2 = getIn(["key1", "subkey1"])
```
versus
```javascript
var obj1 = get("key1");
var obj2 = obj1.get("subkey1");
```

**Comment by tomwidmer** [comment]
I don't think it makes much difference (an array creation/function call or two, but nothing significant). Either way, I think two O(log32 N) calls are required.

**Comment by leebyron** [comment]
They're equivalent. `getIn` is implemented in terms of `get` - it's just a nicer API.
