### ISSUE TITLE
understanding `.toJS()` -- iterable?

### ISSUE THREAD

**Issue by eyston** [facebook/immutable-js#669]
I'm creating an `Immutable.Map` and calling `.toJS()` on the map before passing it to a third-party function.  I end up getting some warning / errors bubbling up from the third party lib but Immutable is in the trace:

![screen shot 2015-10-21 at 10 25 27 pm](https://cloud.githubusercontent.com/assets/187389/10655456/e263cdea-7842-11e5-95c0-199b2721cee9.png)

__at List.Object.defineProperty.get (http://localhost:3000/js/app.js:5118:22)__ is from Immutable.js.

To fix this I can chain `JSON.stringify` and `JSON.parse`.  Suboptimal but works.

My question is -- should I be using something other than `.toJS()` to transform to a javascript object with no vestiges of Immutable.js?  I'm a bit clueless as to why calling `.toJS()` still leaves some code around from Immutable.  Thanks!

**Comment by tomwidmer** [comment]
toJS stops recursing if it finds a non-Immutable object. One possibility is that you have a non-immutable object in your tree (e.g. a plain array or plain key=> value object) that contains the immutable objects. If that's the case, I'd expect you have other problems than just the warning.

**Comment by eyston** [comment]
thanks, I would not be surprised if that was the case!  I don't think I'll get back to looking at it soon so consider case closed ;p
