### ISSUE TITLE
asMutable/withMutations add then subtract failing

### ISSUE THREAD

**Issue by dpwrussell** [facebook/immutable-js#673]
This works:

``` javascript
var x = Immutable.Set().asMutable();
x.add(1);
x.add(2);

console.log(x.toArray());
x.remove(1);
console.log(x.toArray());
```

This fails:
``` javascript
var x = Immutable.Set().asMutable();
x.add(1);
x.add(2);
var y = Immutable.Set([1]);

console.log(x.toArray());
x.subtract(y);
console.log(x.toArray());
```

with:

``` javascript
/Users/dpwrussell/Checkout/immutable_test/node_modules/immutable/dist/immutable.js:1940
        return fn(entry[1], entry[0], this$0);
                       ^

TypeError: Cannot read property '1' of undefined
    at /Users/dpwrussell/Checkout/immutable_test/node_modules/immutable/dist/immutable.js:1940:24
```

The same is true when using `withMutations`.

The documentation for `Set` does mention on `withMutations` that only `add` may be used mutatively, but I am unclear if that is applicable to `asMutable` as well.

This actually does work:

``` javascript
var x = Immutable.Set().asMutable();
x.add(1);
x.add(2);
var y = Immutable.Set([1]);
x = x.asImmutable().asMutable();

console.log(x.toArray());
x.subtract(y);
console.log(x.toArray());
```

As I saId, I'm not sure if this is a documentation issue or an actual bug.

**Comment by tomwidmer** [comment]
The docs say that only `Set.add` can be used mutatively for Sets, so your example isn't legal according to the docs: http://facebook.github.io/immutable-js/docs/#/Set/withMutations

**Comment by dpwrussell** [comment]
Yes, as I mentioned, it is not clear that this applies to `asMutable` as well as `withMutations`.

**Comment by leebyron** [comment]
Closing this aging issue - but noted. There are a few other issues recommending improvements to this usage case.
