### ISSUE TITLE
TypeDefinition is missing emptySet(), emptyList(); requesting Coll.empty()

### ISSUE THREAD

**Issue by danielwegener** [facebook/immutable-js#677]
Hello friends of immutability!
I just tried to used immutable.js from a typescript project and was wondering why there were static "helper" methods like `Set.of()`, `List.of()` but there seemed to be no `Set.empty()` or `List.empty()`.

After diving into the javascript code it turned out that there actually is an `emptySet()` (this one is sadly not exported), `emptyMap()` and `emptyList()`, but all of them are not exposed via typescript type description. I have not yet checked other collection types but i wished each collection could have an `emptyCOLLTYPE()` or even better `empty()`method as static method (prototype method).

(Even better would be a static class property 'Coll.empty', but as far as I understood, we have to wait for ES7 to get them)

**Comment by leebyron** [comment]
You can just call `List()` for an empty list or `Map()` for an empty Map. These return memoized versions of the immutable empty collection, so `List() === List()`.

And as a bonus, it's less characters than `List.empty()`!

**Comment by danielwegener** [comment]
Good point! I must be blind, sorry for stealing your time :)
