### ISSUE TITLE
Return safe ref for no-op `map`

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#679]
This optimization should allow `list === list.map(x => x)` and `map === map.map(x => x)`

**Comment by rawls238** [comment]
@leebyron going to try to do this, do you think a decent approach would be to simply check value equality of the pre-map and post-map iterable and return the pre-map iterable if they're the same?

**Comment by leebyron** [comment]
No I think that will be too expensive, that would require a second full traversal.

An ideal solution should leverage the trie structure of the List and Map underlying implementations such that even if only portions of the collection change, other portions can leverage structural sharing to save memory.

This likely will require a custom implementation of `map` for each type.

**Comment by leebyron** [comment]
My primary concern is that this will add weight to the library, but I hope we can find a terse implementation.

**Comment by rawls238** [comment]
I think we could potentially do it without a second traversal by checking value equality at every stage of iteration (if we get one value where f(x) != x then we know we can't use this optimization). But I'll think about your suggestion and see if I can come up with a lightweight solution, thanks

**Comment by leebyron** [comment]
Your suggestion is also a good one and perhaps a reasonable iterative step forward. That solves the immediate task even though it doesn't yet allow `map()` to benefit from structural sharing (which may be a less common optimization).

I look forward to your PR!
