### ISSUE TITLE
RFC: notSetValue as a function

### ISSUE THREAD

**Issue by rosendi** [facebook/immutable-js#680]
Should some methods (`get`, `update`, etc.) accept `notSetValue` as a function that returns a fallback value or it's redundant?

Before:

```
var items = Map<string, Item>();

if (!items.has(key)) {
  items = items.set(key, new Item(...)); // some expensive initialization
}

let item = items.get(key);
```

After:

```
var items = Map<string, Item>(...);

let item = items.get(key, () => new Item(...))
```

**Comment by tomwidmer** [comment]
I guess the only issue is that the is a breaking change - if you have a map storing functions, then `items.get(key, defaultFuncValue)` is going to break. Probably not a huge issue, but worth mentioning, since someone somewhere will suddenly have an odd bug.

**Comment by leebyron** [comment]
A collection of functions may wish to use a function as it's notSetValue - As interesting as this is, I fear it would add more confusion than value in the long run.

In my opinion, a better version is:

```js
var items = Map<string, Item>(...);
var item = items.get(key);
if (!item) {
  item = new Item()
  items.set(key, item)
}
```
