### ISSUE TITLE
Is there a simple way to see the nodes updated in an Immutable Map?

### ISSUE THREAD

**Issue by thomas-jeepe** [facebook/immutable-js#681]
In a talk, @leebyron explained how immutable data structures work and how any unchanged data is copied while data that is updated is not copied. My question is specifically, "Without comparing old state and new state is there a simple way with immutable js to get the nodes updated or hash input into it?

**Comment by leebyron** [comment]
Closing this aging issue

Unfortunately not without digging into the implementation details
