### ISSUE TITLE
How to set type of map key and value?

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/immutable-js#686]
I want a Map of number to number:

``` js
const x: Im.Map<number, number> = Im.Map([[1, 1]])
```

However, this gives me an error:

```
main.ts(31,7): error TS2322: Type 'Map<{}, {}>' is not assignable to type 'Map<number, number>'.
  Type '{}' is not assignable to type 'number'.
```

Should this be possible?

**Comment by myitcv** [comment]
Instead write:

```typescript
const x = Im.Map<number, number>([[1, 1]])
```

The type annotation on the LHS is not required; instead it can be inferred from the RHS.

Also, `Im.Map([[1, 1]])` implies `Im.Map<{}, {}>([[1, 1]])`. Why? Because that's what the [spec says](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#361-type-parameter-lists):

> Omitting a constraint or specifying type any as the constraint corresponds to specifying the empty object type `{}`. 

Hope that helps.

**Comment by OliverJAsh** [comment]
Your suggestion uses a type assertion to override the type. I was hoping, with the provided type definitions, that TypeScript could infer the type from my usage. Could the type definitions not use generics to allow inference? Still trying to get my head around TypeScript.

**Comment by myitcv** [comment]
Actually I was just checking that..... The type definition for `Map` could indeed be improved to allow:

```typescript
const x = Immutable.Map([[1, 1]]); // Immutable.Map<number, number>
```

[This line](https://github.com/facebook/immutable-js/blob/6075107d7bb42414797473b5adf6dd55f6f01062/type-definitions/Immutable.d.ts#L456) from the type definition:

```typescript
export function Map<K, V>(array: Array</*[K,V]*/Array<any>>): Map<K, V>;
```

could be changed to:

```typescript
export function Map<K, V>(array: Array<[K,V]>): Map<K, V>;
```

**Comment by OliverJAsh** [comment]
That's what I was wondering. :+1: Would love to see this change shipped.

**Comment by OliverJAsh** [comment]
Just come up against this again, completely forgot about this issue. Is immutable js still being maintained? Is there any chance of this being added?

**Comment by simonh1000** [comment]
Thanks @myitcv !!!

**Comment by OliverJAsh** [comment]
I'm using this helper until the typings are fixed upstream:

``` ts
// Immutable's typings could but don't infer key/value types from entries, so we
// use this helper to convert from Entry[] -> Immutable Map.
// https://github.com/facebook/immutable-js/issues/686
type Entry<K, V> = [ K, V ];
export const entriesToMap = <K, V>(tuples: Entry<K, V>[]): Map<K, V> => (
	Map<K, V>(tuples)
)
```

**Comment by leebyron** [comment]
Fixed in master and will be released soon!

**Comment by alessandro-aglietti** [comment]
> Just come up against this again, completely forgot about this issue. Is immutable js still being maintained? Is there any chance of this being added?

Yeah, would be extremely cool if we can define typed maps in the JS version
```js
const Product = Record({sku: null, price: null})
const ProductBySky = Map.ofType(Product)
const r = ProductBySky({'sku123': {sku: 'sku123', price: 123.45}})
r.get('sku123').price
```

**Comment by CMCDragonkai** [comment]
Why does immutable typescript not allow this?

```
type State = Map<number, number>;
```

To define an alias?
