### ISSUE TITLE
How to find and grab an object based on one of its key values?

### ISSUE THREAD

**Issue by kennetpostigo** [facebook/immutable-js#687]
Hello,

Im working on a filter to find an object based of a search phrase that can potentially match any of the values of the objects keys.

For example, If someone searches for `CorpComp` from a list of objects like so:

```javascript
var state = Immutable.Map({
                leads: Immutable.List.of(
                    Immutable.Map(
                        {
                            document_id: "L4234234234234",
                            company_name: "someComp",
                            date_filed:"083815",
                            address:"11111 sw 123 ave",
                            first_name: "john",
                            last_name: "doe"
                        }),
                    Immutable.Map(
                        {
                            document_id: "L11111111",
                            company_name: "CorpComp",
                            date_filed:"091919",
                            address:"22222 sw 456 Ave",
                            first_name: "jane",
                            last_name: "doe"
                        }
                    ),
                    Immutable.Map(
                        {
                            document_id: "L0928745",
                            company_name: "ShitCorp",
                            date_filed:"987432",
                            address:"02938 sw 754 Ave",
                            first_name: "Misa",
                            last_name: "Crane"
                        }
                    )
                )
});
```
In that case it would grab the `2nd` Object within the nested `List`, this is because its the value of the key `company_name` is `==` to `CorpComp`. To try accomplish this functionality I wrote the following:

```javascript
function handleSearchLeads (state, searchPhrase) {
    var leads = state.getIn(['leads']);
    return leads.find((l) => {
        if (l.document_id == searchPhrase || l.company_name == searchPhrase || l.date_filed == searchPhrase || l.address == searchPhrase || l.first_name == searchPhrase || l.last_name == searchPhrase) {
            return state.set('searchedLeads', l);
        }
    });
}
```
Unfortunately my attempt was unsuccessful, and I've grown a weary of trying to find the right methods combo to accomplish what my goal was. Can someone please show me what I'm doing wrong? Any and all help is welcome.

**Comment by swac** [comment]
`Immutable.List#find()`'s first argument should be a function that returns a boolean. Yours returns an `Immutable.Map`, which incidentally will work but is not really correct, given the signature in the [documentation](https://facebook.github.io/immutable-js/docs/#/List/find). Also, immutable maps don't allow element access like `l.document_id`. You want `l.get('document_id')`.

Since you mentioned wanting to find all matching entries, you probably want [`filter()`](https://facebook.github.io/immutable-js/docs/#/List/filter) instead of `find()`.

**Comment by kennetpostigo** [comment]
@swac Thank you very much for the feedback, So after implementing what you said I have successfully been able to `filter` the documents based on the `searchPhrase`:

```javascript
function handleSearchLeads (state, searchPhrase) {
    var leads = state.get('leads');
    var filteredLeads = leads.filter((l) => {
        return l.get('document_id') == searchPhrase || l.get('company_name') == searchPhrase || l.get('date_filed') == searchPhrase || l.get('address') == searchPhrase || l.get('first_name') == searchPhrase || l.get('last_name') == searchPhrase;
    });
    return state.set('searchedLeads', filteredLeads);
}
```

I unit-tested it and it worked great! Thank you very much @swac!
