### ISSUE TITLE
UpdateIn() with predicates?

### ISSUE THREAD

**Issue by aaronkor** [facebook/immutable-js#689]
I am trying to update a nested object which consists of both Maps and Lists:
```javascript
const state = fromJS({
  players: [
    { name: 'Aaron',  forecasts: [ { type: 'winner', val: 1 } ] },
    { name: 'John' }
  ],
  match: { /*...*/ }
});
```
Trying to add a forecast under player, I came up with this:
```javascript
function addPlayerForecast(state, playerName, forecast) {
  const players = state.get('players');
  const newPlayer = players.find(p => p.get('name') === playerName)
                           .update('forecasts', List(), forecasts => forecasts.push(fromJS(forecast)));
  return state.set(
    'players',
    players.set(players.findIndex(p => p.get('name') === playerName), newPlayer)
  );
}
```
which works fine, but I feel that if, for example, there was a way to use updateIn() with an array of predicates instead of strings would make such a code much more simple. Or is there any other way to simplify this task?

**Comment by leebyron** [comment]
Unfortunately not currently supported, but will keep in mind for future versions.

**Comment by WalterWeidner** [comment]
You mean something like this?

```
const forecast = fromJS({type: 'loser', val: 2});
state = state.updateIn(['players', name => name === 'Aaron', 'forecasts', forecasts => forecasts.push(forecast));
```
I feel like some of the biggest complaints about Immutable in our organization involve the verbosity required to modify objects. Something like this would help significantly decrease the number of `findIndex` calls and therefore improve readability.

I had no idea what to search for so I almost created a duplicate of this issue. Is this something that could be reconsidered @leebyron?
