### ISSUE TITLE
How to contribute to the docs?

### ISSUE THREAD

**Issue by chiedoX** [facebook/immutable-js#691]
Thanks again for this awesome package!

I'd like to contribute to the docs. I see that I can edit the docs here: https://github.com/facebook/immutable-js/blob/master/dist/immutable.d.ts

I get that the docs are auto-generated. But how can I generate the docs locally so I can preview the docs before submitting a pull request? 

Thanks,

**Comment by rawls238** [comment]
You should be able to use this to generate some version of the docs locally: https://github.com/sebastian-lenz/typedoc

**Comment by chiedoX** [comment]
Thanks!
