### ISSUE TITLE
Simple value parameter for OrderedMap.update()

### ISSUE THREAD

**Issue by dubrowgn** [facebook/immutable-js#693]
It would be very convenient if `OrderedMap.update()` could take simple values as the second parameter.

`om = om.update("a", 7);`

Instead of:

`om = om.update("a", function() { return 7; });`

**Comment by ThomasCrvsr** [comment]
Can't you use directly `om = om.set('a', 7)` ?

**Comment by dubrowgn** [comment]
I was under the impression that `set` moved the value to the end of the collection, but I'm not seeing that now... Maybe I just assumed `set` and `update` were semantically different. When dealing with a keyed, ordered collection, usually you have two calls to represent the two different ways of updating the collection. First, updating the value for the given key in place, and two for effectively removing the key and re-adding it with a new value. I must have thought `update` covered the first case, and `set` covered the latter. I see now that `update` comes from `Map`, however, so this obviously wouldn't be the case.
