### ISSUE TITLE
Implement OrderedSet.update()

### ISSUE THREAD

**Issue by dubrowgn** [facebook/immutable-js#694]
It would be nice if `OrderedSet` had an `update()` function like `OrderedMap`, to support changing value without changing order.

``` javascript
let os = Immutable.OrderedSet.of(1,2,3); // [1, 2, 3]
os = os.update(2, 7); // [1, 7, 3]
```

This can't be achieved currently because `delete()` followed by `set()` changes order.

**Comment by leebyron** [comment]
Unfortunately this is beyond the current abilities of OrderedSet to do in a performant way.

**Comment by mschipperheyn** [comment]
Could this be achieved in a performant way by doing a concat and a sort?
