### ISSUE TITLE
Values() returns Iterator instead of Seq

### ISSUE THREAD

**Issue by dubrowgn** [facebook/immutable-js#695]
Why does `values()` return `Iterator` instead of `Seq`? I can't do anything with an `Iterator`. Effectively this means there isn't a straight forward way to get a `Seq` of only a map's values, because `toSeq()` returns a keyed sequence.

``` javascript
var om = Immutable.OrderedMap.of(["a", 1], ["b", 2]);
om.values().map(...); // blows up, values() returns Iterator
om.toSeq().map(...); // doesn't blow up, but toSeq() returns Seq of <key, value> pairs
Immutable.Seq(om.values()).map(...); // works, but is clunky and verbose
```

**Comment by dubrowgn** [comment]
Correction: `values()` returns `Iterator` instead of `Iterable`

**Comment by mking** [comment]
@dubrowgn Have you tried `valueSeq`? `values()` is for [ES2015 compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), while `valueSeq` is an Immutable.js extension

**Comment by dubrowgn** [comment]
I did notice `valueSeq`, but I didn't notice ES2015 defined `values` this way. It seems like a terrible and confusing name for a function that returns an iterator, but it's not like we can do anything about it now... I'll go ahead and close this, I guess.
