### ISSUE TITLE
Custom formatter for Chrome Devtools

### ISSUE THREAD

**Issue by andrewdavey** [facebook/immutable-js#696]
Chrome Devtools is getting support for custom formatters (currently in Canary).

https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/preview

This will make debugging immutable values much easier. We'll be able to display useful information in watches, console, etc.

A bare-bones formatter is here: https://gist.github.com/jsdf/e27e0e467dc8db3fb1e1 but we could make one that does way more than just JSONifying.

**Comment by andrewdavey** [comment]
Should this live in a separate project (and NPM module)? Since we'd probably only want it in debug builds. Something like:

```js
import Immutable from "immutable";
if (DEBUG) {
  const initFormatter = require("immutable-devtools");
  initFormatter(Immutable);
}
```

**Comment by andrewdavey** [comment]
I've made a start on this: https://github.com/andrewdavey/immutable-devtools

**Comment by rickhanlonii** [comment]
Dupe of #287

**Comment by Daniel15** [comment]
Closing this out as a duplicate of #287
