### ISSUE TITLE
Wrong Immutable JS version loaded on "documents" tab of the website.

### ISSUE THREAD

**Issue by NakShi** [facebook/immutable-js#698]
- https://github.com/facebook/immutable-js/blob/7c4483e30e8b9528562f6ef34f66bee6bfb3538d/__tests__/merge.ts#L43
- Above test works on `http://facebook.github.io/immutable-js/` but not on `http://facebook.github.io/immutable-js/docs/#/`
- I suspect docs page is loaded up older version of immutable js

- On `http://facebook.github.io/immutable-js/`
<img width="1632" alt="screen shot 2015-11-12 at 5 51 34 pm" src="https://cloud.githubusercontent.com/assets/5334108/11136836/1aeb1968-8967-11e5-8987-8e6a7fa34216.png">
- On `http://facebook.github.io/immutable-js/docs/#/`
<img width="1632" alt="screen shot 2015-11-12 at 6 00 01 pm" src="https://cloud.githubusercontent.com/assets/5334108/11136864/4c58eb42-8967-11e5-86bf-00f63ee6b90c.png">

`key` is always `undefined` in the merger function for the latter case

**Comment by leebyron** [comment]
Fixed!
