### ISSUE TITLE
No scrollbar for the API list on the documentation page

### ISSUE THREAD

**Issue by mnordick** [facebook/immutable-js#701]
This page, https://facebook.github.io/immutable-js/docs/#/Map, for example, there is no scrollbar to view the consolidated list of apis on the left.Makes it impossible to use without a scrollwheel (ie. laptop). I can fix it but I don't know where the html source is located.

**Comment by ericlathrop** [comment]
Same problem here. Tested on both Chrome and Firefox.

**Comment by leebyron** [comment]
Fixed
