### ISSUE TITLE
Map.reduce() has unexpected behaviour

### ISSUE THREAD

**Issue by vkbansal** [facebook/immutable-js#702]
The initial value for the reducer is not respected.

The following code produces error: `TypeError: Cannot set property 'baz' of undefined`
```js
var data = Immutable.Map({
    "foo": "bar",
    "baz": "tofu"
});

console.log(
    data.reduce(function(red, val, key) {
        red[key] = val;
    }, {})
);
```

Immutable version: `3.7.5`
JSBin: http://jsbin.com/matecanija/edit?js,console

**Comment by WRidder** [comment]
You need to return the memo (red in this case) in the reduce function. Like this:

```javascript
var data = Immutable.Map({
    "foo": "bar",
    "baz": "tofu"
});

console.log(
    data.reduce(function(red, val, key) {
        red[key] = val;
        return red;
    }, {})
);
```

**Comment by vkbansal** [comment]
OH! My Bad. thanks @WRidder

**Comment by IgorSzymanski** [comment]
This is old, but I just saw it and couldn't help myself. If you use `immutable-js`, then why not write it in an immutable way?
```ts
data.reduce((red, val, key) => ({ ...red, [key]: val }), {})
```
