### ISSUE TITLE
List.lastIndexOf returns incorrect index

### ISSUE THREAD

**Issue by maxdjohnson** [facebook/immutable-js#703]
Not sure why this is broken, but here's a (jest) test case exposing the issue:
```
    let Immutable = require('immutable');
    let list = Immutable.fromJS([1, 2]);
    let value = list.max();
    let valueIndex = list.lastIndexOf(value);
    expect(Immutable.is(list.get(valueIndex), value)).toBe(true);
```
I get `Expected: false toBe: true` using immutablejs version 3.7.5

**Comment by mking** [comment]
:+1: Immutable.js is currently returning the index in the reversed sequence (ie, the index relative to the end), but I think it should return the index in the forward sequence. This would match both the behavior of [lodash](https://lodash.com/docs#lastIndexOf) and [String.prototype.lastIndexOf].

**Comment by leebyron** [comment]
Thanks for the report!
