### ISSUE TITLE
List type definition issue

### ISSUE THREAD

**Issue by ppoliani** [facebook/immutable-js#704]
Looking into the type definition file I came across this line:

```
export function List<T>(iterable: /*Iterable<T>*/Object): List<T>;
```

The problem with that is that we can actually introduce some bugs into our code. More specifically the above line lets us do things like this:

```
const y = List<string>([10]); 
```

and that's actually right because 

```
 const x: Object = 10;
```

is a valid TS code.

**Comment by leebyron** [comment]
This is an artifact from the type definitions being written before typescript supported ES6. The comment documents the intent while the actual type definition is the best effort typescript would support.

I'm happy to entertain pull requests which improve this!

**Comment by leebyron** [comment]
Fixed in master, will be released soon!
