### ISSUE TITLE
Update typescript definitions to latest version of typescript.

### ISSUE THREAD

**Issue by Strate** [facebook/immutable-js#705]
Typescript now support:
- tuples: `[int, string]` (usable for `entries(): Iterator<[K, V]>`)
- union types: `A | B` (usable for `concat(...valuesOrIterables: Array<Iterable<K,V> | V>`)

**Comment by chadaustin** [comment]
Also polymorphic this, which helps a ton for things like concat.

**Comment by Strate** [comment]
Related to #684

**Comment by Strate** [comment]
```
filter(
      predicate: (value?: V, key?: K, iter?: /*this*/Iterable<K, V>) => boolean,
      context?: any
    ): /*this*/Iterable<K, V>;
```
could be changed to
```
filter(
      predicate: (value?: V, key?: K, iter?: this) => boolean,
      context?: any
    ): this
```

**Comment by myitcv** [comment]
[Related discussion](https://github.com/typings/typings/issues/49)

**Comment by leebyron** [comment]
Updated in master branch, release soon
