### ISSUE TITLE
fromJS(false) should really be "{ }" ?

### ISSUE THREAD

**Issue by TCMiranda** [facebook/immutable-js#706]
FromJS(true)    // true
FromJS(2.5)     // 2.5
FromJS('hello') // hello

FromJS(null)   // { } *
FromJS(false)   // { } *
FromJS(undefined) // { } *

\* ok?

Thanks!!

**Comment by eliseumds** [comment]
@TCMiranda which Immutable.js version are you using? Commits https://github.com/facebook/immutable-js/commit/def9a096d25928d809930aa64fa1e4f07424f460 and https://github.com/facebook/immutable-js/commit/2f4882bcee40daa4c52cd67950fb890f62f9ce48 seem to cope with it.

I'm getting the following results when using version 3.7.5 in the browser and Node 4.2.2:

```
fromJS(null) // null
fromJS(false) // false
fromJS(undefined) // undefined
```

Anyway, I'm in favor of throwing exceptions.

**Comment by TCMiranda** [comment]
@eliseumds thank you for the answer. Happens that I was outdated.

Although, I am not in favor of exceptions, since the side effects could be huge. Also, we are semantically correct.

I am closing this. Thoughts about warnings/exception could be brought to a new issue, right?

Regards,
