### ISSUE TITLE
Immutable.Map() should accept object with numeric key

### ISSUE THREAD

**Issue by Strate** [facebook/immutable-js#707]
There should be one more Map function overload:

```
Map<V>(obj: {[index: number]: V}): Map<number, V>
```

alongside to

```
Map<V>(obj: {[index: string]: V}): Map<string, V>
```

**Comment by mking** [comment]
@Strate I think objects can only have string keys (for both JS and TS)

If you want a Map with integer keys, this works:
```
Immutable.Map([
  [1, 1],
  [2, 1]
])
```

**Comment by Strate** [comment]
This works also:
```
const obj: {[id: number]: any} = {}
Immutable.Map<number, any>(obj as Object)
```
but I should cast `obj` to Object, as you see.
I want to use `{[index: number]: any}` notation to prevent passing string to object keys.

**Comment by destan** [comment]
:+1:

**Comment by leebyron** [comment]
Unfortunately JS object keys are always strings and this is not possible
