### ISSUE TITLE
Generate definitions in index.d.ts

### ISSUE THREAD

**Issue by dlouwers** [facebook/immutable-js#711]
Apparently it's going to be standard for TypeScript to look for definitions in `index.d.ts`. Perhaps `Immutable.d.ts` could be renamed to `index.d.ts`?

**Comment by myitcv** [comment]
If a type definition is shipped with a package, then yes this is true.

However, it may be that [`typings`](https://github.com/typings/typings) is the best approach given the desire to support type definitions (for a given version of a ImmutableJS) for multiple versions of TypeScript. Related https://github.com/typings/typings/issues/49

**Comment by dlouwers** [comment]
Yes, reading https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages adding the path to `Immutable.d.ts` to the `"typings"` field in the distributed `package.json` would also work and in fact be the preferable path.

**Comment by leebyron** [comment]
Thanks for this info! I didn't know this was possible. I will look into making typescript and flow types for npm packages a first class feature in the next major version

**Comment by xogeny** [comment]
A data point.  I tried adding `typings` to `package.json` and pointing it to `dist/immutable.d.ts`.  But it failed.  I suspect that the version of `immutable.d.ts` that is present there is not "framed" properly for what `tsc` needs.  As such, I think a separate `.d.ts` file will be required.  I think I've seen this before and I suspect (although I don't know for sure) that all the is really required is to create a new file that uses a `<reference.../>` at the top to the current file and adds some additional details about the module.  I'll play around with it.

But I want to add that, in my opinion, it is **much** better to include an up to date `.d.ts` file in the NPM repository along with the `typings` field in `package.json` vs. adding the declarations file to `DefinitelyTyped`.  It makes use of NPM modules much easier and makes it much easier to avoid version skew.

**Comment by xogeny** [comment]
Ah, it seems as though #642 perhaps addresses the issue I'm currently seeing with `immutable.d.ts`.

**Comment by xogeny** [comment]
For reference, I submitted a pull request (#717) that shows what is required to get the `typings` field working.  It is pretty simple.  I don't necessarily expect you to accept that PR since it does have some problems (see PR) and I haven't signed an CLA.  But I at least wanted to show that the fix is simple and **really** simplifies using `immutable` with TS+NPM.
