### ISSUE TITLE
Seq backed by database

### ISSUE THREAD

**Issue by irisjay** [facebook/immutable-js#715]
I would like to use a KeyedSeq backed by a database, however the access the the database has some latency and so is accessed using an async method. I was wondering how could I use something like that to back a Seq. Thanks!

**Comment by leebyron** [comment]
You should check out https://github.com/Reactive-Extensions/RxJS - It provides methods for iterating over asynchronous streams.

**Comment by irisjay** [comment]
The thing is streams are quite a different beast from keyed associative arrays ie Objects

**Comment by leebyron** [comment]
That's exactly correct, and the primary difference is synchronicity. If your DB is a single async operation that results in a collection then you can use a JS Promise to model the database call and then use Immutable Seq to model the results. If accessing each next item is itself an async process then a Seq cannot model this, and you need to use something like a Stream or Observable (rxjs)
