### ISSUE TITLE
Permission/License to post TypeScript definition files to DefinitelyTyped 

### ISSUE THREAD

**Issue by leonyu** [facebook/immutable-js#716]
I am posting this issue to requesting permission that TypeScript definitions of `immutable-js` be allowed to be posted to DefinitelyTyped. (Reference: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6623)

Namely the following files:

* dist/immutable.d.ts
* contrib/cursor/index.d.ts
* type-definitions/Immutable.d.ts

Currently `immutable-js`'s definition is located in this repo with BSD license. DefinitelyTyped uses MIT license. I am not sure the difficult of re-licensing the `.d.ts` files. 

I have also written definition files for libraries that depends on `immutable-js`, namely `omniscient`, currently in my own project. I would like to contribute it to DefinitelyTyped, so people can use `omniscient` in TypeScript without having to write their own definitions. However, `omniscient` has a hard dependency on `immutable-js`, as such, my definition file would need to reference `immutable-js` or provide a suitable proxy (e.g. I write my own version of `immutable.d.ts` from scratch) 

Thank you very much.

**Comment by xogeny** [comment]
See #711 (and perhaps others) if you are using immutable as an NPM module.

**Comment by leebyron** [comment]
Closing this since I commented on the DefinitelyTyped task, and that should be good to go.

Moving forward, I believe supporting type definitions distributed through NPM is the right long term solution both for this library and for the node/js community.

**Comment by xogeny** [comment]
:+1:

**Comment by leonyu** [comment]
:+1:
Closing this as license hurdle has been resolved.
