### ISSUE TITLE
Typescript: Is it possible to initialize empty typed Map without coercing its type?

### ISSUE THREAD

**Issue by inakianduaga** [facebook/immutable-js#719]
How does one go about building up a typed map starting from an empty one without the compiler failing?

```js
// Product, ProductCollection are some classes.
const test: Immutable.Map<Product, ProductCollection> = Immutable.Map();
test.set(someProductInstance, someProductCollectionInstance);
```

In the above the first line fails but how on earth can I build up the typed Map otherwise?  

Of course I can always coerce the type like 

```js
// Product, ProductCollection are some classes.
const test: Immutable.Map<Product, ProductCollection> = <Immutable.Map<Product, ProductCollection> >  Immutable.Map();
test.set(someProductInstance, someProductCollectionInstance);
```

Is there a more elegant approach?

**Comment by inakianduaga** [comment]
Actually I just saw that this is also not possible in other languages

http://stackoverflow.com/questions/636126/best-way-to-create-an-empty-map-in-java

where types also have to be coerced. 

And more importantly, just thought about it some more and conceptually it doesn't even make sense that the compiler would infer the type of a map based on set properties because this could be broken anytime.

I'm closing this

**Comment by myitcv** [comment]
```typescript
const test = Immutable.Map<string, number>();
test.set("test", 5);
...
```

The TypeScript compiler can (and does) infer the type of the LHS from the RHS; hence you don't need the type annotation on the LHS.

Incidentally, also no need to declare this map as a `const`: it's immutable :smile:

**Comment by inakianduaga** [comment]
> The TypeScript compiler can (and does) infer the type of the LHS from the RHS; hence you don't need the type annotation on the LHS.

Cool much better with that notation.

> Incidentally, also no need to declare this map as a const: it's immutable

I thought `const` means you fix the reference the variable points to (which I want to do 99% of the time independently of whether the reference itself is an immutable object or not).

```js
let someVar = {};
const test = Immutable.Map<string, number>();
test = someVar
``

so wouldn't it be still useful to have?

**Comment by myitcv** [comment]
> so wouldn't it be still useful to have?

You're right. Not quite sure what I was thinking....
