### ISSUE TITLE
Feedback on cursors alpha support

### ISSUE THREAD

**Issue by tgriesser** [facebook/immutable-js#72]
Saw that you've added cursors to the library and were looking for feedback. Very cool.

I've been working on an implementation of om-style cursors based on mori's data structures, using a custom build of mori which allows for extending [vanilla JS objects with cljs protocols](https://github.com/swannodette/mori/pull/108) (thanks to some great tips from @swannodette)

https://github.com/tgriesser/mori-cursors

One of the coolest things about the om-style cursor implementation IMO is the ability to treat them as basic persistent data structures, each time a value is returned (`get`, `get_in`, `assoc`/`dissoc`, any seqable functions, etc.), so long as the value isn't a primitive, you'll receive a new cursor of the appropriate type (`MapCursor` / `VectorCursor`) which continues to keep track of its path in the root object automatically.

As far as I can tell, in the current implementation, you need to explicitly call `cursor` to create sub-cursors, and even then, it's a bit limited in scope with regards to being able to modify the local value of the cursor. 

For example in the implementation I linked above, you could have something like (using immutable's api):

```js
var data = Immutable.fromJS({
  users: [{
    name: 'Test',
    accounts: { /* deep nested data */ }
  }, {
    name: 'User',
    accounts: { /* deep nested data */ }
  }]
});
var c = data.cursor();
c.get('users') // would return a new VectorCursor, path ['users']
c.getIn(['users', 0]) // would return a new MapCursor, path ['users', 0]
c.getIn(['users', 0, 'name']) // would return 'Test', since name is a primitive

// Returns a new MapCursor, path ['users', 0], just without the 'accounts'
// map. This is useful in cases like React where you want to slice and dice into
// sub-cursors with a limited scope of data for efficient shouldComponentUpdate
c.getIn(['users', 0]).delete('accounts')
```

So the main idea is that the cursors should behave exactly like their respective data-structures from an API standpoint, only differing with the underlying "type" of the cursor, automatically keeping track of their path (which is hugely valuable).

Another main difference between this implementation and the one I mentioned above, is the idea of a "root" cursor, which sub-cursors are created from / updating against. There doesn't seem to be much value of just locating/updating values if they aren't coming from a central "root" object. In OM's case, I believe this is an atom, in the project I linked above it's just a special `RootCursor` which also acts an EventEmitter. My implementation is also pretty basic compared to OM's, nothing about deref'ing / taking into account render states.

Really cool to see that you're adding them to this project though, I've found them invaluable when using persistent data-structures with React, interested to see what you think about these ideas.

**Comment by leebyron** [comment]
Closing this out since it's old and discussion has been slurped up. Thanks again for the feedback, guys! I'm excited to see more cursor implementations come to be.
