### ISSUE TITLE
Node buffers have an .equals() method too

### ISSUE THREAD

**Issue by callumlocke** [facebook/immutable-js#720]
Is this considered a problem for Immutable's `is` algrorithm?

``` js
var Immutable = require('immutable');

var map1 = Immutable.Map({
  foo: new Buffer('hi'),
});

var map2 = Immutable.Map({
  foo: new Buffer('hi'),
});

Immutable.is(map1, map2); // true

map1.get('foo').x = 123;

Immutable.is(map1, map2); // true
map1.get('foo').x; // 123
map2.get('foo').x; // undefined
```

([Try above snippet on Tonic](https://tonicdev.com/callumlocke/node-buffers-as-immutable-values))

see [Node Buffer#equals()](https://nodejs.org/api/buffer.html#buffer_buf_equals_otherbuffer)

**Comment by leebyron** [comment]
Actually this is kind of awesome, I'm not sure I would consider this problematic but an (accidental) usage of Immutable.js's value protocol by node Buffer.

I suppose this is a problem for Immutable.js as much as the following is a problem for Node:

```js
var buf1 = new Buffer('hi');
var buf2 = new Buffer('hi');
buf1.x = 123;
buf1.equals(buf2); // true
```

I'm curious what your expectations here. Should we not treat buffers as values? Does this cause a real issue for you, or is this only a theoretical concern?

**Comment by callumlocke** [comment]
It's just a theoretical concern yeah. I can see it might be a happy accident...

**Comment by leebyron** [comment]
Closing this aging issue
