### ISSUE TITLE
withMutations() should throw if you try to use methods that have no effect

### ISSUE THREAD

**Issue by callumlocke** [facebook/immutable-js#721]
I was trying to debug something like this for a long time:

```
x = x.withMutations(map => {
  map.filter(value => ...).map(value => ...)
})
```

... then I noticed the [footnote](http://facebook.github.io/immutable-js/docs/#/Map/withMutations) that "Only set and merge may be used mutatively."

Why is it possible to call `.filter()`, `.map()` etc if they do nothing? Shouldn't they throw an error?

**Comment by awendland** [comment]
Or better yet, why can't these methods be made to do something when inside a withMutations scope?

**Comment by DetweilerRyan** [comment]
+1

**Comment by jamesopti** [comment]
Similarly, `.delete` behaves in unexpected ways. It should throw if the method being called on the mutating state object is not supported:

```
var l1 = Immutable.List(['a', 'b', 'c']);
var l2 = l1.withMutations(newState => {
  newState.delete(1);
  return newState;
}); 

// Expected
['a', 'c']

// Actual
[]
```

**Comment by leebyron** [comment]
Unfortunately this would add a performance burden. Since `withMutations` is designed to be a critical path optimization, I'd prefer not to incur a performance cost
