### ISSUE TITLE
isSuperset() doesn't work with array as an argument

### ISSUE THREAD

**Issue by adamboduch** [facebook/immutable-js#722]
Not sure if `isSuperset()` is supposed to accept arrays as an argument - it seems like it's supposed to based on the docs. Here's the issue:
```js
// Works...
Immutable.List.of(1, 2, 3).isSuperset(Immutable.List.of(1, 2));
// true

// Doesn't work...
Immutable.List.of(1, 2, 3).isSuperset([ 1, 2 ]);
// Uncaught TypeError: t.isSubset is not a function(…)
```

Here's a [fiddle](https://jsfiddle.net/adamboduch/ctxjn315/) demonstrating the issue.

**Comment by leebyron** [comment]
Thanks for the report!

**Comment by marcacyr** [comment]
@adamboduch Looks like in that fiddle you're using 3.6.4. I just tried this out with 3.7.6 (the newest release from about 15 days ago) and both appear to be working as expected (returning true).

**Comment by adamboduch** [comment]
@marcacyr Cool. That was my bad for not checking the version. Thanks for looking into it.
