### ISSUE TITLE
2016 Roadmap

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#724]
Check out the roadmap for Immutable.js here https://www.facebook.com/notes/lee-byron/immutablejs-2016-roadmap/10153447836068757

This is a strawman document, which means I'm interested in your feedback on these priorities and to understand if I may have missed something.

Feel free to use this issue as a place to leave comments!

**Comment by hackwaly** [comment]
Have you seen this article (http://bendyworks.com/leveling-clojures-hash-maps/)? It might be useful to improve performance.

**Comment by SH4DY** [comment]
@leebyron you mentioned Records in the roadmap. What is the plan for Records in combination with Typescript? I'm refactoring my TypeScript flux implementation to use ImmutableJS but atm I'm losing all the nice type generics in my React Components. I saw some issues here but I wanted to know the 'official' plan?

**Comment by ide** [comment]
Kind of related to API simplicity -- a REPL would go a long way. A big reason I go to the Immutable docs is to open up the Web Inspector and see what different method calls do. Building a REPL is a fairly well-defined task too so getting help from the community could be an option here.

**Comment by pemrouz** [comment]
Nice work on the roadmap! +1 to modularisation (and any other size refinements): 55kB minified is currently too prohibitively large to embrace in many projects/frameworks. I'd like to leverage this internally in my framework, but the rest of the [(full-stack) framework is 6kB](https://github.com/pemrouz/ripple/blob/master/dist/ripple.pure.min.js.gz), so the bloat would make it a burden for some users/cases.

Another option for the size-conscious perhaps could also be to provide a simpler `.lite.js` version/build?

**Comment by MSch** [comment]
We're currently working on using immutable.js with flux. A complete and correct type declaration for immutable.js and good support for Records would be highly appreciated, this is the area where we've been running into roadblocks.

**Comment by SH4DY** [comment]
@MSch yes, same problem here. Flux stores with the power of compile-time type checks have a lot of potential. Combined with immutable data structures even more. Sadly Records are not ready for TypeScript.

**Comment by dashed** [comment]
Modularity is definitely something I'm looking forward to. I've been watching the status of this at this issue https://github.com/facebook/immutable-js/issues/317

**Comment by dubrowgn** [comment]
>  To achieve this, some API changes will be necessary, for example removing `myThing.toMap()` in favor of `Map(myThing)`.

I would just like to point out some issues around getting rid of `toMap()`. Take a look at #600 and #697. Ideally, this sort of behavior would fit better under the `map()` function, but you cannot specify keys via `map()`.

**Comment by danielepolencic** [comment]
On the subject of *Interoperability with JavaScript*, Chrome 47+ supports customer formatters.
[I wrote a simple formatter](https://github.com/danielepolencic/immutablejs-devtools) to prettify the output of Immutable.js data structures.

If this is something of interest, I'm happy to do a PR and include it in the REPL for the doc pages.

**Comment by dashed** [comment]
@danielepolencic oh man that's amazing! :+1: Definitely going to check this out. :smile:

**Comment by dfguo** [comment]
@danielepolencic this is really helpful. Thanks for sharing!

**Comment by vinnymac** [comment]
I am looking forward to Modularity, API Simplicity (which I hope to find some time to contribute to!), and React use cases improving.

It has been requested [before](https://github.com/facebook/immutable-js/issues/88), but a great addition to 2016 would be the [SortedMap](https://docs.oracle.com/javase/8/docs/api/java/util/SortedMap.html). A helpful [implementation](https://github.com/montagejs/collections/blob/master/sorted-map.js) from [collection.js](http://www.collectionsjs.com/). I could see this being useful in several projects.

@danielearwicker I have been using, [immutable-devtools](https://github.com/andrewdavey/immutable-devtools) maybe you guys could collaborate. Thanks for the formatter!

**Comment by danielearwicker** [comment]
@vinnymac you tagged me, but I'm not sure why - was it intentional? :)

**Comment by vinnymac** [comment]
@danielearwicker github's autocomplete ranked you higher up, my mistake 😅. Happy to accidentally include you in this thread.

**Comment by cameronbourke** [comment]
Be really cool to see the roadmap of Immutable find it's way into the language eventually! The spec by Sebastian Markbage is a great start, https://github.com/sebmarkbage/ecmascript-immutable-data-structures. What are people's thoughts?

**Comment by axefrog** [comment]
I'd also like to voice my support for pre-sorted maps, sets and lists. Currently I have to add an item to an ordered map and then sort it. Even though the entire list will have already been in the correct order aside from the last item, it still takes the same amount of time to sort the new item into the correct position as it would if all of the items were out of order. The slowdown is noticeable when dealing with lists containing hundreds of thousands of items, and it's even worse with a million or more items. A sort that is applied at insertion time would mitigate this issue almost entirely. #88

**Comment by deepsweet** [comment]
any news on "Modularity"? maybe it could a good first step to transpile `src/` to `lib/` as is in terms of included files? so we can import Map like `import Map from 'immutable/lib/Map'`.
