### ISSUE TITLE
`deleteIn` behaves incorrectly for Map and OrderedMap 

### ISSUE THREAD

**Issue by bvaughn** [facebook/immutable-js#729]
I would expect the below 3 blocks to function the same but both `Map` and `OrderedMap` throw errors when `deleteIn` is used.

```js
var fromJS = new Immutable.fromJS({ foo: { bar: 'baz' } })
JSON.stringify(fromJS.toJS()) // {"foo":{"bar":"baz"}}
JSON.stringify(fromJS.delete('foo').toJS()) // {}
JSON.stringify(fromJS.deleteIn(['foo', 'bar']).toJS()) // {"0":{}}

var map = new Immutable.Map({ foo: { bar: 'baz' } })
JSON.stringify(map.toJS()) // {"foo":{"bar":"baz"}}
JSON.stringify(map.delete('foo').toJS()) // {}
JSON.stringify(map.deleteIn(['foo', 'bar']).toJS()) // Uncaught Error: invalid keyPath

var orderedMap = new Immutable.OrderedMap({ foo: { bar: 'baz' } })
JSON.stringify(orderedMap.toJS()) // {"foo":{"bar":"baz"}}
JSON.stringify(orderedMap.delete('foo').toJS()) // {}
JSON.stringify(orderedMap.deleteIn(['foo', 'bar']).toJS()) // Uncaught Error: invalid keyPath
```

I see one related issue #489 but it doesn't show the problem quite so clearly IMO.

In my opinion, this problem is serious enough to make use of `Map` and `OrderedMap` very questionable.

**Comment by bvaughn** [comment]
To elaborate a bit on why I think it's a fairly sever issue- it prevents things like the following:
```js
Immutable.List(myArray).toOrderedMap()
```

And instead requires users to use a more verbose approach like so:
```js
Immutable.fromJS(
  myArray
    .reduce((map, item, index) => {
      map[index] = item
      return map
    }, {})
)
```

**Comment by bvaughn** [comment]
For what it's worth, I have noticed that the following doesn't exhibit the problem mentioned above:

```js
Immutable.fromJS(myArray).toOrderedMap()
```

Looks like `Map`, `List`, and others aren't good about converting deep objects?

**Comment by bvaughn** [comment]
After more thought and time spent poking at this issue, I think I'm going to close the bug as invalid. It really boils down to the fact that `fromJS` is the only safe way to instantiate nested structures.

_That being said_ - I think it's too easy to be burned by this. `Map`/`List`/whatever _appear_ to function similarly but will break down the road. Sometimes the "breaks" will manifest as errors (like I initially reported) and sometimes they will just silently fail to return an updated immutable structure. When it happens, it's usually pretty difficult to debug. I've run into similar issues when using `updateIn` or `mergeIn` (accidentally "corrupting" my immutable structure).

I _think_ the objects accept plain JS data-types as constructor parameters so as not to _force_ a tree to be Immutable all the way to the leaves- but (anecdotally) I think it's weird and confusing to have a mix of immutable and non-immutable structures. It makes your operations surprising and hard to reason about.

**Comment by ffxsam** [comment]
I just got bit by this too. @leebyron, can you weigh in on this? Why are these two statements not the same:

```js
fields = Immutable.fromJS({ email: { name: 'email', failProps: { boo: true } } });
fields = Immutable.Map({ email: { name: 'email', failProps: { boo: true } } });
```

**Comment by bvaughn** [comment]
@ffxsam `Immutable.Map()` and `Immutable.List` create shallow immutable structures. They're faster than `fromJS` which creates a deeply immutable structure.

Personally I think it's `fromJS` behaves more intuitively since it prevents nested data from being mutated. But I think the design decision was an intentional one.

Put another way...
```js
var data = { foo: { bar: 'baz' } }
var deep = Immutable.fromJS(data)
var shallow = Immutable.Map(data)

deep.get('foo').bar = 123

JSON.stringify(data) // "{"foo":{"bar":"baz"}}"

shallow.get('foo').bar = 123

JSON.stringify(data) // "{"foo":{"bar":123}}"
```

**Comment by ffxsam** [comment]
I still don't get it. What does "shallow" mean in this context?

This is also interesting:

```
shallow.setIn(['foo', 'bar'], 'wow').toJS()
Result:
Uncaught Error: invalid keyPath(…)

deep.setIn(['foo', 'bar'], 'wow').toJS()
Result:
{
  "foo": {
    "bar": "wow"
  }
}
```

**Comment by bvaughn** [comment]
Shallow meaning..
```js
// If you start with this...
var data = {
  foo: {
    bar: 'baz'
  }
}

// This will create a deeply immutable structure...
const deep = Immutable.fromJS(data)
deep.get('foo') instanceof Immutable.Collection === true

// This will create a shallow immutable structure...
const shallow = Immutable.Map(data)
shallow.get('foo') instanceof Immutable.Collection === false
```
...and all the things that comes with this, meaning that your Immutable calls and methods only go 1 level deep. So you can't use `getIn`, `setIn`, etc. Also means you can mutate the underlying data.

**Comment by ffxsam** [comment]
Ahhhhh! Ok, that makes sense. And also explains why the deep methods don't work. I just wish the documentation better explained these differences. What is even the point of using `Map()` then? I can't think of any scenarios where I'd use it.

**Comment by bvaughn** [comment]
It's faster, so some people prefer it. I think it makes for a really confusing/bizarre experience- particularly if you have an Immutable store and you want to pass pieces of it to React components. If you don't know which piece is Immutable and which isn't- things get harry. :)

**Comment by ffxsam** [comment]
Faster? So my app will save 20 microseconds? 😉

**Comment by bvaughn** [comment]
The perf gains are not worth the added complexity in the applications I use Immutable in- but depending on how big your store tree is, and how frequently it's updated, performance may be a valid concern.

**Comment by leebyron** [comment]
I think @bvaughn summed it up well. Though this isn't really a performance concern, it's more of a correctness concern. Making a `List` of React components is a great example:

`Immutable.fromJS([ <div />, <span /> ])` would coerce those React components into Maps. `Immutable.List([ <div />, <span /> ])` won't touch the children elements.

Obviously there are plenty of examples where this could bite you, React components was just one brought up here. Anything that's intended to remain a JS object shouldn't be forcibly converted. Also `fromJS` only ever builds `List` and `Map`, but of course there are plenty of other data structures you might want to use, which is best represented by using them directly.

This isn't unique to Immutable.js but also is how data structure constructors work in JavaScript:

```Set([ ['A'], ['B'] ])``` does not result in a Set of Sets, it results in a Set of Arrays.

**Comment by bvaughn** [comment]
D'oh. Good point. I tend to use Immutable for making data structures out of POJOs so I overlook use cases like Lists of React components. Thanks for pointing that out. :)
