### ISSUE TITLE
keySeq converts ints to strings

### ISSUE THREAD

**Issue by derekdreery** [facebook/immutable-js#731]
The nodejs code
```javascript
var immutable = require('immutable');                                           
                                                                                
console.log(immutable.fromJS({1: 'test', 2: 'test2'}).keySeq().toJS());
```
outputs
```
[ '1', '2' ]
```

I expected
```
[ 1, 2 ]
```

Is this expected behaviour or a bug?

**Comment by Dashed** [comment]
This is expected behaviour since object keys are **always** strings (provided keys will be converted to strings). Thus, the keys of the object fed into `Immutable.fromJS(...)` are strings.

**Comment by derekdreery** [comment]
Thanks
