### ISSUE TITLE
Updating multiple values with .updateIn()

### ISSUE THREAD

**Issue by kennetpostigo** [facebook/immutable-js#732]
Hello, 

I'm currently using `Immutable` for a project thats under development. I'm pretty new when it comes to immutable. I'm attempting to update multiple values within a `Map` and I know some of the issues that are causing the errors I'm just not sure how to resolve them.

```js
//Initial attempt
export function handleUpdateSneaker (state, sneaker, sneakerDif) {
  var userSneakers = state.getIn(['dashboard', 'userSneakers']);
  var index = userSneakers.indexOf(sneaker);
  return state.updateIn(['dashboard', 'userSneakers'], sItem => {
    sItem.sneakerName = sneakerDif.sneakerName;
    sItem.shoeSize = sneakerDif.shoeSize;
    sItem.price = sneakerDif.price;
    sItem.trade = sneakerDif.trade;
    sItem.isbm = sneakerDif.isbm;
    sItem.info = sneakerDif.info;
    sItem.brand = sneakerDif.brand;
    sItem.quality = sneakerDif.quality;
    sItem.reRelease = sneakerDif.reRelease;
    sItem.colors = sneakerDif.colors;
  });
}

//Trying to solve the 2 problems stated below
export function handleUpdateSneaker (state, sneaker, sneakerDif) {
  var userSneakers = state.getIn(['dashboard', 'userSneakers']);
  var index = userSneakers.indexOf(sneaker);
  return state.updateIn(['dashboard', 'userSneakers', index], sItem => {
    sItem.set('sneakerName', sneakerDif.get('sneakerName', sneakerName));
    sItem.set('shoeSize', sneakerDif.get('shoeSize', shoeSize));
    sItem.set('price', sneakerDif.get('price', price));
    sItem.set('trade', sneakerDif.get('trade', trade));
    sItem.set('isbm', sneakerDif.get('isbm', isbm));
    sItem.set('info', sneakerDif.get('info', info));
    sItem.set('brand', sneakerDif.get('brand', brand));
    sItem.set('quality', sneakerDif.get('quality', quality));
    sItem.set('reRelease', sneakerDif.get('reRelease', reRelease));
    sItem.set('colors', sneakerDif.get('colors', colors));
  });
}
```

In the code snippet above Im using `getIn()` to reach within the `dashboard Map() -> userSneakers List()` and to find the correct `Map` within the `userSneakers List()` I am using `indexOf()` to return the index of the correct item to update its fields. 
Now the __Problems__ that I can identify are:
1. You cant use `.`(dot) notation when trying to use access the values within an *Immutable* `Map`.
2. When I use `updateIn` I'm reaching within  `dashboard Map() -> userSneakers List()` but not specifying the correct object that I got from `indexOf` to modify.

Im not sure how to fix those 2 problems and would appreciate if someone could explain to me how to fix it because I can imagine that I will encounter similar problems throughout the duration of the project.

Any and All help is appreciated 🙂

**Comment by tgriesser** [comment]
First, you need to return the updated value in the `updateIn`

I'd probably do something like:

```js
const KEYS = [
  'sneakerName',
  'shoeSize',
  'price',
  'trade',
  'isbm',
  'info',
  'brand',
  'quality',
  'reRelease',
  'colors'
]

export function handleUpdateSneaker(state, sneaker, sneakerDif) {
  var userSneakers = state.getIn(['dashboard', 'userSneakers']);
  var index = userSneakers.indexOf(sneaker);
  return state.updateIn(['dashboard', 'userSneakers', index], sItem => {
    return KEYS.reduce((map, key) => {
      return map.set(key, sneakerDif.get(key /*, fallbackValue[key] */))
    }, sItem)
  })
}
```

**Comment by kennetpostigo** [comment]
@tgriesser thank you for the feedback, I didn't think about using `reduce`. I'll test it out now and let you know how it goes!

**Comment by kennetpostigo** [comment]
@tgriesser My unit-tests checked out! Thank you so much, going to use this as a blueprint for how I go about making multiple changes through out the App!

**Comment by kennetpostigo** [comment]
@tgriesser , After looking at your code for a bit and trying to understand it, Im not completely sure whats going on. Would you mind explaining whats going on there?
