### ISSUE TITLE
immutable Map in Promise.all

### ISSUE THREAD

**Issue by hydRAnger** [facebook/immutable-js#733]
I got a bug when I use this:
```
const promises = aImmutableMap.map(
      (val, key) => API.get(`something/${val.id}`).then(callback));
 );

await Promise.all(promises);
```
It's failed, at first I think maybe I should use a native JS Array here, but I found: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols
It say: 'Some built-in types are built-in iterables with a default iteration behavior, such as Array or Map, while other types (such as Object) are not.'

So I think a Immutable Map will be Ok(like a native JS Map), but in fact it's not, it seems like Promise.all look for a structure like: [promise1, promise2, promise3], but a Immutable Map iterable like this: [[key1: promise1], [key2: promise2], [key3, promise3]], it dosen't work.

I found this: https://github.com/facebook/immutable-js/issues/236
but this only focus on Immutable List in Promise.all, I want to know is either Immutable Map should supported Promise.all, or my understanding is wrong? thx a lot.

**Comment by leebyron** [comment]
Unfortunately `Promise.all` is fairly limiting in this way.

You might notice that using ES6's `Map` has the same issue.

Since you want to Promise.all the values of the Map, I would suggest:

`await Promise.all(promises.values())`
