### ISSUE TITLE
Typescript compatible

### ISSUE THREAD

**Issue by joesonw** [facebook/immutable-js#734]
add ```"typings":"./dist/immutable.d.ts"``` to `package.json` would allow `Typescript` to automatically import the definitions without implicitly reference it in each file uses it

**Comment by simonh1000** [comment]
+1

**Comment by ogaya** [comment]
+1

**Comment by eliseumds** [comment]
:+1:

**Comment by aslagle** [comment]
+1

**Comment by skomputer** [comment]
+1

**Comment by TheTedAdams** [comment]
For me this results in:

`error TS2656: Exported external package typings file '[...]/node_modules/immutable/dist/immutable.d.ts' is not a module. Please contact the package author to update the package definition.`

**Comment by dsebastien** [comment]
+1 but the module definition seems to have a problem

**Comment by drew-moore** [comment]
+1
