### ISSUE TITLE
best way to make a 2d array immutable?

### ISSUE THREAD

**Issue by ccnuyan** [facebook/immutable-js#736]
help me

**Comment by calesce** [comment]
```Immutable.fromJS([[0, 1], [1, 0]])``` will give you a List of Lists.

**Comment by sabahang** [comment]
```
var a = Immutable.fromJS([[0, 1], [1, 0]]);
console.log(a.toArray());
```

Doesn't give you what it's supposed to! It prints the internals of the Immutable List object instead...

**Comment by leebyron** [comment]
toArray will not alter the items in the list, in this case more Immutable List, since this is a 2D List. Use toJS() to deeply convert Lists to Arrays. Otherwise what you are seeing is fully expected

**Comment by mqliutie** [comment]
How can I do deduplication?

`fromJS([[1,1],[1,1]])` to  **List {size:1}**  `List.toJS() === [[1,1]]`
