### ISSUE TITLE
Possible to use set for multiple insertions?

### ISSUE THREAD

**Issue by skeie** [facebook/immutable-js#738]
Hi, 

This is maybe a pretty stupid question, but anyway. If you have a immutable records looking like this:

```
const user = Record({
    id: null,
    name: '',
    username: null
});
```

is it possible to update id, name and username within the same command?
I mean something like this: `this.set('id': 1337, 'name': 'Test', 'username': 'Test123')` ?

**Comment by dchest** [comment]
First of all, make sure you really want to do it. In your example you're setting all the fields from their default values. You probably want to define a record like this:

```js
const UserRecord = Record({
  id: null,
  name: '',
  username: null
})
```

and then use `new` to create users from it:

```js
const testUser = new UserRecord({
  id: 1337,
  name: 'Test',
  username: 'Test123'
})
```

If you actually want to set multiple properties, you can use `merge`:

```js
const changedUser = testUser.merge({
  name: 'Changed test',
  username: 'Changed Test123' 
})
```

**Comment by skeie** [comment]
Ah, ofc! Thanks @dchest!
