### ISSUE TITLE
[Question] efficient use of reduce with an immutable reduction?

### ISSUE THREAD

**Issue by mattkrick** [facebook/immutable-js#747]
What's the best way to reduce to an `Immutable.List`?

 My first attempt is:
```
const newList = list.reduce((newList, val) => {
      /*do stuff*/
      return newList.push(val);
    }, List())
```
Then i started wondering if I needed something like:
```
const newList = list.withMutations(mutList => mutList.reduce((newList, val) => {
      /*do stuff*/
      return newList.push(val);
    }, List()))
```
Does the second approach do anything? Does the first way already have `withMutations` built-in?

**Comment by leebyron** [comment]
The second list will not do anything, because you're iterating over the temporarily mutable list rather than the immutable seed list:

```js
const newList = List().withMutations(mutList => {
  list.reduce((newList, val) => {
      /*do stuff*/
      return newList.push(val);
    }, mutList))
```
