### ISSUE TITLE
indexOf of list doesn't work even when called on itself

### ISSUE THREAD

**Issue by qhenkart** [facebook/immutable-js#749]
The indexOf method of List is not working with one of the recent updates. We even tested it on itself

state is a Map, items is a List of Maps:
```javascript
state.get("items").indexOf(state.get("items").last())
//-1
```

**Comment by ThomasCrvsr** [comment]
@qhenkart : for the example you wrote, are you sure the List returned by `state.get('items')` is not empty ?

**Comment by qhenkart** [comment]
I am sure, but I cannot duplicate the problem anymore so I'm going to close the issue, thanks anyway! If it happens again I'll put together a better report
