### ISSUE TITLE
Download link for immutable.min.js broken 

### ISSUE THREAD

**Issue by babblebat** [facebook/immutable-js#751]
Clicking on the link to download immutable.min.js from the page at https://facebook.github.io/immutable-js/ gives a 404.

**Comment by P3trur0** [comment]
The actual broken link is this:

https://facebook.github.io/immutable-js/dist/immutable.min.js

Thank you!

**Comment by babblebat** [comment]
That link gives 404 as well.

**Comment by leebyron** [comment]
fixed
