### ISSUE TITLE
Immutable.fromJS() not returning Immutable object in custom REPL

### ISSUE THREAD

**Issue by lastcoolnameleft** [facebook/immutable-js#752]
[tfalgout@beyondinto-lm foo]$ cat repl
# !/usr/bin/env node

var repl = require("repl");

var replServer = repl.start({
  prompt: "necs> ",
});
replServer.context.Immutable = require('immutable');
[tfalgout@beyondinto-lm foo]$ ./repl
necs> Immutable.fromJS({1:2});
{ '1': 2 }
necs> .exit
[tfalgout@beyondinto-lm foo]$ node

> var Immutable = require('immutable');
> undefined
> Immutable.fromJS({1:2});
> Map { "1": 2 }
> .exit
> [tfalgout@beyondinto-lm foo]$ node -v
> v5.2.0
> [tfalgout@beyondinto-lm foo]$ npm list
> /private/tmp/foo
> └── immutable@3.7.6

**Comment by ThomasCrvsr** [comment]
This would be more a problem with the `repl` module which doesn't print the type no ?

**Comment by lastcoolnameleft** [comment]
Bumping this since I would really like to resolve this issue so I can use ImmutableJS:

I don't believe that it's an issue with the repl module since I see this issue even if I console.log() the output.  I'm unable to get ImmutableJS to return a Map in any runtime environment of Node outside of running the CLI:


Doesn't work:
```
[tfalgout@beyondinto-lm necs]$ cat bin/repl2
#!/usr/bin/env node
"use strict";
var repl = require("repl");
var replServer = repl.start({});
[tfalgout@beyondinto-lm necs]$ bin/repl2
>  var Immutable = require('immutable');
undefined
>  Immutable.fromJS({a:{b:{c:[3,4,5]}}});
{ a: { b: { c: [Object] } } }
> console.log( Immutable.fromJS({a:{b:{c:[3,4,5]}}}));
{ a: { b: { c: [Object] } } }
```

Works:
```
[tfalgout@beyondinto-lm necs]$ node
> var Immutable = require('immutable');
undefined
> console.log( Immutable.fromJS({a:{b:{c:[3,4,5]}}}));
Map { "a": Map { "b": Map { "c": List [ 3, 4, 5 ] } } }
undefined
> .exit
```

I'm sure there's something with my environment that is causing problems; however, I'm not sure where to look.  I have the same issue if I run via mocha test too.  (i.e. Immutable returns an object, not a Map)

**Comment by lastcoolnameleft** [comment]
I have tested this issue on v.0.10.41 and v4.3.0

**Comment by leebyron** [comment]
Merging into #1039
