### ISSUE TITLE
set is not zero-based

### ISSUE THREAD

**Issue by danielepolencic** [facebook/immutable-js#754]
```js
Immutable.Set.of(1, 2, 3).get(0)
//undefined
Immutable.Set.of(1, 2, 3).get(1)
//1
Immutable.Set.of(1, 2, 3).toList().get(0)
//1
```

I guess this is by design. Can someone point me to the documentation where this is stated?

**Comment by pandanoir** [comment]
As far as I know, set.get(i) returns i if this has i.

```
Immutable.Set.of(4, 2, 3).get(4); // => 4
```

**Comment by pandanoir** [comment]
get() is defined in IterableImpl.js.

get() calls find(). find() calls findEntry(). findEntry() calls __iterate(). __iterate() uses _map of Set.

Set.of(1, 2, 3)._map is {1: true, 2: true, 3: true}.

**Comment by danielepolencic** [comment]
> Get
> Returns the value associated with the provided key [...]

Maybe the documentation should be updated?

**Comment by pandanoir** [comment]
> When iterating a Set, the entries will be (value, value) pairs. Iteration order of a Set is undefined, however is stable. Multiple iterations of the same Set will iterate in the same order.

I found this explanation about Set. So the documentation don't have to be updated.

**Comment by danielepolencic** [comment]
Thank you. that was what I was looking for
