### ISSUE TITLE
Lenses

### ISSUE THREAD

**Issue by scato** [facebook/immutable-js#758]
Does anyone know of a library that provides lenses for Immutable Maps and Lists? Like https://hackage.haskell.org/package/lens-4.13/docs/Data-Map-Lens.html

If not would this be something to add to contrib?

**Comment by ThomasCrvsr** [comment]
You could give a try with Ramda : http://ramdajs.com/docs/#lens

**Comment by scato** [comment]
@ThomasCrvsr, thanks for the tip!

I can create a lens for a key in a Immutable.Map like so:

```
const R = require('R');

const get = R.invoker(1, 'get');
const set = R.invoker(2, 'set');
const xLens = R.lens(get('x'), set('x'));
```

**Comment by ThomasCrvsr** [comment]
@scato Great ! :) For my curiosity, why is your use case of lenses in your application ?

**Comment by scato** [comment]
@thomascrvsr I didn't get around to writing anything yet, but I was thinking about combining Redux and Immutable. I could use lenses to turn a reducer for an element of a map into a reducer for the entire map.

For example, your world is a Map with keys "rooms" and "inventory", and lists with Rooms and Items as values. If your user performs an Action that opens a box (which is an item), you can define a reducer for one Item and turn that into reducers for a list of Items, a Room, a list of Rooms and finally the world.

**Comment by scato** [comment]
after reading the docs again, I discovered that Map#update() does the same thing as a "over" does for lenses. This could be useful.

**Comment by ThomasCrvsr** [comment]
I began using Redux last week, and your idea looks really interesting :) Gonna try it probably during the next weeks ^^
