### ISSUE TITLE
Typescript definition at DefinitelyTyped

### ISSUE THREAD

**Issue by polkovnikov-ph** [facebook/immutable-js#764]
There's a `tsd` definiton manager that makes using libraries a lot easier. Though it uses a DefinitelyTyped repo. Unluckily, Immutable.js [is not there](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/CONTRIBUTORS.md).

Could you send a PR to DefinitelyTyped, please? I would do that myself, but I'm unsure if it's legal.

**Comment by polkovnikov-ph** [comment]
Any movement?

**Comment by TheTedAdams** [comment]
I think this isn't in DefinitelyTyped because a [immutable.d.ts](https://github.com/facebook/immutable-js/blob/master/dist/immutable.d.ts) is being shipped with the node package, so one in DefinitelyTyped is not necessary (the Typescript compiler should check node_modules for typings). Unfortunately something is wrong with how the typings are set up and the typescript compiler gives me a `error TS2307: Cannot find module 'immutable'.` error

**Comment by polkovnikov-ph** [comment]
@TheTedAdams Have you ever used `tsd` to say it's not necessary? :)

And nope, TypeScript doesn't have to check anything except of project source code and a bunch of external definitions. That's why they're called external.

**Comment by TheTedAdams** [comment]
Yes I use TSD (Although it was recently deprecated so I need to make the switch to Typings).

I just don't see the use of having duplicated d.ts files in node_modules and typings folders. My understanding is that the DefinitelyTyped repository is to fill in for libraries that do not ship with their own typings. If the immutable authors are going to maintain their d.ts files in their own repo and ship it to npm it seems unnecessary to also maintain a second copy in the DefinitelyTyped repo.

That being said, I'm no expert, if you have a reason to have the .d.ts in node_module and typings then sorry to bug ya :)

**Comment by polkovnikov-ph** [comment]
@TheTedAdams The problem is that we need to maintain typings in a controllable, predictable way. If we have to point to an unknown, mutable location somewhere in `node_modules`, we cannot do so. We have no guarantees. We could've probably just trusted `immutable.js` authors to never change that location, but based on broken tests for typings and their level of disrespect for users, I'd rather expect `d.ts` to disappear from `node_modules` folder completely on a first year of having a project in production.

**Comment by dsebastien** [comment]
Personally, I like the fact that typings are delivered with the project.
What's missing is the "typings" property in the package.json file of immutable.js which will let the TS compiler find the typings (i.e., remove the need to have a /// reference at the top of your TS files).

There's an open PR for that: https://github.com/facebook/immutable-js/pull/779

**Comment by leebyron** [comment]
Released
