### ISSUE TITLE
Weird behavior with mergeDeepIn Immutable Map with typeof 'number' keys

### ISSUE THREAD

**Issue by teod** [facebook/immutable-js#766]
mergeDeepIn method breaks the structure when merging on keys of type 'number':
Please see the below testcase:
```javascript
var i = Immutable.fromJS({1: {status: true}, 2: {status: false}});
```
Doing the below operations we will get the results:
```javascript
i.get(1); -> undefined;
i.get('1').toJS(); -> {status: true}
```
Let's say that we create a new Immutable Map by merging i with a new value for the 1 keyed entry:
```javascript
var t = i.mergeDeepIn([1], {status: false});
```
Doing the below operations will get the results:
```javascript
t.size; -> 3;
t.get('1').toJS(); -> {status: true} // initial i's status
t.get(1).toJS(); -> {status: false} // merged t's status

t._root.entries; ->
[["1",{"status":true}],["2",{"status":false}],[1,{"status":false}]] // both i's and merged values

t.toJS(); ->
{"1":{"status":false},"2":{"status":false}} // both statuses false
```
On the other hand if we deepMergeIn using a typeof 'string' key:
```javascript
var t = i.mergeDeepIn(['1'], {status: false});
t.get(1); -> undefined
t.get('1').toJS(); -> {status: false}

t.toJS(); ->
{"1":{"status":false},"2":{"status":false}}

t.size; -> 2
````

Is this a bug in Immutable ?

**Comment by tgriesser** [comment]
Nope, it's the standard behavior of JS objects - see #593, #443. You'll need to use "Iterable of [K, V] tuple entries" form of constructing a map rather than fromJS if you want to preserve the numeric type of the keys.
