### ISSUE TITLE
Setting multiple properties at once on records

### ISSUE THREAD

**Issue by delenius** [facebook/immutable-js#767]
It would be nice to be able to do this:

``` javascript
let newObj = oldObj.set({ a: foo, b: bar })
```

instead of

``` javascript
let newObj = oldObj.set(a,foo).set(b,bar)
```

This would be analogous to

``` javascript
let newObj = Object.assign({}, oldObj, { a: foo, b: bar })
```

This would presumably more efficient as well, since only one new object has to be created.

**Comment by pandanoir** [comment]
merge would work well, but this suggestion seems good for me!

**Comment by delenius** [comment]
Merge behaves differently e.g. when the values merged are lists. It converts list values into immutable List. That is more behavior than I want :)

**Comment by kmsheng** [comment]
+1, would be nice to have this feature

**Comment by bruno12mota** [comment]
This is specially useful on deep structures which often happen in a redux reducer for example. I find myself doing the following:

```js
return state.withMutations(map =>
   map.set('step', 1).setIn(['data', 'type'], action.schemaType)
);
```

Would be much better and clean to simply do:

```js
state.set('step', 1).setIn(['data', 'type'], action.schemaType)
```

Not a big deal though, and technically it might not be possible since each operation should be an immutable one.

**Comment by leebyron** [comment]
merge only converts structures if you pass a javascript object. For now, try:

```js
record.merge(Map({
  a: foo,
  b: foo
}))
```
