### ISSUE TITLE
Deep update syntax/API

### ISSUE THREAD

**Issue by delenius** [facebook/immutable-js#768]
Currently, AFAICT, there is no convenient way to do deep updates such as setting a value in a List which is part of a Record (am I wrong?). For example:

```javascript
var Foo = Immutable.Record({a: null});
var foo = new Foo({a: Immutable.List([42]));
foo = foo.set('a', foo.get('a').push(17));
```

This is awkward to say the least, and gets worse with deeper structures. Note that setIn() doesn't help here.

I would be great to have something like the [update()](https://facebook.github.io/react/docs/update.html) method in the react's immutability helpers.

**Comment by santiagoaguiar** [comment]
It's hard to tell from the docs, but `Record` has all the operations expected from a [`Map`](https://facebook.github.io/immutable-js/docs/#/Map) too, so you can write something like:

```
foo.updateIn('a', a => a.push(17))
```

or

```
foo.merge({ a: foo.a.push(17)})
```

Also, you don't need `.get('a')` for records, you can do `foo.a` directly.

**Comment by delenius** [comment]
@santiagoaguiar thanks, that's great! One thing I still can't find is a way to do a deep delete based on equality, in one step. I find myself doing a lot of this kind of thing:

```javascript
let index = map.getIn([a,b,c]).indexOf(val);
map.deleteIn([a,b,c,index]);
```

Is there a better way to do that?

**Comment by santiagoaguiar** [comment]
Agree, would love to have a delete on `List` by equality :). But, I think you only get it on `Set` collections.

Maybe is not your case, but I think one common pattern (on `redux` at least) is to avoid deleting the item and instead set a `deleted` flag, the main benefit being not having to remove the element id on every place where it has been added, and always filter by `deleted` instead. It feels right with the idea of flattening your state (which was why https://github.com/gaearon/normalizr was created).

**Comment by delenius** [comment]
I am indeed using Redux. Thanks for the suggestion.
