### ISSUE TITLE
OrderedMap positional index

### ISSUE THREAD

**Issue by pablolmiranda** [facebook/immutable-js#772]
Hi,

Any ideas how can I update an OrderedMap but changing the index but keeping the insertion position?
Something like a replace method:
```
var m = Immutable.OrderedMap({ a: 1, b: 2, c: 3});
m = m.replace('a', { d: 4});
// { d: 4, b: 2, c: 3 }
```

**Comment by leebyron** [comment]
Unfortunately this operation is not supported.

You could accomplish this with `mapEntries` though.
