### ISSUE TITLE
Seq documentation incorrect, don't understand how filter gets called only 3 times, and map only called twice

### ISSUE THREAD

**Issue by ericlau-solid** [facebook/immutable-js#773]
The seq documentation section listed below:

> For example, the following performs no work, because the resulting Seq's values are never iterated:
> 
> var oddSquares = Immutable.Seq.of(1,2,3,4,5,6,7,8)
>   .filter(x => x % 2).map(x => x * x);
> Once the Seq is used, it performs only the work necessary. In this example, no intermediate data structures are ever created, filter is only called three times, and map is only called twice:
> 
> console.log(evenSquares.get(1)); // 9

I think evenSquares here is incorrect should be OddSquares. Also, can someone explain how the seq's values are never iterated, yet filter is called 3 times, and may called twice?

**Comment by TheLevenCreations** [comment]
+1

its confusing

**Comment by jpikora** [comment]
@ericlau-solid it should be oddSquares indeed.

Chain is registering some kind of mutation to Seq values, but is only processed when the Seq is used (read). To get the resulting value on index 1, it only needs to calculate two values, thus filter will be called 3 times as the "2" value is omitted and map twice, as it will square just "1" and "3" provided by filter fn.

Haven't seen the internals, but i guess the chain is smartly preprocessed in reverse order so every fn knows how many values it needs to provide for the next one in queue.

**Comment by leebyron** [comment]
Fixed
