### ISSUE TITLE
Serialisation/Deserialisation for OrderedMap

### ISSUE THREAD

**Issue by TheLevenCreations** [facebook/immutable-js#776]
Hi,

This is really a great library, which is quite useful! Thank you for developing such cool immutable classes.

While these classes changed my programming life, I met some issues to do with Serialisation/Deserialisation. Would you please help? For example, I need to store TodoItems(stored in OrderedMap) into LocalStorage, and then read them out next time. 

1) If I use OrderedMap.toJS() to store it as strings using JSON.stringify() in LocalStorage, and read it out using JSON.parse and Immutable.fromJS(), the set order is missing.
2) While OrderedMap can store number as key and JS obj can not, how to serialise OrderedMap would be a problem. For example:

``` javascript
> omap1
OrderedMap { "1": 4, "a": 1, "b": 2, "c": 3 }
> omap1 = omap1.set(2, 5)
OrderedMap { "1": 4, "a": 1, "b": 2, "c": 3, 2: 5 }
> omap1 = omap1.set(1, 6)
OrderedMap { "1": 4, "a": 1, "b": 2, "c": 3, 2: 5, 1: 6 }
> omap1.toJS()
{ '1': 6, '2': 5, a: 1, b: 2, c: 3 }
```

As a result, { '1': 6, '2': 5, a: 1, b: 2, c: 3 } can not be deserialised into { "1": 4, "a": 1, "b": 2, "c": 3, 2: 5, 1: 6 }.

My current workaround(I think) is:
1) To serialise the OrderedMap manually( one by one and also serialise the set order) and deserialise it out manually( read one by one), which is really annoying. 
2) Use List instead...
3) Fork the whole library and implement the my own serialse()/deserialise() method in OrderedMap

Please let me know if I missed something or there is a better way to achieve it. Thanks very much.

BTW, I didn't try OrderedSet yet, probably I will meet the same issue when using OrderedSet? :-(

**Comment by umidbekkarimov** [comment]
Look at http://stackoverflow.com/a/5525820/1709679 

> An object is a member of the type Object. It is an unordered collection of properties each of which contains a primitive value, object, or function. A function stored in a property of an object is called a method.

So even if you will make Serialisation manually, in some browsers ordering still can be wrong

**Comment by TheLevenCreations** [comment]
hi @umidbekkarimov , thanks very much for your comments.

By reading the link you provided, I can see the ordering in "Object" is not guaranteed. I can understand this point and I am looking for another way to resolve this problem. By mentioning "make Serialisation manually", I mean, it can be implemented by a map and a list. You can see the source code of OrderedMap. That list is used for storing the orders(It can be just an Array) while the map stores the unordered key-value datas. The map and list can be serialized/deserialized by using JSON.stringify/parse.

**Comment by umidbekkarimov** [comment]
@TheLevenCreations ok, I get your point now, and as I think - the best solution is to convert `OrderedMap` to `List` and use arrays (keep it simple stupid) when you store data as json, and map it back to `OrderedMap` when you transform back without any serialisation/deserialisation routine that already given by `JSON` class
___
Also, just noticed in your post 

> As a result, { '1': 6, '2': 5, a: 1, b: 2, c: 3 } can not be deserialised into { "1": 4, "a": 1, "b": 2, "c": 3, 2: 5, 1: 6 }.

This is little tricky ~~bug~~ **feature** in `OrderedMap`/`Map` classes, that allows you to use any js type as a key, but when you use `#toJS()` method all keys will be converted to string.

Try in your console
```javascript
> var a = { "1": 4, "a": 1, "b": 2, "c": 3 }; a;
{ '1': 4, a: 1, b: 2, c: 3 }
> a[2] = 5; a;
{ '1': 4, '2': 5, a: 1, b: 2, c: 3 }
> a[1] = 6; a;
{ '1': 6, '2': 5, a: 1, b: 2, c: 3 }
```
So if you can not achieve this with native `Object`, you also can't achieve it with `#toJS()`
___

So immutable js classes give you great tools for managing your collections, but in the end when you have to store data in file/local storage/cookies or send it to server api and you have to deal with JSON Object that also unordered

http://stackoverflow.com/a/4920304/1709679

**Comment by TheLevenCreations** [comment]
hi @umidbekkarimov , thanks for the response and also provided links.

Yeah, I agree with your opinion. So each time I meet the situation "store data in file/local storage/cookies or send it to server api", I have to convert it to another data set, eg, List or Array or raw Object. That's not an easy work. For example, as you mentioned "This is little tricky bug feature in  OrderedMap / Map  classes, that allows you to use any js type as a key", should "1" be parsed to js number 1, or js string 1, or Regex? Probably needs to iterate every js raw types.

I think it would be great if
1) immutable js can provide such APIs, for example, serialize(). Or, just an utility function like fromJS(). 
2) document how to resolve such situation, to avoid improper use of toJS()/JSON.stringify for OrderedMap/OrderedSet.

**Comment by umidbekkarimov** [comment]
Hi @TheLevenCreations take a look at [transit-immutable-js](https://github.com/glenjamin/transit-immutable-js)

**Comment by leebyron** [comment]
Closing this issue

I second the recommendation for [transit-js](https://github.com/cognitect/transit-js) for serialization of custom data structures.
