### ISSUE TITLE
Constructor won't be called automatically for set() in Record's subclass

### ISSUE THREAD

**Issue by TheLevenCreations** [facebook/immutable-js#778]
Hi, 

I just found another issue, would you please help? Thanks.

Following the guide from http://facebook.github.io/immutable-js/docs/#/Record, I subclassed Record and created my own Record:

``` javascript
class ABRecord extends Record({a:1,b:2}) {
  constructor() {
   super();
 }
  getAB() {
    return this.a + this.b;
  }
}

```

While the doc reads "Record Classes can be extended as well, allowing for custom methods on your Record. ", I assume this is just like a normal class, so I did some operations and created some data in constructor:

``` javascript

class ABRecord extends Record({a:1,b:2}) {
  constructor() {
   super();
   // do some operation, for example, check network status
   this.networkstatus = operationfunc();
 }
  getAB() {
    return this.a + this.b;
  }
}
```

The problem is that, after I used set(), the networkstatus is undefined in returned instance:

``` javascript
var myRecord = new ABRecord(b:3);
var newRecord = myRecord.set('a',100);
newRecord.networkstatus  -----> undefined
```

After investigation, the following code is the cause in Record.js:

``` javascript
function makeRecord(likeRecord, map, ownerID) {
  var record = Object.create(Object.getPrototypeOf(likeRecord));
  record._map = map;
  record.__ownerID = ownerID;
  return record;
}
```

So it used Object.create() to create a new instance, while the constructor is not called.

I assume it is worked as designed, however, I think it would be better, at least, to document this behaviour in the doc. This way, user can know what needs to be done and what not in constructor. Thanks.

**Comment by leebyron** [comment]
Unfortunately this is a limitation of Record. Any instance variables like this need to be defined on the Record itself, for example:

```
class ABRecord extends Record({a:1,b:2, networkstatus:null}) {}
```

Calling a function to compute those values is not safe since new Records are "constructed" again every time `set()` is called to preserve immutability.
