### ISSUE TITLE
Error in the Record docs

### ISSUE THREAD

**Issue by AndrewBestbier** [facebook/immutable-js#780]
Error found at: https://facebook.github.io/immutable-js/docs/#/Record

![recorderror](https://cloud.githubusercontent.com/assets/6062416/12816350/a705a308-cb54-11e5-8dd0-1a7bbeec2476.png)

Should be:
```
var myRecord = new ABRecord({b:3})
```

**Comment by jakeboone02** [comment]
This is a duplicate of #565.

**Comment by AndrewBestbier** [comment]
That issue was closed on Ju 28 2015 and supposedly fixed. I made a new issue as it was not

**Comment by jakeboone02** [comment]
Where are you seeing the error?  I just checked the "Error found at:" link and it appears correct.

**Comment by AndrewBestbier** [comment]
Ah sorry @jakeboone02. Must have been fixed since I took that screenshot
