### ISSUE TITLE
toJS reveles a data-structure that was not flattened

### ISSUE THREAD

**Issue by jcalfee** [facebook/immutable-js#782]
```js
> var f =Immutable.List([[[2,[3,{a:[45]}]]]]).flatten()
> f
List [ 2,3,[object Object] ]
> f.toJS()
[ [ [ 2, [Object] ] ] ]
```
3.7.6

**Comment by ntgn81** [comment]
@jcalfee , `Immutable.List` does not convert nested objects into `Iterable`s, and `Immutable.List#flatten` would not flatten the nested arrays in this case because they are not `Iterable`

It would work as you expected if you used Immutable.fromJS instead of Immutable.List

```js
var f =Immutable.List([[[2,[3,{a:[45]}]]]]);
Immutable.Iterable.isIterable(f.get('0')); // false

var f1 =Immutable.fromJS([[[2,[3,{a:[45]}]]]]);
Immutable.Iterable.isIterable(f1.get('0')); // true
f1.flatten().toJS(); // [2, 3, 45]
```

**Comment by leebyron** [comment]
Thanks for answering!

In the future, ask questions on stackoverflow.com/questions/tagged/immutable.js?sort=votes for searchability.
