### ISSUE TITLE
Typescript compiler is blocking when importing Map 

### ISSUE THREAD

**Issue by klimentLambevski** [facebook/immutable-js#785]
I use immutable.js in angular2 app. When i import `Map` in my file, typescript compiler is blocking and i have to restart it. This error happens when i add `/// <reference path="../../node_modules/immutable/dist/immutable.d.ts" />` in `tsd.d.ts` file. Without this reference typescript compiler doesn't block but i get warning errors for every function or class that i'm importing from immutable.js

**Comment by leebyron** [comment]
Hopefully this has been fixed by the recent improvements to typescript and the definitions file. Feel free to report again if this is still an issue.
