### ISSUE TITLE
merging a list within a map using a user-defined function

### ISSUE THREAD

**Issue by mattkrick** [facebook/immutable-js#790]
If i want to do something wacky when i merge a map, I use `mergeDeepWith`. But when I encounter a List within those Maps, I want to do something else that requires both of those Lists (eg prepend the second to the first). Only thing that comes to mind is running a forEach & basically writing my own merger. Is there a cleaner way?

**Comment by leebyron** [comment]
Yeah, currently you're doing it the best way. `merge*With` takes a custom merger which will let you do smarter things when it encounters something that is `List.isList()`

**Comment by kristojorg** [comment]
@leebyron It is my understanding the custom merger is only called when previous and next conflict. Is this not true? If not, what is the default implementation? Thanks!

**Comment by leebyron** [comment]
That's correct. The merger function is only called when both previous and next both exist. The default implementation is (prev, next) => next
