### ISSUE TITLE
Feature request: Multimaps

### ISSUE THREAD

**Issue by JayAndCatchFire** [facebook/immutable-js#792]
Multimaps can be created and used via wrapping code around a Map of Lists, but it would be nice if this could become a native type so we could get convenience functions for deep persistent changes and such.

https://en.wikipedia.org/wiki/Multimap

**Comment by leebyron** [comment]
Could you provide some common uses of Multimap and some of the methods you would expect on it?

**Comment by leebyron** [comment]
Closing this aging issue

**Comment by adit-hotstar** [comment]
A common use of a multimap data structure would be grouping of elements in a list by a certain property. For example, grouping people by last name. Given a list of people, we create a multimap where the keys are the last names and the values are the lists of people with that last name.
