### ISSUE TITLE
flatMap throws an error on a List that has a scalar element

### ISSUE THREAD

**Issue by vanchagreen** [facebook/immutable-js#796]
```javascript
var list = Immutable.fromJS([1, [2, 3]]);
list.flatMap(s => s);
```

The above code throws an `Uncaught TypeError: Expected Array or iterable object of values error`

Contrast this with:

```javascript
var list = Immutable.fromJS([1, [2, 3]]);
list.map(s => s).flatten(true)
```

Which returns `[1, 2, 3]`.

Alternately if you create `list` with `Immutable.List` as opposed to `Immutable.fromJS` the second snippet will return a new list with the same data as the original.

Is this intended behaviour? In Ruby and Clojure, flatMap works on a list that as a scalar in it. 

```ruby
list = [[1, [2, 3]]
list.flat_map {|s| s}
```

Returns `[1, 2, 3]`

**Comment by leebyron** [comment]
This is intended behavior. `flatMap` expects to get back an iterable per item (like an Array or Immutable.List). It is intentionally more strict than `list.map(fn).flatten(true)`

**Comment by vanchagreen** [comment]
Fair enough! The only thing I'd say then is that the docs say that flatMap is `Similar to iter.map(...).flatten(true)`. Which is true, but maybe there should be another sentence or two explaining why they're not exactly the same. Just my two cents. Thanks!
