### ISSUE TITLE
infinite loop hashing Infinity 

### ISSUE THREAD

**Issue by colbyr** [facebook/immutable-js#797]
It seems that causing Immutable to hash `Infinity` triggers an infinite loop (makes sense I suppose :smirk:).

I can reproduce in Chrome and Firefox from the console on [the doc site](http://facebook.github.io/immutable-js/).

```javascript
m = Immutable.Map({test: Infinity});
m.hasCode() // spins forever
```

I haven't really dug into the hasher. If it's not possible to hash infinity, I'd at least expect to see an exception.

cc @marcneuwirth

**Comment by samwgoldman** [comment]
Haha, nice one. If hashing `Infinity` takes forever, does hashing `-Infinity`... reverse time? Let's not even try it just to be safe ;)

**Comment by leebyron** [comment]
Good find.

**Comment by colbyr** [comment]
thanks @leebyron 👍
