### ISSUE TITLE
Documentation for a lot of methods disappeared

### ISSUE THREAD

**Issue by zerkms** [facebook/immutable-js#798]
https://facebook.github.io/immutable-js/docs/#/List --- this lacks heaps of methods of the `List` class, eg: `List.sort`

**Comment by gf3** [comment]
yeah looks like the docs are not longer showing inherited methods. this is not a fun change :(

**Comment by dshorowitz** [comment]
+1

**Comment by jshthornton** [comment]
You can still find them in the Collection section. But yes, I agree, makes it a pain to try and find for specific methods.

**Comment by tshinnic** [comment]
Or the Iterable section, which is the obvious place to describe specialized APIs like `.get()` ...
I guess I'm glad to see this issue, because y'all make it sound like it used to be better... and could be again?

**Comment by vlinder** [comment]
+1

**Comment by GrantMStevens** [comment]
+1 this is a step backwards for docs

**Comment by steida** [comment]
I think it's much more concise now. I really like it. Maybe some link to inherited methods could be useful.

**Comment by dshorowitz** [comment]
How about a simple toggle so you can choose whether to view inherited
methods or not?

**Comment by vlinder** [comment]
Are we ever getting back the documentation?

**Comment by leebyron** [comment]
Fixed!
