### ISSUE TITLE
What causes Map to choose BitmapIndexedNode over ArrayMapNode?

### ISSUE THREAD

**Issue by jshthornton** [facebook/immutable-js#799]
I am working with a pretty easy structure

```
[{
    "id": 1,
    "name": "Example",
    "parent_id": null,
    "order": 0,
    "is_open": false,
    "is_directory": true,
    "meta": {
        "revision": 0,
        "created": 1456997356672,
        "version": 0
    },
    "$loki": 1,
    "children": []
}, {
    "id": 5,
    "name": "Double dip",
    "parent_id": null,
    "order": 0,
    "is_open": false,
    "is_directory": true,
    "meta": {
        "revision": 0,
        "created": 1456997356672,
        "version": 0
    },
    "$loki": 5,
    "children": []
}]
```

However what I get back from `Immutable.fromJS(...)` is a List with two BitmapIndexedNode

**Comment by jshthornton** [comment]
I haven't found the direct cause, but the structure appears not to matter. It's when you have more than 8 items.
```
{
  one: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8
}
=> ArrayMapNode
```

```
{
  one: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9
}
=> BitmapIndexedNode
```

**Comment by leebyron** [comment]
It is 8 entries. This is a performance optimization where the each of these implementations have different performance characteristics for getting and setting, and ~8 entries is where BitmapIndexedNode begins to outperform ArrayMapNode.

**Comment by jackson-sandland** [comment]
Thanks @leebyron

**Comment by Haro10** [comment]
So how can I take data from BitmapIndexedNode in case of the mix ValueNode and BitmapIndexedNode like the picture below.

for ValueNode I just get data by the get function like 'fileUpload.get('createdAt')', but what about the BitmapIndexedNode

![2019-02-19 19 34 09](https://user-images.githubusercontent.com/13564710/53008839-96f97d00-347d-11e9-8bdf-609483ed8131.png)
