### ISSUE TITLE
Type Standards

### ISSUE THREAD

**Issue by ccorcos** [facebook/immutable-js#802]
I'm curious if this project is referencing any standards outside the JS standards for things like Maps and Lists. I want to improve Ramda.js to work well with Immutable, but I want to make sure I'm doing things right -- is there some central agreed-upon spec for things like List.slice or Map.get?

**Comment by leebyron** [comment]
This library references the method prototypes of `Array`, `Map`, and `Set` from ES6 whenever possible, and only diverges when it must or when divergence is relevant to the library.

For example `Map.get` and `Map.set` work identically to ES6 Map.

**Comment by ccorcos** [comment]
Ok. Very pragmatic. Thanks!
