### ISSUE TITLE
Feature request: Limit maximum size of Collection (e.g. LRUMap/LRUList)

### ISSUE THREAD

**Issue by umidbekkarimov** [facebook/immutable-js#806]
I use List/Map collections in my Redux store, and have problem with maintaining map sizes (i need last 5-6 records only)

First attempt to resolve this problem was to create helper function:

```javascript
static sliceMap(map, maxSize = 5) {
    if (!ImmutableUtils.isImmutable(map)) {
        return map;
    }

    if (map.size <= maxSize) {
        return map;
    }

    return map.slice(map.size - maxSize);
}
```

And use it like 

```javascript
let newMap = ImmutableUtils.sliceMap(oldMap);
```
But It's not good solution for me, as i have to call this method every time when i need to mutate map
____
Second attempt was to create new class and extend it with map, override `set`/`setIn`, but super methods will always return new map instance, so it was just pointless
____
So the only solution that is see to create new collections like: `LRUMap`, `LRUList` and else inspired by https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/map/LRUMap.html
___

**EDIT**

Found final solution for my problem

```javascript

let data = Immutable.OrderedMap(); data.toString();

// "OrderedMap {}" - we need OrderedMap (for ... you know ... ordering)
data = data.set(1, 1).set(2, 2).set(3, 3).set(4, 4).set(5, 5).set(6, 6).takeLast(5); data.toString();
// "OrderedMap { 2: 2, 3: 3, 4: 4, 5: 5, 6: 6 }" - look good enough
data = data.set(2, 3).takeLast(5); data.toString();
// "OrderedMap { 2: 3, 3: 3, 4: 4, 5: 5, 6: 6 }" - here we got problem, key '2' took it's previous position
data = data.delete(2).set(2, 3).takeLast(5); data.toString();
// "OrderedMap { 3: 3, 4: 4, 5: 5, 6: 6, 2: 3 }" - that's better
data = data.delete(3).set(3, 4).takeLast(5); data.toString();
// "OrderedMap { 4: 4, 5: 5, 6: 6, 2: 3, 3: 4 }" - yep
data = data.delete(7).set(7, 7).takeLast(5); data.toString();
// "OrderedMap { 5: 5, 6: 6, 2: 3, 3: 4, 7: 7 }" - finally

// working example

static handleFetchSuccess(state, {response, id}) {
        return state
            .update('dataLoading', item => item.delete(id))
            .update('data', item => item.delete(id).set(id, fromJS(response)).takeLast(10));
}
```

**Comment by leebyron** [comment]
These are very different data-structures. I'm unlikely to build them anytime soon, but if someone is interested in contributing, the first step is to consult existing research in persistently immutable cache mechanisms to determine next steps.

Closing this issue though, as it's not something that's on the near-term roadmap.

**Comment by umidbekkarimov** [comment]
@leebyron Thanks for your response,

I really interested in this feature and after some researches of `immutable-js` code I came to some assumption:

```javascript
import {LRUList, LRUMap} from 'immutable'

const ShortList = LRUList(5, 'ShortList'); // pass `maxSize` and className
const list = new ShortList([1,2,3,4,5,6]);

list.toString(); // "ShortList [ 2, 3, 4, 5, 6 ]"

const ShortMap = new LRUMap(5, 'ShortMap');
const map = new ShortMap({1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f'});
map.toString(); // "ShortMap { "2": "b", "3": "c", "4": "d", "5": "e", "6": "f" }"
```

So under the hood:

`LRUMap`
As a `Record` will keep all data in `_map` (that should be `OrderedMap`)

Override:
* `set`
* `update`
* `update`
* `update`
* `update`
* `update`
* `update`

* Override `set`, `update`, `merge`, `mergeWith`, `mergeDeep`, `mergeDeepWith`, `setIn`, `` methods 

(like `this._map.delete(k).set(k, v).takeLast(maxSize)`

`LRUList` 
* Will keep all data in `_list`
* Override `set`, `insert`, `push`, `unshift`, `update`

**Comment by leebyron** [comment]
This should behave correctly, but may not be an efficient implementation.  LRUMaps which seek to be performant and persistent usually use some kind of structure that's easier to clean up like a btree or minheap

**Comment by umidbekkarimov** [comment]
It has been a long time since then, i've tried max heap, btree, and Java TreeMap, and found it useless for current task - because of runtime normalization. 

Everything that I need is limited size, and strict ordering. So I dropped the idea of new implementation and keep using `OrderedMap` + `takeLast`.

But it was a previous story.

____

Recently I start working on custom caching collections and implemented custom `LinkedMap` with es6 `Map` inside of it. And after some time I found that I need to store Immutable collections for keys and I remembered current issue. 

Basically this `LinkedMap` works like `OrderedMap` with three differences:
1. It has limited size. 👍
2. It **always** adds value to the end, even if it's already in map. 👍
3. It's not immutable. 👎

So I guess it will be more efficient than using `OrderedMap` (with `Map` and `List` inside of it).
___
And finally -- **Proposal**.

Add new `LinkedMap` collection with:
* `Map` interface.
* **Strict** ordering.
* `setFirst` and `setLast` methods.
* `set` will behave as `setLast`.
* Custom Class Builder (like `Record` constructor) to allow:
   * Limited Size

For example:
```
import { LinkedMap, LinkedMapBuilder } from 'immutable';

const lm = new LinkedMap().set(1, 0).set(2, 0).set(1, 0); // LinkedMap { 2: 0, 1: 0 }

const CustomLinkedMap = LinkedMapBuilder({ maxSize: 2 }, 'CustomLinkedMap');
const clm = CustomLinkedMap().set(1, 0).set(2, 0).set(1, 0).set(3, 0); // LinkedMap { 1: 0, 3: 0 }
