### ISSUE TITLE
Question about documentation generator for this lib

### ISSUE THREAD

**Issue by ORESoftware** [facebook/immutable-js#812]
I saw at the bottom of your docs

> Documentation
> 
> Read the docs and eat your vegetables.
> 
> **Docs are automatically generated from Immutable.d.ts. Please contribute!**
> 
> Also, don't miss the Wiki which contains articles on specific topics. Can't find something? Open an issue.
> 

So do you (Facebook) use YUIDoc, Docco, JSDoc or https://github.com/documentationjs/documentation ?

Please let me know! I would love to use something similar.

**Comment by ORESoftware** [comment]
Looks like this file gives me some clues:
https://github.com/facebook/immutable-js/blob/master/gulpfile.js

but if you could give me a definitive answer that would be really nice.

**Comment by leebyron** [comment]
It is a custom built solution. The code for which is all found in https://github.com/facebook/immutable-js/tree/master/pages

**Comment by ffxsam** [comment]
I understand the convenience for auto-generated docs, but:

```
findKey(
  predicate: (
    value?: T,
    key?: number,
    iter?: Iterable.Keyed<number, T>
  ) => boolean,
  context?: any
): number
```

This is totally illegible to me, and is kind of a bummer when I'm trying to learn Immutable.

**Comment by leebyron** [comment]
Yep, the docs aren't perfect and what they could really use are example uses

**Comment by ffxsam** [comment]
What's the best way to contribute examples? (and where should they go?) It might be cool to have a "cookbook" section that has some basic common usages, like using with Redux.

**Comment by leebyron** [comment]
The docs are autogenerated from the typescript definitions file in /type-definitions, the doc block above each message turns into the description. It's just commented markdown, so it should be easy to embed example use cases right there

**Comment by leebyron** [comment]
A cookbook would also be cool! Perhaps that's worth its own section on the website (all assembled in this repo in /pages)

**Comment by thomastuts** [comment]
Related: you can use the `gulp dev` task to fire up a local server that serves the docs. Check out https://github.com/facebook/immutable-js/pull/844 for LiveReload functionality when changing the type definitions found in `/type-definitions/`.

**Comment by ffxsam** [comment]
@leebyron I've started to put something together. Please feel free to correct/optimize any of these!

https://gist.github.com/ffxsam/6c9c4fca019eac0dec045ef303affa3c

**Comment by ffxsam** [comment]
Hopefully I'm not being too presumptuous here, but..

Since Immutable is under the umbrella of Facebook, and the devs working on these projects are employees of (and hence paid by) FB.. is it possible someone could be tasked with writing up new documentation? Three times now I've almost given up on using Immutable because it's *so* frustrating to grasp the docs. I'm not alone in this sentiment:

http://stackoverflow.com/questions/29589753/how-to-update-element-inside-list-with-immutablejs#comment47343879_29589753

**Comment by seethroughtrees** [comment]
I have been using this library in all projects over the last year, and almost every time I reach for the docs, I think the same thing.  This documentation has to be a serious barrier to entry for (at least) new users.

Having complete docs with a similar structure to lodash/ramda etc... would be extremely useful.
And would encourage lots more people to use the library in their projects. 

Title -> Type Definition (non-TS) -> Description -> Example
 
The library is innovative on its own, the docs don't need to be, IMO.

**Comment by stkrzysiak** [comment]
I feel the original concern raised by @ffxsam  wasn't addressed completely, it was focused on that confusing syntax and what it means.  Honestly, I think the docs would greatly benefit from adding examples, but also from removing this kind of stuff:

> sort(comparator?: (valueA: T, valueB: T) => number): Iterable<number, T>

If it stays, the first section of the docs should be an intro to this notation, why it's used, and how to use it, as requested in #298

**Comment by soundyogi** [comment]
Tbh. 
Learning Typescript does not take that long. Type Definitions are a great way to learn any API Surface.
They made my life much better. Also there are a _lot_ of comments in the Immutable one:
https://github.com/facebook/immutable-js/blob/master/type-definitions/Immutable.d.ts

What I agree with is that there should be more examples.
