### ISSUE TITLE
Don't rely on .equals()

### ISSUE THREAD

**Issue by georeith** [facebook/immutable-js#814]
I have come across an Issue where a library I am using implements `.equals()` on its objects. These are internally crucial to the functioning of the library, however they should not be used by ImmutableJS, just because two items are what the library considers equal doesn't mean I want them to be considered the same by ImmutableJS.

I want these to only be equal if they reference the same object. Is there any way currently to do that? If not this should really be optional as a lot of people using external modules do not have full control over the object prototypes and `.equals()` is going to be fairly prevalent that I imagine a fair few libraries will have side effects with ImmutableJS.

**Comment by uniphil** [comment]
As a counterpoint, I implemented `.equals()` (and friends) in [`results`](https://github.com/uniphil/results) specifically for compatibility with Immutable. It's nice to be able to do that without introducing a dependency on Immutable, but I suppose it could do bad things if you didn't expect it.

**Comment by arcanis** [comment]
It could use a shared symbol rather than a fixed string.

**Comment by leebyron** [comment]
Unfortunately many rely on this behavior today.

In a future version we can consider requiring a shared symbol instead.

**Comment by georeith** [comment]
@leebyron I don't see why it couldn't be optionally disabled. A setting on Immutable, or the ability to specify your own function name for this.

This doesn't have to be a breaking change. But as it stands it makes ImmutableJS unusable with certain other libraries.

**Comment by elliotbonneville** [comment]
Any updates on this? @georeith's solution seems reasonable.
