### ISSUE TITLE
findIndex not documented?

### ISSUE THREAD

**Issue by jrochkind** [facebook/immutable-js#817]
I had a List, and needed to see if the List contained a certain immutable object, and if so what the index was. 

StackOverflow led me to the `findIndex` method, which works great. 

It seems to not be included in the docs at all though. It's not mentioned on [List](https://facebook.github.io/immutable-js/docs/#/List) or [Iterable](https://facebook.github.io/immutable-js/docs/#/Iterable). 

Am I missing something? Is there a reason it's not doc'd?

**Comment by steida** [comment]
http://stackoverflow.com/a/29655323/233902

**Comment by jrochkind** [comment]
Right, it's mentioned in a StackOverflow answer. I would expect it to be listed in the generated method API docs, no?

**Comment by steida** [comment]
Yes, me too.

**Comment by leebyron** [comment]
Fixed!

**Comment by jrochkind** [comment]
thanks!
