### ISSUE TITLE
Implement Specter-like functionality for querying and transforming data structures

### ISSUE THREAD

**Issue by dahjelle** [facebook/immutable-js#819]
I recently ran across the Clojure(Script) library [Specter](https://github.com/nathanmarz/specter) which adds querying and transforming functionality to Clojure's immutable data structures. For instance, a simple example from their docs:

```
(transform [ALL :a even?]
              inc
              [{:a 1} {:a 2} {:a 4} {:a 3}])
[{:a 1} {:a 3} {:a 5} {:a 3}]
```
There appears to be a lot of other functionality there, too, especially for querying and transforming nested data structures.

Obviously one can do this with the current version of Immutable.js, and I'm not sure if this is better included or as an add-on, but I found it very, very interesting and thought I would mention it here.

**Comment by leebyron** [comment]
This sounds like a great opportunity for a companion library for someone to build! However it probably doesn't belong in this core library.
