### ISSUE TITLE
Typescript Stubs

### ISSUE THREAD

**Issue by tusharmath** [facebook/immutable-js#820]
[0]: http://definitelytyped.org/guides.html
Can we get immutablejs integrated with [Typescript community stubs][0]? I would really help with the intellisense and autocompletion features?

**Comment by myitcv** [comment]
@tusharmath - there is no need for a type definition (that's what's DefinitelyTyped is about, type definitions) to be hosted on DefinitelyTyped for intellisense or auto-completion to work. The type definition simply needs to be referenced in some way, directly or indirectly, by `tsconfig.json` (or similar) and intellisense/auto-completion (assuming you're using some sort of 'standard' TypeScript setup) will simply work.

In some ways your request is related to #779, but this isn't a blocker - you can make it work, albeit somewhat manually for now.

**Comment by leebyron** [comment]
Thanks for answering!
