### ISSUE TITLE
`Repeat` behavior [question]

### ISSUE THREAD

**Issue by nicolasbrugneaux** [facebook/immutable-js#824]
Just a small question about `Repeat`. I'm just wondering if this thought makes any sense.

```js
const _list = Repeat(0);
const zeroArray = n => _list.take(n);

console.log(zeroArray(10) === zeroArray(10));
```

Currently the last statement logs `false`, but naively I thought it'd be `true`, am I missing something there?

**Comment by leebyron** [comment]
A `Repeat` is an object. So this is false for the same reason that this will log `false`.

```js
console.log({ k: "v" } === { k: "v" })
```

However you can write `zeroArray(10).equals(zeroArray(10))` or `Immutable.is(zeroArray(10), zeroArray(10))` to get `true` by using *value equality*.

In the future, ask on http://stackoverflow.com/questions/tagged/immutable.js?sort=votes!
