### ISSUE TITLE
Map::deleteAll for removing multiple keys from a map

### ISSUE THREAD

**Issue by xixixao** [facebook/immutable-js#825]
Could we add this to the library? What is the policy around these helpers combining multiple collections?

``` javascript
const base = Immutable.Map({x: 1, y: 2, z: 3});
const shrinked = base.deleteAll(['x', 'z']); // or `subtract`?
// => shrinked == Immutable.Map({y: 2});
```

(Java collections usually have these)

**Comment by levidobson** [comment]
deleteAllIn could also be useful.

**Comment by rawpixel-vincent** [comment]
For those who find this, it's how I did it

```javascript
const base = Immutable.Map({x: 1, y: 2, z: 3});

let myNewBase = base;
['y', 'z'].forEach((idToDelete) => { myNewBase = myNewBase.delete(idToDelete); });

```

**Comment by umidbekkarimov** [comment]
I guess this https://github.com/facebook/immutable-js/commit/ba535442737d4045cbd412cae3350b4413f9ee9b should be close this issue.
