### ISSUE TITLE
How to Read Deep Values

### ISSUE THREAD

**Issue by Kay2dan** [facebook/immutable-js#826]
Apologies for the newbie question, however, Im struggling with this:

My state is like this:
```
import { List as list,
	     Map as map } from "immutable";

const initialTabState = list.of(
	map({
		tabClass : "tabPreview tab activeTab",
		tabName : "Preview"
	}),
	map({
		tabClass : "tabBody tab",
		tabName : "Body"
	}),
	map({
		tabClass : "tabSleeve tab",
		tabName : "Sleeve"
	})
);
```

In my reducer function, I get 'typeError' when I do this:
`console.log( "Initial State is...", initialTabState.isList() );`

And how do I 'read' the value of third Map obj nested within the 'initialTabState' if I was to read it in console?

Thanks for the help

**Comment by NgoKnows** [comment]
If you want to read the third value you can do `initialTabState.get(2)`, and if you want to read a nested value you can do `initialTabState.getIn([2, 'tabName'])`, passing it an array, and same works for setting values.

**Comment by leebyron** [comment]
Thanks for answering!

In the future, answer on http://stackoverflow.com/questions/tagged/immutable.js?sort=votes
