### ISSUE TITLE
How to access Map value?

### ISSUE THREAD

**Issue by wizardnet972** [facebook/immutable-js#831]
Hi,

I have interface like this:

```
export interface IApplicationState {
  visibility: string;
  context: IContext;
}
```
In my service I have public var:
`public state: Map<String, IApplicationState>;`

how can i read this object?
console.log('res: ', this.state<IApplicationState>.visibility); 

any ideas?

**Comment by thomastuts** [comment]
You read values from a `Map` by using the `.get()` method and passing in a key. In your case, this would be `this.state.get('visibility');`, I think.

For example:

import {Map, List} from 'immutable';

const cat = Map({
  name: 'Pliskin',
  appearance: Map({
    type: 'tabby',
    color: 'black'
  }),
});

console.log(cat.name); // undefined!
console.log(cat.get('name')); // 'Pliskin'

See https://facebook.github.io/immutable-js/docs/#/Iterable/get for more information.

**Comment by leebyron** [comment]
Great answer @thomastuts 

In the future, ask questions on http://stackoverflow.com/questions/tagged/immutable.js?sort=votes
