### ISSUE TITLE
Documentation doesn't show inherited functions

### ISSUE THREAD

**Issue by jv-PintoBobcat** [facebook/immutable-js#835]
The immutable-js docs were recently updated.  One of the changes causes inherited methods to be omitted.  For example, although `Map` extends `Collection.Keyed`, none of the methods from the `Collection` classes appear on `Map`'s doc page.

Perhaps inherited methods can still be shown, but in a different color or tagged?  I miss being able to see them.

**Comment by leebyron** [comment]
Fixed!
