### ISSUE TITLE
Hidden divs blocking links on Immutable website

### ISSUE THREAD

**Issue by ffxsam** [facebook/immutable-js#843]
There's a div with class `coverFixed` that hangs around, and blocks half the page (making links not clickable). See below.

![screen_shot_2016-04-17_at_12_04_41_pm](https://cloud.githubusercontent.com/assets/12532733/14589358/be2c06a2-0494-11e6-9d8a-e77d83f79022.png)

**Comment by leebyron** [comment]
Ah, yikes! thanks for the report, I'll look into a fix.
