### ISSUE TITLE
website: logo doesn't overflow in Firefox

### ISSUE THREAD

**Issue by tomByrer** [facebook/immutable-js#847]
Hero looks as intended in Chrome, not Fx:
![fb-immutable-firefox](https://cloud.githubusercontent.com/assets/1308419/14614871/566d9518-0560-11e6-9d97-1e0295aabd10.jpg)

**Comment by leebyron** [comment]
I can't reproduce this in my Firefox browser - can you share more details about OS/Browser versions?

**Comment by leebyron** [comment]
Closing this aging issue - feel free to reopen if still having troubles
