### ISSUE TITLE
Expected Map comparison behavior?

### ISSUE THREAD

**Issue by sbai** [facebook/immutable-js#851]
What's the expected behavior when comparing two unordered `Map` objects using `<`, `>`, etc.? Is there a defined way it should behave? I noticed an instance of the result being different when using version `3.8.0` vs `3.8.1`.

**Comment by leebyron** [comment]
Javascript `>` and `<` operators attempt to coerce values into primitives before comparing - so doing that with a collection like `Map` is surely going to get weird unexpected results.
