### ISSUE TITLE
Default import from `immutable`. This module has no default export.

### ISSUE THREAD

**Issue by Anahkiasen** [facebook/immutable-js#854]
### What happened

I was using Flow with Immutable without problem but since definitions were added I'm getting this error everywhere:

```
src/Services/SchemaConverter.js:2
  2: import Immutable from 'immutable';
            ^^^^^^^^^ Default import from `immutable`. This module has no default export.
```
### How to reproduce

Simply import Immutable and enable Flow on the file

**Comment by jedwards1211** [comment]
I just remembered, I think they wrote the type defs this way because Flow unfortunately doesn't allow a class to be a static property of another class right now.  There are some notes in [immutable.js.flow](https://github.com/facebook/immutable-js/blob/master/type-definitions/immutable.js.flow) that will hopefully wind up in the docs soon.

**Comment by jedwards1211** [comment]
Is there any simple workaround for dealing with the large number of Flow errors about this in preexisting code?  If not, I really don't think the flow defs should be included in the official release until they don't break (cause invalid Flow errors) on preexisting code that has followed the long standing import conventions in the docs.

**Comment by gf3** [comment]
as annoying as this might be for those using the default export, please don't remove the flow type annotations—they're incredibly valuable. i've already been able to fix a couple edge-case bugs in my app because of them!

**Comment by jedwards1211** [comment]
Yes, but the annotations could easily be moved to a well-publicized branch until they're a bit more mature, so that people can `npm install facebook/immutable-js#flowtype` for example

**Comment by ccorcos** [comment]
I created a PR for this fix: https://github.com/facebook/immutable-js/pull/961

**Comment by leebyron** [comment]
Fixed in master will be release soon
