### ISSUE TITLE
Documentation still missing for Map.mapEntries()

### ISSUE THREAD

**Issue by dubrowgn** [facebook/immutable-js#857]
### What happened

There is no documentation for `Map.mapEntries()` on https://facebook.github.io/immutable-js/docs/#/Map
### How to reproduce

1) Go to https://facebook.github.io/immutable-js/docs/#/Map
2) Ctrl+F for 'mape'
3) Notice, no matches found

**Comment by leebyron** [comment]
Fixed now!
