### ISSUE TITLE
Documentation still incomplete for map()

### ISSUE THREAD

**Issue by dubrowgn** [facebook/immutable-js#858]
### What happened

The documentation does not mention the difference between `Iterable.Indexed.map()` and `Iterable.Keyed.map()`, or even that there is a difference (see also #697).

The missing information is the mapper function passed to `Iterable.Indexed.map()` can return arrays of the form `[key, value]`, while `Iterable.Keyed.map()` cannot. In order to accomplish the same result, one must use `Iterable.Keyed.mapEntries()` instead, which is currently not documented at all (see #857).
### How to reproduce

1) go to https://facebook.github.io/immutable-js/docs/#/Iterable/map
2) note the lack of documentation regarding key functionalities mentioned above

**Comment by leebyron** [comment]
The docs have been updated recently with more examples, hopefully that clears up how to use `.map()`

> The missing information is the mapper function passed to Iterable.Indexed.map() can return arrays of the form [key, value], while Iterable.Keyed.map() cannot.

This isn't correct - there is no significant difference on how `map()` works between Indexed and Keyed collections - both operate on values.
