### ISSUE TITLE
Import with system.js throws error: Derived constructor must call super()

### ISSUE THREAD

**Issue by wshager** [facebook/immutable-js#862]
I've configured system.js to run in the browser with bower-traceur, but I can't seem to import from src. Perhaps this could be solved by calling super() in extended classes, but I didn't get through all of them yet.

**Comment by wshager** [comment]
I understand this is due to the factory style but IMO it shouldn't interfere with ES6 modules. Perhaps using something like dojo/compose would be an option.

**Comment by leebyron** [comment]
`src/` is pre-compiled source and because this source was originally written in early 2014, it's not perfect ES6 code - unfortunately at present you have to rely on dist/
