### ISSUE TITLE
findLastEntry no longer returns reverse index in 3.8.1

### ISSUE THREAD

**Issue by BigDataSamuli** [facebook/immutable-js#864]
3.8.0:

``` javascript
Immutable.Seq([1, 2, 3, 4]).findLastEntry(i => true)
=> [ 0, 4 ]
```

3.8.1:

``` javascript
Immutable.Seq([1, 2, 3, 4]).findLastEntry(i => true)
=> [ 3, 4 ]
```

Seems to be caused by using toKeyedSeq instead of toSeq [here](https://github.com/facebook/immutable-js/commit/5eaf97f93bbb300d91d8ac77dd68355b034f4d3c#diff-11243f5857d9d9e7c1a844a8580fe4b6R4512).

**Comment by leebyron** [comment]
That's correct - the previous behavior was a bug. Clearly the value at index `0` is `1` and not `4` in your example, so the entry `[0, 4]` does not actually exist in the sequence, however the entry `[3, 4]` does. That bug was fixed in 3.8.1
