### ISSUE TITLE
add comparators for Seq

### ISSUE THREAD

**Issue by wshager** [facebook/immutable-js#867]
Feature request: add general purpose comparator for (flat) sets, in addition to equals(). The goal is to compare 2 sets (Seqs) for greater-than, less-than, greater-than-equals, less-than-equals, and combine tests with or / and.

**Comment by leebyron** [comment]
I'm not sure a Seq can be meaningfully compared in a numeric greater/less-than way.

**Comment by wshager** [comment]
@leebyron I don't mean strictly numerical comparison, more like an intersection / distinction on values in a Seq, based on generic comparisons. The algorithm can be a written as a reduction over Seqs, so I figure it belongs in userland anyway. Also, it would make more sense on Sets I suppose.

**Comment by leebyron** [comment]
That definitely sounds like a useful userland code, or perhaps a supporting library!
