### ISSUE TITLE
Array functions always return an Iterable in TypeScript definition

### ISSUE THREAD

**Issue by Strato** [facebook/immutable-js#871]
According to the doc, array functions like map() or filter() should return _a new Iterable of the same type_.

```
map<M>(
  mapper: (value?: V, key?: K, iter?: Iterable<K, V>) => M,
  context?: any
): Iterable<K, M>;
```

But it happens that they always return an Iterable<K, M>. We start with a List() or Map() and end up with an Iterable that we have to cast or it breaks the flow (following methods expect a List() or Map()).

My best guess is that it should be like this:

```
map<T extends Iterable<K, V>>(
  mapper: (value?: V, key?: K, iter?: T) => any,
  context?: any
): T;
```

I haven't tried it though and I don't think that's exactly right.

Would you accept a pull request for this?

**Comment by Strate** [comment]
```
declare function transformVToM(v: V): M;
let a: Map<K, V>
a.map(transformVToM) // should return Map<K, M>
```
with your proposal, result of a.map would be `Map<K, any>`, isn't it?

**Comment by Strato** [comment]
Well, as I said I don't think my proposal is _exactly_ right. You're right, your example should return a `Map<K, M>`.

**Comment by Strate** [comment]
I think that better solution would be adding `map` declaration to each concrete collection classes. Yes, more "duplicate", but better typings.

**Comment by leebyron** [comment]
Fixed in master will be released soon
