### ISSUE TITLE
Subtyping relationship of Set types makes Iterable#map and friends unsound

### ISSUE THREAD

**Issue by samwgoldman** [facebook/immutable-js#879]
`SetIterable` is a subtype of `Iterable` by setting `T=K` and `T=V`. There is a similar relationship between `SetCollection`/`Collection` and `SetSeq`/`Seq`.

This is actually problematic and prevents us from soundly defining methods on `Iterable` which change either `K` or `V`, like `map` and `flatMap`.

Here's a subset of type definitions that I can use to show the problem:

``` js
interface Iterable<K,V> {
  map<M>(
    mapper: (value: V, key: K, iter: this) => M,
    context?: any,
  ): Iterable<K,M>;
}

interface Set<T> extends Iterable<T,T> {
  map<M>(
    mapper: (value: T, key: T, iter: this) => M,
    context?: any,
  ): Set<M>;
}
```

I should be able to define a function that operates on arbitrary `Iterable`s, but if that function maps over the iterable, we end up with unsound behavior.

``` js
function f(iter: Iterable<string, string>): Iterable<string, number> {
  // what does this return? if we pass a set, this function's type is wrong
  // if we pass any other iterable, this function's type is OK
  return iter.map(s => s.length);
}
```

I don't have a solution to this, but one idea is to override `Set`'s `map` function to return an `Iterable` and not a `Set`. This would make `map` also obey a commonly assumed law: `x.map(f).size = x.size`.

`Set` could also provide an alternate `mapSet` function, or similar, that does what `Set.prototype.map` does today.

**Comment by svieira** [comment]
Since a `Set` is "keyed" by number when iterated over, wouldn't it be possible to preserve the soundness of `.map` by simply providing the specific type of `K`:

```js
interface Set<T> extends Iterable<number,T> {
  map<M>(
    mapper: (value: T, key: number, iter: this) => M,
    context?: any,
  ): Set<M>;
}
```

**Comment by leebyron** [comment]
Seems to be fixed in master by moving the definitions of `map` to their subtypes
