### ISSUE TITLE
[Feature Request] List.updateOrPush

### ISSUE THREAD

**Issue by alanzanattadev** [facebook/immutable-js#883]
Hi,

While coding reducers for redux, I always have to deal with merges of refreshed data and saved data ; to do this, I use a combination of map and concat with filter, this is an example :

``` javascript
function databases(state = [], action) {
  switch (action.type) {
    case DATABASES_REFRESHED:
    let dbs = fromJS(state);
    let newDBs = fromJS(action.databases);
      return dbs
              .map(db => newDBs.find(database => database.get('name') == db.get('name'), this, fromJS({})).merge(db))
              .concat(newDBs.filterNot(db => dbs.find(database => database.get('name') == db.get('name'))))
              .toJS();
      break;
    default:
      return state;
  }
}
```

I use this combination in every reducers, and it would be great if Immutable.js would implement a updateOrPush method on List to let people merge data easily.

function updateOrPush(findClosure, mergeConflictResolver, data): updatedList

If this already exists, it's not obvious in the documentation because I can't find it.

Thank you for your great work !

**Comment by leebyron** [comment]
Sorry, but I don't think such a function is appropriate for the general library. Though this may be something you can create an npm package from if it is of common usage!
