### ISSUE TITLE
plans for standards to share immutables by reference with Workers

### ISSUE THREAD

**Issue by jedwards1211** [facebook/immutable-js#888]
I'm thinking about writing an app that would use Immutable.js and `Worker`s heavily.  Immutables would be the ideal data structures for safe and efficient communication of large amounts of data between threads, since no copying would be necessary.

Obviously it's not currently possible to share immutables between threads or transfer them quickly like objects that implement the [Transferable](https://developer.mozilla.org/en-US/docs/Web/API/Transferable) interface.  (I assume the browser will copy them when sent in [`postMessage`](http://devdocs.io/dom/worker/postmessage), but I haven't tested it to make sure.)

However, since sharing Immutables between threads should be safe in theory, it would be valuable if Browsers one day make that possible.

Is anyone who's involved in browser/spec development aware of plans to enable sharing read-only objects like immutables with `Worker`s by reference?

**Comment by vinnymac** [comment]
Some discussion has begun on the subject of `Persistent Immutable Data Structures`. It is definitely on people's minds, but it hasn't been fleshed out yet afaik. One good discussion on the subject is [this](https://esdiscuss.org/topic/es6-es7-es8-and-beyond-a-proposed-roadmap#content-12) one.

**Comment by jedwards1211** [comment]
Cool, glad to hear other people want this to become a possibility!

**Comment by leebyron** [comment]
Closing this aging issue

Unfortunately this sort of thing still isn't possible in a performant way.
