### ISSUE TITLE
Perf of Map.from

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#89]
Map.from is ~0.6x as performant as a manually written for loop within `withMutations`, it should have less overhead.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Closing this since we've removed `Map.from` and the `Map` factory is a for loop within a `withMutations` call.
