### ISSUE TITLE
quoteString tries to stringify string in stead of object

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/immutable-js#894]
IterableImpl.js 

```
function quoteString(value) {
  return typeof value === 'string' ? JSON.stringify(value) : String(value);
}
```

I think it should be 

```
function quoteString(value) {
  return typeof value === 'object' ? JSON.stringify(value) : String(value);
}
```

**Comment by leebyron** [comment]
The original is correct. It's goal is to return a strings which have been "quoted", otherwise 

Input: `'string "foo" bar'`
Output: `'"string \"foo\" bar"'`

This is used for stringifying output so it is clear which values are strings and which values are something else.
