### ISSUE TITLE
Records & List.flatMap

### ISSUE THREAD

**Issue by matrinox** [facebook/immutable-js#896]
Using 3.7.6 but also tested this on 3.8.1 (latest so far)
### What happened

I was trying to flatMap over an immutable list containing immutable records. The custom record has 3 keys. I noticed that the count of the result was way bigger than the number of items in the list, even though no arrays were returned. If the flatMap function just returns the item, for a list of 2 items, the result should have 2 count. The result is 6 items because the keys in the record are destructured into 3 items each, for a total of 6.
### How to reproduce

Here's the code I used:

``` javascript
var Rec = Immutable.Record({a: 1, b: 2, c: 3})
var list = Immutable.List([new Rec(), new Rec()])
var result = list.flatMap(function(item) { return item });
result.count() !== 2;
```

I've narrowed it to this line of code in flatMapFactory function:

``` javascript
var coerce = iterableClass(iterable);
return iterable.toSeq().map(
  function(v, k)  {return coerce(mapper.call(context, v, k, iterable))} // <-- problematic here
).flatten(true);
```

The problem is that `Immutable.Iterable.Indexed` don't wrap the records properly. `Immutable.Iterable.Keyed` works for obvious reasons. I shouldn't have to use a map as the collection just so the flatMap works with records.
### How to get around

The fix for now is to just wrap records in arrays, e.g. `return [new Rec()]`

**Comment by leebyron** [comment]
Unfortunately this is a consequence of Records being iterable. You'll notice that if you do the same thing with `Map` in place of `Record` that you'll see the same behavior.

The solution here is to use `map()` instead of `flatMap()` if you're not returning values that do not need to be flattened, or to ensure that you're always returning a collection to be flattened.
