### ISSUE TITLE
Why does fromJS() return Seq's when you use a reviver

### ISSUE THREAD

**Issue by devboell** [facebook/immutable-js#897]
Hi there,

   Seeing how fromJS() without a reviver returns Lists and Maps, I was kind of expecting that with a reviver it would do the same. Instead I got Seq objects which I had to convert to List or Map, in order to convert the data.

   one (somewhat random) example I was testing is:

```
   const json3 = [
     {'a': 1, 'b': 2, 'c': 3, 'd': 4},
     {'a': 1, 'b': 2, 'c': 3, 'd': 4}
   ]

   const conv3 = fromJS(json3, (k, v) => {
     if (v instanceof Seq.Indexed) return v.toList()
     return v.toMap().set('c', 10)
   })

   console.log('conv3 = ', conv3)
   // List [ Map { "a": 1, "b": 2, "c": 10, "d": 4 }, Map { "a": 1, "b": 2, "c": 10, "d": 4 } ]
```

   Looking at the fromJS() source code, I found that if I modified the fromJSWith function, like:

```
   function fromJSWith(converter, json, key, parentJSON) {
     if (Array.isArray(json)) {
       return converter.call(parentJSON, key, IndexedSeq(json).map((v, k) => fromJSWith(converter, v, k, json)).toList());
     }
     if (isPlainObj(json)) {
       return converter.call(parentJSON, key, KeyedSeq(json).map((v, k) => fromJSWith(converter, v, k, json)).toMap());
     }
     return json;
   }
```

   I could write my example like this:

```
   const json3 = [
     {'a': 1, 'b': 2, 'c': 3, 'd': 4},
     {'a': 1, 'b': 2, 'c': 3, 'd': 4}
   ]

   const conv3 = fromJS(json3, (k, v) => {
     if (v instanceof List) return v
     return v.set('c', 10)
   })

   console.log('conv3 = ', conv3)
   // List [ Map { "a": 1, "b": 2, "c": 10, "d": 4 }, Map { "a": 1, "b": 2, "c": 10, "d": 4 } ]

```

  which I find a bit cleaner. (I tried a few other examples, but didn't test this extensively.)

   So, yeah, why is it like this? It feels a bit inconsistent, but maybe I am overlooking something?

Thanks!

**Comment by iansinnott** [comment]
I also noticed this inconsistency recently. Doesn't seem intentional. Here's a link to the source for anyone else who finds this issue: https://github.com/facebook/immutable-js/blob/master/src/fromJS.js#L30

**Comment by devboell** [comment]
@iansinnott Now that I look at this again, maybe it is because with a reviver you may want to convert an array into a Set or an object into a Record. So they use a lower level data type.
