### ISSUE TITLE
Immutable nested objects

### ISSUE THREAD

**Issue by mehdishojaei** [facebook/immutable-js#899]
When I run this code:

``` javascript
var foo = { a: { name: 'Mehdi' } },
    a1 = Immutable.Map(foo).get('a'),
    a2 = Immutable.Map(foo).get('a');

console.log(a1 === a2); // -> true
```

But I expect to be: false

While:

``` javascript
var foo = { a: { name: 'Mehdi' } },
    foo1 = Immutable(foo),
    foo2 = Immutable(foo);

console.log(foo1 === foo2); // -> false
```

**Comment by ianstormtaylor** [comment]
Immutable isn't changing any of the regular Javascript semantics here, everything looks fine. 

In the first example, the `foo` object is passed into Immutable, which doesn't change it at all, so that when it's accessed later with `.a` the nested object is still equal by reference.

In the second example, two instances of `Immutable` are created, which are separate objects, and thus aren't equal, as far as Javascript is concerned.

Looks like what you want is the [`.fromJS()`](https://facebook.github.io/immutable-js/docs/#/fromJS) function, which will deeply convert the input objects.

**Comment by mehdishojaei** [comment]
Thanks, First of all I done a typo fix. `.a` -> `.get('a')`.
Yes, Immutable doesn't change JavaScript semantics and doesn't change `foo`.


> In the second example, two instances of Immutable are created, which are separate objects, and thus aren't equal, as far as Javascript is concerned.


If so both the `Immutable(foo)` in the first example are the same, because they are created from the same object (`foo`). So `.get('a')` of the both must be the same, but is not.


I personally think the first example is not correct but the second one is correct.

**Comment by ianstormtaylor** [comment]
Try using `Immutable.fromJS()` to get similar functionality to `seamless-immutable`, and see if that works.

**Comment by mehdishojaei** [comment]
`Immutable.fromJS()` also gets the similar result and is not similar to `seamless-immutable`:
```javascript
Immutable.fromJS(foo).a === Immutable.fromJS(foo).a
```

**Comment by r4j4h** [comment]
> I know that Immutable.Map(foo).get('a') just returns an plain object and not an Immutable.Map. But I think it's not a good reason to consider the a1 and a2 to be equal by reference. I think its a bit confusing.

Pardon me for interrupting, but it's been 17 days and OP has not responded but did change the title.

I think what @ianstormtaylor is trying to say is not that `Immutable.Map(foo).get('a')` should return an immutable Map. `.get('a')` precludes that, but that shouldn't `Immutable.Map(foo)` create an immutable instance *based on* but not equal to `foo`? In that case, `a1` and `a2` are indeed different.

The problem I believe is from immutable.js being shallow, and `fromJS` is the way around it. It makes sense that immutable.js would keep the given reference until it changes in some way as opposed to automatically making an immutable clone.

**Comment by leebyron** [comment]
Thanks for the great explaination! `fromJS` is the right path
