### ISSUE TITLE
immutable installation 3.8.1 installs 3.7.6

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/immutable-js#900]
Got a bit of a weird issue. I try to install immutable 3.8.1 but seem to get 3.7.6

```
"dependencies": {
"harmony-proxy": "^1.0.1",
"immutable": "^3.8.1",
"lodash": "^4.2.1",
"lodash-es": "^4.2.1",
"normalizr": "^2.0.2"
```

  },

I get on one project this one, and on another directory the same project gets the other one.

<img width="636" alt="correct" src="https://cloud.githubusercontent.com/assets/384959/16274802/969e050a-387d-11e6-8017-6435bec26f38.png">
<img width="634" alt="wrong" src="https://cloud.githubusercontent.com/assets/384959/16274803/96a0cc54-387d-11e6-8676-4ed5b52a28f6.png">

**Comment by leebyron** [comment]
I cannot reproduce this in a fresh `npm init` test directory.

In the _args and _requested section of your installed package, it looks like `^3.7.6` was requested. I expect that you might have multiple versions of your dependency listed in your project - or perhaps npm is installing in a buggy way.
