### ISSUE TITLE
Handling Conversion Efficiently

### ISSUE THREAD

**Issue by jamestwiggle** [facebook/immutable-js#910]
I found that @leebyron has said in the past that the least efficient operation in immutable are the `fromJS()` and alike conversions. I'm working on an application with GraphQL and currently we use `fromJS()` to convert the JSON payloads to `immutable`. Is there a better conversion strategy than using `fromJS()`?

**Comment by leebyron** [comment]
fromJS() is exactly for converting JSON payloads to Immutable Maps and Lists! You're doing it right. 

The least efficient operation is toJS(). Immutable collections already can be provided to JSON.stringify() so there are only rare cases to use toJS() and yet unfortunately it's quite common. Overuse of toJS() can negate a lot of the beneficial properties the data structures in this library offer.
