### ISSUE TITLE
Is it possible to use List.updateIn()?

### ISSUE THREAD

**Issue by brycepj** [facebook/immutable-js#911]
It's included in the [List docs](http://facebook.github.io/immutable-js/docs/#/List/updateIn).

It doesn't accept an index as a parameter, and passing `[ 0, 'prop1', 'prop2']` as a `keypath` (0 being the index of the item to update), throws an 'invalid keypath' error. Passing the index as a string causes the same error. 

I'm confused as to how someone would use `updateIn` on a List.

**Comment by ev1stensberg** [comment]
[SO to the rescue!](http://stackoverflow.com/questions/29589753/how-to-update-element-inside-list-with-immutablejs)

**Comment by brycepj** [comment]
I actually read that a couple of days ago, and it's part of the reason I
asked this question. You'll notice that none of the answers actually use
`updateIn`. Again, I don't really see how its signature can be used with a
list. Maybe there's something I'm not seeing?

**Comment by ev1stensberg** [comment]
correct! However, I don't know if indexes are supported, for now, regular keypaths are ok :)

**Comment by leebyron** [comment]
You definitely can use indices! I added a test to illustrate
