### ISSUE TITLE
map method does not work inside withMutations

### ISSUE THREAD

**Issue by janmarek** [facebook/immutable-js#913]
Hi,
look at the example:

``` js
Immutable.List([1, 2]).withMutations(list => {
    list.map(a => a * 2);
}).toString();

// expected result
List [ 2, 4 ]

// actual result
List [ 1, 2 ]
```

It is the same with Map structure.

**Comment by leebyron** [comment]
`map()` and most other sequence transform functions do not mutate and always return new collections. Check out the docs for more info http://facebook.github.io/immutable-js/docs/#/List/withMutations

**Comment by jackson-sandland** [comment]
How does one achieve what the OP desired to achieve when they posted the code above?

**Comment by varunrau** [comment]
One possibility:

```
Immutable.List([1, 2]).withMutations(list => {
   for (let i = 0; i < list.size; i++) {
      list.set(i, list.get(i) * 2);
   }
}).toString();
```
