### ISSUE TITLE
Passing wrong parameter to set function will produce wrong results

### ISSUE THREAD

**Issue by dYb** [facebook/immutable-js#915]
I'm not sure if it's a bug, but it's really strange

```
const data = Immutable.fromJS({data: 'data'})

const data2 = data.set(['data'], 'data2') // I know it's wrong, setIn should be here, but not throwing any error
console.log(data2.get('data')) // data(that's right)
console.log(data2.toJS().data) // data2(that's wrong)
```

version 3.8.1
 reproduce in [here](http://jsbin.com/yoqudi/edit?html,js,console,output)

**Comment by leebyron** [comment]
#1002 explains this

Immutable collections allow any sort of key, not just strings. Array keys are just fine!
