### ISSUE TITLE
Add filter with type guard combination method

### ISSUE THREAD

**Issue by Strate** [facebook/immutable-js#923]
Please follow example:

``` typescript
let a = Immutable.List<string | number>()
declare function isString(a: any): a is string;
a.filter(isString) // result expected to be Immutable.List<string>
```

I've tried to implement that thing with adding overload for `filter` in `List` in that way:

```
filter<S extends T>(
  predicate: (value: T, key: number, iter: this) => value is S,
  context?: any
): List<S>;
```

And gulp task `typedef` fails with `Error: Not yet implemented: type constraint`. Could someone implement that feature?

**Comment by leebyron** [comment]
Done in master! Will be released soon
