### ISSUE TITLE
Record and ES6 Spread operator

### ISSUE THREAD

**Issue by jezikk** [facebook/immutable-js#936]
Hi,

I have a question: why this approach doesn't work
```
const obj1 = Record({
    param: 1,
})();

const obj2 = Record({
    ...obj1,
    param2: 2,
})();
```
, while the following one does?

```
const obj1 = Record({
    param1: 1,
})();

const obj2 = Record({
    ...obj1.toObject(),
    param2: 2,
})();
```

I think it would be good to use spread operator to extend the Record with new parameters.

Thank you.

**Comment by mshenfield** [comment]
There's a pretty good discussion of why object destructuring isn't supported for Immutable.js [here](http://stackoverflow.com/questions/34762608/can-i-use-destructuring-assignment-with-immutable-js). Long story short, object destructuring is only supported for native JavaScript objects.
There is a [babel plugin](https://github.com/vacuumlabs/babel-plugin-extensible-destructuring) that makes this work for variable assignment (though [not function arguments](https://github.com/vacuumlabs/babel-plugin-extensible-destructuring/issues/10))
