### ISSUE TITLE
[Feature Request] Side Effect method which returns the state

### ISSUE THREAD

**Issue by alanzanattadev** [facebook/immutable-js#937]
Hi,

It would be great to have a side effect method which returns the previous state, to be able to add some logs or others into chains.

for example : return fromJS(state).get('myList').filter(l => l.get('id')).log(list => list.forEach(elem => console.log(elem)));

I don't know if the philosophy around immutablejs can accept that, because it makes the transformation not pure, but I'd like to discuss about that.

So what do you think ?

Thank you !

**Comment by leebyron** [comment]
Try this:

```
return fromJS(state).get('myList').filter(l => l.get('id')).map(list => (list.forEach(elem => console.log(elem)), list));
```
