### ISSUE TITLE
Mutable List that was emptied using pop does not return EMPTY_LIST

### ISSUE THREAD

**Issue by philpl** [facebook/immutable-js#939]
### What happened

When List is being emptied in a mutable state (`asMutable`) it can be emptied using
the `pop` method, which is still available while other classes only allow additive methods
in their mutable states. After a Mutable List was emptied using `pop` and is converted back
using `asImmutable`, the result is not the EMPTY_LIST reference, but rather a separate
instance.

This is since `asImmutable` is the same as Map's one, that just returns `this.__ensureOwner()` and doesn't check for `this.size === 0` before.
### How to reproduce

``` js
const filled = new List([ 'a' ]);
const empty = new List();

filled === empty // false: as expected
filled.clear() === empty // true: as expected

filled.withMutations(list => {
  list.pop()
}) === empty // false: oops
filled.asMutable().pop().asImmutable() === empty // false: oops
filled.asMutable().pop().asImmutable().size // 0: oops
```

I found this, while writing a project for extendable immutable types.

If this turns out to be a bug, I'd be glad to file a PR myself :)

**Comment by leebyron** [comment]
Not really a bug per-se since there's never guarantees about `===` working - that's a perf optimization. However this does seem like it could be a pretty easy enhancement for someone looking to contribute.
