### ISSUE TITLE
getIn(string) should throw an error

### ISSUE THREAD

**Issue by mhagmajer** [facebook/immutable-js#940]
``` js
Immutable.fromJS({a: {b: 4}, ab: 5}).getIn('ab') // returns 4
// whereas someone might expect 5 but really an error should be thrown
```

A correct way to do this would be:

``` js
Immutable.fromJS({a: {b: 4}, ab: 5}).getIn(['a','b'])
```

Strings are Iterable but often not considered collections because that leads to confusion.

**Comment by Davorak** [comment]
I have seen people try and use:

`Immutable.fromJS({a: {b: 4}, ab: 5}).getIn('ab')`

and expect to get `4` since that is the syntax they are used to from mongodb.
