### ISSUE TITLE
Bug in Map.set(key: number, value: any)

### ISSUE THREAD

**Issue by aisfo** [facebook/immutable-js#945]
If a map has a key like '1', and then set is called with a key 1, the value is replaced is object representation, but not a list one. Here's the example:

var obj = Immutable.Map({ '1': 'a' });
obj.toObject() ---> Object {1: "a"}
obj.toArray() ---> ["a"]

obj = obj.set(1, 'b');
obj.toObject() ---> Object {1: "b"}
obj.toArray() ---> ["a", "b"]

obj = obj.set('1', 'c');
obj.toObject() ---> Object {1: "b"}
obj.toArray() ---> ["c", "b"]

**Comment by kentor** [comment]
not a bug imo. js objects can only have strings (and symbols) as keys, so 1 will be converted to '1' when constructing the js object

**Comment by aisfo** [comment]
I agree, numbers should be converted to strings. The problem is with toArray(), it returns values of both 1 and '1'. Underlying mechanism doesn't get rid of the old value of '1', when value with key 1 is added.

**Comment by kentor** [comment]
toArray() doesn't convert it to a plain object first and then extract the values. it grabs all the values in the map.
