### ISSUE TITLE
Immutable DataStructures

### ISSUE THREAD

**Issue by sandysaders** [facebook/immutable-js#948]
@leebyron this is a really awesome library, thank you for making it. I'd like to know if you have any resources for learning about datastructures/immutable datastructures as I really want to learn more about them. Resources like articles, videos, books (hopefully not too expensive 😅), tutorials, courses, etc. If you can I would really appreciate it.

**Comment by leebyron** [comment]
Highly recommend https://www.amazon.com/Purely-Functional-Structures-Chris-Okasaki/dp/0521663504
