### ISSUE TITLE
fromJS() does not convert objects to maps inside immutable lists or maps

### ISSUE THREAD

**Issue by anjdreas** [facebook/immutable-js#949]
### What happened

`Immutable.fromJS()` does not convert JS objects to `Immutable.Map` when placed inside an `Immutable.List` or `Immutable.Map`. The result is that `getIn()` and similar keypath methods fails when it encounters the plain JS object.

I typically encounter this when mixing plain JS and immutablejs in my Redux state object, since immutablejs does not play too well with TypeScript and other strongly typed transpilers.

```
// bar
console.log(Immutable.fromJS([{
  foo: 'bar'
}]).getIn([0, 'foo']));

// undefined
console.log(Immutable.fromJS(Immutable.List([{
  foo: 'bar'
}]).getIn([0, 'foo'])));

// undefined
console.log(Immutable.fromJS(Immutable.Map([{
  foo: 'bar'
}]).getIn([0, 'foo'])));
```
### How to reproduce

JS Fiddle:
https://jsfiddle.net/anjdreas/gp6sz7yc/7/

**Comment by foxsky** [comment]
The same with me.

**Comment by leebyron** [comment]
That's correct. fromJS() expects plain JS arrays and objects as input. It does not operate on anything else.

**Comment by danilobrinu** [comment]
@leebyron but not work, i pass plain object but no convert array into Immutable.List ??
