### ISSUE TITLE
List implementation

### ISSUE THREAD

**Issue by sandysaders** [facebook/immutable-js#952]
Is the List implementation the same as a LinkedList? If not whats the main difference?

**Comment by philpl** [comment]
No, it's not a LinkedList. It's a Trie data structure. You can learn more about it in @leebyron's talk:

https://www.youtube.com/watch?v=I7IdS-PbEgI&feature=youtu.be

**Comment by sandysaders** [comment]
@philpl Thanks 👍🏼

**Comment by 1shadyone** [comment]
No i thinlk i should be thanking you all these fucked up messaged and hidden society was making me think i was crazy 
On Aug 19, 2016 5:57 PM, his <notifications@github.com> wrote:@philpl Thanks 👍🏼

**Comment by 1shadyone** [comment]
Is there anytjing elsw i can do? Or can you help me out with something? Its personal and it may be very hazardous to my future ...but i need to know something about my wife 
On Aug 19, 2016 5:57 PM, his <notifications@github.com> wrote:@philpl Thanks 👍🏼
