### ISSUE TITLE
keySeq().has returns false against object with integer as key

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/immutable-js#958]
It seems that if an immutable Map is initialized with an object that has integers as keys, the "has" function doesn't work as expected. Could be my ignorance.

```
var myObj= new Map({1:'foo'});
var state = {myObj};
var action = {payload:{id:1}};

state.myObj.keySeq().has(action.payload.id);//false
state.myObj.keySeq().has(action.payload.id+'');//false
```

I assume it has something to do with objects supporting only strings as keys, but accepting integers nonetheless.

**Comment by kentor** [comment]
keySeq is not a set...

**Comment by leebyron** [comment]
> I assume it has something to do with objects supporting only strings as keys, but accepting integers nonetheless.

Bingo!

```
❯ node
> Object.keys({1:'foo'})
[ '1' ]
>
```

JavaScript Objects only support string keys, but they allow specifying them without the quotes (as of ES3) which makes numeric character string keys *look* like numbers, but they're not.
