### ISSUE TITLE
Projects using Immutable.js

### ISSUE THREAD

**Issue by YurySolovyov** [facebook/immutable-js#960]
Continuation of [Twitter thread](https://twitter.com/leeb/status/767040753025429504) /cc @leebyron 

It would be nice to have a list of projects that use Immutable.js with links on GH and short description of some sort.

This list can serve as a good reference to new users who want to get started with Immutable.js, or take a look at how people solved typical problems, stuff like that.

Things to take into consideration:
- Projects come in all shapes and sizes, should we add some requirements for inclusion in such list?
- Projects usually belong to some categories: npm module, webapp/service, desktop app etc. Need a way to somehow categorize them.
- We need to encourage users to submit theit projects to the list, maybe put some call to action into readme?

**Comment by Daniel15** [comment]
Just open-source projects, or any projects? We use immutable-js very heavily in ads frontend code at Facebook :smile:

**Comment by Daniel15** [comment]
Just open-source projects, or any projects? We use immutable-js very heavily in ads frontend code at Facebook :smile: 

Anyone can edit the wiki (https://github.com/facebook/immutable-js/wiki), so creating a new wiki page is one possible approach.

**Comment by YurySolovyov** [comment]
@Daniel15 Idea is to add projects that can be studied, so yeah, open-source ones will be better.
We can also add a section for closed-source ones, just for reference.

**Comment by leebyron** [comment]
Great idea. If there are any candidates, I think a page on the wiki is the right place for this.
