### ISSUE TITLE
the React element as a immutable List does not work well. 

### ISSUE THREAD

**Issue by seap** [facebook/immutable-js#965]
In my app, the prop 'products' is a Immutable List as below 

```
  render() {
    return (
      <div>
        {this.props.products.map((product, index) => (
          <ProductView key={index} item={product} />))}
      </div>
    );
  }
```

after mapping of List instance, the return value is still a Immutable List. 
In lower-cost version of webview, it does not work.
So I can only change the List instance to pure javascript by toJS function. 
Who can explain the reason exactly? thanks in advance.

**Comment by leebyron** [comment]
Closing this aging issue.

Sorry, I'm not sure I follow. Immutable is designed to provide iterable collections which React can collect as children via the technique described in [iterall](https://github.com/leebyron/iterall). Ensure your version of React is up to date.
