### ISSUE TITLE
Suggestion: getters that throw errors

### ISSUE THREAD

**Issue by mockdeep** [facebook/immutable-js#968]
It's easy to forget to set and fetch things via `set()` and `get()` and end up trying to do `myMap.a = 'stuff'`. It might be handy when a key is set on a map to prevent setting properties of the same name via [js getters and setters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set).

```
{
  set: function (key, value) {
    var newMap = howeverYouCreateAMap();
    Object.defineProperty(newMap.prototype, key, {
      get: function () { throw "don't do that"; },
      set: function () { throw "don't do that either"; }
    });
    // other stuff
  }
}
```

I also noticed [this issue about proxies](https://github.com/facebook/immutable-js/issues/440), so it seems like it could roll nicely into that when it's available...

**Comment by leebyron** [comment]
Unfortunately proxies are *really* slow, so I'm not sure we would want to add this into the core library. Cool idea though! 

Reopen or submit a PR if you have an idea for how to do this in a performant way
