### ISSUE TITLE
get() and getIn() return type in flow definition is not correct

### ISSUE THREAD

**Issue by jpolo** [facebook/immutable-js#972]
We use immutable and flow. Recently we had a bug because flow did not check that if getIn() has no `notSetValue` then the result could be undefined.

The current code :

``` typescript
// in immutable.js.flow
get<T>(searchKeyPath: ESIterable<any>): T;
getIn<T>(searchKeyPath: ESIterable<any>): T;
```

The right definition :

``` typescript
get<T>(searchKeyPath: ESIterable<any>): void|T; // or ?T
getIn<T>(searchKeyPath: ESIterable<any>): void|T; // or ?T
```

There is also an inconsistency between get(searchKeyPath, notSetValue) and getIn(searchKeyPath, notSetValue) that should be corrected :

``` typescript
getIn<V_>(searchKeyPath: ESIterable<any>, notSetValue: V_): V|V_; // or ?T
```

**Comment by bastoche** [comment]
🐐

**Comment by leebyron** [comment]
Thanks for this report.

Actually `getIn` isn't possible to correctly type check unfortunately since the key path may lead to a collection of a totally different type and Flow can't translate that, so I'll convert them to return `any`. However you're totally right that `get` could return void.
