### ISSUE TITLE
Flow: dynamic type tests & Set.isSet

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/immutable-js#976]
### What happened

I'm not sure if it's Immutable.js interface issue or issue w/ Flow itself, but dynamic type tests doesn't work w/ static methods like `isSet`, `isMap` etc.
### How to reproduce

``` js
import { Set } from 'immutable';

type Status = Set | boolean;
type SetStatus = (status: Status, id: *) => Status;

const setStatusOn: SetStatus = (status, id) => (
  status instanceof Set ? status.add(id) : true // fine!
);

const setStatusOn: SetStatus = (status, id) => (
  Set.isSet(status) ? status.add(id) : true     // nope: Property `add` not found in Boolean
);
```

**Comment by leebyron** [comment]
Unfortunately Flow doesn't have this capability just yet, but it's planning on it. I've put in the necessary syntax with fingers crossed that a future version of Flow works correctly, but in the meantime you'll need to use `status instanceof Set`
