### ISSUE TITLE
Flow: static `Map.of` constructor not included in flow definition

### ISSUE THREAD

**Issue by yusefnapora** [facebook/immutable-js#982]
### What happened

I tried using `Map.of` in a flow-typed project, but got an error saying that the property `of` was not found in `Map`

### How to reproduce

I'm using flow v3.8.1, but the definition is also missing in master.

``` javascript
const { Map: IMap } = require('immutable')
const foo = IMap.of('foo', 'bar')
```

Results in the following flow error:

```
 62: const foo = IMap.of('foo', 'bar')
                      ^^ property `of`. Property not found in
652:   Map,
       ^^^ statics of Map. See: node_modules/immutable/dist/immutable.js.flow:652
```

**Comment by leebyron** [comment]
This is intentional as the method is deprecated and will be removed from the documentation in the next release.

I suggest using `Map([[ 'foo', 'bar' ]])` or `Map({ foo: 'bar' })`
