### ISSUE TITLE
Documentation Nomenclature

### ISSUE THREAD

**Issue by slashwhatever** [facebook/immutable-js#983]
The way the docs for Immutable.js are written is difficult to understand for many JS developers.

Can you explain the nomenclature used so we can all more easily decipher the documentation and put this framework to more effective use?

**Comment by aj07** [comment]
Yo are most welcome to contribute. :)

**Comment by slashwhatever** [comment]
I'd love to. My point is, I don't understand the docs to begin with and therefore can't contribute.

**Comment by awv-inf** [comment]
Same problem. It looks like C++/Boost. It's just not expected for a dynamically typed language and it makes it harder to parse. In some cases i have not the slightest idea what is meant, and there are no usecases or examples. I wish it would be documented as virtually all other js projects are, like lodash, etc.

**Comment by tsironis** [comment]
I totally agree, and also there are no real world example that you can wrap your head around them.

I really like Underscore's documentation and subsequently, lodash and it helped understand both how the library works and made me better developer.

**Comment by leebyron** [comment]
The documentation function types are written in [typescript](http://www.typescriptlang.org/) to help explain how various methods work.

Some but not all documentation contains examples. If you wish, adding examples and improving documentation is an excellent way to contribute back to open source software.

All documentation for this library is automatically generated from https://github.com/facebook/immutable-js/blob/master/type-definitions/Immutable.d.ts which should make contributions easier
