### ISSUE TITLE
Immutable.Record keys not enforced consistently on initialization and set

### ISSUE THREAD

**Issue by jcarbo** [facebook/immutable-js#985]
### What happened

Record keys seem to be enforced only on `set`, not during initialization (see steps below). I'd prefer it to not throw and/or you could configure whether or not it throws an error, but I found the inconsistency weird. Here's my use-case:

I'm using Records to store data returned from an API in a normalized store. If a record doesn't exists, I create one. If one does exist, I merge the data into the existing record. If the API has added keys that my client app is not aware of, on initialization everything works (just ignores the keys it's not aware of) but on the merge will throw.

As per [this dicussion (#573)](https://github.com/facebook/immutable-js/issues/573#issuecomment-131736533), the commenter says:

> Records are only meant to be used if you want to enforce a certain schema for your data while providing defaults when removing a key.

I'd disagree. For me, the enforcement of keys has actually caused more headache than benefit. I use Records so that I have the benefits of immutable data while still being able to use `.` access and destructure in a sane way throughout my app without needing to call `get` everywhere.

Thoughts?
### How to reproduce

``` node
$ node
> var Immutable = require('immutable')
undefined
> var MyRecord = Immutable.Record({ foo: undefined })
undefined
> var record = new MyRecord({ foo: 5, bar: 10 })
undefined
> record.toJS()
{ foo: 5 }
> record.set('bar', 10)
Error: Cannot set unknown key "bar" on Record
    at Record.set (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:3690:15)
    at repl:1:8
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
```

**Comment by volkanunsal** [comment]
I just declare all the keys I need upfront. It forces me to think hard about the schema and you can build a simple helper function very easily.

```js
> const makeSchema = (...rest: string[]) = rest.reduce((s, v) => Object.assign(s, {[v]: undefined}), {})
> var MyRecord = Immutable.Record(makeSchema('foo', 'bar'))
> var record: Record<{foo: number, bar: number}> = new MyRecord({ foo: 5, bar: 10 })
> record.set('bar', 10)
```

**Comment by jcarbo** [comment]
I would do this, however I'm not in control of the schema since I'm using data from a third-party API. Adding new fields to an API response is generally considered backwards compatible since 99% of the time they will just be ignored. In this case, however, they will cause the code to throw.

To better illustrate my use-case, imagine I'm using an API and I know the response includes the `foo` field. In a recent API update, they started also returning the `bar` field:
```js
$ node
> var Immutable = require('immutable')
undefined
> var MyRecord = Immutable.Record({ foo: undefined })
undefined
> var apiData = { foo: 5, bar: 5 }
undefined
> var record = new MyRecord(apiData)
undefined
> record.toJS()
{ foo: 5 }
> var updatedApiData = { foo: 10, bar: 10 }
undefined
> record.merge(updatedApiData)
Error: Cannot set unknown key "bar" on Record
    at Record.set (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:3690:15)
    at mergeIntoMap (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:1960:22)
    at /Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:3018:36
    at ObjectSeq.__iterate (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:420:13)
    at KeyedIterable.mappedSequence.__iterateUncached (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:606:16)
    at KeyedIterable.Seq.__iterate (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:276:14)
    at KeyedIterable.forEach (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:4383:19)
    at /Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:1963:19
    at Record.Map.withMutations (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:1355:7)
```

**Comment by caspg** [comment]
I also think it is a little inconsistent that error is thrown only on `merge`.

To overcome this issue, I'm doing this hack:

```js
...
const updatedApiData = { foo: 10, bar: 10 }

record.merge(new MyRecord(updatedApiData))
```

But I'm not sure if it is the best approach. Maybe some function which filter properties from `apiData` before merging would be a better idea?

**Comment by caspg** [comment]
Yeah, my above solution is stupid. It resets keys, not provided in `updatedApiData` to initial value.
Currently I'm filtering unwanted keys before merging them.

**Comment by mnpenner** [comment]
I think I actually like the current behaviour. If your API endpoint returns too much data and you simply stuff it into a `Record`, then `Record` will quietly lop off all the extra data you don't need. If you knew you needed it, then you would put it in the spec, no?

@jcarbo  [Your example](https://github.com/facebook/immutable-js/issues/985#issuecomment-254020305) doesn't make sense to me. If the API starts returning more data, and you want to start using that data, why can't you update the `Record`? When would you be in control of the code that uses the `Record`, but not the `Record` definition?

If the Record definitions are maintained by the API-creator, then the user just needs to update his lib. If the Record definitions are created by the user, then he needs to update the Record before he can start using the updated API. 

The only scenario I can think of where this would be a problem is if there are 3 parties are involved: the API-creator, the lib maintainer, and the end-developer.

**Comment by jcarbo** [comment]
@mnpenner - I can (and have been) updating the record... after realizing that some unrelated, non-breaking API update has broken my app. Here's a scenario:

### Initially
```
$ node
> let Immutable = require('immutable')
> 
> // GET /api/user
> let apiData = {
...   first_name: 'John',
...   last_name: 'Smith'
... }
> 
> // Record in my app
> let User = Immutable.Record({ first_name: undefined, last_name: undefined })
> 
> // Initialize a user
> let user = new User(apiData)
> 
> // Update a user
> user.merge(apiData)
Record { "first_name": "John", "last_name": "Smith" }
```

### API adds a field

This is a backwards-compatible change. An existing application will just be unaware of the new field and just ignore it. However, using records will cause a crash.

```
$ node
> let Immutable = require('immutable')
> 
> // GET /api/user
> let apiData = {
...   first_name: 'John',
...   last_name: 'Smith',
...   company: 'Smith Co.'
... }
> 
> // Record in my app
> let User = Immutable.Record({ first_name: undefined, last_name: undefined })
> 
> // Initialize a user
> let user = new User(apiData)
> 
> // Update a user
> user.merge(apiData)
Error: Cannot set unknown key "company" on Record
    at Record.set (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:3690:15)
    at mergeIntoMap (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:1960:22)
    at /Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:3018:36
    at ObjectSeq.__iterate (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:420:13)
    at KeyedIterable.mappedSequence.__iterateUncached (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:606:16)
    at KeyedIterable.Seq.__iterate (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:276:14)
    at KeyedIterable.forEach (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:4383:19)
    at /Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:1963:19
    at Record.Map.withMutations (/Users/jeffcarbonella/Documents/contactually/frontend/node_modules/immutable/dist/immutable.js:1355:7)
>
```

This is a simple example, so you could theoretically filter out undeclared fields. However, for me this is occurring during a `deepMerge` with nested records so that's really not a tenable solution.

**Comment by mnpenner** [comment]
@jcarbo Oh..okay, I see the problem now.

That's kind of a tough one. On one hand, I agree with you that that should just work, but on the other hand, if fields quietly go missing, we would want to know about that, no?

What about `user.set`? Should that throw or not? If you're setting fields one-by-one from API data for some reason, then you would want it to quietly do nothing, but if you're explicitly trying to set a field based on some business logic, then you would want to know when you messed it up. But in this scenario, you could actually try/catch it if you needed to, but that's not true of `merge` (due to partial success/failure).

I think we might need some options or additional methods to handle this.

**Comment by briantobo** [comment]
I have the same issues with the same use case as mentioned above.
@jcarbo: Did you end up finding a good solution to this? Thanks

**Comment by jcarbo** [comment]
@briantobo - I wound up replacing `mergeDeep` with my own recursive `mergeWith`.

Here's the code:
```js
const isMap = Immutable.Map.isMap
const isRecord = (a) => a && isMap(a._map) // There's no built-in `isRecord` :|
const isObject = (a) => typeof(a) === 'object'

function safeMergeDeep(a, b) {
  if (isRecord(a) && isObject(b)) {
    // Based on merge functionality in Map which record inherits:
    // https://github.com/facebook/immutable-js/blob/master/src/Map.js#L756-L778
    return a.withMutations(
      (record) => Immutable.fromJS(b).forEach(
        (value, key) => { record.has(key) ? record.set(key, value) : record }
      )
    )
  }

  return (a && a.mergeWith) ? a.mergeWith(safeMergeDeep, b) : b
}
safeMergeDeep(user, apiData)

// Note based on the examples above the following will still
// fail because you won't have a reference to `user`
// to know it's a record. This isn't an issue in my case since
// the record merging is happening within a nested map but if
// it were an issue you'd just need to use the
// functional style: safeMergeDeep(user, apiData)
user.mergeWith(safeMergeDeep, apiData)
```

**Comment by Freddy03h** [comment]
Experiencing the same issue.

Even if you have the full controls of the schema on yours app and api ; adding an attribute on an existing ressource api that break the app is extremely harmful.

The app that consume the api can be desynchronized with the api : browser cache, service worker… Or more eloquent example : a (react-)Native app. The app the end-user use isn't always up-to-date, that's why we versioning api and we need to think about it since v1 for a native app.

But, adding an attribut or nested ressource to an existing object isn't, usually, a breaking change. It's only ignored by olds apps versions.
The actual behavior of `set` and `merge` of `Records` (that is inconsistent with Record initialization) is really annoying.

I'll prefer too that `set` and `merge` ignore unknown attributes. Just like on the `Record` initialization.

**Comment by leebyron** [comment]
Fixed in master - will be released soon
