### ISSUE TITLE
misreference to this in equals function

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/immutable-js#988]
I'm using React-Native and trying to create an equals functions for a Record like so:

```
Post.prototype.equals = (that) => !( (!this && !that) || (!this && that) || (this && !that) ) && this.id === that.id;
```

However, this is compiled to

```
Post.prototype.equals = (that) => !( (!_this && !that) || (!_this && that) || (_this && !that) ) && _this.id === that.id;
```

Note the _this. However, runtime _this is undefined and this is not. And so, I get an undefined error. This is solved by using function instead of arrow functions. Am I doing this wrong?

**Comment by leebyron** [comment]
Sorry for the long delay. Closing this aging issue, so I hope you figured it out.

Prototype methods need to use `function () {}` instead of arrows in order to refer to the class instance as `this`.
