### ISSUE TITLE
flow: Map#equals incompatible with Map?

### ISSUE THREAD

**Issue by kentor** [facebook/immutable-js#989]
### What happened

Getting this with Flow 0.33

``` js
 11: Immutable.Map().equals(Immutable.Map());
                            ^^^^^^^^^^^^^^^ Map. This type is incompatible with
 45:   equals(other: Iterable<K,V>): boolean;
                     ^^^^^^^^^^^^^ Iterable. See: node_modules/immutable/dist/immutable.js.flow:45
```

.flowconfig:

```
[ignore]
<PROJECT_ROOT>/node_modules/fbjs/.*
<PROJECT_ROOT>/node_modules/npm/.*
<PROJECT_ROOT>/node_modules/react-side-effect/.*
<PROJECT_ROOT>/node_modules/react-timeago/.*
```
### How to reproduce

``` js
const Immutable = require('immutable');
Immutable.Map().equals(Immutable.Map());
```

Should not be an error since Map extends KeyIterable which extends Iterable

**Comment by NullDivision** [comment]
Same thing happens for list. I'm guessing the declarations for `Map` and `List` don't extend `Iterable`.

**Comment by kentor** [comment]
Is it because of mixins?

Flow inheritance:
```
_Iterable <- Collection (mixins KeyedIterable) <- KeyedCollection <- Map
_Iterable <- Iterable <- KeyedIterable
```

**Comment by kandros** [comment]
Reproduced with Immutablejs v3.8.1 and flow 0.37.4

also reproduced for List on typescript 
```{
  "resolution": "main",
  "tree": {
    "src": "https://raw.githubusercontent.com/alitaheri/immutable-unambient/3e5ef14e1677e2db90770b8263be889b71c4d444/typings.json",
    "raw": "registry:npm/immutable#3.7.6+20160411060006",
    "main": "immutable.d.ts",
    "version": "3.7.6",
    "name": "immutable"
  }
}
```

**Comment by dimitarg** [comment]
```List().equals(List())```

Flow: List. This type is incompatible with Iterable.


```
    "flow-bin": "^0.36.0",
    "flow-typed": "^2.0.0",
    "immutable": "^3.8.1",
```

**Comment by leebyron** [comment]
Fixed in master will be released soon!

**Comment by ndbroadbent** [comment]
@leebyron Do you think there could be a `3.8.2` release with this fix, as well as the ["default import" issue](https://github.com/facebook/immutable-js/issues/854)?

I tried out the latest `4.0.0-rc.2`, but I ran into some different problems with types. It would just be great if I could get flow working at 100%.

**Comment by ndbroadbent** [comment]
Also I'm new to flow, and I just discovered that you can add a `$FlowFixMe` comment to ignore errors:

```js
// $FlowFixMe
import Immutable, { Map } from 'immutable'

// ...

// $FlowFixMe
if (map.equals(otherMap)) ...
```

Hopefully that will help any other perfectionists who want to go from 99.999% to 100% :)
