### ISSUE TITLE
Can we strengthen the return type of Record constructor?

### ISSUE THREAD

**Issue by volkanunsal** [facebook/immutable-js#992]
I have whole chunks of code that seems to be uncovered by Flow because of this TODO item:

```
//TODO: Once flow can extend normal Objects we can change this back to actually reflect Record behavior.
// For now fallback to any to not break existing Code
declare class Record<T: Object> {
  static <T: Object>(spec: T, name?: string): /*T & Record<T>*/any;
```

I'm wondering if anyone knows when Flow will have a fix for this in place, so that we can start type checking Records.

**Comment by rgbkrk** [comment]
I would love to see and use this.

The other issue I run into is with including the container types on `Record`s is that it says that a `Callable signature not found in Record` (which is true). I love Immutable.js and I love `flow`. I wish I could use them both more fully.

**Comment by rgbkrk** [comment]
This makes me wonder where the discussion for "extend[ing] normal Objects" is and if we need to retitle this to make it more apparent what's missing
