### ISSUE TITLE
Repetitive code to check for null/undefined Immutable objects

### ISSUE THREAD

**Issue by mkolodny** [facebook/immutable-js#994]
I find myself often checking whether variables are `null` or `undefined` before converting immutable objects to JS:

```
let category = page.get('category')
if (category !== null) {
    category = category.toJS()
}
```

I think shorthand for this would save a lot of lines of code. Something like:

```
const category = page.getJS('category')
```

Thoughts?

**Comment by leebyron** [comment]
Closing this aging issue.

I'd like to avoid relying on `toJS` any more since it's a performance pitfall. Pro tip if you're doing lots of accessing, `getIn` can help access a chain of keys
