### ISSUE TITLE
Seq methods problem. Returns new object

### ISSUE THREAD

**Issue by BrunoQuaresma** [facebook/immutable-js#995]
### What happened

When i use toIndexedSeq() or valueSeq() is always returns one more object.

`console.log("=========>", props.targets.toJS(), props.targets.toIndexedSeq().toArray())`

=========> Object {0: Object} [Map, Map]

My question is why returns 2 Map objects when must be only 1

**Comment by leebyron** [comment]
Sorry, without code that I can run locally I can't reproduce your problem
