### ISSUE TITLE
Concerning the `size` member

### ISSUE THREAD

**Issue by Yomguithereal** [facebook/immutable-js#997]
Hello `immutable-js` team. Being currently designing a `Graph` data structure for JavaScript, I am trying to gather inspiration from a lot of sources and this library is definitely a fine one.

I see that the `size` member of `immutable-js` collections seems to be mutable. So I was wondering what were the reasons you did not choose to "protect" the member through a getter or else or even used a method returning the information. Just asking because I am pondering all those solution for the `order` and `size` of my graph and was wondering how you made this design choice.

Have a good day.

**Comment by leebyron** [comment]
The size member should not be mutable - I'll be adding a change to the typescript types to make that more clear. Unfortunately JavaScript does not provide many facilities for protecting readonly members in a performant way and performance is paramount in this library
