### ISSUE TITLE
Links for docs

### ISSUE THREAD

**Issue by willdevelops** [facebook/immutable-js#999]
The docs on the following URL have links on the right hand side navigation that redirects me to a different webserver to a generic page (code.facebook.com).  

http://facebook.github.io/immutable-js/docs/#/Stack/shift

Is there an updated URL I should be accessing for these docs?

**Comment by tmikoss** [comment]
Encountering the same issue, every link but the very first page of documentation leads to code.facebook.com.

**Comment by vinnymac** [comment]
@willdevelops @tmikoss I ran into this issue today. I noticed a `cdn.jsdelivr.net` was being blocked by privacy badger. I switched it to only block cookies and now the docs site is working properly. So if you use any sort of blocking tool, I would look at that first. Hope this helps.

**Comment by willdevelops** [comment]
@vinnymac Hey, lookie there, it worked.. Thanks!  👍  Problem resolved.
